### ISSUE TITLE
docs: Calls to resource methods return classed resources, responses(, or requests)

### ISSUE THREAD

**Issue by Voziv** [googleapis/google-api-php-client#1140]
Edit January 29th, 2018: I've updated the description to be more detailed for anyone searching this via google.

## The problem
I upgraded to a newer (`^2.1`) version of `google-api-php-client` and file fetching broke.

The reason is that the class being returned was not `Google_Service_Storage` as the `@return` doc block stated. It was returning the raw Guzzle change. With the library upgrade also came an update to `Guzzle` which broke it.

The 'alt' parameter isn't even mentioned in the docblock of the `get()` method.

## The fix (for users)

Instead of echoing the result like so:
`echo $file_contents; // This is relying on a toString method of an older version of Guzzle`

Instead you use the `getBody()` method.
`echo $file_contents->getBody();`

## Code snippet
```
// Init your google client as usual.
$google_storage_service = new Google_Service_Storage($google_client);
$file_metadata          = $google_storage_service->objects->get($bucket, $filename);

echo get_class($file_contents);
// Method @return states Google_Service_Storage_StorageObject.
// GuzzleHttp\Psr7\Response is what really comes back.
```

See  [voziv/google-api-php-client-1140](https://github.com/Voziv/google-api-php-client-1140) for a working example.

**Comment by mattwhisenhunt** [comment]
I wasn't able to reproduce this result. Please include a bit longer code snippet.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by Voziv** [comment]
Hi,

I've created a code sample here: [voziv/google-api-php-client-1140](https://github.com/Voziv/google-api-php-client-1140)

It makes sense that the raw response is returned when requesting `['alt' => 'media']`. However it was not mentioned in the function phpdocs. It's only mentioned in the middle of the function `Google_Service_Resource::call()`

The only reason this came up as an issue originally was due to a change in Guzzle when I updated from an older version to `google/google-api-php-client ^2.1` 1 year ago.

Possible Fixes
- Could add a note in the function comment.
- Could change the `@return Google_Service_Storage_StorageObject` to be `@return Google_Service_Storage_StorageObject|GuzzleHttp\Psr7\Response`
- Refactoring to make file media fetching a separate function. _Probably not worth doing until a major release_

Not sure if changing `@return` is desirable in this case.

**Comment by jdpedrie** [comment]
I've verified that what you're reporting is correct. We don't have much control over the docblocks for these generated methods at the moment, unfortunately. I'm not sure there's much to be done with this until improvements are made to the code generator.

In the meantime, to any users reading this, you will likely have a much better experience using cloud storage via [`google/cloud-storage`](https://github.com/googleapis/google-cloud-php-storage) as opposed to this library.

@Voziv Thanks again for the detailed report, and apologies that we aren't able to address it sooner. I'll be sure to include it in future discussions about the generator.
