### ISSUE TITLE
Google_IO_Curl fails to parse response if connection done via proxy

### ISSUE THREAD

**Issue by tselina** [googleapis/google-api-php-client#117]
When connection done via proxy curl adds proxy headers to the whole response:

HTTP/1.1 200 Connection Established - that is proxy heades
Date: Thu, 06 Mar 2014 17:05:35 GMT
Proxy-Connection: Keep-Alive
Via: 1.1 localhost.localdomain

HTTP/1.1 200 OK - that is Google response started

So expressions on lines 85-86

```
$responseBody = substr($response, $headerSize);
$responseHeaderString = substr($response, 0, $headerSize);
```

parse response incorrectly and due to that json_decode fails to parse response body

To fix that we need to find start of Google answer.
I do that in that way:
starting from line 83

```
$headerSize = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
$bodySize = curl_getinfo($curl, CURLINFO_SIZE_DOWNLOAD);

$response = substr($response, -($headerSize + $bodySize));
$responseBody = substr($response, $headerSize);
$responseHeaderString = substr($response, 0, $headerSize);
```

I hope that will help.

**Comment by adamors** [comment]
This is still a problem.

**Comment by romanopablo** [comment]
Anyone has solved this? i had to replace the 1rst header with empty value. But i need a more elegant solution...
