### ISSUE TITLE
unauthorized_client: 

### ISSUE THREAD

**Issue by DerManoMann** [googleapis/google-api-php-client#1247]
Hi there,

I've got some code to access GA and GWT data which is working fine using service accounts that I created following the instructions in this comment: https://github.com/google/google-api-php-client/issues/801#issuecomment-171417538 

I had to set up a service account for a new google email and it seems that this process doesn't work any more:
````
PHP Fatal error:  Uncaught Google_Service_Exception: {
 "error": "unauthorized_client",
 "error_description": "Client is unauthorized to retrieve access tokens using this method."
}
 in ./vendor/google/apiclient/src/Google/Http/REST.php:118
Stack trace:
#0 ./vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 ./vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 ./vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
#3 ./vendor/google/apiclient/src/Google/Client.php(788): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...', Array)
#4 ./vendor/google/apiclient/src/Google/Http/REST.php on line 118
````

The PHP code looks something like this:
````
$client = new Google_Client();
$client->setApplicationName('Automated Access');

$client->setAuthConfig($jsonAuth);
$client->setSubject($email);
$client->setScopes([Google_Service_Webmasters::WEBMASTERS_READONLY]);

$wm = new Google_Service_Webmasters($client);

$wm->sites->listSites();
````

I can see the OAuth ID/Service Account in the list of allowed apps, so I would expect this to work just like with the older accounts.

Thanks, mano

**Comment by mattwhisenhunt** [comment]
Did you call $client->authorize() after you set its configuration?

**Comment by DerManoMann** [comment]
Hmm, no, could try that I guess. However, why does the code as-is work with older accounts?

**Comment by zmears** [comment]
Did you resolve this issue? I have the same problem with with the My Business API.

**Comment by DerManoMann** [comment]
Nope. I haven't been in the situation yet where I need a new account, but dreading the day.

**Comment by danielgsims** [comment]
Hi @DerManoMann! Are you still having issues with this, and did you try the auth suggestion? If this isn't something we're actively trying to work through still, I'd like to close this issue.

**Comment by DerManoMann** [comment]
I did try the auth suggestion and the issue still exists.
However, I have come to the conclusion that this is due to limited understanding on how the auth stuff works.
I am happy for this to be closed as we can cope with the accounts that we have for now (unless they stop working, that is).
