### ISSUE TITLE
fetchAccessTokenWithRefreshToken returns invalid_grant error, Bad Request

### ISSUE THREAD

**Issue by jjeeknowre** [googleapis/google-api-php-client#1360]
I can't seem to figure out how to refresh an access token to work. I've spent many hours online looking for how to do it, but nothing seems to work for me. Here is my code:

`
$client = new Google_Client();
$client->setApplicationName('Application Name');
$client->setClientID('client id here');
$client->setClientSecret('client secret here');
$client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/auth/authCallback.php');
$client->addScope([
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/gmail.compose'
]);
$client->setAccessType('offline');

$client->setAccessToken($_SESSION['access_token']);
if ($client->isAccessTokenExpired()) {
    $token = $client->fetchAccessTokenWithRefreshToken($_SESSION['refresh_token']);
    $client->setAccessToken($token);
}
`

$_SESSION['refresh_token'] is a string of the refresh token retrieved from the database when the user first authorized the application, and $_SESSION['access_token'] is set whenever the user logs in, and an access token is given.

Can someone please help me?

**Comment by kevinszuchet** [comment]
I have the same problem, if I use the **refreshToken** method it returns me an invalid_grant error
I use **revokeToken** and go to the consent screen every time the token expires (but obviously this way is quite annoying).

**Comment by hi-rafa** [comment]
I have the same problem, too! why is this issue still open?

**Comment by mattwhisenhunt** [comment]
@jjeeknowre , @kevinszuchet looks like this issue slipped through the cracks. Are you still having problems with fetchAccessTokenWithRefreshToken?

**Comment by ardabeyazoglu** [comment]
@mattwhisenhunt I get the same error with `fetchAccessTokenWithAuthCode`. This was working some time ago.

**Comment by ardabeyazoglu** [comment]
Just checked again and found the issue. Using `setAuthConfig` method with json configuration (where you get from google credentials page), it works. However, if you manually set app id and secret, you get `400 bad request`.

**Comment by zim32** [comment]
Have this bug too. Reverting ti previous version helps me

**Comment by mattwhisenhunt** [comment]
@ardabeyazoglu You may get this error with `fetchAccessTokenWithAuthCode` if you try to use the same code again.

@zim32 If you are still having problems please create a new issue with as much detail as possible, especially a code snippet that reproduces this error for you.
