### ISSUE TITLE
Drive V2 missing

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-php-client#1366]
Is it me or are we not building for drive v2 anymore i can only find [v3](https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Service/Drive.php)

Links back to [Google Drive API - PHP-Client missing trash()-Method?](https://stackoverflow.com/q/48187233/1841839)

**Comment by mattwhisenhunt** [comment]
That is correct. The problem is with the generator code (which is in limbo and not really owned by any team.) I am tracking the problem in this issue: https://github.com/google/google-api-php-client-services/issues/44

**Comment by LindaLawton** [comment]
I thought this library used the standard generator the one written in python.

**Comment by mattwhisenhunt** [comment]
Yeah, that is right. So I guess the current workaround is to get it off PyPI or Github and run it for a single version of a service.

**Comment by LindaLawton** [comment]
so there is no interest in fixing this issue?

**Comment by tmatsuo** [comment]
Sorry about the inconveniences. I'd like to hear input from you. Is there an equivalent feature in V3? If not, does it make sense to add something to the API V3?

**Comment by LindaLawton** [comment]
@tmatsuo which method are you looking for?  If you want something add to the V3 of google drive you will need to post an issue on the Google drive api issue forum.  We can only build an api out of what they offer.

**Comment by tmatsuo** [comment]
Let's have a generic workaround with providing a library generator available. PR is already opened at:
https://github.com/googleapis/google-api-php-client-services/pull/132/files

**Comment by mattwhisenhunt** [comment]
https://github.com/googleapis/google-api-php-client-services/pull/132 got a little long in the tooth it is now at https://github.com/googleapis/google-api-php-client-services/pull/145.
