### ISSUE TITLE
Documentation for Class Google_Service_Slides_PresentationsPages_Resource

### ISSUE THREAD

**Issue by jessecowens** [googleapis/google-api-php-client#1404]
Hello, 

I noticed that the documentation for the Pages Resource has an error.
https://developers.google.com/resources/api-libraries/documentation/slides/v1/php/latest/class-Google_Service_Slides_PresentationsPages_Resource.html

It states that the typical usage is 

`$pages = $slidesService->pages;`

When in fact the usage is

`$pages=$slidesService->presentations_pages;`

**Comment by mattwhisenhunt** [comment]
Fixed in https://github.com/googleapis/google-api-php-client-services/commit/3bf818b9b643a4cd979fba52a0dc515edb9d5d95
