### ISSUE TITLE
setApprovalPrompt() is setting 'approval_prompt' instead of 'prompt'

### ISSUE THREAD

**Issue by bigguy1990** [googleapis/google-api-php-client#1480]
The valid values for the parameter prompt found here do not match the documentation here 
https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient

It looks like a version at some point changed from 'approval_prompt' to 'prompt' ? 

If i replace approval_prompt=consent with prompt=consent everything works as expected. 

Version : 2.2.1 installed through composer.

**Comment by siburny** [comment]
Actually, there is a separate function to set `prompt` called `setPrompt`: https://github.com/google/google-api-php-client/blob/593058802a4bada447e541a454601025c38bb2a9/src/Google/Client.php#L640

**Comment by mattwhisenhunt** [comment]
Looks like they are both going to the same place: https://github.com/googleapis/google-api-php-client/blob/593058802a4bada447e541a454601025c38bb2a9/src/Google/Client.php#L306-L308
One must have been left in to support older code bases.
