### ISSUE TITLE
PHP Warning using listFiles.

### ISSUE THREAD

**Issue by newincentivesdeveloper** [googleapis/google-api-php-client#1489]
I used the following code snippet:

`
        require_once('/home/ubuntu/googleCli/lib/vendor/autoload.php');

	putenv('GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/googleCreds3.json');

	$client = new Google_Client();
	$client->useApplicationDefaultCredentials();
	$client->setSubject('fill_In@Subject.here');
	$client->addScope('https://www.googleapis.com/auth/drive');

	$service = new Google_Service_Drive($client);

	$files = $service->files->listFiles('fill_In_Drive_Folder_ID_Here'); 

	print_r($files);
`

And it did return the list of my files. However, it also output these warnings:

> Warning: array_merge(): Argument #2 is not an array in /home/ubuntu/googleCli/lib/vendor/google/apiclient-services/src/Google/Service/Drive/Resource/Files.php on line 204
> 
> Warning: Invalid argument supplied for foreach() in /home/ubuntu/googleCli/lib/vendor/google/apiclient/src/Google/Service/Resource.php on line 136
> 
> Warning: Invalid argument supplied for foreach() in /home/ubuntu/googleCli/lib/vendor/google/apiclient/src/Google/Service/Resource.php on line 274

Nothing show-stopping, but I thought you'd like to know.

**Comment by mattwhisenhunt** [comment]
Looks like I had this issue misclassified. This warning is caused by your argument to listFiles. It needs to be in the form ['q'=> 'fill_In_Drive_Folder_ID_Here'] See https://developers.google.com/drive/api/v3/search-parameters for other 'q's.
