### ISSUE TITLE
Returns wrong token id data

### ISSUE THREAD

**Issue by 4youplay** [googleapis/google-api-php-client#1498]
Hi, i configured the login example (idtoken.php) from the examples, when i login with 2 different accounts (different browsers too) almost at same time, it returns the token data of the first login user. 

If i refresh the page, the user with the wrong data becomes correct.

Need help.

**Comment by mattwhisenhunt** [comment]
Thanks for creating this issue. To help me reproduce the problem you are seeing please include the example code you are using and a details list of steps to perform to consistently observe this behavior.

**Comment by pracucci** [comment]
We're experiencing the same issue and - after hours of debugging - we've no clue on the root cause. We're still debugging and will share any information as soon as we find it.

**Comment by 4youplay** [comment]
Pracucci my workaroud was removing the redirect part. I think is related to the $Session.

**Comment by mattwhisenhunt** [comment]
Have either of you been able to verify that $_SESSION variables are leaking to other clients? What environment and versions are you running?

**Comment by mattwhisenhunt** [comment]
Seems like this issue is more or less resolved. Thanks for opening it. Please feel free add a comment and we can reopen.
