### ISSUE TITLE
Bug in guzzle for PHP Version 7.2.8

### ISSUE THREAD

**Issue by drrhf** [googleapis/google-api-php-client#1507]
I'm not sure where to mention this, but google-api-php-client-2.22 (the latest I think) still fails with the 'count()' error discussed in [guzzle/guzzle#1956](https://github.com/guzzle/guzzle/issues/1956) when using PHP Version 7.2.8.  The problem does not occur with PHP Version 7.0.4.
I mentioned this on the guzzle forum but thought it appropriate to mention it here as well.

**Comment by mattwhisenhunt** [comment]
Greetings @drrhf,

I was under the impression this got fixed. What's your version of guzzle (`composer info`)? Please attach a sample of code that reproduces this issue.

**Comment by drrhf** [comment]
Matt,
I don't use Composer. 
Rather I downloaded what I thought was the latest release: google-api-php-client-2.2.2.
Thanks,
Bob

**Comment by Renkas** [comment]
This is fixed in Guzzle 6.3

This library installs Guzzle 6.2.3 (at least it has done so for me)

**Comment by drrhf** [comment]
You are correct.  Somehow I was using a version of guzzle that had (in src\Handler\CurlFactory.php)
"private $handles;"   In guzzle Version 6.3.3 this is replaced with "private $handles = [];" and the code works correctly with PHP Version 7.2.8.
Thanks,
Bob
