### ISSUE TITLE
Multi client authentication

### ISSUE THREAD

**Issue by emanuelcanha** [googleapis/google-api-php-client#1508]
Hi,
We are using the library to authenticate users on our backend server. With the libraries for other languages, there is an option to add one or more audiences as shown below for Java. Is this possible with PHP as well?

`GoogleIdTokenVerifier verifier = new GoogleIdTokenVerifier.Builder(transport, jsonFactory)
    // Specify the CLIENT_ID of the app that accesses the backend:
    .setAudience(Collections.singletonList(CLIENT_ID))
    // Or, if multiple clients access the backend:
    //.setAudience(Arrays.asList(CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3))
    .build();`

**Comment by mattwhisenhunt** [comment]
Hello. :wave:
Unfortunately, that is not a feature that ever got added to this client.

**Comment by emanuelcanha** [comment]
Thanks for the information.
If we add that functionality is just a matter of checking the token audience against an array of client IDs or is there anything else we need to be aware of?

**Comment by mattwhisenhunt** [comment]
I'm not sure if I understand the first part of your question, but no I can't think of any gotchas. I would say it is probably easier to instantiate services and clients per client than trying to manage state by swapping out ids (or clients). But I don't think that is what you are suggesting. 
Did you hit any snags last week?

**Comment by emanuelcanha** [comment]
We are only using the library to authenticate users on our backend server. We need to verify JWT tokens from multiple apps, which have different Client IDs.
Besides the integrity checks, the library is also checking that the Client ID (aka audience) sent by the app is the same as the Client ID set on the backend. The change I'm suggesting is to allow for multiple Client IDs to be set on the backend. This would make it the same as the other languages.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After consideration, we have decided not to proceed with this enhancement. If you disagree, please add a comment to this issue and explain why you believe it is essential for users of this client library.
