### ISSUE TITLE
bigquery curl not working in production environment

### ISSUE THREAD

**Issue by yehudahkay** [googleapis/google-api-php-client#1509]
Hi, I am running a bigquery query using

$response = $jobs->query('$project_id, $query);

It works for me in 2 environments but in the 3rd environment I get the following error:

PHP Fatal error:  Uncaught exception 'GuzzleHttp\\Exception\\ConnectException' with message 'cURL error 28: Connection timed out after 150003 milliseconds

Any help appreciated, thank you!

**Comment by mattwhisenhunt** [comment]
My first guess would be that there is a proxy in the third environment.

You might want to try to get other connections to timeout: a request with command line curl or a guzzle request to a different host in PHP.

**Comment by mattwhisenhunt** [comment]
It seems like this got resolved. Let us know if you have anymore questions.

**Comment by yehudahkay** [comment]
@mattwhisenhunt thank you, yes I needed a proxy thank you
