### ISSUE TITLE
PHP sample issue

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-php-client#1511]
[googleads-adsense-examples](https://github.com/googleads/googleads-adsense-examples/tree/master/php-clientlib-1.x/v1.x)   Can one of you googlie people figure out who controls this and have it updated?  

Its causing issues for people https://stackoverflow.com/q/52251794/1841839

**Comment by mattwhisenhunt** [comment]
@JustinBeckwith I can put together a updated v2 example if the repo owners want a PR.

**Comment by nielsnl68** [comment]
Would you mind showing the changes here.? I just need to generate a adsense report. And i'm getting a bit lost with all the api's available.

**Comment by LindaLawton** [comment]
@nielsnl68  i have some generated adsence samples here they might help https://github.com/LindaLawton/Google-APIs-PHP-Samples/tree/master/Samples

**Comment by mattwhisenhunt** [comment]
@LindaLawton, I'm am going to close this issue. Hopefully links your samples with be found and help people with a more modern version of this client.
