### ISSUE TITLE
Uploading file to google drive

### ISSUE THREAD

**Issue by ShirGrinblat** [googleapis/google-api-php-client#1515]
Hello,
How can i upload a file to google drive with google API?
I try the example that this git having but it's written:
include_once(\google-api-php-client-master\src\Google\autoload.php): failed to open stream: No such file or directory.
I downloaded google-api-php-client file, maybe the path isn't correct? 
If someone can write a little example it will be very helpful!!
Thank you very much!!

**Comment by watawep23** [comment]
Try this bro.

```
$fileMetadata = new Google_Service_Drive_DriveFile(array(
    'name' => 'My Report',
    'mimeType' => 'application/vnd.google-apps.spreadsheet'));

$content = file_get_contents('files/report.csv');

$file = $driveService->files->create($fileMetadata, array(
    'data' => $content,
    'mimeType' => 'text/csv',
    'uploadType' => 'multipart',
    'fields' => 'id'));
printf("File ID: %s\n", $file->id);
```

**Comment by mattwhisenhunt** [comment]
Hi @ShirGrinblat :wave:

It looks like you may have found file at src\Google\autoload.php and changed the scripts in the example directory to point at that. They should all be pointing at ../vendor/autoload.php:
```php
include_once __DIR__ . '/../vendor/autoload.php';```
```
But that doesn't exist on a clean `git clone`. You will need to run `composer install` for that vendor directory to show up and then warnings should go away.

See
https://github.com/googleapis/google-api-php-client/tree/master/examples#how-to-run-the-examples
https://github.com/googleapis/google-api-php-client#installation

Let me know if you have any other questions.
