### ISSUE TITLE
BeforeValidException - catch or declare?

### ISSUE THREAD

**Issue by davidsickmiller** [googleapis/google-api-php-client#1516]
Hi!

I've noticed that I sometimes receive a BeforeValidException when I call AccessToken::verifyIdToken().  This comes from that function's call to JWT::decode().

verifyIdToken() will catch a ExpiredException or SignatureInvalidException if thrown by JWT::decode().  Is it a mistake that it was excluded?  Or if you intentionally want it to pass through, why not add a @throws to the method comment block for verifyIdToken()?

**Comment by mattwhisenhunt** [comment]
Hi David,

It sounds like the fix for this is the @throws tag. I will do some testing and find out.
