### ISSUE TITLE
Uncaught Google_Service_Exception: Error calling POST 403

### ISSUE THREAD

**Issue by chenliangliang008** [googleapis/google-api-php-client#1518]
Hello,
Need help.
I got following errors when insert event for google calendar.
Could you tell me how to solve it?
Fatal error: Uncaught Google_Service_Exception: Error calling POST https://www.googleapis.com/calendar/v3/calendars/m45gnl8k65evae50n9bsdsdsadsadgroup.calendar.google.com/events: (403) Forbidden in D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Http\REST.php:110 Stack trace: #0 D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Http\REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client)) #1 D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Task\Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request)) #2 D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Http\REST.php(46): Google_Task_Runner->run() #3 D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Client.php(593): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request)) #4 D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\ in D:\CLN5\xampp\XAMPP\htdocs\googlecalendar\google-api-php-client\src\Google\Http\REST.php on line 110

**Comment by chenliangliang008** [comment]
addition

code as below.

<?php

require_once __DIR__.'/google-api-php-client/vendor/autoload.php';
$json_path = __DIR__.'/google-api-php-client/key/hoge1123.json';
    $calendarId='m45gnl8k65evae50n9bsdsdsadsadgroup.calendar.google.com';
    $json_string = file_get_contents($json_path, true);
    $json = json_decode($json_string, true);
    $scopes = array('https://www.googleapis.com/auth/calendar');
    $client = new Google_Client();
    $client->setApplicationName("Google Calendar PHP API");
    $client->setAuthConfig($json_path);
    $client->setScopes($scopes);
    if ($client->isAccessTokenExpired()) {
        $client->refreshTokenWithAssertion();
    }

$service = new Google_Service_Calendar($client);
$event = new Google_Service_Calendar_Event(array(
  'summary' => 'test20180911',
  'start' => array(
    'dateTime' => '2018-09-12T11:00:00+09:00',
    'timeZone' => 'Asia/Tokyo',
   ),
  'end' => array(
    'dateTime' => '2018-09-12T12:12:00+09:00',
    'timeZone' => 'Asia/Tokyo',
   ),
));

$event = $service->events->insert($calendarId, $event);
printf('Event created: %s\n', $event->htmlLink);

**Comment by chenliangliang008** [comment]
Thank you for your reply.
Yes, the calendar API is enabled in the APIs console.

**Comment by mattwhisenhunt** [comment]
Make sure `$scopes` has both `https://www.googleapis.com/auth/calendar` and `https://www.googleapis.com/auth/calendar.events`.

**Comment by mattwhisenhunt** [comment]
@chenliangliang008 It seems like you have got this issue resolved. Let me know if that is not the case.
