### ISSUE TITLE
How to dynamically define mimeType when uploading a file 

### ISSUE THREAD

**Issue by watawep23** [googleapis/google-api-php-client#1519]
Hello,

In the code below (from google documentation v3), the mimeType has a value of "application/vnd.google-apps.spreadsheet" because the actual file is a **csv** file.

But what if we don't know what type of file the user will upload, what should be the value of mimeType?

```
$fileMetadata = new Google_Service_Drive_DriveFile(array(
    'name' => 'My Report',
    'mimeType' => 'application/vnd.google-apps.spreadsheet'));

$content = file_get_contents('files/report.csv');

$file = $driveService->files->create($fileMetadata, array(
    'data' => $content,
    'mimeType' => 'text/csv',
    'uploadType' => 'multipart',
    'fields' => 'id'));
printf("File ID: %s\n", $file->id);
```

**Comment by mattwhisenhunt** [comment]
Drive will attempt to automatically detect an appropriate value from uploaded content if no value is provided. The value cannot be changed unless a new revision is uploaded.

If a file is created with a Google Doc MIME type, the uploaded content will be imported if possible. The supported import formats are published in the About resource.

**Comment by watawep23** [comment]
Hi Matt,

It gives me funny characters when i try to upload a file
![image](https://user-images.githubusercontent.com/39287835/45394340-a8369600-b662-11e8-826c-55ddbcced1ea.png)
