### ISSUE TITLE
Client access key

### ISSUE THREAD

**Issue by Nehadigi** [googleapis/google-api-php-client#1520]
Is there any way to get access key with authenticate or we can authenticate automatically by giving login details. Because in my app i want to save all files on google drive but when I always require the authentication. If I want to use the upload the file on the single user drive which not going to change then why I  always login and then give the access permission. 
Please help me to this with getting login screen.

**Comment by mattwhisenhunt** [comment]
https://developers.google.com/identity/protocols/OAuth2 walks you through how to use this library and  Google API Console automate authentication and authorization.

**Comment by Nehadigi** [comment]
This is not working. If want to upload the file on my drive then there should be a way to upload image without authenticate again and again. All user file will upload on my drive
