### ISSUE TITLE
I need to fetch the goggle drive folder and there id

### ISSUE THREAD

**Issue by Nehadigi** [googleapis/google-api-php-client#1521]
Is there any possible way to get the all folder and there sub folders only.

**Comment by mattwhisenhunt** [comment]
Hi @Nehadigi :wave:
The Google Drive API has a pretty slick search interface https://developers.google.com/drive/api/v3/search-parameters.

To do want you are looking for just use mimeType:
```php
$driveService->files->listFiles(['q'=> "mimeType = 'application/vnd.google-apps.folder'"]);
```

**Comment by Nehadigi** [comment]
I know but google drive giving me 1 level directories. Is that possible to fetch it in the tree form,
