### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by watawep23** [googleapis/google-api-php-client#1522]
Hi,

I'm currently making a breadcrumbs, and i have noticed that the "parent" attribute given by listFiles() method only returns 1 value of array, even the file is placed in nested folder (folder 1 > folder 1.1 > file).

```
[parents] => Array
                (
                    [0] => 1_EBE64VqDKiHZadW7923EGfp9lj03PFc
                )
```
Is there any other way around to build a breadcrumbs?

Thank you.

**Comment by mattwhisenhunt** [comment]
I think it is parents with an s because you can put one file in multiple folders (labels). To get the file's complete ancestry you could get a list of all the folders `$driveService->files->listFiles(['q'=> "mimeType = 'application/vnd.google-apps.folder'"]);` and then match parents to ids.
