### ISSUE TITLE
not getting auth code

### ISSUE THREAD

**Issue by MikeMwangi** [googleapis/google-api-php-client#1524]
Hi,
I am unable to get auth code in callback page from config file. Config file has the following code:

require_once "GoogleAPI/vendor/autoload.php";
    $gClient = new Google_Client(); $gClient->setClientId("1006072093466-9env5sf4fjqkkgoh04moceuh2jd78l4a.apps.googleusercontent.com");
    $gClient->setClientSecret("9w-4ukC4lj4GH8eZB0-cP_iz");
    $gClient->setApplicationName("WildWatersKenya");
    $gClient->setRedirectUri("https://www.wildwaterskenya.com/pricing-and-hours");
    //$gClient->setRedirectUri("https://www.wildwaterskenya.com/googleredirect.php");
    $gClient->addScope("https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email");

NB: Project is in public_html, but callback page is in outer folder under home directory cpanel as a laravel project which has the following code to access the auth code:

require_once "logingoogle/config.php";
if(isset($_SESSION['access_token']))
{
    $gClient->setAccessToken($_SESSION['access_token']);
}
else if (isset($_GET['code']))
{
    $token = $gClient->fetchAccessTokenWithAuthCode($_GET['code']);
    $_SESSION['access_token'] = $token;
}
else
{
    header('Location: https://www.wildwaterskenya.com/login9.php');
    exit();
}

NB: The index page has the following code to reference the config file and the $loginUrl variable is placed in the "login with google" button as a url to the callback page

require_once "../membership/resources/views/logingoogle/config.php";
$loginUrl = $gClient->createAuthUrl();

PS: The pointing of the directories to config file are pointing fine, kindly help

Michael M

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
