### ISSUE TITLE
Line 421 bug

### ISSUE THREAD

**Issue by victork2015** [googleapis/google-api-php-client#1526]
Is [this](https://github.com/googleapis/google-api-php-client/blob/6fe60b1b5780925a23c71e2c86be09b50da46540/src/Google/Client.php#L421) a bug?

if ($json = json_decode($token, true)) {...

**Comment by mattwhisenhunt** [comment]
The intention of this code is indeed: test the result of the assignment to verify the usability of `$json`.
Not a PHP bug. Though other languages would not allow it.

**Comment by mattwhisenhunt** [comment]
Thanks for opening this issue. Let us know if you have anymore questions.
