### ISSUE TITLE
Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 401, 

### ISSUE THREAD

**Issue by mariyamh** [googleapis/google-api-php-client#1528]
Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "errors": [ { "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "domain": "global", "reason": "unauthorized" } ], "status": "UNAUTHENTICATED" } } in C:\xampp\htdocs\steplancer\GoogleApi\src\Google\Http\REST.php:118 Stack trace: #0 C:\xampp\htdocs\steplancer\GoogleApi\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 C:\xampp\htdocs\steplancer\GoogleApi\src\Google\Task\Runner.php(1 in C:\xampp\htdocs\steplancer\GoogleApi\src\Google\Http\REST.php on line 118

**Comment by mattwhisenhunt** [comment]
Please include a snippet of the code you are trying to get working.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by amindeed** [comment]
#1532
