### ISSUE TITLE
The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.

### ISSUE THREAD

**Issue by wangrong1994** [googleapis/google-api-php-client#1529]
Hi:
my code :

$client = new \Google_Client();
    putenv('GOOGLE_APPLICATION_CREDENTIALS=F:\gitbitback\lets-android.api\api\credentials.json');
    $client->useApplicationDefaultCredentials();
    $client->setApplicationName('world.letsgo.booster.android.demo');
    $client->setClientId('104041803775097038014');
    $client->addScope('https://www.googleapis.com/auth/androidpublisher');
    $res = $client->getAccessToken();
    $service = new \Google_Service_AndroidPublisher($client);
    $purchase = $service->purchases_products->get($responseData['packageName'], 
   $responseData['productId'], $responseData['purchaseToken']);

response 403 error:
{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"androidpublisher\",\n    \"reason\": \"projectNotLinked\",\n    \"message\": \"The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.\"\n }\n}\n

how can i do? I'm already linked the google play developer console
Thank you!

**Comment by nokite** [comment]
I have the same problem. Since the Google API console UI was updated, I can't get the API key to work. I follow the same steps as before.
I'm using Fastlane to submit an APK by using an API key.  
I get "projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."

I can see the project ID from the API console listed in the Google Play console. Under: Users & Permissions > Users with access. I've also given it all the necessary permissions (Release manager). 

I created the key using:
Create service account
Role: Service accounts - Service account user
JSON key

**Comment by mattwhisenhunt** [comment]
@wangrong1994 Can you confirm that you still receive this error after uploading your app manually for the first time?

**Comment by mattwhisenhunt** [comment]
Looks like this one is resolved.

**Comment by zhangzhibin** [comment]
> I have the same problem. Since the Google API console UI was updated, I can't get the API key to work. I follow the same steps as before.
> I'm using Fastlane to submit an APK by using an API key.
> I get "projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."
> 
> I can see the project ID from the API console listed in the Google Play console. Under: Users & Permissions > Users with access. I've also given it all the necessary permissions (Release manager).
> 
> I created the key using:
> Create service account
> Role: Service accounts - Service account user
> JSON key
> 
> Edit: A few hours later a tried this: I uploaded the Android app manually, and after that the API access seems to work. It looks like the error I was seeing was simply the wrong one. It should have been similar to "no app found with the ID specified".

Thanks, your solution of uploading new Apk to Google Play Console solved my issue.

**Comment by evaldsurtans** [comment]
Yes, This must be added to documentation, key starts to work only after APK upload

**Comment by prabhat-oodles** [comment]
> Yes, This must be added to documentation, key starts to work only after NEW APK upload (existing will not work)

You saved our day, thanks a lot.
