### ISSUE TITLE
Fatal error a few minutes after user authentication. Conflicting web sites.

### ISSUE THREAD

**Issue by amindeed** [googleapis/google-api-php-client#1532]
Hello everybody,

I have been trying out version 2.2.2, with the following examples:

* `google-php-oauth2-example`: [PHP example on the official Google API guide web site](https://developers.google.com/identity/protocols/OAuth2WebServer#example)
* `phpflow-php-google-oauth`: [PHP Web Application Authentication Using Google OAuth 2.0 - Phpflow.com](https://www.phpflow.com/php/php-web-application-authentication-using-google-oauth-2-0/)

On the same browser, when a Google user gets authenticated on one of the two examples, we get the following error whenever we try to visit the home URL of the other one. After one hour or so, even the first tested example will end up throwing the same error if we refresh its browser tab:

```
( ! ) Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "errors": [ { "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "domain": "global", "reason": "unauthorized" } ], "status": "UNAUTHENTICATED" } } in C:\wamp64\www\phpflow-php-google-oauth\src\Google\Http\REST.php on line 118

( ! ) Google_Service_Exception: { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "errors": [ { "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "domain": "global", "reason": "unauthorized" } ], "status": "UNAUTHENTICATED" } } in C:\wamp64\www\phpflow-php-google-oauth\src\Google\Http\REST.php on line 118

```

For information, I have been trying an old code using version 0.6.0 of the API client, along with the above examples. So far, it has been working without issues.

Here is a summary of my testing environment specifications:

|                                     | google-php-oauth2-example                       | phpflow-php-google-oauth              | old example                                                                                   |
|-------------------------------------|-------------------------------------------------|---------------------------------------|-----------------------------------------------------------------------------------------------|
| **Google API PHP Client**           | v2.2.2                                          | v2.2.2                                | v0.6.0                                                                                        |
| **GCP Project**                     | Project A                                       | Project B                             | Project A                                                                                     |
| **Credentials used by the web app** | OAuth Client ID / Web App. JSON file.           | OAuth Client ID / Web App. JSON file. | OAuth Client ID / Web App. Variables: Client ID, Client Secret, Redirect URL, Home URL        |
| **Scopes**                          | email, profile, openid, drive.metadata.readonly | email, profile, openid                | email, profile, openid, drive.metadata.readonly ('drive.metadata.readonly' scope is not used) |

* **Dev/Test env (1)**
    * __Server__: Windows 10 Pro x64, WampServer Version 3.1.3 64bit, Apache 2.4.33, PHP (tested with both 5.6.35 and 7.2.4). Notable modules: php_curl and apache ssl_module enabled.
    * __Client (browser)__: Windows 10 Pro, Firefox 62.0.3, Chrome 68.0.3550.0.
* **Dev/Test env (2)**
    * __Server__: Windows 7 Pro SP1 x64, WampServer Version 3.1.4 64bit, Apache 2.4.35, PHP 7.2.10. Notable modules: php_curl and apache ssl_module enabled.
    * __Client (browser)__: Windows 7 Pro SP1 x64, Firefox 62.0.3, Chrome 68.0.3550.0.

Thank you.

**Comment by mattwhisenhunt** [comment]
Access tokens do expire after an hour. To refresh them after that time you need have a refresh token which will be provided the first time they log in and authorize your app if you have set access type to offline:
```php
$client->setAccessType("offline");
$auth_url = $client->createAuthUrl();
header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));
```
If your access token has a refresh token you can refresh without prompting the user for permission:
```php
if ($client->isAccessTokenExpired()) {
  $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
}
```

**Comment by mattwhisenhunt** [comment]
Let us know if you need anything else.

**Comment by Muneeb1998** [comment]
@mattwhisenhunt Hello, Can you help me.
**Code**
![image](https://user-images.githubusercontent.com/50280520/151922198-3fc5ff56-3e1c-4684-b67a-1b64b82bc642.png)
**Result (Error)**
![image](https://user-images.githubusercontent.com/50280520/151922264-92f8be83-ec77-46be-ad47-caca08db1d24.png)
