### ISSUE TITLE
disallowed_useragent

### ISSUE THREAD

**Issue by sundarpenumarthiwiomw** [googleapis/google-api-php-client#1541]
I am trying to let users login with google when they try connecting to my wifi. Everything works great except for when user try to connect with their iphone it gives an error **Error 403 disallowed_useragent**
**Google can't sign you in safely inside this app. You can use Google sign-in by visiting this app's website in a browser like Safari or Chrome.**
It is a splash page that pops up when you try connecting to wifi that is giving this error. Could someone suggest a fix for this issue? 
TIA
![image1](https://user-images.githubusercontent.com/28317662/47817158-f4c55600-dd22-11e8-9d61-14c38a91cc31.png)

**Comment by mattwhisenhunt** [comment]
Please provide more details on how to reproduce this error include the snippet of PHP that is producing this unexpected result. (Make sure to remove keys and secrets)

**Comment by sundarpenumarthiwiomw** [comment]
Thanks for your response @mattwhisenhunt. You may not be able to reproduce the error on your end due to the hardware restrictions but I can provide you with the different useragents I get on different browsers and also on the iOS app (It is not our app but the default splash page that pops up when you try connecting to the wifi). 

Iphone Safari
=============
mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X)
Apple WebKit/605.1.1.5 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

Chrome Iphone
==============
mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X)
Apple WebKit/604.1.34 (KHTML, like Gecko) CriOS/70.0.3538.75 Version/11.0 Mobile/15E148 Safari/604.1

Splash page
============
mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X)
Apple WebKit/605.1.1.5 (KHTML, like Gecko) Mobile/15E302

Please find the code snippet below
`
<!DOCTYPE html>
<html>
<head>
  <title></title>
    
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxapps.googleusercontent.com">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        function onSignIn(googleUser) 
        {
            var profile = googleUser.getBasicProfile();
            $("#email").text(profile.getEmail());
        }
    </script>
</head>
<body>
<div class="g-signin2" data-onsuccess="onSignIn"></div>
<div class="data">
<p id="email"></p>
</div>
</body>
</html>`

I get the 403 error as soon as click on the button. 
TIA.

**Comment by mattwhisenhunt** [comment]
It looks like this is expected behavior. My guess is they don't want you using webviews. Check out https://developers.google.com/identity/sign-in/ios/sign-in. I'm sorry I can't be of more help but the scope of this library is almost completely back-end PHP code. Please let me know if I can help you in that realm.
