### ISSUE TITLE
Google Sign-In Button For PHP using css does not work

### ISSUE THREAD

**Issue by OmarMaadarani** [googleapis/google-api-php-client#1545]
Hey,

I am running into a constant error "cookiepolicy is a required field" when trying to implement the Google Sign-In button, using the images given on the developers website. I'm using CSS for the button sizing.

Here Is the CSS:

`.g-signin
    {
      background-image: url(../Pictures/google_signin_buttons/Google_signin_button.sketch);
      font-family: 'Roboto', sans-serif;
      color: white;
      width: 200px;
      height: 50px;
      border-radius: 10px;
      border-style: solid;
      padding-left: 50px;
    }
    .google-btn
    {
      background: url(../Pictures/google_signin_buttons/web/2x/btn_google_signin_dark_normal_web.png) no-repeat;
    }`

I have also added these for the Google API:
`   <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="CLIENT_ID.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/api:client.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">`

And to note, this is a school summative and my teacher made the whole API file to sign in using google, so i cant add anything...

**Comment by mattwhisenhunt** [comment]
Your question is not related to this library. StackOverflow is probably the right place to ask it.
