### ISSUE TITLE
Cloud Talent Solution - Cloud Events

### ISSUE THREAD

**Issue by caleuanhopkins** [googleapis/google-api-php-client#1548]
**Is your feature request related to a problem? Please describe.**
Looking at the Cloud Talent Solution libraries, there doesn't appear to be a Class or Resource for sending events through the PHP SDK to Cloud Talent Solution's Package Client Event endpoint. We're currently integrating parts of our job board into Talent Solution and would like to be able to send events when candidates enter the application process after searching for jobs through Talent Solution's search filter.

 **Describe the solution you'd like**
A Class that allows for the sending of events in the PHP SDK to match the documentation on the [Talent Solution website](https://cloud.google.com/talent-solution/job-search/docs/client-event?authuser=1#EventType).

 **Describe alternatives you've considered**
Sending custom Guzzle requests to the available endpoint. We are using the PHP SDK for almost everything else for Talent Solution so is a bit of a mess switching to Guzzle requests when everything else is nicely handled through the SDK.

 **Additional context**
Apologies if this class already exists in the SDK but I'm struggling to find it.

**Comment by mattwhisenhunt** [comment]
Hi, Callum. :wave: Looks like it is named [JobService](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/JobService.php), definitely not the first place I would have looked either.

Thanks for your question.

**Comment by caleuanhopkins** [comment]
@mattwhisenhunt Perfect, thanks for looking to this for me. Is there plans to update the directory name to match the service name (client events)?
