### ISSUE TITLE
OAuth JSON file location and idtoken.php

### ISSUE THREAD

**Issue by jubilus** [googleapis/google-api-php-client#1551]
I'm trying to follow the examples and create a simple script that creates an event on a user's calendar. I have the application and everything set up via the API Console, have downloaded the JSON file, etc. In the "idtoken.php" example there is a line that says:

```
/*************************************************
 * Ensure you've downloaded your oauth credentials
 ************************************************/
if (!$oauth_credentials = getOAuthCredentialsFile()) {
  echo missingOAuth2CredentialsWarning();
  return;
}
```

Yet there's no explanation as to where this file should be located or a variable that explains where to place a location. Am I missing something?

Running the example produces the following message:
![screen shot 2018-11-21 at 10 09 37 am](https://user-images.githubusercontent.com/250180/48856442-04611900-ed7c-11e8-8163-5a3c90c15f15.png)

So I figured I would rename and place the file in the root directory of the site and load the page again... no change. 
I then placed the file in the "templates" folder... no change.
I placed the file in the "vendor" folder... no change.

I can't for the life of me figure out where this JSON file should be located. Any help?

**Comment by mattwhisenhunt** [comment]
It needs to be in a directory above the one in which idtoken.php is located, that is two directories above [base.php](https://github.com/googleapis/google-api-php-client/blob/736ffceb170db1ec16e4fba83d0065996b23e855/examples/templates/base.php#L139).

Make sure to not let your oauth-credentials.json file be web accessible. Just add a comment if you have any other questions.

**Comment by inside83** [comment]
Man, I just spent 2h looking for a way to make it work
