### ISSUE TITLE
Class not found when used with MyBusiness

### ISSUE THREAD

**Issue by pelcomppl** [googleapis/google-api-php-client#1558]
Hi
I use Google_Client and MyBusiness.php library in Laravel.
File MyBusiness.php has many classes.
I can use this library in controller:
```
$gClient = new Google_Client();
$mybusinessService = new Google_Service_MyBusiness($gClient);
```
but this code:
```
$mybusinessService = new Google_Service_MyBusiness($gClient);
$accounts = $mybusinessService->accounts;
$accountsList = $accounts->listAccounts()->getAccounts();
```
gives mi error: 
Symfony\Component\Debug\Exception\FatalThrowableError: Class `'Google_Service_MyBusiness_ListAccountsResponse' not found in file /home/pp/pr/diagnostic-marketing-medrev-backend/vendor/google/apiclient/src/Google/Http/REST.php on line 128`

How to fix it?

**Comment by mattwhisenhunt** [comment]
My Business is a bit of an oddball, it is not listed in the API directory available through the Discovery API and it requires a developer key and project acceptance into My Business. There is [a tool on the way](https://github.com/googleapis/google-api-php-client-services/pull/145) that will help developers maintain their own version of such service classes. When it is ready and you have a project with My Business enabled you should be able to run:
```php
export API_KEY=yourkey
bin/generate 'https://mybusiness.googleapis.com/$discovery/rest?version=v4&key=$API_KEY' generated-output
```
and then you can move the contents of generated-output/mybusiness-v4 anywhere you want in your include path.
That discovery URL has been known to change as new versions come out so keep and eye on https://developers.google.com/my-business/reference/rest/

**Comment by LindaLawton** [comment]
@mattwhisenhunt  can you contact the my business team and tell them to remove the PHP library from this page if this is still the case. 

[Samples](https://developers.google.com/my-business/samples)
