### ISSUE TITLE
add support for monolog 2.0

### ISSUE THREAD

**Issue by blacknell** [googleapis/google-api-php-client#1562]
Can you enable support for [monolog/monolog](https://github.com/Seldaek/monolog) 2.0

I'd like to use it in my project but because 1.17 is a dependency of google/apiclient composer won't allow

relates #1369

**Comment by danielgsims** [comment]
I did a little bit of research here:

Version 2 of Monolog is still in development. At the time of writing this comment, it has a beta release in packagist. I looked at compatibility of the library as of this commit: https://github.com/Seldaek/monolog/commit/ebb804e432e8fe0fe96828f30d89c45581d36d07.

The PSR-3 Usage of Monolog remains consistent. This library uses the SyslogHandler and StreamHandler for Monolog, which also are consistent, other than type hinting.

Monolog 2 requires PHP 7.1, so when Version 2 is released, we will need to support Monolog 1.X for lower versions of PHP.

**Comment by jdpedrie** [comment]
Thanks @danielgsims. There hasn't been a 2.0 since beta1 last December. This looks like it'll be pretty straightforward, but until they get (at least) to RC stage, let's just continue to watch it.

**Comment by dlw-libs** [comment]
Can you enable support for monolog/monolog 2.0 now that it is at v2.0.0?

Thanks!

**Comment by zek** [comment]
Can we please release a version including this feature?

**Comment by jdpedrie** [comment]
@zek it's in the works: https://github.com/googleapis/google-api-php-client/pull/1707

**Comment by jdpedrie** [comment]
Please upgrade to [`v2.3.0`](https://github.com/googleapis/google-api-php-client/releases/tag/v2.3.0). :)

**Comment by CtrlShiftN** [comment]
it has been conflicted when I use google/apiclient
