### ISSUE TITLE
teamdrive and drive queries being cached?

### ISSUE THREAD

**Issue by stecca21** [googleapis/google-api-php-client#1564]
I'm getting the feeling that query results are being cached, or a list of teamdrives and their folders is placed in cache and referenced.

I can manually delete a folder through the drive interface and have it returned as being available in the api. I can create a folder through the api and not be able to find it with the returned id for 5-15 seconds.

Is cache being used in these scenarios? If so, is there a way to clear the cache or force no-cache use during these queries?

**Comment by mattwhisenhunt** [comment]
Hi @stecca21. No there shouldn't be any caching of responses in this client. You will definitely need to execute new requests to the API though:
```php
$results = $driveService->teamdrives->listTeamdrives()
```

I am not really familiar with the Drive API but it may be that the only difference between a deleted and not deleted folder is that the trashed field is set. I don't know why a new folder would take so long to show up via API calls.

Finally I will just note that you might be interested in tools like API Explorer or mitmproxy or Charles. Those are always helpful to me when I am getting an unexpected result and I'm trying to figure out why.
https://developers.google.com/apis-explorer/#p/drive/v3/drive.files.list
https://mitmproxy.org/
https://github.com/googleapis/google-api-php-client#debugging-your-http-request-using-charles

**Comment by stecca21** [comment]
@mattwhisenhunt I started off using listTeamdrives() but quickly noticed that new TeamDrives didn't always show up in the list after being created. This led me to bake in a verification that the drive comes back in a results set before moving on in the code, and using list is not efficient in that case.

I'm now instead doing a search for the newly created Teamdrive via id to verify it exists.  Still, I have to wrap this in a 'while' loop until a result comes back.

**Comment by mattwhisenhunt** [comment]
Sounds great if that approach is working for you. You may also want to look into [receiving push notifications](https://developers.google.com/drive/api/v3/manage-changes).

And of course please add comments below if you have any more questions.
