### ISSUE TITLE
Could not determine client ID from request. Google Client

### ISSUE THREAD

**Issue by jpcodeforit** [googleapis/google-api-php-client#1565]
Here is the Detailed issue
https://stackoverflow.com/questions/53754876/could-not-determine-client-id-from-request-google-client

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by jdpedrie** [comment]
Hi @jpcodeforit,

The stackoverflow link you provided is 404. Looks like it was removed. If you're still having issues, please update this issue with more detail and reopen it.

**Comment by jpcodeforit** [comment]
@jdpedrie .yup .after posting within few min i got sollution for my issue.THanks :)

**Comment by xiebruce** [comment]
@jpcodeforit Could you tell me how do you solve this issue? I encounter this issue too.
