### ISSUE TITLE
google + is being deprecated

### ISSUE THREAD

**Issue by tylik1** [googleapis/google-api-php-client#1570]
Today got email that Google + is deprecated and will shut down soon. I deleted Google + from dev console, and the lib stopped working. Is there a plan to migrate anytime soon? 
I'm using lib for oauth2 user authorization. Maybe I'm missing something and it is already possible to use oauth without google+ service.

`Client error: `GET https://www.googleapis.com/plus/v1/people/me?prettyPrint=false resulted in a 403 Forbidden response: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. Google+ API (truncated...) , 400`

**Comment by NxKai** [comment]
I've been keeping track of this issue since the news broke out. I found this link [here](https://stackoverflow.com/a/24510214/10560484) about a way to do it just by using the default email scope given. Does anyone know how to use it on the Client Library? Help would be much appreciated. Thanks!

**Comment by mxdpeep** [comment]
https://bitbucket.org/gscloud/gscloud/src/master/app/v1/LoginPresenter.php

line 35+


s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by Nazalas** [comment]
I am using the client->createAuthUrl() method. Will this continue to work correctly after the Google+ deprecation?

**Comment by mxdpeep** [comment]
I am using PHP League for OAuth client, Google+ issues already fixed

**Comment by artetrad** [comment]
I am using the Google_Client's `verifyIdToken` method. Will this continue to work after the Google+ deprecation?

**Comment by nacesprin** [comment]
What is the alternative to?
```
$plus = new Google_Service_Plus($client);
$me = $plus->people->get('me');
```

**Comment by tylik1** [comment]
UPD.
I was using Socialite Laravel plugin to authorize via Google. In latest release they've fixed issue. 
From the commit I can see that the main change was made in the endpoint
From: 
`https://www.googleapis.com/plus/v1/people/me`
To:
`https://www.googleapis.com/userinfo/v2/me`

Here is the link if anyone is interested in complete changes list
https://github.com/laravel/socialite/pull/319/commits

**Comment by ApacheEx** [comment]
[Hybridauth](https://github.com/hybridauth/hybridauth) has been also migrated to Google Sign In, more info here: https://github.com/hybridauth/hybridauth/commit/6123c31700bda7acd49cef7f1f0c138b60f39070

**Comment by scottybo** [comment]
I've added another issue related to this which some might find useful #1589

**Comment by w-schmidenberg** [comment]
> What is the alternative to?
> 
> ```
> $plus = new Google_Service_Plus($client);
> $me = $plus->people->get('me');
> ```

@nacesprin I changed the scope to:
`$client->addScope(['email','profile']);`

After you fetch the Access Token, you can use this:
`$token_data = $client->verifyIdToken();`
to provide the email.

**Comment by squierll** [comment]
> 
> 
> What is the alternative to?
> 
> ```
> $plus = new Google_Service_Plus($client);
> $me = $plus->people->get('me');
> ```

@nacesprin, here is alternative that I use to get user profile data:
```
$account = new Google_Service_Oauth2($client);
$me = $account->userinfo->get();
```

**Comment by tmatsuo** [comment]
Let's close this
