### ISSUE TITLE
IAP products generated by Google api not showing up in Unity until next day?

### ISSUE THREAD

**Issue by eeahktzugr** [googleapis/google-api-php-client#1572]
I am using this clientto generate and insert new IAP products to a Unity game. Everything was working fine a month back and new products showed up in real time. Now they show up after mid night. I cant find anything on the internet that would point to the fact that Google has changed something. I am out of ideas. Unity just returns Unavailable product error.

The products show up in Google Console just fine and if I add them manually from the console they also show up in the game just fine.

**Comment by danielgsims** [comment]
Hi there @eeahktzugr! I'm sorry to hear you're having some unexpected behavior. If you're still having an issue, could you provide some example code of your problem? Also, could you provide what you were running from the console? I'll help dig into what's going on to see what behavior changed. Thanks!

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open, but please if so, supply additional information previously requested.
