### ISSUE TITLE
At the moment, resources are not available to link Google Keep with another application?

### ISSUE THREAD

**Issue by ivanfretes** [googleapis/google-api-php-client#1573]
I wanted to write an application to link a tool with Google Keep, and I have not found resources, it would be interesting to be able to link it with other tools

**Comment by danielgsims** [comment]
Hi @ivanfretes. I think having a Google Keep API would be great too! Unfortunately, there isn't one right now. The best way to let the team know you would like an API is by providing feedback through the Google Keep application.

If and when they publish an API, we will gladly create a library to help you integrate your PHP applications with it!
