### ISSUE TITLE
No attribute on class Product for return_address_label or return_policy_label

### ISSUE THREAD

**Issue by ankitdeveloper** [googleapis/google-api-php-client#1576]
I have search across the lib but I was not able to locate `return_policy_label` and `return_address_label`. 

According to Google documentation We need to pass this attribute in the feed to make it work but there is no method available related to this.

Here is the reference URL.

https://support.google.com/merchants/answer/7660817?hl=en

Thanks!

**Comment by jdpedrie** [comment]
Hi @ankitdeveloper,

The answer given by Chris in the [ruby issue](https://github.com/googleapis/google-api-ruby-client/issues/728#issuecomment-444684621) also applies to us. As the [discovery document](https://www.googleapis.com/discovery/v1/apis/content/v2/rest) does not provide the attributes you're looking for, we cannot add support to this library. You may be able to accomplish your goals using the [`Google_Service_ShoppingContent_OrderLineItemReturnInfo::setPolicyUrl()`](https://github.com/googleapis/google-api-php-client-services/blob/bf7adcd0acf1abfdaa1184ec32a31afda7a1cdc1/src/Google/Service/ShoppingContent/OrderLineItemReturnInfo.php#L40) method.

**Comment by ankitdeveloper** [comment]
@jdpedrie thank you for a reply. I have checked his response and understand that there is no specification about return label in their document. Can we reach out to Google for same?

**Comment by jdpedrie** [comment]
Certainly! You can communicate with the team responsible for the Shopping Content API [here](https://groups.google.com/forum/#!forum/google-content-api-for-shopping).
