### ISSUE TITLE
cant reach to user data from modelData

### ISSUE THREAD

**Issue by azisyus** [googleapis/google-api-php-client#1577]
its how i init Google_Client();
```

        $google = new Google_Client();
        $google->setClientId(_MY_CLIENT_ID_);
        $google->setClientSecret(_MY_CLIENT_SECRET_);
        $google->setApplicationName(_APP_NAME);
        $google->addScope(Google_Service_Oauth2::USERINFO_EMAIL);
        $google->setRedirectUri($this->callbackUrl);
        $this->google = $google;
```

then

```
        $token = $this->google->fetchAccessTokenWithAuthCode($_GET["code"]);
        $this->google->setAccessToken($token);
        $client = new Google_Service_Oauth2($this->google);
        $this->user = $client->userinfo->get();
```

so i got 2 method which is implements a interface to reach user data so i can auth em etc etc.

```
    public function getFirstName()
    {
        // TODO: Implement getFirstName() method.
        return $this->user["modelData"]["given_name"];
    }

    public function getLastName()
    {
        // TODO: Implement getLastName() method.
        return $this->user["modelData"]["family_name"];
    }
```
but the problem is, sometimes modelData is empty, and this things was working maybe a month ago, what did you change or did you change, what am i missing? the main question is, whats the purpose of modelData if i can already reach these credentials without it?

and this is inside of $this->user prop 
```
Google_Service_Oauth2_Userinfoplus {#286 ▼
  #internal_gapi_mappings: array:3 [▶]
  +email: "XXXXXXXXXXX@gmail.com"
  +familyName: "X_surname"
  +gender: null
  +givenName: "X_name"
  +hd: null
  +id: "112056566688779011880"
  +link: "https://plus.google.com/112056566123779011880"
  +locale: null
  +name: "X_name X_surname"
  +picture: ""
  +verifiedEmail: true
  #modelData: array:3 [▼
    "verified_email" => true
    "given_name" => "X_name"
    "family_name" => "X_surname"
  ]
  #processed: []
}
```

**Comment by tmatsuo** [comment]
I haven't tested, but does it work when you add [Google_Service_Oauth2::USERINFO_PROFILE](https://github.com/googleapis/google-api-php-client-services/blob/581f76bb3db1c8bff908de7e9bbb8af1a362b0c8/src/Google/Service/Oauth2.php#L40)?

**Comment by jdpedrie** [comment]
I'm not able to replicate the error. It looks like you may be encountering a transient error which could be resolved by checking that the response is missing info and re-running it. @tmatsuo's idea may also work, though I get the expected data with either scope.

If you're still having trouble and our ideas don't fix the issue, please re-open and we'll continue to investigate.
