### ISSUE TITLE
can't access files in Team Drives 

### ISSUE THREAD

**Issue by qcol** [googleapis/google-api-php-client#1584]
Is there any problem with accessing files located in "team drives" through this client?  I have created an email address in "api console/service account". If I share a folder for this email address in "My drive" - I have access to it through the client. If I add this address to Team drives users - I do not have access to files. Why? 

a fragment of the code that opens the Google sheet:

```
$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
		$spreadsheetFeed = $spreadsheetService->getSpreadsheetFeed();
		try {
		$spreadsheet = $spreadsheetFeed->getByTitle($file_name);
		}
```

**Comment by jdpedrie** [comment]
Hi @qcol,

Unfortunately we are poorly positioned here to answer questions about API behavior. Our area of expertise is in the way the API client itself behaves. If you're still having trouble, the Drive API team suggests posing questions on Stackoverflow using the [`google-drive-sdk`](https://stackoverflow.com/questions/tagged/google-drive-sdk) tag. They monitor those questions and should be able to assist!
