### ISSUE TITLE
Problem With Access Token

### ISSUE THREAD

**Issue by ashujangra** [googleapis/google-api-php-client#1586]
Hello Team,

I am facing  very weird error, I have initially able to access token on development server, but when I moved that code on production server it automatically stop working. I have added production URL in my project console. Interesting part is that code is exact same. I can't see any error to fix this. Also When I am using 'offline access token' as type it still expire in 1 hour. Please help me with this. Here is my code

             //////////// Index.php

              $google_redirect_url = base_url('index2.php');
		$client = new Google_Client();
		$client->setAuthConfig($this->google_credentials);
		$client->setAccessType("offline");        // offline access
		$client->setIncludeGrantedScopes(true);   // incremental auth
		$client->addScope('https://www.googleapis.com/auth/plus.business.manage');
		$client->setRedirectUri($google_redirect_url);
		$google_auth_url = $client->createAuthUrl();

Here is my code handler.

            //////////// Index2.php
                              $client = new Google_Client();
				$client->setAuthConfig($this->google_credentials);
				$client->setAccessType("offline");
				$client->authenticate($_GET['code']);
				$access_token = $client->getAccessToken();

**Comment by ashujangra** [comment]
after modify $access_token = $client->fetchAccessTokenWithAuthCode($_GET['code']); I got to know the error that showing invalid_grant. Seriously i don't know whats going wrong, Please help

**Comment by danielgsims** [comment]
Hi @ashujangra. Are you having issues with this still?

**Comment by ashujangra** [comment]
yes ..

**Comment by LindaLawton** [comment]
Standard cause for invalid_grant error

- Your server’s clock is not in sync with NTP. (Solution: check the server time if its incorrect fix it. )
- The refresh token limit has been exceeded.       (Solution: Nothing you can do they cant have more refresh tokens in use)
 Applications can request multiple refresh tokens. For example, this is useful in situations where a user wants to install an application on multiple machines.  In this case, two refresh tokens are required, one for each installation. When the number of refresh tokens exceeds the limit, older tokens become invalid. If the application attempts to use an invalidated refresh token, an invalid_grant error response is returned. The limit for each unique pair of OAuth 2.0 client and is 25 refresh tokens (note that this limit is subject to change). If the application continues to request refresh tokens for the same Client/Account pair, once the 26th token is issued, the 1st refresh token that was previously issued will become invalid. The 27th requested refresh token would invalidate the 2nd previously issued token and so on.

**Comment by jdpedrie** [comment]
Hi @ashujangra,

Did @LindaLawton's information help solve your problem?

**Comment by tmatsuo** [comment]
Let's close this. However, feel free to reopen @ashujangra
