### ISSUE TITLE
Sorting Not Possible using Google Search Console API

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#1587]
Hi,

There is some example on the API documentation mentioned that **Get Top 10 pages, sorted by click count, descending**

link to documentation [here](https://developers.google.com/webmaster-tools/search-console-api-original/v3/how-tos/search_analytics#top-10-pages-sorted-by-click-count-descending)

But I cannot do any sorting through API.

Does sorting supported by this Library for Google Search Console API analytics section?

Thanks,

**Comment by danielgsims** [comment]
Hi @chiragvels! It looks like the API only supports sorting by click count descending, which is the default sorting operation. If you need to sort in any other way, you will have to pull all of your data and sort yourself. I hope this helps!

**Comment by santma** [comment]
For a Search Engine, this search console api isn't great. Maybe Google should stop meddling in other businesses outside it's scope and focus more on products regarding search.
