### ISSUE TITLE
Google_Service_Drive()->files->listFiles with query can't accept urlEncoded parameters

### ISSUE THREAD

**Issue by babushona** [googleapis/google-api-php-client#1588]
OS: Windows 10
PHP Version 5.6.26
Package name and version: google-api-php-client v2.2.2

I want to get list of children under a folder using V3 API.

[https://developers.google.com/drive/api/v3/search-parameters](https://developers.google.com/drive/api/v3/search-parameters)

This is the code I used. $drive is google_Service_Drive(). I could get the storage quota etc using $drive. So, its already authenticated. 0ABh5NHZAS9DZUk9PVA is the folder ID whose children I am querying for.

```
echo "Child Listing: BEGIN<br>";
try {
  $files = $drive->files->listFiles(array(
                                            'q' => "'0ABh5NHZAS9DZUk9PVA'+in+parents",
                                          ))->getFiles();
  } catch (Google_Exception $e) {
    echo "In Catch::ERROR : " . $e->getMessage();
  }
  echo "Child Listing: END<br>";
```
This is what Charles captured
![image](https://user-images.githubusercontent.com/46716000/51928907-fe8f5000-241c-11e9-8886-845e9a37d296.png)

So, the client library is correctly URL-encoding the queryString. The Google API server is supposed to decode it back before executing the API service. But it is returning Error.

Then I tried the same query using Guzzle HTTP Client. Here is the code.

```
$folder_id = "0ABh5NHZAS9DZUk9PVA";
$httpClient = new GuzzleHttp\Client([
    'proxy' => 'localhost:8888', // by default, Charles runs on localhost port 8888
    'verify' => false, // otherwise HTTPS requests will fail.
]);
    $r = $httpClient ->request('GET', "https://www.googleapis.com/drive/v3/files",
        [
            'headers' =>  [
                'Cache-Control'=> 'no-store',
                'Content-Type' => 'application/x-www-form-urlencoded',
                'Authorization' => 'Bearer '.$acc_token,
            ],
            'query' => ['q' => "'".$folder_id."'+in+parents"]
        ]
    );

```
This is what Charles captured

![image](https://user-images.githubusercontent.com/46716000/51929364-10bdbe00-241e-11e9-8eed-b086f6d75568.png)

Guzzle's "query" option also performs URL-encoding. Hence same response from Google API Service.

Then I tried this code to bypass Guzzle's URL-encoding.

```
$folder_id = "0ABh5NHZAS9DZUk9PVA";
$httpClient = new GuzzleHttp\Client([
    'proxy' => 'localhost:8888', // by default, Charles runs on localhost port 8888
    'verify' => false, // otherwise HTTPS requests will fail.
]);
$r = $httpClient ->request('GET', "https://www.googleapis.com/drive/v3/files?q='".$folder_id."'+in+parents",
        [
            'headers' =>  [
                'Cache-Control'=> 'no-store',
                'Content-Type' => 'application/x-www-form-urlencoded',
                'Authorization' => 'Bearer '.$acc_token,
            ],
            //'query' => ['q' => "'".$folder_id."'+in+parents"]
        ]
    );

```
**And Voila, The API worked!!!** This is what Charles showed,

![image](https://user-images.githubusercontent.com/46716000/51930110-d3f2c680-241f-11e9-8509-05a1e1776fcd.png)

So, when the query String is "**NOT**" URL-encoded, the API service worked. It seems a bug to me...in the Google API service itself, not in PHP client library.

I don't know where bug for Google API should be filed. I believe some Google folks who developed the API service, are in development team of PHP client library too. Hence filing the bug here with a hope that somebody from the dev team here will report it to the API dev team.

**Comment by mxdpeep** [comment]
the problem is due to the apostrophes IMHO

*Filip Oščádal*
*https://fredbrooker.gscloud.cz/cs <https://fredbrooker.gscloud.cz/cs>*

**Comment by babushona** [comment]
The apostrophes are required by the documentation.

[https://developers.google.com/drive/api/v3/search-parameters](https://developers.google.com/drive/api/v3/search-parameters)

![image](https://user-images.githubusercontent.com/46716000/51984847-5df36b80-24c2-11e9-9ace-4930733e7506.png)

The API actually worked with 'raw' apostrophes.

Funny thing is that in the same listFiles method, you can pass other parameters, like files.

```
$files = $drive->files->listFiles(array(
                                            'fields' => "files(id, name, mimeType, parents, properties, trashed, quotaBytesUsed, kind, size)"
                                      ))->getFiles();
```
      
This too gets urlEncoded and same API is called and works.

![image](https://user-images.githubusercontent.com/46716000/51985167-436dc200-24c3-11e9-8022-c30df56c4735.png)


So, the Google API service is accepting 'files' in urlEncoded format but not 'q'.

**Comment by dwsupplee** [comment]
I think the problem is because the `+` is being URL encoded `%2B`. You shouldn't need those in the string passed in through the library, it should just be `'0ABh5NHZAS9DZUk9PVA' in parents`.
