### ISSUE TITLE
Google_Client::verifyIdToken throws undocumented exception

### ISSUE THREAD

**Issue by crtl** [googleapis/google-api-php-client#1591]
#### Environment details

  - PHP version: 7.2
  - Package Version: 2.2

#### Steps to reproduce

Pass an invalid non JWT Token to `Google_Client::verifyIdToken`.

#### Code example

```php
try {
    $token = $this->googleClient->verifyIdToken("123");
} catch (\LogicException $ex) {
    throw new \Exception("Could not retrieve user information", $ex->getCode(), $ex);
}
//Uncaught exception UnexpectedValueException
```

It will throw a `UnexpectedValueException` but `verifyidToken` is only hinted to throw `LogicException`.

**Comment by jdpedrie** [comment]
Thanks for the report @crtl. I've opened #1592 to fix this.
