### ISSUE TITLE
Request Slow

### ISSUE THREAD

**Issue by rubenperezpro** [googleapis/google-api-php-client#1593]
hi, 
all requests made to the API are slow, like the connexion for get token of the user with code is during 30 seconds 

$accessToken = $client->fetchAccessTokenWithAuthCode($_GET['code']);

thx for your help

**Comment by jdpedrie** [comment]
Hi @rubenperezpro,

Unfortunately, without additional information it's hard to assist much. Have you checked to see if the slow connection times are specific to Google services? Perhaps try making an HTTP call to another service and comparing. If both are slow, you'll need to debug the reasons why your server is having trouble getting a decent connection.

This forum is for issues specifically related to the API client. We're certainly happy to help however we can, but before we can, we need to know whether the problems you're having are related to a problem with the API client.

**Comment by rubenperezpro** [comment]
@jdpedrie 
thx for your reply (and sorry for my bad English)

yes example when I use file_get_contents it's working as well
I think its from Guzzle Client maybe because when I use  CURL  in the normal way all my requests go fast

**Comment by jdpedrie** [comment]
@rubenperezpro have you checked your server logs to see if there are any issues which may not be immediately apparent?

**Comment by rubenperezpro** [comment]
its okay i found solution its fix my problem, i set timeout to guzzle client  :

             $guzzle = new GuzzleHttp\Client(['timeout'  => 2.0,]);
            $client = new Google_Client();
            $client->setHttpClient($guzzle);

thx @jdpedrie

**Comment by seliver** [comment]
One can also reuse the config provided by the Google_Client and add additional options:
```
$googleApiClient = new Google_Client();
$config = $googleApiClient->getHttpClient()->getConfig();
$config['read_timeout'] = 10;
$config['connect_timeout'] = 10;
$config['timeout'] = 60;
$googleApiClient->setHttpClient(new GuzzleHttp\Client($config));
```
