### ISSUE TITLE
Could not resolve host: www.googleapis.com

### ISSUE THREAD

**Issue by Simprosys-InfoMedia** [googleapis/google-api-php-client#1596]
Hello,

Can you please look into this error? It is showing Host could not be resolved for www.googleapis.com URL.

This has stopped all our Feed service to be submitted to Google Merchant Center.

Below is the Detailed Error Message:.

Error Message :cURL error 6: Could not resolve host: www.googleapis.com
Error Code : 0

WE are getting this issue everyday.

**Comment by jdpedrie** [comment]
This generally indicates an issue with your server. Have you replicated the issue in another environment (i.e. locally, or on another server in a different location)?

**Comment by regmanua** [comment]
have the same error working on apache2 behind corporate proxy (all other internet things working good). At the same time my script working perfectly on machine with direct internet access. Also, `curl www.googleapis.com` command in console doesn't gives any errors

`[php7:error] [pid 29106] [client ::1:38088] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 6: Could not resolve host: www.googleapis.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/psylabrest/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185\nStack trace:\n#0 /var/www/psylabrest/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /var/www/psylabrest/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /var/www/psylabrest/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 /var/www/psylabrest in /var/www/psylabrest/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185`

My environment:
- Apache/2.4.29
- PHP 7.2.15-0ubuntu0.18.04.2
- curl 7.58.0

**Comment by jdpedrie** [comment]
You can configure proxy settings be providing your own Http Client instance:

```php
use GuzzleHttp\Client;

$client = new Google_Client();
$http = new Client([
  'proxy' => $myProxy
]);

$client->setHttpClient($http);
```

Guzzle proxy settings documentation may be found [here](http://docs.guzzlephp.org/en/stable/request-options.html#proxy).

**Comment by regmanua** [comment]
> You can configure proxy settings by providing your own HTTP Client instance:
> 
> ```
> use GuzzleHttp\Client;
> 
> $client = new Google_Client();
> $http = new Client([
>   'proxy' => $myProxy
> ]);
> 
> $client->setHttpClient($http);
> ```
> 
> Guzzle proxy settings documentation may be found [here](http://docs.guzzlephp.org/en/stable/request-options.html#proxy).

thanks a lot, it works!

**Comment by jdpedrie** [comment]
Glad to hear it. @Simprosys-InfoMedia, As we've not heard back from you, I'm going to close this. If you're still having problems, please re-open the issue and let us know.
