### ISSUE TITLE
Need in app products change local price for other countries

### ISSUE THREAD

**Issue by safciplak** [googleapis/google-api-php-client#1597]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: macos Mojave 10.14.2
  - PHP version: 7.3.2
  - Package name and version:

#### Steps to reproduce

  1. ...

#### Code example

```php

        $currency = 'RUB';
        $priceInMicros = '100'; // 1lira
        $sku = 'testsafak5002';
        $purchaseType = 'managedUser'; // managedUser // subscription
        $defaultLanguage = 'ru-RU';
        $listings['ru-RU']['title'] = 'safak test 5002 ru';
        $listings['ru-RU']['description'] = 'safak test desc 5002 ru';

        $googlePrice = new \Google_Service_AndroidPublisher_Price();
        $googlePrice->setCurrency($currency);
        $googlePrice->setPriceMicros($priceInMicros);

        $googleInAppProduct = new \Google_Service_AndroidPublisher_InAppProduct();

        $googleInAppProduct->setPrices($googlePrice);
        $googleInAppProduct->setSku($sku);
        $googleInAppProduct->setStatus('inactive'); // active inactive
        $googleInAppProduct->setPurchaseType($purchaseType);
        $googleInAppProduct->setDefaultLanguage($defaultLanguage);
        $googleInAppProduct->setPackageName($this->packageName);
        $googleInAppProduct->setSubscriptionPeriod('P1M');
        $googleInAppProduct->setListings($listings);


        $service->inappproducts->update(
            $this->packageName,
            $sku,
            $googleInAppProduct,
            ['autoConvertMissingPrices' => true]
        );

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jdpedrie** [comment]
Please provide additional information as to what the expected outcome is, and what is actually happening. A code snippet without context doesn't give us enough data to assist.

**Comment by safciplak** [comment]
i wanna update local price for example
My main currency TRY
But i need RUB = russion ruble
or EUR
or USD 
or other curriences

**Comment by tmatsuo** [comment]
@safciplak I'm sorry, but we can not help you with the information you gave. I suggest you post your question on Stackoverflow.
