### ISSUE TITLE
how to call search console api work on cron . when i use the service account got an empty list。

### ISSUE THREAD

**Issue by ZGINMADAO** [googleapis/google-api-php-client#1598]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
As shown above

**Comment by dwsupplee** [comment]
Hi @ZGINMADAO, could you share a code snippet so we can help take a look?

**Comment by ZGINMADAO** [comment]
> Hi @ZGINMADAO, could you share a code snippet so we can help take a look?
thank you  very much for your reply, here is my code. the code references service-account.php in the examples. 
![image](https://user-images.githubusercontent.com/17716544/54255083-81193c80-4591-11e9-9ff3-3f2f03a88405.png)

**Comment by ZGINMADAO** [comment]
> > Hi @ZGINMADAO, could you share a code snippet so we can help take a look?
> > thank you  very much for your reply, here is my code. the code references service-account.php in the examples.
> > ![image](https://user-images.githubusercontent.com/17716544/54255083-81193c80-4591-11e9-9ff3-3f2f03a88405.png)
the response
![image](https://user-images.githubusercontent.com/17716544/54255410-f46f7e00-4592-11e9-9ec7-856390cbe0f8.png)

**Comment by dwsupplee** [comment]
@ZGINMADAO make sure you call `getSiteEntry` on the `SitesListResponse` to get an array you can iterate over, for example:

```php
$results = $service->sites->listSites();

foreach ($results->getSiteEntry() as $entry) {
    var_dump($entry->getSiteUrl());
}
```

**Comment by dwsupplee** [comment]
I'm going to close this out now, please feel free to re-open if you're still running in to any issues.
