### ISSUE TITLE
Calendar API: Sening EXDATE in PUT Request for Recurrent Event doesn't Delete the event

### ISSUE THREAD

**Issue by muhammadtaqi** [googleapis/google-api-php-client#1599]
I'm creating Events via APIs, All other are case are working except below;

1. Created a Recurrent event of 5 days, Success.
2. Then Update the event send EXDATE to delete one event among them.
```php
  "recurrence": [
    "RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR,SA,SU;UNTIL=20190323T185959Z",
    "EXDATE:20190321T180000Z"
  ],
```
API returns 200, but in calendar event on EXDATE is still exists. Can't understand why it's not deleting... 

#### Environment details
  - OS: Ubuntu
  - PHP version: 7.2
  - Package name and version: v2.x-dev of google-api-php-client

#### Steps to reproduce

  1. Create recurrent event.
  2. Update the event with passing EXDATE with some value.

**Comment by jdpedrie** [comment]
Hi @muhammadtaqi,

This question does not appear to be the result of an issue with the API client, and thus should be directed to the Calendar API team. Please see the [How To Get Help](https://developers.google.com/calendar/support) page for information on support with the API itself.
