### ISSUE TITLE
Youtube API search->listSearch order is being ignored

### ISSUE THREAD

**Issue by acidjazz** [googleapis/google-api-php-client#1601]
All other parameters are working fine, passing different `maxResults` reflects perfectly.  Any valid `order` value I pass is ignored and the order is always the same.

**Comment by LindaLawton** [comment]
Might help [Issue 129264189](https://issuetracker.google.com/issues/129264189)

**Comment by jdpedrie** [comment]
Thanks @LindaLawton,

@acidjazz, as this appears to be a known issue in the API, I suggest you follow along with the issue Linda linked to. Once the API team resolves the issue, if you still have trouble, feel free to re-open this issue and let us know!
