### ISSUE TITLE
Google_AuthHandler_Guzzle6AuthHandler::attachCredentials() must be callable or null, string given

### ISSUE THREAD

**Issue by CharlesBilbo** [googleapis/google-api-php-client#1602]

**Comment by jdpedrie** [comment]
Hi @CharlesBilbo,

In order to assist, we need more information. Please provide a code sample which raises the error described.

**Comment by CharlesBilbo** [comment]
i apologize i ad meant to delete this posting as i had solved my issue

**Comment by jdpedrie** [comment]
Glad to hear it!
