### ISSUE TITLE
Adding guests to created event, trigerrs invalid email address for correct email address

### ISSUE THREAD

**Issue by jayanthanantharapu** [googleapis/google-api-php-client#1605]
```
exception 'Google_Service_Exception' with message '{
"error": {
 "errors": [
  {
   "domain": "global",
   "reason": "invalid",
   "message": "Invalid attendee email."
  }
 ],
 "code": 400,
 "message": "Invalid attendee email."
}
}
```

**Comment by jdpedrie** [comment]
Hi @jayanthanantharapu, please share the code snippet which raised the error.

**Comment by jayanthanantharapu** [comment]
`$service = new Google_Service_Calendar($this->client);
$event = $service->events->get($this->calendar_id, $event_id);
$event->setAttendees(array(array('email' => $this->email)));
$updatedEvent = $service->events->update($this->calendar_id, $event->getId(), $event, $this->event_update_param);`

email is having leading and trailing spaces lead to invalid email
