### ISSUE TITLE
Connection Error Google People Api

### ISSUE THREAD

**Issue by rsRamgharia** [googleapis/google-api-php-client#1606]
I am trying to connect people api using php, but it always give me no connection found,
but whenever i trying from javascript it works, please help in php, how can i access data.

Here is the code. if error in this code than please help

`<?php
require __DIR__ . '/vendor/autoload.php';

function getClient()
{
    $client = new Google_Client();
    $client->setApplicationName('People API PHP Quickstart');
    $client->setScopes(Google_Service_PeopleService::CONTACTS_READONLY);
    $client->setAuthConfig('credentials.json');
    $client->setAccessType('offline');
    $client->setPrompt('select_account consent');

    // Load previously authorized token from a file, if it exists.
    // The file token.json stores the user's access and refresh tokens, and is
    // created automatically when the authorization flow completes for the first
    // time.
    $tokenPath = 'token.json';
    if (file_exists($tokenPath)) {
        $accessToken = json_decode(file_get_contents($tokenPath), true);
        $client->setAccessToken($accessToken);
    }

    // If there is no previous token or it's expired.
    if ($client->isAccessTokenExpired()) {
        // Refresh the token if possible, else fetch a new one.
        if ($client->getRefreshToken()) {
            $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
        } else {
            // Request authorization from the user.
            $authUrl = $client->createAuthUrl();
            // printf("Open the following link in your browser:\n%s\n", $authUrl);
            // print 'Enter verification code: ';
            header('location:'.$authUrl);
            $authCode = trim($_GET['code']);

            // Exchange authorization code for an access token.
            $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
            $client->setAccessToken($accessToken);

            // Check to see if there was an error.
            if (array_key_exists('error', $accessToken)) {
                throw new Exception(join(', ', $accessToken));
            }
        }
        // Save the token to a file.
        if (!file_exists(dirname($tokenPath))) {
            mkdir(dirname($tokenPath), 0700, true);
        }
        file_put_contents($tokenPath, json_encode($client->getAccessToken()));
    }
    return $client;
}

// Get the API client and construct the service object.
$client = getClient();
$service = new Google_Service_PeopleService($client);

// Print the names for up to 10 connections.
$optParams = array(
  'pageSize' => 10,
  'personFields' => 'names,emailAddresses',
);
$results = $service->people_connections->listPeopleConnections('people/me', $optParams);

if (count($results->getConnections()) == 0) {
  print "No connections found.\n";
} else {
  print "People:\n";
  foreach ($results->getConnections() as $person) {
    if (count($person->getNames()) == 0) {
      print "No names found for this connection\n";
    } else {
      $names = $person->getNames();
      $name = $names[0];
      printf("%s\n", $name->getDisplayName());
    }
  }
}
?>`

**Comment by dwsupplee** [comment]
Hi @rsRamgharia, could you share the exact error you receive?

**Comment by rsRamgharia** [comment]
Sorry to disturb everyone, but i got the solution
