### ISSUE TITLE
Google Search Console API - Sitemaps 

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#1607]
Hi,

Google Search Console API is not giving any Sitemaps Details for a Domain property siteUrl.
Like : sc-domain:example.com

We can get Sites and Performance data for a Domain property siteUrl, but issue with Sitemaps.

Thanks,

**Comment by jdpedrie** [comment]
Hi @chiragvels, can you share a code snippet please?

**Comment by chiragvels** [comment]
Hi @jdpedrie ,

My code snippet

```
$client = new Google_Client();
$client->setClientId($client_id);
$client->setClientSecret($client_secret);
$client->setRedirectUri($redirect_uri);
$webmastersService = new Google_Service_Webmasters($client);
$sitemaps = $webmastersService->sitemaps;
$totalsitemaps = $sitemaps->listSitemaps($url);  //sc-domain:example.com                
$siteMaps = $totalsitemaps->getSitemap();
```


Thanks,

**Comment by jdpedrie** [comment]
Hi @chiragvels,

I'm not seeing any issues fetching sitemaps. I tried running your code snippet with a domain I own and it worked fine. The [API documentation](https://developers.google.com/webmaster-tools/search-console-api-original/v3/sitemaps/list) states that the URL should include the protocol; Could you be providing an invalid URI?

**Comment by chiragvels** [comment]
Hi @jdpedrie ,

I was also getting sitemaps perfectly for regular domains like http://www.example.com/.

But my question is Google Search Console API is not giving any Sitemaps Details for a **Domain property siteUrl**.

Domain property siteUrl is URIs like **sc-domain:example.com** which was introduced [recently](https://webmasters.googleblog.com/2019/02/announcing-domain-wide-data-in-search.html).

**Comment by pankajYIT** [comment]
Google Search Console API is not giving any Sitemaps Details for a Domain property siteUrl. please give me any solution

**Comment by jdpedrie** [comment]
Ah, thanks for the additional information. I see the same thing when trying to fetch a sitemap using the domain property URL.

```php
$sites = $webmastersService->sites->listSites();
foreach ($sites as $site) {
    $totalsitemaps = $sitemaps->listSitemaps($site->getSiteUrl());
}
```

It appears as though the List Sitemaps API does not support domain property urls at this time.

I suggest sending a report to the team using the "Submit Feedback" link in the bottom left corner of the Search Console. I'm very sorry for the inconvenience!

Since this issue isn't specific to the client library, but exists within the API itself, there's not much more we can assist with here, unfortunately. Again, I suggest letting the API team know your feedback; hopefully they can add the feature, or perhaps share some information that isn't obvious.

Best of luck!

**Comment by arch1v1st** [comment]
@jdpedrie & @chiragvels,

While developing a new custom Google SC API implementation, I faced the same problem.  Initially tried the root domains (and sub-domains - no matter the protocol, and even prefixing the URL with 'sc-domain:' did not help at first).  We have lots of websites and domain properties registered and hit some oddities.   Not sure at this point what fixed it exactly but after going through some (but not ALL) additional Google domain re-verifications via DNS/TXT records and the varying website protocols (HTTP/HTTPS/etc), and waiting a while (hours, not days), the same queries against these endpoints/URLs returned expected results.

A key difference here is we did not have a need to query ```$webmastersService->sites->listSites()```, but were initially experiencing the same types of errors when trying to access ```$webmastersService->searchanalytics``` methods.

Code snippet for reference (which is working ATM!):

```
  $client = new Google_Client();
  $google_private_key = variable_get('cw_google_private_key');
  $client->setAuthConfig($google_private_key);
  $client->addScope('https://www.googleapis.com/auth/webmasters.readonly');
  $webmastersService = new Google_Service_Webmasters($client);
  $searchanalytics = $webmastersService->searchanalytics;
```

So for those of you that hit this problem - please fiddle with your Google Webmaster tools verification's, retry, and post your issues/observations here!

```
https://www.google.com/webmasters/verification/home?hl=en
```

**Comment by holtkamp** [comment]
@chiragvels did you submit the feedback and get any response?

@jdpedrie would it be an idea to keep this issue open until it is possible again to list sitemaps for domain properties?

@arch1v1st you describe that \Google_Service_Webmasters::$searchanalytics does support a format like `sc-domain:example`, but this does not allow us to load a sitemap, right?

**Comment by jdpedrie** [comment]
@holtkamp unless we determine that the issue lies within the PHP client library, there's no benefit in keeping it open, so far as I can see.

**Comment by holtkamp** [comment]
@jdpedrie yeah, I suppose you are right. My "problem" / the community's challenge is that this issue with [domain properties](https://searchengineland.com/google-search-console-gives-us-domain-properties-to-replace-property-sets-313109) seems to be around for some time and there is no place to report it other than the approach you suggested:

>I suggest sending a report to the team using the "Submit Feedback" link in the bottom left corner of the Search Console

For what it's worth / future searchers: some other mentions I encountered on this topic:

- https://github.com/googleapis/google-api-python-client/issues/820#issuecomment-614092145
- https://stackoverflow.com/questions/57920769/how-do-we-fetch-sitemaps-from-google-search-console-for-a-site-with-has-domains
- https://support.google.com/webmasters/thread/15194304?hl=en&msgid=15201612

**Comment by jdpedrie** [comment]
@holtkamp I definitely understand the frustration. I suggest perhaps submitting this as an issue in the [public issue tracker](https://issuetracker.google.com/).

**Comment by holtkamp** [comment]
Thanks for the suggestion @jdpedrie, just created https://issuetracker.google.com/issues/166291453, hopefully it will set some things in motion 🚀

**Comment by parthea** [comment]
I see that domain properties is now listed in the [documentation](https://developers.google.com/webmaster-tools/search-console-api-original/v3/sites/add) :
```
siteUrl | string | The URL of the property to add. Examples: http://www.example.com/ (for a URL-prefix property) or sc-domain:example.com (for a Domain property)
```

**Comment by Queens666** [comment]
> Gracias por la sugerencia @jdpedrie , recién creado https://issuetracker.google.com/issues/166291453 , con suerte pondrá algunas cosas en movimientocohete

**Comment by ysverma** [comment]
when i try to access google search console api script in php for fetching 500 errors urls but showing this errror Raw API Response: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v3/sites/https%3A%2F%2Fwww.yourquorum.com%2F/urlCrawlErrorsSamples?category=serverError&amp;platform=web</code> was not found on this server.  <ins>That’s all we know.</ins>
Error decoding JSON response: Syntax error

this is my script     <?php
    require 'google-api-php-client--PHP8.3/vendor/autoload.php';

    use Google\Client;
    use Google\Service\SearchConsole;

    function fetch500Errors($siteUrl) {
        // Path to the service account key file
        $keyFilePath = './project2-credentials.json';

        $client = new Client();
        $client->setAuthConfig($keyFilePath);
        $client->addScope(SearchConsole::WEBMASTERS);
        $client->setAccessType('offline');

        $searchConsoleService = new SearchConsole($client);

        // Ensure the site is added to Google Search Console
        $sites = $searchConsoleService->sites->listSites();
        $siteExists = false;
        foreach ($sites->getSiteEntry() as $site) {
            if ($site->getSiteUrl() == $siteUrl) {
                $siteExists = true;
                break;
            }
        }

        if (!$siteExists) {
            echo "The site is not found in Google Search Console.";
            return;
        }

        // Retrieve crawl errors
        $errors = [];
        
        $url = "https://searchconsole.googleapis.com/v3/sites/" . urlencode($siteUrl) . "/urlCrawlErrorsSamples?category=serverError&platform=web";
        $accessToken = $client->getAccessToken();
        
        if (empty($accessToken['access_token'])) {
            die('Error: No access token found.');
        }
        
        $headers = [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $accessToken['access_token']
        ];
        
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $response = curl_exec($ch);
        
        if (curl_errno($ch)) {
            die('Curl error: ' . curl_error($ch));
        }
        
        curl_close($ch);

        if ($response === FALSE) {
            die('Error fetching data from Google Search Console API');
        }

        // Debug the raw response
        echo "<pre>Raw API Response: " . htmlspecialchars($response) . "</pre>";

        $data = json_decode($response, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            die('Error decoding JSON response: ' . json_last_error_msg());
        }

        if (isset($data['urlCrawlErrorSamples'])) {
            foreach ($data['urlCrawlErrorSamples'] as $error) {
                if ($error['responseCode'] == 500) {
                    $errors[] = [
                        'url' => $error['pageUrl'],
                        'responseCode' => $error['responseCode'],
                        'lastCrawled' => $error['lastCrawled']
                    ];
                }
            }
        }

        echo json_encode($errors, JSON_PRETTY_PRINT);
    }

    // Example usage
    $siteUrl = 'https://www.example.com/';
    fetch500Errors($siteUrl);
    ?>
please comment for what error in my script
