### ISSUE TITLE
Consider nonce / security_token support

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-php-client#1608]
I am not seeing any support for nonce and securty_token validation in the library.    It may be an good idea to consider supporting this.

[OpenID Connect](https://developers.google.com/identity/protocols/OpenIDConnect)

**Comment by tmatsuo** [comment]
Hi @LindaLawton 
Thanks for the report. What kind of support you want to see? Isn't it enough to use a function like [random_bytes](https://www.php.net/manual/en/function.random-bytes.php) possibly with [bin2hex](https://www.php.net/manual/en/function.bin2hex.php)?

**Comment by LindaLawton** [comment]
[Authenticating the user](https://developers.google.com/identity/protocols/OpenIDConnect#authenticatingtheuser) 

Maybe i have miss read the code but i am not seeing anyway to add nonce to this call and have it validated when it returns

```
https://accounts.google.com/o/oauth2/v2/auth?
 client_id=424911365001.apps.googleusercontent.com&
 response_type=code&
 scope=openid%20email&
 redirect_uri=https://oauth2-login-demo.example.com/code&
 state=security_token%3D138r5719ru3e1%26url%3Dhttps://oauth2-login-demo.example.com/myHome&
 login_hint=jsmith@example.com&
 openid.realm=example.com&
 nonce=0394852-3190485-2490358&
 hd=example.com
```

Would you mind adding a sample so that we can see how its done?

**Comment by tmatsuo** [comment]
@LindaLawton 

Ok, let's say you're using just a random string for state (optionally you can add more info to represent the "state" of the user at the time of request).

Before the redirect, you do:
```php
$state = bin2hex(random_bytes(64)); // needs PHP 7 or higher
# save the state into session, how to do this varies depending on your framework of choice
$app['session']->set('state', $state);
# then construct the URL with the state
```

After the redirect (on the redirect_url), you do:
```php
if ($request->get('state') != ($app['session']->get('state'))) {
    return new Response('Invalid state parameter', 401);
}
```

I hope it answers your question!
