### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Google_AccessToken_Verify' not found in src/Google/Client.php

### ISSUE THREAD

**Issue by Glasindor** [googleapis/google-api-php-client#1611]
Api installed manually, not via Composer, downloaded from here (version 2.2.2): https://github.com/google/google-api-php-client/releases
I put API in /root/google-api-php-client on my Server.
I call /root/VerifyToken.php
```
$id_token = $_POST['idToken'];
$client = new Google_Client(['client_id' =>'xxxxxxx.apps.googleusercontent.com']);
$payload = $client->verifyIdToken($id_token);
```

I got this error:
`Fatal error: Uncaught Error: Class 'Google_AccessToken_Verify' not found in /root/google-api-php-client/src/Google/Client.php:705`

I find Google_AccessToken_Verify in AccessToken/Verify.php but Client.php dont found it. 

Any Hint?

**Comment by Glasindor** [comment]
jdpedrie i have this in my PHP /root/VerifyToken.php:  `require_once 'google-api-php-client/vendor/autoload.php';`
I dont know why AccessToken/Verify.php is not include. This php file is not in the folder Vendor, is in the folder src, but maybe autoload include this folder too.

**Comment by tmatsuo** [comment]
@Glasindor 

The right way to include the library is to have

```php
<?php
require_once 'google-api-php-client/vendor/autoload.php';
```

at the beginning of your script.

I can not reproduce your problem. Can you give me a way to reproduce? For example, create a zip file of your root folder and send it to me? Without the way to reproduce your problem, there's nothing I can help.

**Comment by Glasindor** [comment]
With 2.2.1 is everything OK
