### ISSUE TITLE
Uncaught exception 'Google_Service_Exception'

### ISSUE THREAD

**Issue by lidya1859** [googleapis/google-api-php-client#1612]
Hi,
I got this error whenever the token is expired. Here is my code

```php
try {
	$client->setAccessToken($_SESSION['access_token']);			
} catch (Exception $e) {
	unset($_SESSION['access_token']);
}
```

Why the exception cannot be caught?
I'm using version 2.2.2, php version 5.5.38
Thank you

**Comment by lidya1859** [comment]
I have tried to change
`$client->setAccessToken($_SESSION['access_token']);`
with
`throw new Exception("Error Processing Request", 1);`
and the session is successfully unset.
So I guess there's no problem with my Exception.

**Comment by tmatsuo** [comment]
@lidya1859 

Do you have a namespace declaration in your PHP file?
If so, do you have a class `Exception` in the same directory?
What happens if you just change your code with the following as John suggests?:

```php
catch (\Exception $e) {
```

**Comment by tmatsuo** [comment]
I think we can close this, but feel free to reopen

**Comment by zubairIftikharKwe** [comment]
i've Same Issue..
`use Exception;`
```
 try{
            $this->client->setAccessToken($token);
        }catch (Exception $e){
               echo  'sad';die;

        }
```
But not Catch Exception How to Catch error.
Why i need try catch here?
 if token is expire it return follow error with HTTP Status 500
```
{ 
   "error":{ 
      "code":401,
      "message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
      "errors":[ 
         { 
            "message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
            "domain":"global",
            "reason":"unauthorized"
         }
      ],
      "status":"UNAUTHENTICATED"
   }
}
```
