### ISSUE TITLE
 Google Play API client libraries update to v3

### ISSUE THREAD

**Issue by eliddon** [googleapis/google-api-php-client#1614]
I use the AndroidPublisher feature from the Google client API and it is mentioning that the Google Play API client libraries need to be migrated to v3 as EOL is December 2019.

Is there going to be fix? I see in the AndroidPublisher.php file that it seems to be hardcoded to v2. Not sure if I can just change it to use v3 and keep the current functionality.

**Comment by jdpedrie** [comment]
Hi @eliddon,

The [latest version](https://github.com/googleapis/google-api-php-client-services/blob/84496e2/src/Google/Service/AndroidPublisher.php#L65) of `AndroidPublisher.php` indicates that the client is using v3.

Have you tried running `composer update` to obtain the latest version of the client? If so, check your composer require to ensure that you are not depending on a specific version of `google/apiclient-services`.

**Comment by eliddon** [comment]
Your correct - my apologies. I had not installed the latest versions of the dependencies.

Thank you!
