### ISSUE TITLE
Error in google people api during create contact

### ISSUE THREAD

**Issue by rsRamgharia** [googleapis/google-api-php-client#1615]
I got an error while insert data using api , if there is an error in coding than please suggest me.

   { "error": { "code": 400, "message": "Request contains an invalid argument.", "errors": [ { 
    "message": "Request contains an invalid argument.", "domain": "global", "reason": 
    "badRequest" } ], "status": "INVALID_ARGUMENT" } }

    $service = getClient();

	$person = new Google_Service_PeopleService_Person();

	$name = new Google_Service_PeopleService_Name();
	$name->setDisplayName('Test');
	$person->setNames($name);

	$exe = $service->people->createContact($person);

**Comment by jdpedrie** [comment]
Couple issues.

First, `$person->setNames()` accepts an array. Second, as the [documentation](https://developers.google.com/people/api/rest/v1/people#Person.Name) states, `displayMame` ` displayNameLastFirst` are read-only. This means that the API will provide them in GET requests, but they cannot be sent in create or update operations. Google will determine the value based on the other fields you provide and the viewer's locale.

Try something like this instead:

```php
$person = new Google_Service_PeopleService_Person();

$name = new Google_Service_PeopleService_Name();
$name->setFamilyName('Test');
$person->setNames([$name]);

$exe = $service->people->createContact($person);
```

Be sure to use the [API Reference](https://developers.google.com/people/api/rest/), as most of these problems can be answered there. :)

If this answer doesn't fix the problem, please feel free to re-open the issue and let me know!

**Comment by rsRamgharia** [comment]
Thanku so much @jdpedrie , it works
