### ISSUE TITLE
How to get the Mediation report from AdmobMediation 

### ISSUE THREAD

**Issue by karam89** [googleapis/google-api-php-client#1617]
Hello all:

I'm using google-api-php-client to get the AdmobMediation report remotely from our servers

Every thing works fine, except that the response report is only related to the "**Admob Network**", not the "**Mediation report**"

so as a result, the metrics are Incomplete

So I have two questions:

- Is there a way to get **Mediation report** instead of only **Admob Network** report using the SDK?
- Is there a way to download a saved report we made on "Admob dashboard" using the php SDK?

Thanks in advanced

**Comment by jdpedrie** [comment]
Hi @karam89,

Can you provide the code snippet you're using currently?

**Comment by karam89** [comment]
Thanks for your response
Here is the detailed code

```
	$startDate = '2019-04-01';
	$endDate = '2019-04-09';
	$AppId = 'xxxx';
	$accountId = 'xxxx';
	
	/*
		Create the client
	*/
	$client = new Google_Client();
	$client->addScope('https://www.googleapis.com/auth/adsense.readonly');
	$client->setAccessType('offline');
	
	/*
		Authentication
	*/
	$client->setClientId('xxx');
	$client->setClientSecret('xxx');
	$client->setRedirectUri("urn:ietf:wg:oauth:2.0:oob");
	
	
	$refreshedAccessToken = $client->refreshToken('xxx');
	$client->setAccessToken($refreshedAccessToken);

	/*
		Create the service
	*/
	$service = new Google_Service_AdSense($client);
	
	
	/*
		Get the result
	*/
	$metrics = array(
		'AD_REQUESTS', 'VIEWED_IMPRESSIONS', 'IMPRESSIONS_RPM', 'CLICKS', 'REACHED_AD_REQUESTS',
		'IMPRESSIONS_CTR', 'COST_PER_CLICK', 'AD_REQUESTS_RPM', 'EARNINGS'
	);
	$filter = array(
		'APP_ID==' . $AppId
	);
	$optParams = array(
	  'currency' => 'USD',
	  'metric' => $metrics,
	  'dimension' => 'DATE',
	  'sort' => '+DATE',
	  'filter' => $filter,
	  'useTimezoneReporting'=>true
	);
	$result = $service->accounts_reports->generate($accountId, $startDate, $endDate, $optParams);
```

**Comment by jdpedrie** [comment]
Hi @karam89,

After reviewing your code and the API documentation, I've not been able to determine how you can fetch the report you need or download reports via the API.

Unfortunately, we are not well positioned here to answer questions beyond those specific to the use of, and problems with, this client. For questions specific to an API itself, I'll refer you to [Stackoverflow](http://stackoverflow.com/questions/tagged/adsense-api). Ask a question there, tag it as `adsense-api`, and someone with more knowledge of the Adsense API should be able to better assist.
