### ISSUE TITLE
People API needs an update (personFields not found)

### ISSUE THREAD

**Issue by RoyIL** [googleapis/google-api-php-client#1618]
PHP Version: 7.2 
It seems that there is a problem with Google People API, here is the error I get: 
` Uncaught Google_Exception: (get) unknown parameter: 'personFields' in C:\xampp\htdocs\TestProject\google-api-php-client-2.2.2\src\Google\Service\Resource.php:147 `
Here is the code I used: 
```
        $myPeople = new Google_Service_People($gClient);
        $me = $myPeople->people->get(
            'people/me', array('personFields' => 'names,emailAddresses'));
```
Thank you!

**Comment by RoyIL** [comment]
Comment: I changed the personFields parameter to array('requestMask.includeField' => 'person.names') 
However when I login it doesn't even ask me for permission to read my information (Google_Service_People::USERINFO_PROFILE) and when I call the client it says I don't have enough perms to read the info (Request had insufficient authentication scopes).

**Comment by jdpedrie** [comment]
Try...

```php
$my = $myPeople->people->get('people/me', [
    'requestMask' => [
        'includeField' => 'names'
    ]
]);
```

Generally, the [API documentation](https://developers.google.com/people/api/rest/v1/people/get), used in conjunction with the PHP docblocks, will help in answering questions more clearly than the docblocks alone.

**Comment by RoyIL** [comment]
Hmmm @jdpedrie 
`Fatal error: Uncaught Google_Exception: (get) unknown parameter: 'requestMask' in C:\xampp\htdocs\MyProject\google-api-php-client-2.2.2\src\Google\Service\Resource.php:147 Stack trace: #0 C:\xampp\htdocs\MyProject\google-api-php-client-2.2.2\vendor\google\apiclient-services\src\Google\Service\People\Resource\People.php(52): Google_Service_Resource->call('get', Array, 'Google_Service_...') #1 `

**Comment by jdpedrie** [comment]
Sorry about that @RoyIL, the docs are unclear here.

Try this:

```php
$client = new Google_Client();
$client->addScope([
  Google_Service_People::USERINFO_PROFILE
]);

$people = new Google_Service_People($client);
print_r($people->people->get('people/me', [
  'requestMask.includeField' => 'person.names'
]));
```

Using an OAuth token with the `Google_Service_People::USERINFO_PROFILE` scope, I get a successful response using that snippet.

**Comment by jdpedrie** [comment]
I'm going to close this. If you're still experiencing trouble, please re-open.

**Comment by hervehobbes** [comment]
Hello,

Isn't _RequestMask_ deprecated ?
As stated here:
https://developers.google.com/people/api/rest/v1/RequestMask

So in People.php, line 92, we should use:

`
'personFields' => array(
`

instead of 

`
'requestMask.includeField personFields' => array( 
`
