### ISSUE TITLE
ERROR in https://developers.google.com/drive/api/v3/search-files

### ISSUE THREAD

**Issue by 4mesolutions** [googleapis/google-api-php-client#1619]
Hello,

There is a error in the [EXAMPLES](https://developers.google.com/drive/api/v3/search-files) page for PHP....

The example shows the code `$pageToken = $repsonse->pageToken;`

But it is wrong and it wont work....

It needs to be: `$pageToken = $repsonse->nextPageToken;`

**Comment by jdpedrie** [comment]
Please use the "Send Feedback" link on the linked documentation page to let them know about documentation errors. :)

![Screen Shot 2019-04-24 at 10 25 44 AM](https://user-images.githubusercontent.com/89034/56667186-5b488280-667b-11e9-9614-b7d5cddf7e31.png)
