### ISSUE TITLE
Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.

### ISSUE THREAD

**Issue by 4mesolutions** [googleapis/google-api-php-client#1620]
I am really stuck with this... I followed the instructions on [Issue 801](https://github.com/googleapis/google-api-php-client/issues/801) and authorized my APP. It is now shown on  [your authorized clients](https://myaccount.google.com/permissions).

But I am getting a error: 

> Message: { "error": "unauthorized_client", "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested." }

My email is gabriel***paiva@gmail.com ... 

Bellow is a simple function to create a FOLDER inside the drive...

```php
function newFolder() {
       
        require_once APPPATH . 'third_party/google-api-php-client-2.2.2/vendor/autoload.php';

        putenv('GOOGLE_APPLICATION_CREDENTIALS='. APPPATH . 'third_party/google-api-php-client-2.2.2/Asist-428f3540df9a.json');
        $client = new Google_Client();
        $client->useApplicationDefaultCredentials();
        //$client->setAuthConfig(APPPATH . 'third_party/google-api-php-client-2.2.2/Asist-428f3540df9a.json');
        $client->addScope("https://www.googleapis.com/auth/drive");
        $client->setSubject('gabriel***paiva@gmail.com');

        $driveService = new Google_Service_Drive($client);

        $fileMetadata = new Google_Service_Drive_DriveFile(array(
            'name' => 'new folder name',
            'mimeType' => 'application/vnd.google-apps.folder'));
        $file = $driveService->files->create($fileMetadata, array(
            'fields' => 'id'));
        printf("Folder ID: %s\n", $file->id);
    }
```

**Comment by jdpedrie** [comment]
Your example is using the Application Default Credentials. Could it be that those credentials are different from the service account used to create the authorized client?

**Comment by 4mesolutions** [comment]
Hello Sir,

Thank you very much for the quick response !

I have created only one credential for my project... I think that it is not possible that I used the wrong one.... Is there a way to verify that ?

I tried to do the entire process again, with a different gmail account and I got the same error... 

![image](https://user-images.githubusercontent.com/46403653/56683732-8abfb500-66a4-11e9-856e-09b6607a9367.png)

![image](https://user-images.githubusercontent.com/46403653/56683865-d83c2200-66a4-11e9-9512-b432bb3d96e4.png)

Here is my code:

`    function NovaPasta() {

        
        require_once APPPATH . 'third_party/google-api-php-client-2.2.2/vendor/autoload.php';

        $client = new Google_Client();
        $client->setAuthConfig(APPPATH . 'third_party/google-api-php-client-2.2.2/Asist-428f3540df9a.json');
        $client->addScope("https://www.googleapis.com/auth/drive");
        $client->setSubject('tallitarm@gmail.com');

        $driveService = new Google_Service_Drive($client);

        $fileMetadata = new Google_Service_Drive_DriveFile(array(
            'name' => 'new folder name',
            'mimeType' => 'application/vnd.google-apps.folder'));
        $file = $driveService->files->create($fileMetadata, array(
            'fields' => 'id'));
        printf("Folder ID: %s\n", $file->id);
    }
`
Is there anything I can do to verify this ?

THANK YOU VERY MUCH !

**Comment by ComradePashka** [comment]
Hello!

I had similar issue and reproduce all steps in #801 but got same `unauthorized_client` error message.
Finally I remove lines that use service account credentials:

```
putenv('GOOGLE_APPLICATION_CREDENTIALS='some/path/to/service_account_credentials.json');
$client->useApplicationDefaultCredentials();
$client->setSubject('service_account@gmail.com');
```

and instead added code that refreshes tokens:

```
$client->setAuthConfig('some/path/to/oauth_2_0_client_with_type_other.json');
$credentials_file = 'some/path/to/real/credentials.json';
if (file_exists($credentials_file)) {
    $accessToken = json_decode(file_get_contents($credentials_file), true);
} else {
    $accessToken = "MUST BE CREATED!!!"; // real creation process must be placed here
}
$client->setAccessToken($accessToken);
if ($client->isAccessTokenExpired()) {
    $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
    file_put_contents($credentials_file, json_encode($client->getAccessToken()));
}
```

and everything start working well. In my case I using Gmail API and also going to add Drive API.
I am still not sure, but probably service accounts are working as described only with G-Suite accounts (as also was mentioned in last message in #801 but not confirmed yet) and have no any sense for regular google accounts.

**Comment by tmatsuo** [comment]
Drive API needs OAuth2

> Your application must use OAuth 2.0 to authorize requests.

https://developers.google.com/drive/api/v3/about-auth
