### ISSUE TITLE
Fail to try to return data from Google_Service_Drive_Resource About->get

### ISSUE THREAD

**Issue by valeck** [googleapis/google-api-php-client#1622]
- OS: Linux
  - PHP version: 7.xx
  - Package name and version: google-api-php-client 2.2.2

#### Steps to reproduce

1..Click on the login button

2..Accept authentication window

3 ... the error occurs when trying to recover the user's information using the methods about-> get ().
In the method createRequestUri is not passing the data correctly
File: vendor / google / apiclient / src / Google / Service / Resource.php
Line: 191
Function: createRequestUri
Annex source code of the petition and screenshot of the return

```php
 $this->client = new Google_Client();
      $this->client->setApplicationName('report');
      $this->client->setClientId($this->CI->config->item('client_id'));
      $this->client->setClientSecret($this->CI->config->item('client_secret'));
      $this->client->setRedirectUri($this->CI->config->item('redirect_uri'));
      $this->client->setAccessType("offline");
      $this->client->setScopes(array(
      	"https://www.googleapis.com/auth/drive",
      	"https://www.googleapis.com/auth/drive.file",
      	"https://www.googleapis.com/auth/drive.readonly",
	"https://www.googleapis.com/auth/drive.metadata.readonly",
      )
    );

   $drive = new Google_Service_Drive($this->client);
   $drive->about->get(array('user'))


    $url = $this->createRequestUri(
        $method['path'],
        $parameters
    );
```

This result:
`
![screencapture-proyecti-website-analytics-2019-04-28-02_06_33](https://user-images.githubusercontent.com/13982886/56860276-71479300-695a-11e9-80dd-ad394b1bf443.png)

The fault is presented here because the $ method ['parameters'] array should be passed, so that it works correctly, but when modifying that part the following error is presented

```php
    $url = $this->createRequestUri(
        $method['path'],
        $method['parameters']
    );

if ($paramSpec['location'] == 'query') {

        if (is_array($paramSpec['value'])) {
          foreach ($paramSpec['value'] as $value) {
            $queryVars[] = $paramName . '=' . rawurlencode(rawurldecode($value));
          }
        } else {
          $queryVars[] = $paramName . '=' . rawurlencode(rawurldecode($paramSpec['value']));
        }
      }
```

![screencapture-proyecti-website-analytics-2019-04-28-02_06_33 (1)](https://user-images.githubusercontent.com/13982886/56860462-5bd36880-695c-11e9-848f-0b1cec2302ad.png)

I hope the information is enough to solve this bug and get the necessary information.

**Comment by jdpedrie** [comment]
The underlying error is the last one in your screenshot, i.e. "The 'fields' parameter is required for this method."

To fix it, modify your call to `get()`:

```php
$drive->about->get([
    'fields' => 'user'
]);
```

By making this change, I received the expected response from the API.

If for any reason that doesn't do the trick, please let me know and re-open the issue. :)
