### ISSUE TITLE
Bad request in Google_Service_AndroidPublisher

### ISSUE THREAD

**Issue by mitskovets** [googleapis/google-api-php-client#1627]
#### Environment details

  - OS: Windows 7
  - PHP version: 7.1.5
  - Package name and version: Google_Service_AndroidPublisher v3

#### Return error

   { "error": { "errors": [ { "domain": "global", "reason": "invalid", "message": "Bad request" } ], "code": 400, "message": "Bad request" } }

#### Code example

```php
include_once __DIR__ . '/../vendor/autoload.php';

$client_id = 'client_id';
$client_secret = 'client_secret';
$redirect_uri = 'http://api-google-test.site';
$package_name = "package_name";

$client = new Google_Client();
$client->setApplicationName($package_name);
$client->setClientId($client_id);
$client->setClientSecret($client_secret);
$client->setRedirectUri($redirect_uri);
$client->addScope(Google_Service_AndroidPublisher::ANDROIDPUBLISHER);
$client->setAccessType('offline');

if(!$client->getAccessToken() && !isset($_GET['code'])) {
	$authUrl = $client->createAuthUrl();
	echo "<a class='login' href='$authUrl'>Connect Me!</a>";
}

if(isset($_GET['code'])){
	$accessToken = $client->fetchAccessTokenWithAuthCode($_GET['code']);
}

if (isset($accessToken)){
	print "<a class='logout' href='".$_SERVER['PHP_SELF']."?logout=1'>LogOut</a><br>";

	$service = new Google_Service_AndroidPublisher($client);

	$optParams = array(
		"maxResults"=>10,
		"startIndex"=>0,
		"token"=> $accessToken['access_token'],
		"translationLanguage"=>"en"
	);

	try {
		$response = $service->reviews->listReviews($package_name,$optParams);
		echo "<pre>".print_r($response,true)."</pre>";
	}
	catch (Google_Service_Exception $e) {
		$json = $e->getMessage();
		echo $json;
	}
}
```

How to get a list of reviews?
Thanks

**Comment by jdpedrie** [comment]
Are you certain you've authenticated correctly? Try sending a different request to a different service to verify authentication status.

**Comment by mitskovets** [comment]
If I use the code from the example 
```
$service = new Google_Service_Books ($client);
$optParams = array ('filter' => 'free-ebooks');
$results = $service-> volumes-> listVolumes ('Henry David Thoreau', $optParams);
foreach ($results as $item) {
echo $ item ['volumeInfo'] ['title'], "<br /> \ n";
}
```
then the answer is: {"error": {"errors": [{"domain": "global", "reason": "insufficientPermissions", "message": "Insufficient Permission: Request had insufficient authentication scopes." }], "code": 403, "message": "Insufficient Permission: Request had insufficient authentication scopes." }}

**Comment by mitskovets** [comment]
And when authenticating, the token is returned
`$accessToken = $client->fetchAccessTokenWithAuthCode($_GET['code']);

Array
(
    [access_token] => ya29.......................................LJw
    [expires_in] => 3600
    [scope] => https://www.googleapis.com/auth/androidpublisher
    [token_type] => Bearer
    [created] => 1557238369
)
`

**Comment by dwsupplee** [comment]
@mitskovets,

The `token` optional parameter is used for pagination, and shouldn't be your access token. The list response should come back with a `nextPageToken`\`previousPageToken` which can be passed in instead.

I'm going to close this out now, but if it doesn't help please feel free to re-open.
