### ISSUE TITLE
Can't run php update.php

### ISSUE THREAD

**Issue by Mikaca** [googleapis/google-api-php-client#1628]
- OS: Windows 10
  - PHP version: 7.1.16
  - Package name and version: google/apiclient 2.2.2/WikiMedia 1.34 Alpha

Hello, I can't run bash command php update.php, which I need to run for updating my db to have the Google Login format. Here's screenshot of it;
![error](https://user-images.githubusercontent.com/50488840/57528375-7f21ee80-7332-11e9-8d61-c19075d91338.PNG)
After running composer update --no-dev:
![error2](https://user-images.githubusercontent.com/50488840/57528597-0c654300-7333-11e9-9694-4ba8c4ab8c24.PNG)
And after that I'm back at first screenshot. Any help/ideas?

**Comment by dwsupplee** [comment]
Hey @Mikaca,

I've just tried to run the update script with a fresh installation of 1.34.0-alpha of MediaWiki and had no problems. Have you tried deleting your vendor directory and composer.lock files prior to running the update script?

**Comment by Mikaca** [comment]
My main idea was to use update.php, so my DB for GoogleLogin would have update with needed information. Somehow the combo of doing update.php, deleting the vendor and composer.lock and composer dump-autoload made it work. 
Many thanks!
