### ISSUE TITLE
Is there a way to check if a refresh token has been revoked ?

### ISSUE THREAD

**Issue by slecutiez-kryzalid** [googleapis/google-api-php-client#1629]
Hey,

First of all I am sorry if my question seems stupid or something but I am a very young developer and english is not my native language.

I am building a tool that makes use of the Google Drive API. I am using Laravel but for some reason had to not use Socialite for managing OAuth access and do it myself.

Long story short I have to reimplement all of the OAuth flow, and it works fine except for the case where a user goes to their Google account settings and revokes the app's access to their account, or for some reason Google decides to revoke said access.

In this case I know that when the user does something that require the Google Drive API, I should take the user to go through the whole process again (logging to their Google account, authorizing the app, etc) but I just can't figure out how I'm supposed to detect whether the access has been revoked or not.

By looking at the issues here or the questions on SO it looks like everyone just ignore this case and are fine with it but I am not. Or perhaps I'm missing something.

I have found [someone](https://stackoverflow.com/a/42675158) that tests if there's an error after trying to make a request, but I can't afford to wait for having to query the API to auth the user. Plus I'm not getting the same error as him (mine is `{ "error": { "errors": [ { "domain": "global", "reason": "authError", "message": "Invalid Credentials", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Invalid Credentials" } }`).

So is there a way to know if the refresh token has been revoked ?

**Comment by dwsupplee** [comment]
Hey there @slecutiez-kryzalid, welcome - and thanks for raising this well thought out question.

Do you know if you happen to be caching access tokens? If so, the cache won't know when the token has been revoked and it will attempt to use the now expired token against the Google Drive API. That would explain the 401 response you are receiving. If you clear out the caching mechanism, you will see the "Token has been expired or revoked" error message upon attempting to get a fresh token.

> it looks like everyone just ignore this case and are fine with it but I am not.

All you really need to worry about is whether the token is expired/revoked and at that point re-authenticate the user - what is the case you think is being ignored?

> So is there a way to know if the refresh token has been revoked ?

If someone has revoked access outside the scope of your application the only way to detect this is with the "Token has been expired or revoked" message received when attempting to fetch a token.

Hopefully this helps, I'm going to close this out now but let me know if there is anything I can do to help clarify.

**Comment by guillefd** [comment]
Code example to refresh a token and confirm it has been revoked :

```php
// somewhere in your code where you set the client() token
// ...
// $accessToken has the value of the previously saved token (the one we don't know yet it is revoked :( )
// set the token
$client->setAccessToken($accessToken);
// refresh the token
$accessTokenRefreshed = $client->fetchAccessTokenWithRefreshToken();
// if the token array has an 'error' element, then the token is invalid
if (isset($accessTokenRefreshed['error'])) {
   echo "Error: ".$accessTokenRefreshed['error_description'];
  // should display: "Error: Token has been expired or revoked."
}
//...
```
