### ISSUE TITLE
Fatal error: Uncaught Google_Service_Exception

### ISSUE THREAD

**Issue by ruwanaru** [googleapis/google-api-php-client#1631]
### This is a Code im Using 

```php
<?php
	require_once 'vendor/autoload.php';
	
	$client = new Google_Client();
$client->setApplicationName("My Application");
$client->setDeveloperKey("[key]");
	
	$service = new Google_Service_Calendar($client);
	
	
	
	
	// Refer to the PHP quickstart on how to setup the environment:
// https://developers.google.com/calendar/quickstart/php
// Change the scope to Google_Service_Calendar::CALENDAR and delete any stored
// credentials.

$event = new Google_Service_Calendar_Event(array(
  'summary' => 'Google I/O 2015',
  'location' => '800 Howard St., San Francisco, CA 94103',
  'description' => 'A chance to hear more about Google\'s developer products.',
  'start' => array(
    'dateTime' => '2019-05-14T09:00:00-07:00',
    'timeZone' => 'America/Los_Angeles',
  ),
  'end' => array(
    'dateTime' => '2019-05-14T17:00:00-07:00',
    'timeZone' => 'America/Los_Angeles',
  ),
  'recurrence' => array(
    'RRULE:FREQ=DAILY;COUNT=1'
  ),
  'attendees' => array(
    array('email' => 'lpage@example.com'),
    array('email' => 'sbrin@example.com'),
  ),
  'reminders' => array(
    'useDefault' => FALSE,
    'overrides' => array(
      array('method' => 'email', 'minutes' => 24 * 60),
      array('method' => 'popup', 'minutes' => 10),
    ),
  ),
));

$calendarId = 'primary';
$event = $service->events->insert($calendarId, $event);
printf('Event created: %s\n', $event->htmlLink);
```

### Im gettinng error of this

```
Fatal error: Uncaught Google_Service_Exception: { "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } } in C:\wamp64\www\google\vendor\google\apiclient\src\Google\Http\REST.php:118 Stack trace: #0 C:\wamp64\www\google\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 C:\wamp64\www\google\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 C:\wamp64\www\google\vendor\google\apiclient\src\Google\Http\REST.php(58): Google_Task_Runner->run() #3 C:\wamp64\www\google\vendor\google\apiclient\src\Google\Client.php(798): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), in C:\wamp64\www\google\vendor\google\apiclient\src\Google\Http\REST.php on line 118
```

**Comment by jdpedrie** [comment]
I'm looking into this. First though, please take a moment to invalidate your developer key and generate a new one. The code snippet you provided included a secret key which could grant access to unauthorized users. Please review the [securing an API key](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) for best practices.

**Comment by jdpedrie** [comment]
Please review the [calendar API quickstart](https://developers.google.com/calendar/quickstart/php) guide. You must provide a scope with permission to create calendar events:

```php
$client->setScopes(Google_Service_Calendar::CALENDAR_EVENTS);
```

You also need an access token. The quickstart guide includes an example of the authentication flow. For testing purposes, you can generate an access token in the [OAuth Playground](https://developers.google.com/oauthplayground) and set it using `setAccessToken()`, as I demonstrate below, however this can only be used for testing. You will need to configure login for your users as demonstrated in Step 3 of the quickstart.

```php
$client->setAccessToken($myAccessToken);
```

To fetch an access token from the playground, enter `https://www.googleapis.com/auth/calendar.events` in the "Input your own scopes" field, and follow the authentication flow until you receive an access token.

**Comment by ruwanaru** [comment]
Thank YOu you have saved me it helped

**Comment by howcouldyouforget** [comment]
I'm getting a similar error running the below

<?php
// include your composer dependencies
require_once 'google-api-php-client/vendor/autoload.php';

define('APPLICATION_NAME', 'XYZserviceaccount');
define('CREDENTIALS_PATH',__DIR__.'/XYZ-calendar-api-5bbae1a294b9.json');
define('SCOPES', implode(' ', array(
    Google_Service_Calendar::CALENDAR)
    ));

putenv('GOOGLE_APPLICATION_CREDENTIALS=C:\Apache24\htdocs\php\XYZ-calendar-api-5bbae1a294b9.json');


$calendarId = 'dan@XYZ.com;   //XYZ I use a real domain where authorization has been granted

$optParams = array(
    'maxResults' => 10,
    'orderBy' => 'startTime',
    'singleEvents' => TRUE,
    'timeMin' => date('c'),
);

$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(SCOPES);

$service = new Google_Service_Calendar($client);
$results = $service->events->listEvents($calendarId, $optParams);
$events = $results->getItems();

if (empty($events)) {
    print "No upcoming events found.\n";
}else {
    foreach ($events->getItems() as $event) {
        $start = $event->start->dateTime;
        if (empty($start)) {
            $start = $event->start->date;
        }
        printf($event->getSummary() . " " . $start . "<br>");
    }
}

Any help would be appreciated.

**Comment by howcouldyouforget** [comment]
I'm getting a similar error running the below:

`<?php
// include your composer dependencies
require_once 'google-api-php-client/vendor/autoload.php';

define('APPLICATION_NAME', 'meetingscienceserviceaccount');
define('CREDENTIALS_PATH',__DIR__.'/meeetingscience-calendar-api-5bbae1a294b9.json');
define('SCOPES', implode(' ', array(
    Google_Service_Calendar::CALENDAR)
    ));
putenv('GOOGLE_APPLICATION_CREDENTIALS=C:\Apache24\htdocs\php\meeetingscience-calendar-api-5bbae1a294b9.json');
$calendarId = 'dan@xyz.ccom';
$optParams = array(
    'maxResults' => 10,
    'orderBy' => 'startTime',
    'singleEvents' => TRUE,
    'timeMin' => date('c'),
);

$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(SCOPES);
$service = new Google_Service_Calendar($client);
$results = $service->events->listEvents($calendarId, $optParams);

$events = $results->getItems();

if (empty($events)) {
    print "No upcoming events found.\n";
}else {
    foreach ($events->getItems() as $event) {
        $start = $event->start->dateTime;
        if (empty($start)) {
            $start = $event->start->date;
        }
        printf($event->getSummary() . " " . $start . "<br>");
    }
}
print "Done!";`

Any help would be appreciated.

**Comment by howcouldyouforget** [comment]
I'm getting a similar error running the below:

`<?php
// include your composer dependencies
require_once 'google-api-php-client/vendor/autoload.php';

define('APPLICATION_NAME', 'xyzserviceaccount');
define('CREDENTIALS_PATH',DIR.'/xyz-calendar-api-5bbae1a294b9.json');
define('SCOPES', implode(' ', array(
Google_Service_Calendar::CALENDAR)
));
putenv('GOOGLE_APPLICATION_CREDENTIALS=C:\Apache24\htdocs\php\xyz-calendar-api-5bbae1a294b9.json');
$calendarId = 'dan@xyz.ccom';
$optParams = array(
'maxResults' => 10,
'orderBy' => 'startTime',
'singleEvents' => TRUE,
'timeMin' => date('c'),
);

$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(SCOPES);
$service = new Google_Service_Calendar($client);
$results = $service->events->listEvents($calendarId, $optParams);

$events = $results->getItems();

if (empty($events)) {
print "No upcoming events found.\n";
}else {
foreach ($events->getItems() as $event) {
$start = $event->start->dateTime;
if (empty($start)) {
$start = $event->start->date;
}
printf($event->getSummary() . " " . $start . "
");
}
}
print "Done!";`

Any help would be appreciated.
