### ISSUE TITLE
Demo code should run. Using Compute Engine Templates using the PHP API

### ISSUE THREAD

**Issue by ftrotter** [googleapis/google-api-php-client#1638]
Hello,
        I am trying to create a compute engine instance from an instance template using the PHP library. 

I understand that I am making a compliant about a specific service, rather than the library as a whole. But if you want me to go find "the best place to go is to the teams for those specific APIs ". I have no idea where that is. And I have already sent these problems as "feedback" to the API page in question. So I am more than happy to go elsewhere to make this compliant, but so far, I have no information on where that compliant can be effectively made. So I am making it here.

Technically, there is a "demo" listed on this page: 

https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

It is profoundly frustrating that this demo code does not work out of the box. There are multiple required components on the "requestBody" object. Some (but frustratingly, not all) of these required fields are described in the document. Others are still required but not listed as [REQUIRED] in the documentation. 

Most frustrating of all is that this API seems to require that I define the CPU, and network configuration AND the compute engine template. What is the point of the template if I have to define all of these things in the template and then I STILL have to detail them in the requestBody? If I have to tall the API exactly what CPU to use... then what is the use of having a template? Needing to repeatedly specify all of the things is the problem that this is supposed to solve. 

Most frustratingly, your demo code is just massively far away from actually running. Your examples are missing all of the details needed to actually get running and instead you have a "TODO" listed. I do not know if this means that there is work for me as the user to do to get this working,  or work that your team has not done yet?

I expect that you should be play-testing your example code. I am dubious that your team has watched someone hit the 5-10 walls where your documentation drops you off a cliff here. Doing that will help you realize that your examples are not nearly good enough. 

To be clear, my expectation is that if I am creating a new instance, and I have a template, and I know by project id, then I would be able to take your example code, insert that template_id and that project_id... and assuming my credentials are valid... that should work with no modification. It would be lovely if the compute instance honored the network settings and CPU sizing in the template. But it would be acceptable if your example had hard-coded medium-level instance specifications to ensure that it just worked.  

Is my expectation that I should be able working example code for all of the Google APIs, and if that is not something that I can expect, then please tell me now so that I can extricate myself from the position of insisting that we use the Google Cloud API services. I know for a fact that I could have gotten the equivalent functionality to work in the amount of time it has taken me to write this. 

I have seen substantial improvements to the overall documentation as the result of previous complaints, and I am hopeful that this can be resolved in a similar manner.

**Comment by ftrotter** [comment]
I am removing some of the emotional bile from this comment as part of my ongoing commitment to non-violent communication.

**Comment by dwsupplee** [comment]
@ftrotter, thanks for filing the report. I can agree that there isn't much guidance on how to create an instance utilizing a template, and my apologies for that. There is a trade off we make when generating client services - on one end we can get products out to users faster, but on the other it means our documentation sometimes need a little extra love.

I did a little testing and here's a snippet exampling how you can create an instance using a template, if you haven't found it out yet already:

```php
$client = new Google_Client;
$service = new Google_Service_Compute($client);
$project = '[YOUR_PROJECT]';
$zone = '[YOUR_ZONE]';
$requestBody = new Google_Service_Compute_Instance();
$requestBody->setName('blah');

$response = $service->instances->insert($project, $zone, $requestBody, [
	'sourceInstanceTemplate' => '[YOUR_TEMPLATE]'
]);
```

I'll see what we can do about making required parameters more obvious, although there may already be some traction on this given your report on the API documentation page.

**Comment by ftrotter** [comment]
Thanks for the help!

I am happy to close the comment because I did figure out the solution to the problem.. I had not noticed that at the bottom of every page on the cloud console there is a link that shows how you would do what you are doing with the GUI via REST. 

This is enough to actually reverse engineer what I need to do to leverage a template and to get a cloud instance running.

I very much appreciate your efforts here, and I think I would likey be able to work from your reply to get an instance up as well. 

But I think the deeper issue here is that your php-based per-API documentation is actually not terrible reflective of what the API needs in order to function. I have 3 suggestions. 

First, in the place of TODO on the documentation of every php example on every individual service instead say "see REST generator in the google console GUI for exact parameter values" and then link to a video that shows how to get to the curl command generator for each API action. 

Second, rather than just generating the raw curl compatible command to run. You should just autogenerate a working code example for every language that you support and have it in tabs. https://txt2re.com/ does a brilliant job of this kind of trivial code generation. 

Third, you should host the code for your examples in the documentation directory of this example. Right now, you have solved my problem for me, and I think I have solved my own problem too, but hundreds of PHP programmers a week hit a wall of the code example in the  API, and none of them are going to come here and read your solution. Instead, if the example itself were sourced from here, then you would be actually fixing the master version and adding your improvements to the example. 

In any case, I thank you for your help with this issue and you are welcome to close the issue now, as the initial problem I had is now solved. 

Regards,
-ft

**Comment by dwsupplee** [comment]
Really appreciate the thoughts @ftrotter, we'll work towards making improvements on our docs. 👍
