### ISSUE TITLE
outdated version on packagist

### ISSUE THREAD

**Issue by recipe** [googleapis/google-api-php-client#1639]
when I try to update google/apiclient to v2.2.3 it's showing:

`Could not find package google/apiclient in a version matching 2.2.3` 

[Packagist](https://packagist.org/packages/google/apiclient) shows v2.2.2 as latest version

**Comment by DHANDAPANISATTANATHAN** [comment]
using this `composer require google/apiclient:"^2.0"`

I can download V2.2.2.

**Comment by recipe** [comment]
I've already had 2.2.2 and would like to test against v2.2.3

**Comment by jdpedrie** [comment]
Thanks for the heads up. We'll get this addressed today.

**Comment by jdpedrie** [comment]
Please give it another shot. v2.2.3 is now available on packagist. Sorry for the inconvenience!
