### ISSUE TITLE
Error caused by guzzle psr-7 update

### ISSUE THREAD

**Issue by rajeshjayan60** [googleapis/google-api-php-client#1661]
#### Environment details

  - OS: Ubuntu
  - PHP version: 5.6
  - Package name and version: Google api client 2.2.3

#### Error

```
Header value must be a string or an array of strings.
```

#### Code

```php
$token = $client->fetchAccessTokenWithAuthCode($code);
```

The latest update to Guzzle psr7 https://github.com/guzzle/psr7/pull/250, causes an error with google api client when trying to fetch an access token.

To fix it I had to downgrade the Guzzle psr7 version to 1.5.2 in composer.json

```
"guzzlehttp/psr7": "1.5.2"
```

**Comment by agwidarsito** [comment]
Thanks rajeshjayan60, I too am getting errors but I'm yet to identify which of the packages is using Guzzle in a way that's causing it.

**Comment by agwidarsito** [comment]
Update: This breaks the aws/aws-sdk-php package version 3.99.2 S3 client

**Comment by jdpedrie** [comment]
v1.5.2 is the latest release of `guzzlehttp/psr7`, so I'm not sure what you are downgrading from. Are you using dev-master or another unreleased version of the dependency? We don't recommend relying on unreleased package versions when it can be avoided.

It appears that they've merged a fix for this already: https://github.com/guzzle/psr7/pull/272

**Comment by rajeshjayan60** [comment]
Thanks for the reply. It seems my `guzzlehttp/psr7` dependency was pointing to dev-master. Changing the `minimum-stability ` to `stable` in composer.json seems to do the trick.
