### ISSUE TITLE
Overwrite user agent (suffix included)

### ISSUE THREAD

**Issue by Grafikart** [googleapis/google-api-php-client#1662]
## The problem 

I'm currently using this library with GoogleMyBusiness. When my request is incorrect I get an error with status `INVALID_ARGUMENT` without the details. 

```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
}
```

I investigated further and Google servers seems to skip the details if the user-agent include `google-api-php-client`. Here is the same request without the user agent

```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.mybusiness.v4.ValidationError",
        "errorDetails": [
          {
            "code": 10,
            "field": "photos.additional_photo_urls",
            "message": "Image too small. Got: 283px/200px (min: 250px/250px w/h).",
            "value": "XXXXXX",
            "subErrorCode": 21
          }
        ]
      }
    ]
  }
}
```

*Much easier to debug* ;)

Still this is a very odd move from Google to strip some information based on the user agent :(

## The solution
Currently there is no way to completely overwrite the user agent set by the request. 
Adding this to the config option would solve the problem. 
https://github.com/googleapis/google-api-php-client/blob/master/src/Google/Client.php#L792

## Alternative solution
Another solution is to create a new Class in the userland that extends `Google_Client` where we overwrite the `execute()` method.

**Comment by jdpedrie** [comment]
Hi @Grafikart,

Thanks for bringing this to our attention. Could you share code which demonstrates the behavior you report? This will help us in making sure any changes we make address your specific concern.

**Comment by jdpedrie** [comment]
Hi @Grafikart,

I think #1644 may help with this. Can you give it a shot, and if it doesn't address your concerns, feel free to reopen this and we'll investigate our options further.
