### ISSUE TITLE
Documentation site redirects back to github

### ISSUE THREAD

**Issue by mvanbaak** [googleapis/google-api-php-client#1663]
Starting today, http://developers.google.com/api-client-library/php and all pages under it are redirecting to this github repo.
So now the complete documentation about this library is offline.

**Comment by dwsupplee** [comment]
Thanks for raising this @mvanbaak, we are working on getting the referenced documentation site up and running until we have a replacement for it in place.

**Comment by grant** [comment]
The repo description has been removed. When @dwsupplee has a proper URL, he will add it.
