### ISSUE TITLE
How to Create new Contact using People API with multiple values

### ISSUE THREAD

**Issue by ruwanaru** [googleapis/google-api-php-client#1664]
### these codes are working but i cannot push multiple phone numbers and email addresses  

```php
    $person = new Google_Service_PeopleService_Person();
    

    $name = new Google_Service_PeopleService_Name();
    $name->setGivenName('00nirman');
    $name->setFamilyName('weerasinghe');
    $person->setNames($name);

$email1 = new Google_Service_PeopleService_EmailAddress();
    $email1->setValue('test@example.com');
    $person->setEmailAddresses($email1);

$phone1 = new Google_Service_PeopleService_PhoneNumber();	
    $phone1->setValue('0777677305');
	$phone1->setType('home');
    $person->setPhoneNumbers($phone1);
   $exe = $people_service->people->createContact($person)->execute;
```

Is there any way to do that

**Comment by jdpedrie** [comment]
Provide the email addresses and phone numbers as arrays of objects:

```php
$email1 = new Google_Service_PeopleService_EmailAddress();
$email1->setValue('test@example.com');

$email2 = new Google_Service_PeopleService_EmailAddress();
$email2->setValue('test2@example.com');

$person->setEmailAddresses([$email1, $email2]);
```

**Comment by ruwanaru** [comment]
> Provide the email addresses and phone numbers as arrays of objects:
> 
> ```
> $email1 = new Google_Service_PeopleService_EmailAddress();
> $email1->setValue('test@example.com');
> 
> $email2 = new Google_Service_PeopleService_EmailAddress();
> $email2->setValue('test2@example.com');
> 
> $person->setEmailAddresses([$email1, $email2]);
> ```

than you
this is working im using this one for now 
but this is creating objects for every email i'm looking other options to use easily
example calendar Api creating events

**Comment by jdpedrie** [comment]
Please explain in more depth what you are looking for. I'm not sure what you mean.

**Comment by ruwanaru** [comment]
> Please explain in more depth what you are looking for. I'm not sure what you mean.

Instead of Using This

```
$email1 = new Google_Service_PeopleService_EmailAddress();
$email1->setValue('test@example.com');

$email2 = new Google_Service_PeopleService_EmailAddress();
$email2->setValue('test2@example.com');
``` 
similer format like this 

```

$event = new Google_Service_Calendar_Event(array(
  'summary' => 'Google I/O 2015',
  'location' => '800 Howard St., San Francisco, CA 94103',
  'description' => 'A chance to hear more about Google\'s developer products.',
  'start' => array(
    'dateTime' => '2019-05-27T09:00:00',
    'timeZone' => 'Asia/Colombo',
  ),
  'end' => array(
    'dateTime' => '2019-05-27T17:00:00',
    'timeZone' => 'Asia/Colombo',
  ),
  'recurrence' => array(
    'RRULE:FREQ=DAILY;COUNT=1'
  ),
  'attendees' => array(
    array('email' => 'lpage@example.com'),
    array('email' => 'sbrin@example.com'),
  ),
  'reminders' => array(
    'useDefault' => FALSE,
    'overrides' => array(
      array('method' => 'email', 'minutes' => 24 * 60),
      array('method' => 'popup', 'minutes' => 10),
    ),
  ),
));

```

**Comment by jdpedrie** [comment]
```php
$person = new Google_Service_PeopleService_Person([
    'names' => [
        [
            'givenName' => 'foobar',
            'familyName' => 'barfoo'
        ]
    ],
    'emailAddresses' => [
        [
            'value' => 'test@example.com'
        ], [
            'value' => 'test2@example.com'
        ]
    ],
    'phoneNumbers' => [
        [
            'value' => '0777677305',
            'type' => 'home'
        ],
        [
            'value' => '0777677305',
            'type' => 'mobile'
        ],
    ]
]);

$exe = $service->people->createContact($person);
```

**Comment by ruwanaru** [comment]
> ```
> $person = new Google_Service_PeopleService_Person([
>     'names' => [
>         [
>             'givenName' => 'foobar',
>             'familyName' => 'barfoo'
>         ]
>     ],
>     'emailAddresses' => [
>         [
>             'value' => 'test@example.com'
>         ], [
>             'value' => 'test2@example.com'
>         ]
>     ],
>     'phoneNumbers' => [
>         [
>             'value' => '0777677305',
>             'type' => 'home'
>         ],
>         [
>             'value' => '0777677305',
>             'type' => 'mobile'
>         ],
>     ]
> ]);
> 
> $exe = $service->people->createContact($person);
> ```

You are a lifesaver thank you very much this code are working
