### ISSUE TITLE
Get Resource Name while creating a contact using People API

### ISSUE THREAD

**Issue by ruwanaru** [googleapis/google-api-php-client#1666]
This is the code im using how can i define or get the server generated ResourceName

```
$people_service = new Google_Service_PeopleService($client);
    $person = new Google_Service_PeopleService_Person();

    $name = new Google_Service_PeopleService_Name();
    $name->setGivenName('00nirman');
    $name->setFamilyName('weerasinghe');
    $person->setNames($name);

	$email1 = new Google_Service_PeopleService_EmailAddress();
    $email1->setValue('test@example.com');
    $person->setEmailAddresses($email1);

$phone1 = new Google_Service_PeopleService_PhoneNumber();
$phone2 = new Google_Service_PeopleService_PhoneNumber();
$phone1->setValue('0777677305');
$phone2->setValue('0774112128');
$person->setPhoneNumbers([$phone1,$phone2]);


$exe = $people_service->people->createContact($person)->execute;
```

**Comment by jdpedrie** [comment]
Use the following:

```php
$exe = $people_service->people->createContact($person);
$name = $exe->getResourceName();
```

The resource name is assigned by the server and cannot be manually set or modified.

**Comment by ruwanaru** [comment]
> Use the following:
> 
> ```
> $exe = $people_service->people->createContact($person);
> $name = $exe->getResourceName();
> ```
> 
> The resource name is assigned by the server and cannot be manually set or modified.

Thank you Very much you save lots of time  this code is working

**Comment by ruwanaru** [comment]
> Use the following:
> 
> ```
> $exe = $people_service->people->createContact($person);
> $name = $exe->getResourceName();
> ```
> 
> The resource name is assigned by the server and cannot be manually set or modified.

Thank you Very much you save lots of time this code is working
