### ISSUE TITLE
Undefined Method Google_Service_ShoppingContent_Product::setProductType()

### ISSUE THREAD

**Issue by eojeel** [googleapis/google-api-php-client#1667]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Centos 7
  - PHP version: 7.4
  - Package name and version:
https://packagist.org/packages/google/apiclient
2.2.2 & 2.2.3

#### Steps to reproduce

  1. ...

Send a product using the SetProductType() Method results in Fatal error: Uncaught Error: Call to undefined method Google_Service_ShoppingContent_Product::setProductType(), 2.2.2 & 2.2.3, refresh installs of the API via composer. 

Setting product 

#### Code example

Issue solely with the below method
```php
$product->setProductType()
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by eojeel** [comment]
Fixed by moving to productTypes[], as document suggests https://developers.google.com/shopping-content/v2/reference/v2.1/products/insert.

code still includes productType() possible needs removing. 

closing as issue resolved. via updated method.

**Comment by nei** [comment]
BREAKING CHANGE introduced on the latest minor version.
