### ISSUE TITLE
Minor broken link in README

### ISSUE THREAD

**Issue by coderintherye** [googleapis/google-api-php-client#1669]
#### Steps to reproduce

  1. Go to https://github.com/googleapis/google-api-php-client/ or open up the README file
  2. Click or open the link in "Follow the instructions to Create a Service Account"
  3. See that it does not take you to the intended location

**Comment by dwsupplee** [comment]
Good catch @coderintherye, really appreciate the call out. We recently changed up our documentation site (it is currently hosted here, on GitHub). We'll get this fixed shortly.

**Comment by coderintherye** [comment]
thanks for fixing it so fast @dwsupplee !
