### ISSUE TITLE
Remove attendee from Calendar API

### ISSUE THREAD

**Issue by ruwanaru** [googleapis/google-api-php-client#1671]
i Have Used this code to update the calendar with a new attendee

```
$event = $service->events->get('primary', $geid);

$attendee1 = new Google_Service_Calendar_EventAttendee();
     $attendee1->setEmail($remail);
     $attendees = array($attendee1);
$event->attendees = $attendees;
$updatedEvent = $service->events->update('primary', $event->getId(), $event);
```

**I want to remove the attendee from the calendar can someone help with this**
@jdpedrie

**Comment by jdpedrie** [comment]
Remove the attendee from the list of attendees and update the resource.

For instance, if your event has a single attendee, update with an empty list:

```php
$event = $service->events->get('primary', $eventId);
$event->setAttendees([]);

print_r($service->events->update('primary', $eventId, $event));
```

If your event has multiple attendees, filter the list:
```php
$event = $service->events->get('primary', $eventId);

$attendees = array_filter($event->getAttendees(), function ($attendee) {
   // Remove the attendee with `foo@bar.com` email.
   return $attendee->getEmail() !== 'foo@bar.com';
});
$event->setAttendees($attendees);

print_r($service->events->update('primary', $eventId, $event));
```

**Comment by ruwanaru** [comment]
> Remove the attendee from the list of attendees and update the resource.
> 
> For instance, if your event has a single attendee, update with an empty list:
> 
> ```
> $event = $service->events->get('primary', $eventId);
> $event->setAttendees([]);
> 
> print_r($service->events->update('primary', $eventId, $event));
> ```
> 
> If your event has multiple attendees, filter the list:
> 
> ```
> $event = $service->events->get('primary', $eventId);
> 
> $attendees = array_filter($event->getAttendees(), function ($attendee) {
>    // Remove the attendee with `foo@bar.com` email.
>    return $attendee->getEmail() !== 'foo@bar.com';
> });
> $event->setAttendees($attendees);
> 
> print_r($service->events->update('primary', $eventId, $event));
> ```

Thank you This is working

**Comment by JosephGabito** [comment]
According to php docs: https://www.php.net/manual/en/function.array-filter.php

`Array keys are preserved, and may result in gaps if the array was indexed. The result array can be reindexed using the [array_values()](https://www.php.net/manual/en/function.array-values.php) function.`

Make sure to re-index the `$attendees` 
by

 `$event->setAttendees( array_values( $attendees ) );`
