### ISSUE TITLE
Medium security risk in REST.php (Reflection Injection)

### ISSUE THREAD

**Issue by seegitter** [googleapis/google-api-php-client#1674]
#### Environment details
  - OS: Windows 10
  - PHP version: 7.2
  - Package name and version: google/apiclient: 2.2.3

#### Steps to reproduce
Run a code scanning tool that analyzes risks

#### Code example
Suspicious code (REST.php line 125-128):
```php
    if ($expectedClass = self::determineExpectedClass($expectedClass, $request)) {
      $json = json_decode($body, true);
      return new $expectedClass($json);
    }
```

#### Output of the code scanning tool

ASVS: 4.0.1: 5.2.4
OWASP Top 10: 2017: A5
CWE: 470
SANS 25: Rank 16
PCI DSS: 6.5.8
Severity: Medium

Issue #2976336 - include/vendor/google/apiclient/src/Google/Http/REST.php: 128
Path: include/vendor/google/apiclient/src/Google/Http/REST.php
Line: 128
Sink:
Source: _SERVER
Taint: HTTP

The HTTP header 'X-PHP-EXPECTED-CLASS' is received in line 157 of the file include/vendor/google/apiclient/src/Google/Http/REST.php in the method Google_Http_REST::determineExpectedClass(). The user-supplied data is then used unsanitized in line 128 of the file include/vendor/google/apiclient/src/Google/Http/REST.php in the method Google_Http_REST::decodeHttpResponse().

A reflection injection vulnerability occurs when unsanitized user input is used as a function or
method name. An attacker can call arbitrary functions or methods which can lead to unexpected
control flow of the application. For example, it can be abused to bypass authentication or access
control checks.
To prevent abuse, it is necessary to make sure that user input cannot freely invoke any code of
the attackers choice that could lead to unintended behavior. This is best achieved by verifying
the supplied function or method name against a whitelist before invoking it.

**Comment by jdpedrie** [comment]
Thanks for bringing these to our attention. We're investigating.

**Comment by dwsupplee** [comment]
@jdpedrie any update on this?

**Comment by jdpedrie** [comment]
Yeah, I had a draft idea [here](https://github.com/googleapis/google-api-php-client/pull/1676).

**Comment by jdpedrie** [comment]
I'll continue tracking this in the pull request.
