### ISSUE TITLE
redirect_uri_mismatch when requesting anything other than profile scope

### ISSUE THREAD

**Issue by joncojonathan** [googleapis/google-api-php-client#1679]
I've searched and reviewed the other support issues but they don't seem to quite match my scenario.  Any advice would be appreciated.

I have a Yii2 based application currently using the following library versions:
```
google/apiclient                   v2.2.3             Client library for Google APIs
google/apiclient-services          v0.104             Client library for Google APIs
google/auth                        v1.5.1             Google Auth Library for PHP
yiisoft/yii2                       2.0.23             Yii PHP Framework Version 2
yiisoft/yii2-authclient            2.1.8              External authentication via OAuth and OpenID for the Yii framework
```

I have my Google OAuth API key and have set the authorised Javascript origins and authorised redirect URIs.  I can see in the response from Google that the `redirect_uri` matches what's in the API console _exactly_, there are no trailing slashes or differences.

If I set my application's scope to `profile` I'm able to use Oauth fine.  If I change the scope to be `userinfo.profile` or `userinfo.email` I get `HTTP 400 Bad Request (redirect_uri_mismatch)`.  At no point have I changed the redirect URI, which continues to match _exactly_ what I have in the API console.

My request is being sent to https://accounts.google.com/o/oauth2/auth.  In the developer console, under "OAuth consent screen", I can see I'm allowed to use `email` (https://www.googleapis.com/auth/userinfo.email), `profile` (https://www.googleapis.com/auth/userinfo.profile) and `openid` (openid).  These addresses match the request that's being sent to Google:

```
https://accounts.google.com/o/oauth2/auth?
client_id=SECRET_CLIENT_ID_STRING
&response_type=code
&redirect_uri=SECRET_REDIRECT_URI_MATCHES_CONSOLE
&xoauth_displayname=Management
&scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
&state=STATE_STRING
```

Can anyone offer any advice please?  I'm completely stumped as everything matches exactly.

Thanks in advance.

**Comment by bjosephpare** [comment]
What was your solution? I am experiencing the same issue.

**Comment by joncojonathan** [comment]
Hi @bjosephpare.  In the end the problem seemed to be how my web application was sending the data through to Google.  The web application was sending everything after `&redirect_uri` as part of that parameter, which Google was correctly rejecting.

In the end we re-architected part of the web application to change the address that was calling Google.  Originally our app called Google for OAuth via `https://example.org/site/auth&authclient=google` which was causing the problem.  Instead we now `https://example.org/site/auth/google` which seems to be fine.  Required a re-write of our internal page routing (Yii2).

Hope that helps!

**Comment by bjosephpare** [comment]
Thanks for following up!

In my case - it seemed I had to put "postmessage" as the redirect URL in making my request. Google's documentation somehow makes no mention of this very specific requirement...
