### ISSUE TITLE
oAuth get refresh token from second time with out using prompt =consent

### ISSUE THREAD

**Issue by BandaSatish07** [googleapis/google-api-php-client#1686]
Hi Team,

How can we get refresh a token with out using consent screen.

My case here. 
We have prompt=consent initially and we got refresh token every time and consent screen displays every time. Now we want to change prompt = select_account so that consent screen wont appears again and again. But if change we are missing *refresh token* which we need to process further. Earlier we didn't saved refresh token for users, now if we change prompt=select_account we are not getting *refresh token* once user logged in.

I've tried prompt="consent"/ "select_account"/ "none"

Please suggest us way to achieve this to remove consent screen again and again for users and also to get refresh token with out affecting the already logged in users. 

Earliest reply more help full for us.

Thanks.

**Comment by jdpedrie** [comment]
Refresh tokens are only provided on the first user authorization, or when prompt is set to consent. Unfortunately, in order to get a new refresh token, you will need to ask your users to consent again.
