### ISSUE TITLE
Translate Service problem

### ISSUE THREAD

**Issue by CedNet** [googleapis/google-api-php-client#169]
Hi! Something has happened to the getTranslation method in the Translate class. I get NULL returned. On my production server stuff works as I've not updated the package there, but in my development environment where I've updated packages more recently... translate don't work properly.

Test scenario:
var_dump() the $response and you'll see it has protected translaction data that is not returned by getTranslations() correctly. 

The var dump echos

```
object Google_Service_Translate_TranslationsListResponse (5) {
protected translationsType -> string (45) "Google_Service_Translate_TranslationsResource"
protected translationsDataType -> string (5) "array"
protected collection_key -> string (5) "items"
protected modelData -> array(1) [
    'data' => array(1) [
        'translations' => array(1) [
            array(1) [
                'translatedText' => string (33) "Svar p├Ñ unders├©kelsen av nyhets"
            ]
        ]
    ]
]
protected processed -> array()
}
```

Now if I wish to get the translation, this is how I've done it... but it has stopped working.

```
$text = "Whatever text you wish to translate";
$response = $service->translations->listTranslations($text, $language);

foreach($response->getTranslations() as $translation) {
    return $translation->translatedText;
}
```

What I had to do in order to get this to work was to on line 339 of Translate.php change:

```
return $this->translations;
```

into

```
return $this->modelData['data']['translations'];
```

What has changed? Is it on Google's side or on yours?

Got to figure out where stuff's gone wrong...

**Comment by LeonB** [comment]
I'm having the same issue. `return $this->modelData['data']['translations'];` worked for me.
