### ISSUE TITLE
Can't create a project Google Cloud Project anymore

### ISSUE THREAD

**Issue by igoooor** [googleapis/google-api-php-client#1690]
According to the documentation here https://cloud.google.com/resource-manager/reference/rest/v1/projects/create?apix_params=%7B%22resource%22%3A%7B%7D%7D
we should be able to create a google cloud project with this library.
But the classes/files specified in the documentation are now missing, and I haven't found a replacement.
Anyone know why how to do this now?

**Comment by jdpedrie** [comment]
The latest release of `google/apiclient-services` includes a wrapper for Resource Manager v2. The projects API is part of Resource Manager v1, and is not present in v2. You could pin `google/apiclient-services` to [`v0.50.0`](https://github.com/googleapis/google-api-php-client-services/tree/v0.50) to get the required API.

**Comment by veperr** [comment]
so how would one _"You could pin google/apiclient-services to v0.50.0 to get the required API."_???

**Comment by jdpedrie** [comment]
In your `composer.json`, add to the `required` object:

```
    "google/apiclient-services": "v0.50"
```
