### ISSUE TITLE
inserting customBatch

### ISSUE THREAD

**Issue by ysaurabh33** [googleapis/google-api-php-client#1693]
```
An uncaught Exception was encountered
Type: Error

Message: Call to undefined method Google_Service_ShoppingContent_ProductsCustomBatchRequest::toSimpleObject()

Line Number: 108

Backtrace:

File: vendor/google/apiclient-services/src/Google/Service/ShoppingContent/Resource/Products.php
Line: 40
Function: call
```

**Comment by jdpedrie** [comment]
Please share the code you're executing which is raising this error.

**Comment by jdpedrie** [comment]
As we don't have enough information to assist in resolving this issue, I'm going to close it. If you're still having trouble, please feel free to reopen, providing the information requested, and we'll be happy to continue assisting!

**Comment by ysaurabh33** [comment]
@jdpedrie Thanks for looking into the issue. later I figured it, that it was due to same class name which I was using in my project. The class name was "Google_model".

It is know been resolved and is working great at my end :-)
