### ISSUE TITLE
Using App Engine with file limit (10 000)

### ISSUE THREAD

**Issue by hfhbd** [googleapis/google-api-php-client#1694]
Hey, 
I want to deploy my PHP website, using the google-api-php-client library, to the Google Cloud, using App Engine. Unfortunately, there is a limit of 10 000 files. The google-api-php-client library contains alone 9600 files! It is possible to reduce the files, like import only some modules of google-api-php-client?

**Comment by jdpedrie** [comment]
App Engine will install your composer dependencies when you deploy. Create a file called [`.gcloudignore`](https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore) in your project root and add `vendor` to it.
