### ISSUE TITLE
Prevent installation of all API Services.

### ISSUE THREAD

**Issue by dmzoneill** [googleapis/google-api-php-client#1701]
10000+ files
dmzoneill@dave-laptop:~/Desktop/ashtangayoga.ie/gapi$ du -sh .
51M	.

Is there a simpler way to do this.  It seems like there is an excessive amount of code to make a few http requests.  none of which i would want to point up on a webserver.  Attack surface....

is the oath flow and response simplified somewhere in this solution or you could recommend something else as reference?

Thanks

**Comment by jdpedrie** [comment]
The files installed by the `google/apiclient-services` dependency are not required for the library to function. They are only required if you need to make calls to that API. If you desire to use this library only for authentication, you may use the `provide` property in your composer file to skip installation of the services:

```json
{
    "provide": {
        "google/apiclient-services": "*"
    }
}
```

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
