### ISSUE TITLE
Google tokenID from iOS device login not working

### ISSUE THREAD

**Issue by Aghamyr** [googleapis/google-api-php-client#1704]
Hi, 

I'm not sure if it's a bug but I have a problem on my API using this library on v1.1.5 
On my Ionic3 app we're using cordova-plugin-googleplus(I tried different version of the plugin without seeing any difference)

My API receive a google tokenID from a mobile app to allow people to register or login on the app with google. The problem is as follow : 

- For tokenID coming from Android devices there is no issues
- For tokenID coming from iOS devices the verifySignedJwtWithCert() fails when checking if
 ` $aud == $required_audience `

When debugging I found out that for Android in the tokenID, azp value is the Android clientID and the aud value is the web clientID, but for iOS both azp and aud values are the iOS clientID which explains why the check fails.

Did anyone ever encounter this issue or do you have advices on how to solve it ?

PS : I think I found a somewhat working workaround by adding the iOS clientID in my config and modifying the library to check ` !in_array($aud, $required_audience) ` but it doesn't feel right...

**Comment by Aghamyr** [comment]
I found out the answer 

Apparently for iOS if you don't add the option ` 'offline' : 'true' ` when calling the google login it doesn't use the webClientID you specified.
Not sure why it does that for iOS and not for Android though

It's in GooglePlus.m : 
```
NSString* serverClientId = options[@"webClientID"];
...
if (serverClientId != nil && offline) {
    signIn.serverClientID = serverClientId;
}
```

I'm still interested into why the different behavior for iOS and Android or if it's a bug, but hopefully this will help someone else someday

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!

**Comment by kjfdebruin** [comment]
Thanks @Aghamyr - this really helped!
