### ISSUE TITLE
Calendar events auto cancelled after creation

### ISSUE THREAD

**Issue by vishal-genome** [googleapis/google-api-php-client#1708]
Since last week I am facing issue that when I create google event, suddenly it is cancelled and I can see that event in "Trash". When I am trying to restore that event It again fails and moved to trash.

**Comment by jdpedrie** [comment]
Without a code sample demonstrating the issue we cannot offer any assistance. Update your post to include the code you are using to create events and verify that the calendar is not controlled by any 3rd party applications which may be removing events without your consent.

**Comment by vishal-genome** [comment]
It is working fine before a week and there is no any change made in code. Its hard to share code here due to privacy and also there is some architecture based code so not in single file. It would be good if anyone can assist. Thanks!

**Comment by jdpedrie** [comment]
This forum is intended for specific help with problems related to the client library. If the issue has begun without any code change, it's unlikely to be a library issue, and given that you are not able to share any code which would allow us to verify that, I must assume it to be true. You may be able to gain assistance from the [Calendar community forum](https://support.google.com/calendar/community/?hl=en&gpf=%23!forum%2Fcalendar).

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!

**Comment by solovievmaxim** [comment]
In case someone else looking at same problem 
The bug is still open but the as of 11/13/2019 looks likes google fixed the issue
https://issuetracker.google.com/issues/140819378
