### ISSUE TITLE
How to get OAuth 2.0 access token for Firebase Cloud Messaging HTTP v1 API

### ISSUE THREAD

**Issue by andreszs** [googleapis/google-api-php-client#1714]
The [FCM HTTP V1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) requires the server to get a "short-lived OAuth 2.0 access token" to use as the `Authorization: Bearer=TOKEN` request header. To do so, the docs simply point in the direction of this **API Client Library**, and they show some examples for the Node and other non-PHP languages:

![image](https://user-images.githubusercontent.com/10298071/65037760-c180bb00-d924-11e9-8107-dbb1acef82e7.png)

After exploring the present google-api-php-client library, I can't find any possible way to get this token. There are mentions to OAuth 2.0 and tokens in many places, but there isn't a simple example or explanation on **how to get an OAuth 2.0 access token for use with FCM HTTP V1 requests.**. That is all I need to get to continue with my own PHP-based curl() implementation of the FCM API.

If google wants developers to migrate to the **HTTP v1 API**, this process should be clearly explained in a simple example in the very home page of the PHP client library.

**Does anyone know how to get such token with this library?** Is it even possible? Thanks in advance.

**Comment by jdpedrie** [comment]
You may use either of the following methods to obtain an access token:

```php
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/keyfile.json');
$scope = 'https://www.googleapis.com/auth/analytics.readonly';
$client = new Google_Client();
$client->setScopes($scope);
$client->useApplicationDefaultCredentials();
print_r($client->fetchAccessTokenWithAssertion());
```

```php
use Google\Auth\CredentialsLoader;

$scope = 'https://www.googleapis.com/auth/analytics.readonly';
$credentials = CredentialsLoader::makeCredentials($scope, json_decode(file_get_contents(
    '/path/to/keyfile.json'
), true));

print_r($credentials->fetchAuthToken());
```

If you are not using the API Client for anything besides obtaining an access token, I suggest the latter, as it only requires installation of `google/auth`, allowing you to drop the much larger dependency on `google/apiclient`.

If you wish to call Firebase Cloud Messaging via the PHP API Client, you can allow the client to authenticate on your behalf similarly to the first example:

```php
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/keyfile.json');
$scope = 'https://www.googleapis.com/auth/analytics.readonly';
$client = new Google_Client();
$client->setScopes($scope);
$client->useApplicationDefaultCredentials();

$fcm = new Google_Service_FirebaseCloudMessaging($client);
// construct and execute API requests, will be authenticated using the service account.
```

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!

**Comment by ominfowave** [comment]
HI @andreszs is your issue resolved using the solution provided by @jdpedrie ?

**Comment by daniel15111982** [comment]
hello, 
I have the following problem, I put your code above but it doesn't find one of the classes to follow the authentication

Fatal error: Uncaught Error: Class "Google\Auth\CredentialsLoader" not found in /var/www/html/google-api/teste.php:13 Stack trace: #0 {main} thrown in /var/www/html/google-api/teste.php on line 13

<?php
 error_reporting(E_ALL);
 ini_set('display_errors', TRUE);
 ini_set('display_startup_errors', TRUE);
 date_default_timezone_set('America/Sao_Paulo');
 require '/var/www/html/google-api/vendor/autoload.php';

//die("aki");

use Google\Auth\CredentialsLoader;

$scope = 'https://www.googleapis.com/auth/analytics.readonly';
$credentials = CredentialsLoader::makeCredentials($scope, json_decode(file_get_contents(
    '/var/www/html/google-api/newjson.json'
), true));

print_r($credentials->fetchAuthToken());

**Comment by andreszs** [comment]
> HI @andreszs is your issue resolved using the solution provided by @jdpedrie ?

No, I've solved with this rudimentary function written by GPT instead:

```php
/**
     * Genera nuevo ouath2 access token para FCM.
     * @return string
     */
    private static function get_fcm_oauth2_access_token() {
        // Lee las credenciales desde el archivo JSON
        $serviceAccount = __DIR__.'/keys/'.self::SERVICE_ACCOUNT_KEY;
        $credentials = json_decode(file_get_contents($serviceAccount), true);
        if (empty($credentials)) {
            error_log('Error fetching access token: Failed to parse service account credentials');
            return null;
        }

        // URL del token de Google OAuth2
        $url = 'https://oauth2.googleapis.com/token';

        // Crea el JWT (assertion)
        $header = base64_encode(json_encode(array('alg' => 'RS256', 'typ' => 'JWT')));
        $now = time();
        $expiry = $now + 600; // 10' this stores the expiration time in the token file

        $claimSet = base64_encode(json_encode(array(
            'iss' => $credentials['client_email'],
            'scope' => 'https://www.googleapis.com/auth/cloud-platform',
            'aud' => $url,
            'iat' => $now,
            'exp' => $expiry
        )));

        $signatureInput = $header.'.'.$claimSet;

        // Firma el JWT con la clave privada
        $signature = '';
        if (!openssl_sign($signatureInput, $signature, $credentials['private_key'], 'SHA256')) {
            error_log('Error signing the JWT');
            return null;
        }
        $signedJwt = $signatureInput.'.'.base64_encode($signature);

        // Envía la solicitud para obtener el token
        $postFields = http_build_query(array(
            'grant_type' => 'urn:ietf:params:oauth:grant-type:jwt-bearer',
            'assertion' => $signedJwt
        ));

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);

        $response = curl_exec($ch);
        curl_close($ch);

        $data = json_decode($response, true);

        // Return generated token if available
        if (isset($data['access_token'])) {
            return $data['access_token'];
        } else {
            error_log('Error fetching access token: '.$data['error_description']);
            return null;
        }
    }
```

Where the `SERVICE_ACCOUNT_KEY` constant points to the JSON service account file downloaded from the Firebase console. 

You can store the retrieved token in a tokens table, alongside the user ID and expiry time, in order to easily retrieve it for reuse while it's still valid. Firebase does not disclose the access token vailidity time, so I've set it to 10 minutes because it's a nice round number, but its real duration could be an hour, a day, a week... nobody knows.

**Comment by andreszs** [comment]
> hello, I have the following problem, I put your code above but it doesn't find one of the classes to follow the authentication
> 
> Fatal error: Uncaught Error: Class "Google\Auth\CredentialsLoader" not found in /var/www/html/google-api/teste.php:13 Stack trace: #0 {main} thrown in /var/www/html/google-api/teste.php on line 13
> fetchAuthToken());

You either failed to download/unzip the classes in the correct path, or your autoloader is not working. Try to install it with **Composer** whenever possible which takes care of the autoload scripts for you, or figure out why your autoload is failing.
