### ISSUE TITLE
How to get the large uploaded file id?

### ISSUE THREAD

**Issue by lordspace** [googleapis/google-api-php-client#1716]
I've implemented the large file upload which is similar to this example.
https://github.com/googleapis/google-api-php-client/blob/master/examples/large-file-upload.php

Is there a way to get the uploaded file id?

```
 $service->files->create( $fileMetadata, array(
		    'mimeType'   => $content_type,
		    'uploadType' => 'multipart',
		    'fields'     => 'id'
	    ) );

```

**Comment by jdpedrie** [comment]
Does that call return an instance of `Google_Service_Drive_DriveFile`? If so, call `getId()`. The example you cited uses the `Google_Http_MediaFileUpload` class to handle resumable and multipart uploads. Your code snippet appears to be bypassing this. That may cause issues with broken streams on large files.

If you follow the example to use the uploader, the `Google_Service_Drive_DriveFile` will be available [once the upload is complete](https://github.com/googleapis/google-api-php-client/blob/master/examples/large-file-upload.php#L127).

**Comment by lordspace** [comment]
Thanks for the quick reply.
It returns request. Here's a video:

https://youtu.be/7HA-o06RA6A

**Comment by lordspace** [comment]
I am wondering if the ID can be extracted from $media->getResumeUri(); It's a hackish approach.
The upload_id looks pretty long though.
![image](https://user-images.githubusercontent.com/137558/65336321-d5e7e080-dbce-11e9-80f8-0c210079fd8e.png)

**Comment by jdpedrie** [comment]
The upload ID is different from the final Google Drive file ID. The upload ID identifies an upload *session*, not the resource being uploaded. The Drive file ID will not be available until the upload has completed. Once the upload completes, the new file resource will be returned from the final call to `$media->nextChunk()`. From there, you can obtain the ID via `getId()`.

**Comment by lordspace** [comment]
@jdpedrie Yep! That worked. Thanks a lot!
