### ISSUE TITLE
How to use App Engine default credentials to authenticate Google_Service_Sheets

### ISSUE THREAD

**Issue by michelolvera** [googleapis/google-api-php-client#1717]
# Hi, I hope someone can help me with the following problem:

I am trying to use the default credentials of the service account to authenticate with Google_Service_Sheets, on my local computer this works fine since I have configured the GOOGLE_APPLICATION_CREDENTIALS PATH to my JSON key, however the same code does not work in App Engine.

My source code running in a standard App Engine environment PHP 7.2
```
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->addScope(Google_Service_Sheets::SPREADSHEETS_READONLY);
$service = new Google_Service_Sheets($client);
$spreadsheetId = '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms';
$range = 'Class Data!A2:E';
$response = $service->spreadsheets_values->get($spreadsheetId, $range);
$values = $response->getValues();
```

App Engine response:
```
{
"error": {
"code": 403,
"message": "Request had insufficient authentication scopes.",
"errors": [
{
"message": "Request had insufficient authentication scopes.",
"domain": "global",
"reason": "forbidden"
}
],
"status": "PERMISSION_DENIED"
}
}
```

The local service account and App Engine account are the same.

Thank you.

P.S. It should be noted that the OAuth2 token with BigQuery works perfectly with the same account.

**Comment by jdpedrie** [comment]
Hi @michelolvera, sorry for the delay. I am not able to duplicate the issue. Are you certain that you are not overriding the scope elsewhere prior to sending the request?

**Comment by michelolvera** [comment]
Yes, I'm completely sure, I don't understand what's going on because it's a very simple piece of code.
Did you try it in an App Engine instance and it worked correctly for you?

**Comment by michelolvera** [comment]
Today I update my composer dependencies and it works correctly, I don't know if I fix that but thanks anyway.
