### ISSUE TITLE
Command-line / Offline app token token keeps expiring even though there's refresh token

### ISSUE THREAD

**Issue by lordspace** [googleapis/google-api-php-client#1718]
This is from this example: I will post it in the other repo.
https://developers.google.com/drive/api/v3/quickstart/php
https://github.com/gsuitedevs/php-samples/blob/master/drive/quickstart/quickstart.php

https://youtu.be/NMGaXlq0qAk

#### Environment details

  - OS: Windows 10 Home, 64 bit
  - PHP version: PHP 7.2.22 (cli) (built: Aug 28 2019 09:29:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
  - Package name and version: const LIBVER = "2.4";

#### Steps to reproduce

  1. ... https://youtu.be/NMGaXlq0qAk

#### Code example (fix)

```php
			$renewed = 0;

			// Refresh the token if possible, else fetch a new one.
			if ( $client->getRefreshToken() ) {
				$client->fetchAccessTokenWithRefreshToken( $client->getRefreshToken() );
				$renewed = 1;
			} else {
				// Request authorization from the user.
				$authUrl = $client->createAuthUrl();
				printf( "Open the following link in your browser:\n%s\n", $authUrl );
				print 'Enter verification code: ';
				$authCode = trim( fgets( STDIN ) );

				// Exchange authorization code for an access token.
				$accessToken = $client->fetchAccessTokenWithAuthCode( $authCode );
				$client->setAccessToken( $accessToken );

				// Check to see if there was an error.
				if ( array_key_exists( 'error', $accessToken ) ) {
					throw new Exception( join( ', ', $accessToken ) );
				}
			}

			if (! $renewed) {
				// Save the token to a file.
				if ( ! file_exists( dirname( $tokenPath ) ) ) {
					$mkdir_res = mkdir( dirname( $tokenPath ), 0700, true );

					if ( empty( $mkdir_res ) ) {
						throw new Exception( "Cannot create parent directory for file: " . $tokenPath );
					}
				}

				$save_res = file_put_contents( $tokenPath, json_encode( $client->getAccessToken() ), LOCK_EX );

				if ( empty( $save_res ) ) {
					throw new Exception( "Cannot save file: " . $tokenPath );
				}
			}
```

**Comment by fatica** [comment]
Hi, I just wanted to let you know that this was an issue for us as well, and @lordspace's post solved the issue for us.  We were running this Google Drive import as a command line job (using Redis/Resque) and it would always fail after 3600 seconds.  

Thinking the same code wasn't the source of the issue, we spent many hours looking elsewhere, and the cause was just as described above.  The $renewed flag fixes the issue.  Thanks for posting this issue and please consider updating the sample code accordingly.

**Comment by bshaffer** [comment]
If I'm reading this right, this skips saving the access token to a file if the access token was fetched using `fetchAccessTokenWithRefreshToken`.

I think the root issue here could have been that the `refresh_token` field was not being added back to the access token, but this was fixed 6 years ago in https://github.com/googleapis/google-api-php-client/pull/1121, so I think the problem has been resolved.
