### ISSUE TITLE
error in Google OAuth 2.0 api to Fitch user data from idToken

### ISSUE THREAD

**Issue by ibraheem9** [googleapis/google-api-php-client#1719]
```php
try {
    $client = new \Google_Client([
        'client_id' => env('GOOGLE_CLIENT_ID'),
        ]);

    $ticket = $client->verifyIdToken($request->token);
    dd($ticket);
    if ($ticket) {
        $payload = $ticket->getAttributes();
        return $payload['payload']['sub']; // user ID
    }
} catch(\UnexpectedValueException $e) {
    dd($e);
    return $this->sendResponse(false,'This Token For Google+ Is Not Valid',null,401);
}
```

this is my code and if i remove this line  'client_id' => env('GOOGLE_CLIENT_ID'), 
user data will return successfully 
else 
this function  $client->verifyIdToken($request->token); will always return false 
i think problem is in this code in library 

```php
if (property_exists($payload, 'aud')) {
    if ($audience && $payload->aud != $audience) {
        return false;
    }
}
```

**Comment by jdpedrie** [comment]
How are you obtaining the token you are attempting to verify?

**Comment by jdpedrie** [comment]
As we don't have enough information to assist in resolving this issue, I'm going to close it. If you're still having trouble, please feel free to reopen, providing the information requested, and we'll be happy to continue assisting!
