### ISSUE TITLE
Image not uploaded correctly when using incorrect mimetype 

### ISSUE THREAD

**Issue by rafa-guillermo** [googleapis/google-api-php-client#1720]
If you are still having issues, please be sure to include as much information as possible:

When uploading a JPG image to Drive using the API v3 in PHP but with mimetype application/pdf, a screenshot of the 'Sign in to continue to Google Drive' webpage appears in Drive with the file name. This also happens with application/msword but not with application/vnd.google-apps.drawing so I am unsure how many mimetypes this does work for.
#### Environment details

  - OS: N/A
  - PHP version: 7.3

#### Steps to reproduce

Run the following code snippet in PHP, change the filename to a valid .jpg file on the local disk

#### Code example

```php
$fileMetadata = new Google_Service_Drive_DriveFile(array(
    'name' => 'filename.jpg'));
$content = file_get_contents('filename.jpg');
$file = $service->files->create($fileMetadata, array(
    'data' => $content,
    'mimeType' => 'application/pdf',
    'uploadType' => 'media',
    'fields' => 'id'));
printf("File ID: %s\n", $file->id);
```

#### Expected Result
Either the image should be uploaded as a pdf (unlikely, this is not an export/convert) or the application should return Error 400    "Invalid MIME type provided for the uploaded content." like it does for other unsupported mime types.

#### Actual result
The .jpg file gets uplaoded but the pdf/word document contains a login screenshot.  
Original image: 
![original_image_porygon](https://user-images.githubusercontent.com/2607946/65697772-ca3b6480-e07b-11e9-94be-a74465f55755.jpg) 
Screenshot of pdf or word doc that gets uploaded:
![Screenshot 2019-09-26 at 4 36 06 PM - Display 2](https://user-images.githubusercontent.com/2607946/65697781-cf98af00-e07b-11e9-9f88-2099a3494b76.png)

**Comment by jdpedrie** [comment]
Hi @rafa-guillermo,

This looks to be an issue in the Drive API, not this client. Unfortunately we can't help much with that; this forum is intended for assistance with issues specific to the API client. While I'm happy to help debug issues with the APIs where I can, in this case it looks to be outside my control, and you appear to have configured the request properly. The Drive API team has a [support page](https://developers.google.com/drive/api/v3/support) showing how you can get in touch with them to report issues (Stackoverflow, or their issue tracker if you believe this is a bug).

If I've misunderstood the issue, or you believe this is a problem with the client, please feel free to reopen it and let me know.
