### ISSUE TITLE
Files: create method using Drive API V3 in PHP creating corrupted images on upload

### ISSUE THREAD

**Issue by rafa-guillermo** [googleapis/google-api-php-client#1721]
If you are still having issues, please be sure to include as much information as possible:

Having issues when uploading .jpg file to Drive using the Files: create method in Drive API v3. Was able to reproduce using the code provided on https://developers.google.com/drive/api/v3/manage-uploads#simple. The script completes and returns a file ID for the newly uploaded file though it is unviewable.

#### Environment details

  - OS: Chrome: N/A
  - PHP version: 7.3

#### Steps to reproduce
Run the following code snippet in PHP, change the filename to a valid .jpg file

```php
$fileMetadata = new Google_Service_Drive_DriveFile(array(
    'name' => 'filename.jpg'));
$content = file_get_contents('filename.jpg');
$file = $service->files->create($fileMetadata, array(
    'data' => $content,
    'mimeType' => 'image/jpeg',
    'uploadType' => 'media',
    'fields' => 'id'));
printf("File ID: %s\n", $file->id);
```
or:
```php
$file = $request->file('Arquivos');
$Curl = new WebService_CurlCustom();
$Dados = ['file' => curl_file_create($file,$file->getClientMimeType(),$file->getClientOriginalName())];
$DadosReturn = $Curl->Url(self::GOOGLE_URL_API)
                                       ->SslVerific(false)
                                       ->Authorization('Bearer '.$this->GetNewToken())
                                       ->ContentType($file->getClientMimeType())
                                       ->ContentLength($file->getSize())
                                       ->post()
                                       ->ExecutarCurl($Dados);
```

Expected Result: 
The image.jpg file should be uploaded to the user's Drive with no issues.

Actual result:
The file becomes corrupted and can not be viewed in Drive. It can also not be opened by external applications if downloaded to a local machine.

Using the same original file as: https://github.com/googleapis/google-api-php-client/issues/1720

**Comment by jdpedrie** [comment]
Hi @rafa-guillermo,

I'm unable to replicate this issue. Using your first example, I can successfully upload and view a jpg image with no issue. Can you provide any other detail which may impact the process?

**Comment by jdpedrie** [comment]
As we don't have enough information to assist in resolving this issue, I'm going to close it. If you're still having trouble, please feel free to reopen, providing the information requested, and we'll be happy to continue assisting!
