### ISSUE TITLE
Syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in Logger.php

### ISSUE THREAD

**Issue by cuongd86** [googleapis/google-api-php-client#1723]
I get this error on PHP Version 7.0.33-11+0~20190923.20+debian9~1.gbpd05c7e
I'm running the Wordpress click to deploy on the compute engine.
`Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /...../google/vendor/monolog/monolog/src/Monolog/Logger.php on line 33`

What should i do to solve this error?

**Comment by cuongd86** [comment]
i found the way to solve this error

**Comment by dwsupplee** [comment]
Glad to hear that @cuongd86, would you be able to share for anyone else who may run in to this in the future?

**Comment by cuongd86** [comment]
@dwsupplee 
I upgrade php version from 7.0 to 7.3. Same error like this issue https://github.com/doctrine/DoctrineBundle/issues/847

**Comment by josalhor** [comment]
I'm currently having this issue on PHP 5.4

**Comment by CtrlShiftN** [comment]
> i found the way to solve this error

my php is 7.0.3 and still same error

**Comment by Pappuchauhan** [comment]
Hi everyone,

I have solved the issue.
You need to download SDK from https://github.com/googleapis/google-api-php-client/releases
