### ISSUE TITLE
add attendee not working in google calendar

### ISSUE THREAD

**Issue by avni-logistic** [googleapis/google-api-php-client#1725]
Create event just fine without attendee.

get error with addAttendee

Google_Service_Exception: {
"error": {
"errors": [
{
"domain": "usageLimits",
"reason": "quotaExceeded",
"message": "Calendar usage limits exceeded."
}
],
"code": 403,
"message": "Calendar usage limits exceeded."
}
}

use https://github.com/spatie/laravel-google-calendar

**Comment by jdpedrie** [comment]
The error message seems to indicate the issue.

Please review the [Calendar use limits](https://support.google.com/a/answer/2905486?hl=en) and [Google Calendar API Usage Limits](https://developers.google.com/calendar/pricing) pages for more information and possible next steps.

**Comment by avni-logistic** [comment]
![image](https://user-images.githubusercontent.com/44438686/66630546-21b40580-ec22-11e9-8c5c-03a85707ce97.png)

**Comment by jdpedrie** [comment]
Looks like you found this and commented already, but for others who may be looking, it appears there may be an [issue](https://issuetracker.google.com/issues/141704931) in the service. Please track that report for further information!

**Comment by rafgod-ML** [comment]
I got the same error, I also probe creating a new event without attendees and later update this event adding some attendees and don't works eather

**Comment by rafgod-ML** [comment]
i'm using Go not php

**Comment by jawwadturabi** [comment]
I am having the same issue. It is working without attendees. I have also checked that I have exceeded the limit of usage.

**Comment by rafgod-ML** [comment]
> I am having the same issue. It is working without attendees. I have also checked that I haven't exceeded the limit of usage.

Hi, can you send me the code to check it, I resolved this problem but not remembered how, maybe if I see your code I will remember what I did to fix this

**Comment by orlando-rojas** [comment]
$event = new Google_Service_Calendar_Event(array(
            'summary' => $titulo,
            'location' => 'Jr. Emilio Althaus 166',
            'description' => 'Clase',
            'attendees' => array(
              array('email' => 'orlandorm0117@gmail.com'),
              array('email' => 'seeyoulatertv@mgail.com'),
            ),
          ));

if i delete attendees the code works normally

**Comment by farminf** [comment]
I have the same issue....quotaExceeded
only works without any attendee

**Comment by EduardoRicardez** [comment]
I have the same issue....quotaExceeded
only works without any attendee

**Comment by charlesjacobsonrarebirds** [comment]
same issue. i see that there's a lot of us facing this

**Comment by pavnishsrijan** [comment]
This is due to the Service accounts cannot invite attendees without Domain-Wide Delegation of Authority.
You need to be  Enable G Suite Domain-wide Delegation on your service account
