### ISSUE TITLE
JobServiceClient cannot be found after installing the library Google Talent Solutions

### ISSUE THREAD

**Issue by georgeka98** [googleapis/google-api-php-client#1726]
After following the instructions like a robot, I am having this issue:
`Class 'Google\Cloud\Talent\V4beta1\JobServiceClient' not found`

I used `composer require google/apiclient` to install the google library (Google Talent Solutions) the following is the code:

`

use Google\Cloud\Talent\V4beta1\JobServiceClient;
use Google\Cloud\Talent\V4beta1\HistogramQuery;
use Google\Cloud\Talent\V4beta1\RequestMetadata;

use Google\Cloud\Talent\V4beta1\CompanyServiceClient;

$jobServiceClient = new JobServiceClient();

        dd($jobServiceClient);

        $projectId = 'perfect-job-match-255511';
        // $tenantId = 'Your Tenant ID (using tenancy is optional)';
        $tenantId = '';
        // $query = 'count(base_compensation, [bucket(12, 20)])';
        $formattedParent = $jobServiceClient->tenantName($projectId, $tenantId);
        $domain = 'www.techlunar.com';
        $sessionId = 'Hashed session identifier';
        $userId = 'Hashed user identifier';
        $requestMetadata = new RequestMetadata();
        $requestMetadata->setDomain($domain);
        $requestMetadata->setSessionId($sessionId);
        $requestMetadata->setUserId($userId);
        $histogramQueriesElement = new HistogramQuery();
        $histogramQueriesElement->setHistogramQuery($request->query);
        $histogramQueries = [$histogramQueriesElement];

        try {
            // Iterate through all elements
            $pagedResponse = $jobServiceClient->searchJobs($formattedParent, $requestMetadata, ['customRankingInfo' => $customRankingInfo, 'orderBy' => $orderBy]);
            foreach ($pagedResponse->iterateAllElements() as $responseItem) {
                printf('Job summary: %s'.PHP_EOL, $responseItem->getJobSummary());
                printf('Job title snippet: %s'.PHP_EOL, $responseItem->getJobTitleSnippet());
                $job = $responseItem->getJob();
                printf('Job name: %s'.PHP_EOL, $job->getName());
                printf('Job title: %s'.PHP_EOL, $job->getTitle());
            }
        } finally {
            $jobServiceClient->close();
        }`

Why do instructions have to be written wrong all the time when dealing with API's?

**Comment by jdpedrie** [comment]
Looks like you've simply installed the wrong dependency. :)

`google/cloud-talent` will get you what you need. It's part of [`google/cloud`](https://github.com/googleapis/google-cloud-php), which you can also install if you're using a number of cloud services, but if you're just using talent, definitely go for `google/cloud-talent`.

If you have any other questions, support for Talent is part of the issues on the Google Cloud PHP repository!

**Comment by georgeka98** [comment]
Hi,

Thanks for your answer. I updated my code and now I am struggling with getting the tenant_id. The instructions are not very clear for me unfits. Is there a way to get my default tenant_id?

Cheers,

**Comment by jdpedrie** [comment]
Tenants can be created via the API, as [this example](https://cloud.google.com/talent-solution/job-search/docs/tenants#create_a_tenant) demonstrates.

**Comment by georgeka98** [comment]
Hi,

Ok, I trie adding an externalId. I assigned this number as the externalId = 2134324. Now I am getting the following error:
{ "message": "The caller does not have permission", "code": 7, "status": "PERMISSION_DENIED", "details": [] }

Any Ideas on how you could fix this is

Regards
