### ISSUE TITLE
Google API V3

### ISSUE THREAD

**Issue by rivella50** [googleapis/google-api-php-client#1728]
Hi there,

our company was let known that by December 1st the Google Play Developer API versions 1 & 2 are no longer supported.
Therefore my question: Is the latest version of this client library already target V3 of the mentioned Google API?

Thank you.

**Comment by jdpedrie** [comment]
Yes. As you can see [here](https://github.com/googleapis/google-api-php-client-services/blob/8f36831c9986ce4ef4e2fb26ed920b7ca7e1ba78/src/Google/Service/AndroidPublisher.php#L66), this client uses v3 of the API!

**Comment by rivella50** [comment]
Great, thank you very much!

**Comment by chenxinlong** [comment]
@jdpedrie 

But in the OAuth2.php [here](https://github.com/googleapis/google-api-php-client-services/blob/8f36831c9986ce4ef4e2fb26ed920b7ca7e1ba78/src/Google/Service/Oauth2.php#L57) , it's v2. 

So the OAuth2 related API can still use v2 ?

**Comment by jdpedrie** [comment]
Yes, each API is versioned separately by its maintainers.

**Comment by chenxinlong** [comment]
Thx. 

Another confusion is: APIs with `googleapis.com/oauth2/` prefix is not considered as Google Play Developer API? Or just the API maintainer forgot to upgrade it to v3 [here](https://github.com/googleapis/google-api-php-client-services/blob/8f36831c9986ce4ef4e2fb26ed920b7ca7e1ba78/src/Google/Service/Oauth2.php#L57)? 

If I continue to use the latest version of this lib, will my OAuth2 function be affected after December 1st?

**Comment by jdpedrie** [comment]
> If I continue to use the latest version of this lib, will my OAuth2 function be affected after December 1st?

No.
