### ISSUE TITLE
Security permission needed when using Google Cloud Solutions

### ISSUE THREAD

**Issue by georgeka98** [googleapis/google-api-php-client#1729]
Hi,

While trying to add a new Tenant, I am getting the following issue: 

{ "message": "The caller does not have permission", "code": 7, "status": "PERMISSION_DENIED", "details": [] }

Here is my code:

putenv('GOOGLE_APPLICATION_CREDENTIALS=/Users/georgeka/sites/jobs-hunt/perfect-job-match-255511-46f5a65b7c09.json');

        $tenantServiceClient = new TenantServiceClient();

        // $projectId = 'Your Google Cloud Project ID';
        // $externalId = 'Your Unique Identifier for Tenant';
        $formattedParent = $tenantServiceClient->projectName("my-project-id");
        $tenant = new Tenant();
        $tenant->setExternalId(2134324);
    
        try {
            $response = $tenantServiceClient->createTenant($formattedParent, $tenant);
            printf('Created Tenant'.PHP_EOL);
            printf('Name: %s'.PHP_EOL, $response->getName());
            printf('External ID: %s'.PHP_EOL, $response->getExternalId());
        } finally {
            $tenantServiceClient->close();
        }

Furthermore, I am not sure what it means by externalId. I read the Google docs, but they didn't explain it. Help will be much appreciated.

**Comment by jdpedrie** [comment]
Moved to [Google Cloud PHP](https://github.com/googleapis/google-cloud-php/issues/2408).
