### ISSUE TITLE
Services are out of date

### ISSUE THREAD

**Issue by sarunint** [googleapis/google-api-php-client#1730]
### Environment details

  - OS: Ubuntu 18.04
  - PHP version: 5.4
  - Package name and version: google-api-php-client-2.4.0_PHP54

#### Steps to reproduce

  1. Class `Google_Service_Directory_Resource_Members` has no `hasMember` function.
  2. Class `Google_Service_Directory_Member` has no `deliverySettings` field.

I know that in [googleapis/google-api-php-client-services](https://github.com/googleapis/google-api-php-client-services), the services are up to date, but the release zip file is out of date.

**Comment by jdpedrie** [comment]
As part of our periodic release process, we install dependencies at the time of release. Therefore, they will tend to grow stale over time. As this client includes wrappers for over 150 services, it is not feasible to keep the release packages entirely up-to-date. In cases where this is an issue, you have the option to install the client using composer, which will provide the most up-to-date reflection of the API services:

```
$ composer require google/apiclient
```

If you need help installing or using Composer, check out [this guide](https://getcomposer.org/doc/00-intro.md).
