### ISSUE TITLE
listGroups in Directory api

### ISSUE THREAD

**Issue by RobertoBu** [googleapis/google-api-php-client#1733]
I use the function listGroups to retrieve all groups in my directory.

I use this params

```php
$params = array(
    'domain' => 'mydomain.com',
    'userKey'=> $userkey,
    'query'=>'name=abuse'
);
```
but I obtain this exception:

```
(list) unknown parameter: 'query'
```

is it a bug?

In function docs i read

```
@opt_param string query Query string search. Should be of the form "". Complete documentation is at https://developers.google.com/admin- sdk/directory/v1/guides/search-groups
```

And I haven't problems if i try the function by the tool at

https://developers.google.com/admin-sdk/directory/v1/reference/groups/list

**Comment by jdpedrie** [comment]
Are you perhaps using a very old version of the API client? `query` was added to the API in [May 2018](https://github.com/googleapis/google-api-php-client-services/commit/9acaa85f6c6b2f863e33fa9fe46524063b668ec0). Make sure the version you have installed is more recent than that. In my tests against the latest version of the client, I do not see the error you report, but when I roll back to `google/apiclient-services` v0.57, I do.

**Comment by RobertoBu** [comment]
ok thank you, i updated the version, now it works
