### ISSUE TITLE
 error trying to use filters and dimensions

### ISSUE THREAD

**Issue by fabianamanu** [googleapis/google-api-php-client#1734]
Hello I'm sorry for the bad English, but not my native language so I have a following question my api connects can get and call some metrics, but unfortunately I can not implement filters and dimensions, someone would have a clear example because in the documentation is not clear .. .. already thank you very much for your attention

this is how I consult

![image](https://user-images.githubusercontent.com/12700210/68229809-ac481480-ffd6-11e9-886e-5c6508b420f8.png)

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
