### ISSUE TITLE
"Invitation pending" on User Permissions: create with JavaScript

### ISSUE THREAD

**Issue by konradstrek** [googleapis/google-api-php-client#1737]
I'm using `user_permissions.create` to add new admin to the Google Tag Manager account. The problem is that even If we have `"permission": "admin"` in code, we still have yellow Invitation pending badge. How to make it directly green (Has access)?

Note: User making `create` request allowed our app to make this request.

![ice_screenshot_20191106-134400](https://user-images.githubusercontent.com/37452287/68299605-5342b400-009c-11ea-8b1d-97826d9bfa54.png)

```
return gapi.client.tagmanager.accounts.user_permissions.create({
  "parent": "accounts/0123456789",
  "resource": {
    "path": "accounts/1111111111",
    "accountId": "1111111111",
    "emailAddress": "myemail@gmail.com",
    "accountAccess": {
      "permission": "admin"
    },
    "containerAccess": [
      {
        "containerId": "123456789",
        "permission": "edit"
      }
    ]
  }
})
.then(function(response) {
  console.log("Response", response);
},
function(err) {
  console.error("Execute error", err);
});
```

**Comment by jdpedrie** [comment]
Please open this issue on the [`googleapis/google-api-nodejs-client`](https://github.com/googleapis/google-api-nodejs-client) repository.
