### ISSUE TITLE
Cannot get userinfo from id_token

### ISSUE THREAD

**Issue by syncupasia** [googleapis/google-api-php-client#1738]
Hi. Maybe this is not a bug. Hope it's okay I do it here. I'm trying to get the userinfo using oauth2 with id_token instead of code.

So instead of the following which worked:

```php
$google_client->authenticate($_GET['code']);
$token = $google_client->getAccessToken();
if ($google_client->getAccessToken()) { // auth call to google
    $google_service = new Google_Service_Oauth2($google_client);
    $data = $google_service->userinfo->get();
}
```

From the above token I can get the id_token data so I tried to get userinfo data by id_token

Note: hard-code $id_token for testing

```php
$verify_res = $google_client->verifyIdToken($id_token);
$google_service = new Google_Service_Oauth2($google_client);
$data = $google_service->userinfo->get();
```

But it doesn't work and I got this error. The reason I'm using id_token because if it's for mobile app sign in then app side seems can only pass the id_token and not the code value.

```
Fatal error: Uncaught Google_Service_Exception: Error calling GET https://www.googleapis.com/oauth2/v2/userinfo: (401) Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. in /test/Google/Http/REST.php on line 110
```

I'm using ver 1.1.5 though. But is it possible to get userinfo from id_token instead?

**Comment by jdpedrie** [comment]
`verifyIdToken()` does not cache the token in the client, so it will not be added to future API requests. Have you tried setting the token using `Google_Client::setAccessToken()`?

```php
$verify_res = $google_client->setAccessToken($id_token);
$google_service = new Google_Service_Oauth2($google_client);
$data = $google_service->userinfo->get();
```

**Comment by syncupasia** [comment]
Tried it and got the following error.

Fatal error: Uncaught Google_Auth_Exception: Could not json decode the token in Google/Auth/OAuth2.php on line 186

That function expect a json string with these:

{"access_token":"TOKEN", "refresh_token":"TOKEN", "token_type":"Bearer",
 "expires_in":3600, "id_token":"TOKEN", "created":1320790426}

I only have id_token and even i pass a json string {"id_token":"..."} it returns the following error.

Fatal error: Uncaught Google_Auth_Exception: Invalid token format in Google/Auth/OAuth2.php on line 189

**Comment by syncupasia** [comment]
Hi. I'm changing to use the latest version now and is there a way I can do it with id_token then?

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
