### ISSUE TITLE
Error insert account user

### ISSUE THREAD

**Issue by zigou13** [googleapis/google-api-php-client#1742]
Hello,
when adding a user account, I encounter this problem, do you have any ideas?

```
"error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Given/Family Name: FamilyName"
   }
  ],
  "code": 400,
  "message": "Invalid Given/Family Name: FamilyName"
 }
}
```

this my code

```php
$useroptParamsInsertUserAccount = array(
	'name' => array(
		'familyName' => 'familyName',
		'givenName' => 'givenName',
		'fullName' => 'familyName givenName'
	),
	'password' => '123456789',
	'primaryEmail' => 'test1@xxx.fr'
);
$postBody = array(
	'postBody' => 'json',
);
try {
    $resultsInsertUserAccount = $adminService->users->insert($UserApi,$postBody,$useroptParamsInsertUserAccount);
	debug($resultsInsertUserAccount);
}
catch (exception $e) {
	$getMessage = $e->getMessage();
	$result = json_decode( $getMessage,true );
	//echo 'Error : ';
	print_r($result);
}
```

**Comment by jdpedrie** [comment]
We maintain a very large number of clients in this library. Could you update your sample to show the instantiation of `$adminService` in order to facilitate us easily understanding the precise API you are using?

Make sure not to include any private information such as API keys or secrets.

**Comment by zigou13** [comment]
> $client 		= getClient($KEY_FILE_LOCATION);
$adminService 	= new Google_Service_Directory($client);

>

**Comment by zigou13** [comment]
`
function getClient($KEY_FILE_LOCATION) {
    $client = new Google_Client();
    $client->setApplicationName('G Suite Directory API PHP Quickstart');
	$client->setScopes('https://www.googleapis.com/auth/admin.directory.user');
    $client->setAuthConfig($KEY_FILE_LOCATION);
    $client->setAccessType('offline');
    $client->setPrompt('select_account consent');
    $tokenPath = 'token.json';
    if (file_exists($tokenPath)) {
        $accessToken = json_decode(file_get_contents($tokenPath), true);
        $client->setAccessToken($accessToken);
    }
    // If there is no previous token or it's expired.
    if ($client->isAccessTokenExpired()) {
        // Refresh the token if possible, else fetch a new one.
        if ($client->getRefreshToken()) {
            $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
        } else {
            // Request authorization from the user.
            $authUrl = $client->createAuthUrl();
            printf("Open the following link in your browser:\n%s\n", $authUrl);
            print 'Enter verification code: ';
            $authCode = trim(fgets(STDIN));

            // Exchange authorization code for an access token.
            $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
            $client->setAccessToken($accessToken);

            // Check to see if there was an error.
            if (array_key_exists('error', $accessToken)) {
                throw new Exception(join(', ', $accessToken));
            }
        }
        // Save the token to a file.
        if (!file_exists(dirname($tokenPath))) {
            mkdir(dirname($tokenPath), 0700, true);
        }
        file_put_contents($tokenPath, json_encode($client->getAccessToken()));
    }
    return $client;
}


$client 		= getClient($KEY_FILE_LOCATION);
$adminService 	= new Google_Service_Directory($client);`

**Comment by tmatsuo** [comment]
I successfully created a new account with the following code:

```php
// Get the API client and construct the service object.
$client = getClient();
$service = new Google_Service_Directory($client);

$name = new Google_Service_Directory_UserName();
$name->setFamilyName('familyName');
$name->setGivenName('givenName');
$name->setFullName('familyName givenName');

$user = new Google_Service_Directory_User();
$user->setName($name);
$user->setPrimaryEmail('test1@your-domain.example.com');
$user->setPassword('123456789');
try {
  $resultsInsertUserAccount = $service->users->insert($user);
	var_dump($resultsInsertUserAccount);
}
```

hope it helps
