### ISSUE TITLE
Packaged google-api-php-client-services is deprecated

### ISSUE THREAD

**Issue by lionscribe** [googleapis/google-api-php-client#1746]
You include the _google-api-php-client-services_ in the zip file, at _\vendor\google\apiclient-services_
The included version, uses the **v2** of the AndroidPublisher API, as you can see in _\vendor\google\apiclient-services\src\Google\Service\AndroidPublisher_. This version has been deprecated, and will stop working on Dec 1 2019. Please update it to the latest version of the _google-api-php-client-services_ library, which uses **V3**.

**Comment by jdpedrie** [comment]
[Version 2.4.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.4.0) and its archives provide v3 of the Android Publisher API.

**Comment by lionscribe** [comment]
It seems that we are both rights, as you only updated it in the regular php version, but in the php54 version you still have the old one. 
https://github.com/googleapis/google-api-php-client/releases/download/v2.4.0/google-api-php-client-2.4.0.zip has V3
but...
https://github.com/googleapis/google-api-php-client/releases/download/v2.4.0/google-api-php-client-2.4.0_PHP54.zip has V2

**Comment by jdpedrie** [comment]
Ah, you're 100% correct, I apologize. We'll figure out how to address this.

**Comment by jdpedrie** [comment]
@lionscribe I've updated the archive attached to the latest release. Let me know if you have further issues.

**Comment by hto** [comment]
@jdpedrie 
`google/apiclient": "^2.0",`
I used to version, Do I need to update ?

**Comment by jdpedrie** [comment]
@hto this issue only applies to the packaged downloadable archives found on the releases page. If you are installing via composer, you are fine.

---

We will make sure to package with the newest version of apiclient-services for all future releases.
