### ISSUE TITLE
PHP version 5.6 required?

### ISSUE THREAD

**Issue by d-kar** [googleapis/google-api-php-client#1747]
When I try to install using composer I get this error:
```

./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ralouphie/getallheaders 3.0.3 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
    - ralouphie/getallheaders 3.0.3 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
    - Installation request for ralouphie/getallheaders (installed at 3.0.3) -> satisfiable by ralouphie/getallheaders[3.0.3].


Installation failed, deleting ./composer.json.

```

**Comment by jdpedrie** [comment]
Could there be another dependency which is calling for this version? I was just able to install the dependencies in PHP 5.5 with no issue.

**Comment by d-kar** [comment]
Yes,  ralouphie/getallheaders 3.0.3 requires php >=5.6
But why does it try to install this version if my php version is 5.5.9?
Shouldn't it try the lower version that requires php 5.3?
I'm using composer for the first time so I don't know if I make any sense.

**Comment by d-kar** [comment]
Can someone advise what steps should I take to resolve this?
