### ISSUE TITLE
Sheets API: Creating a basic filter for a sheet first column is not working

### ISSUE THREAD

**Issue by andresduarte94** [googleapis/google-api-php-client#1748]
#### Environment details
  - OS: N/A
  - PHP version: 7.3.5
  - Package name and version: google/apiclient:^2.0

#### Steps to reproduce
1) Turn off the filters in the sheet.
2) With the quickstart [1] implementation to get the client, run the below code. 

Expected behavior:
It should create a filter for the first column of the sheet.

Actual behavior:
It doesn’t create the filter and throws the following error:
Fatal error: Uncaught Google_Service_Exception: {
  "error": {
    "code": 400,
    "message": "Invalid value at 'requests.set_basic_filter.filter' (Map), Cannot bind a list to map for field 'criteria'.",
    "errors": [
      {
        "message": "Invalid value at 'requests.set_basic_filter.filter' (Map), Cannot bind a list to map for field 'criteria'.",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

#### Code example
```php
# example
$client = getClient();
$service = new Google_Service_Sheets($client);

$body = new Google_Service_Sheets_BatchUpdateSpreadsheetRequest(array(
'requests' => array(
    'setBasicFilter' => array(
        'filter' => array(
            'range' => [
                'sheetId' => 0,
                'startColumnIndex' => 0,
                'endColumnIndex' => 0
            ],
            'criteria' => array(
                '0' => array(
                    'condition' => array(
                        'type' => 'TEXT_EQ',
                        'values' => array(
                            'userEnteredValue' => 'global_city_actors'
                        )
                    )
                )
            )
        )
    )
)
));

var_dump($service->spreadsheets->batchUpdate("[SPREADSHEET-ID]", $body));
```

#### Additional information:
1) I only tested the request with the condition type “TEXT_EQ”.
2) Useful information [2][3].
2) Making the same request directly from “Try this API” does work as expected, creating the filter in the first row [4].

[1] https://developers.google.com/sheets/api/quickstart/php 
[2] https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#setbasicfilterrequest
[3] https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#BasicFilter
[4] https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate?apix_params=%7B%22spreadsheetId%22%3A%221-0mnkH5HORTy-FJ3WEY5TOl1fa7wUGLNsuQPtahqGUA%22%2C%22resource%22%3A%7B%22requests%22%3A%5B%7B%22setBasicFilter%22%3A%7B%22filter%22%3A%7B%22range%22%3A%7B%22sheetId%22%3A0%2C%22startColumnIndex%22%3A0%2C%22endColumnIndex%22%3A0%7D%2C%22criteria%22%3A%7B%220%22%3A%7B%22condition%22%3A%7B%22type%22%3A%22TEXT_EQ%22%2C%22values%22%3A%5B%7B%22userEnteredValue%22%3A%22global_city_actors%22%7D%5D%7D%7D%7D%7D%7D%7D%5D%7D%7D

**Comment by tmatsuo** [comment]
Seems like using stdClass works for me?

```php
$criteria = new stdClass;
$criteria->{'0'} = array(
    'condition' => array(
        'type' => 'TEXT_EQ',
        'values' => array(
            'userEnteredValue' => 'global_city_actors'
        )
    )
);
$body = new Google_Service_Sheets_BatchUpdateSpreadsheetRequest(
    array(
        'requests' => array(
            'setBasicFilter' => array(
                'filter' => array(
                    'range' => [
                        'sheetId' => 0,
                        'startColumnIndex' => 0,
                        'endColumnIndex' => 0
                    ],
                'criteria' => $criteria
                )
            )
        )
    )
);

var_dump($service->spreadsheets->batchUpdate($spreadsheetId, $body));

```
Hope it helps!
