### ISSUE TITLE
Obtaining new access token using saved refresh token, refreshToken() and fetchAccessTokenWithRefreshToken() returns nothing

### ISSUE THREAD

**Issue by pinoybai** [googleapis/google-api-php-client#1750]
I'm having problem obtaining a new access token using refresh token. I followed all the steps mentioned in various sources and nothing seems to be working. following is what I did.

1) First I obtained Access token by exchanging it with auth code from google ( using `$client->authenticate($_GET['code'])`), for the first time that returns with refresh token.

2) I saved both access token array and the refresh token in my database.

3) Then set up the access token to the client object using `setAccessToken()` method.

4) It works fine untill the access token expiration. but when i try obtaining a new access token using the following code, nothing gets returned. where could i be going wrong?

Here is the code that saves the access and refresh token in database inside authcallback.php file:

```php
$client = new Google_Client();
$client->setAuthConfigFile('client_secret.json');
$client->setRedirectUri('http://'.$_SERVER['HTTP_HOST'].'/authcallback.php');
$client->addScope('https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/spreadsheets');
$client->setAccessType('offline');
$client->setIncludeGrantedScopes(true);
$client->setApprovalPrompt('force');
```

```php
if (!isset($_GET['code'])) {
  $auth_url = $client->createAuthUrl();
  header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));
} else {
  $client->authenticate($_GET['code']);
  
  $access_token = mysqli_real_escape_string($conn, serialize($client->getAccessToken()));
  //this is the first request so we got the refresh token, save access and refresh to database
  $refresh_token = mysqli_real_escape_string($conn, $client->getRefreshToken());

//then i save them both in database
}
```

code in Dashboard.php:
```php
$client = new Google_Client();
    $client->setAuthConfig('client_secret.json');
    $client->setRedirectUri('http://'.$_SERVER['HTTP_HOST'].'/dashboard.php');
    $client->addScope('https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/spreadsheets');
    $client->setAccessType('offline');
    $client->setIncludeGrantedScopes(true);
```

```php

//get access token array from database and set to the client object
$token = unserialize($row['access_token']);
            
            $client->setAccessToken($token);

if($client->isAccessTokenExpired()){
     //has expiered
     //request for a new access token using saved refresh token and
     //set the new access token to the client object
			
	$client->refreshToken($client->getRefreshToken());
		    
	echo $client->getAccessToken(); //this echos nothing
}
```

when i echo out the `$client->getRefreshToken()`, it has no problem in echoing the refresh token. but the problem is with the method `$client->refreshToken($client->getRefreshToken())` (I also tried `$client->fetchAccessTokenWithRefreshToken($client->getRefreshToken())` but no luck).

I went thought other issues like mine here [https://github.com/googleapis/google-api-php-client/issues/1475](https://github.com/googleapis/google-api-php-client/issues/1475)

But doesn't seems to be a solution. what could be the problem? I also get an error like the following in my error log:

    `[26-Nov-2019 06:13:20 America/New_York] PHP Warning:  Unsupported declare 'strict_types' in /path/to/google-api-php-client/vendor/monolog/monolog/src/Monolog/Logger.php on line 1`

    '[26-Nov-2019 06:13:20 America/New_York] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /path/to/google-api-php-client/vendor/monolog/monolog/src/Monolog/Logger.php on line 33`

Any help would be great!!

Thanks!

**Comment by pinoybai** [comment]
@JustinBeckwith and @theacodes , any help would be appreciated :)

**Comment by tmatsuo** [comment]
@pinoybai 
I'll read the Client code and try to answer your question

**Comment by tmatsuo** [comment]
The refreshing code in our quickstarts seems to work:
https://developers.google.com/sheets/api/quickstart/php

Can you try some of our quickstarts to see how token refresh works? It won't directly solve your problem, but it will definitely help you understand how it works.

It seems like getAccessToken returns an array representing the access token. This array contains refresh token as well.

If so, you don't need to store the refresh token. It doesn't solve your problem, but FYI.

> I also get an error like the following in my error log:

I think it's more appropriate to ask that question on Stackoverflow or somewhere.

**Comment by pinoybai** [comment]
Hi, thank you for your answer. upgrading to PHP 7.3 version solved the problem.

**Comment by pinoybai** [comment]
for those people who don't wanna upgrade but jsut wanna solve this issue with php. I used 'curl' function in php to send post request to google oauth URL `https://www.googleapis.com/oauth2/v4/token` . you can find working example in google oauth 2.0 playground.

Thanks,

**Comment by audas** [comment]
How is this issue closed - it does not return an access token?

`
$client->getRefreshToken()
`

Is empty ?

**Comment by 662781** [comment]
<img width="346" alt="quick screenshot" src="https://user-images.githubusercontent.com/70585970/196189047-90fb5ff6-d3b4-4567-9c7c-fdd1f8ce7244.png">

In 2022, I have a similar problem; I never get a refresh token. It should be present in the array you get after requesting an access token, according to Google's documentation. 

I can't refresh the access token now, which results in a 401 error after an hour (the expiration time).
