### ISSUE TITLE
unauthorized client

### ISSUE THREAD

**Issue by shahidgepl** [googleapis/google-api-php-client#1753]
Type: Google_Service_Exception

Message: { "error": "unauthorized_client", "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested." }

I am using the google-apiclient-services to connect to Gmail using a Service Account. 

my code is
$client = new Google_Client();
$client->setApplicationName('test');
$client->useApplicationDefaultCredentials();
$client->setScopes(Google_Service_Gmail::GMAIL_READONLY);
$client->setSubject('test@gmail.com');
$service = new Google_Service_Gmail($client);
$user = 'me';
$results = $service->users_messages->listUsersMessages($user);

please let me know what i'm doing wrong

**Comment by tmatsuo** [comment]
I recommend that you follow our quickstart at:
https://developers.google.com/gmail/api/quickstart/php

Hope it helps!

**Comment by AleeeKoi** [comment]
Hi @shahidgepl , same here.
I'm authenticating with a gmail service account with granted access in workspace domain.
@tmatsuo , I'm trying to make a service-to-service connection, so I can't manage automatically like oath2 approvation.
@shahidgepl have you resolved?
Thanks
