### ISSUE TITLE
problem with v3 API after update

### ISSUE THREAD

**Issue by trone007** [googleapis/google-api-php-client#1754]
API services not available to use V3 GoogleApi

Problem in version of google/apiclient-services in composer.json. after manual update required lib problem was solved.

**Comment by Hexa-IT** [comment]
I have the same problem, I can't even require it.

**Comment by jdpedrie** [comment]
Hello,

I'm sorry but I'm having trouble understanding the issue. Are you using the packages available on the [releases](https://github.com/googleapis/google-api-php-client/releases) page, or installing via composer?

What version of `google/apiclient` are you using?

**Comment by mohitokade** [comment]
Hi Stepan Zolotukhin,

Please let me know what exactly needs to be changed. I dont see V3 available on git and am currently using 2.0.0-RC5 which says API deprecated.

**Comment by jdpedrie** [comment]
Which API are you attempting to use?

**Comment by mohitokade** [comment]
Android publisher api. Got the solution. Replaces v2 with v3 in androidpublisher.php

**Comment by trone007** [comment]
> I have the same problem, I can't even require it.

try to run 
```composer require google/apiclient-services v0.121 ```
