### ISSUE TITLE
Seldom 403 error - Request had insufficient authentication scopes. MyBusiness

### ISSUE THREAD

**Issue by bizmate** [googleapis/google-api-php-client#1756]
### Environment details

  - OS: Ubuntu 16.04.2 LTS
  - PHP version: 7.0.22
  - Package name and version: google/apiclient v2.4.0

#### Steps to reproduce

  1. GET https://mybusiness.googleapis.com/v4/accounts 

#### Code example

```php

const DEFAULT_SCOPES = array(
		'https://www.googleapis.com/auth/userinfo.email',
		'https://www.googleapis.com/auth/userinfo.profile',
		'https://www.googleapis.com/auth/plus.business.manage'
);

// how $this->client is created
private function setGoogleClient( $clientSecret ) {
		$client = new Google_Client();
		$client->setAuthConfig($clientSecret);
		$client->setAccessType("offline");        // offline access
		$client->setIncludeGrantedScopes(true);   // incremental auth
		$client->addScope( $this->scopes );
		$appHostname = getenv('APP_HOSTNAME') ? getenv('HOSTNAME') : self::DEFAULT_APP_HOSTNAME;
		$client->setRedirectUri('https://' . $appHostname . self::GMB_CODE_REDIRECT_PATH);
		$client->setApprovalPrompt('force');
		
		return $client;
	}

// account request
$accountsResponse = $this->httpClient->request(
    'GET',
    self::GMB_HOST . self::GMB_API_VERSION . self::GMB_ACCOUNTS_RESOURCE,
        [
            'headers' => ['Authorization' => 'Bearer ' . $gmbAuth->accessToken ]
        ]
);

//fetching, so initial fetching is based on the redirect, that provides the code, is the simple call to 			
$this->googleClient->fetchAccessTokenWithAuthCode($authCode);
$accessToken = $this->googleClient->getAccessToken();

//refreshing the token looks at the age of it and then auto refresh it before making a request. 
// If already expired this is called
$accessToken = $this->googleClient->fetchAccessTokenWithRefreshToken(
			$gmbAuth->refreshToken
		);

/** 
the call to accounts resource is only made if the token refresh is successful, 
else the whole Auth object (access token including code, refresh code, when created, TTL etc) 
is disabled and the user is only able to see cached locations, 
as ultimately the scope is to get the locations for all accounts.
Not sure where the problem is coming from but as I see it, the access tokens are definitely valid when making the request and the scopes are fixed.
**/
```

The above is an extract of the code that does not permanently fail. The exception is 
```
Client error: `GET https://mybusiness.googleapis.com/v4/accounts` resulted in a `403 Forbidden` response:
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISS (truncated...)
```

But the scopes are always a fixes set as shown above and `plus.business.manage` is always included in the calls. As mentioned above this is not a permanent error and given the scopes do not change I have no idea where the problem is coming from. Any suggestion on what might be going wrong?

**Comment by bshaffer** [comment]
Hi there! What does your code look like for fetching the access token?

**Comment by bizmate** [comment]
@bshaffer I have added snippets of code on 
- how the client is instatiated
- how the first access token/object  is fetched from the code provided by the redirect
- how the whole access token is refreshed and a description of the logic that ensures this token is indeed valid

**Comment by bshaffer** [comment]
In my own code I'm getting `Service 'mybusiness.googleapis.com' not found or permission denied.`. Have you been granted special access to this API?

**Comment by bizmate** [comment]
@bshaffer yes this is a private api

**Comment by phil294** [comment]
Why was this closed?

**Comment by bshaffer** [comment]
I cannot tell from [the documntation](https://developers.google.com/my-business/content/accounts) which scopes are required for this API call, but would try a broader scope. unfortunately since this API is not yet public, I cannot advise what the best scope is.

**Comment by bizmate** [comment]
Here is the documentation showing what [scopes are required](https://developers.google.com/my-business/content/implement-oauth)
