### ISSUE TITLE
Example request: updates - Calendar, etc

### ISSUE THREAD

**Issue by briancoogan** [googleapis/google-api-php-client#1757]
Despite fairly extensive searching, it's difficult or impossible to find how to use this library for updates, ie: using PATCH, if possible, but really just wanting to know what is considered best practice.  I'm asking here given your statement at the end of the documentation page!

Would it be possible to find out what is recommended for updating records?

Some questions for which answers would make life so much easier:
 - what is best practice for updates?
 - does the existing update() method do PATCH automatically?

For example, a couple of examples shoring the following would make things much clearer:
 - changing the color of a an existing Calendar Event
 - updating a contact just to add a phone number

I've looked through both the client documentation and the Calendar API documentation and I can't see any PHP examples for updates.  There seems to be very little in terms of PHP update examples available via Google search too, though possibly I just had the wrong keywords.

**Comment by briancoogan** [comment]
As another point that would be useful in this day and age where security is all-critical, it might also be worth emphasizing (in several places) that best practice for credentials.json and token.json file is that they should be kept outside the docroot so they can't be viewed over the web.  I wonder how many projects have these files, or other json credential files, currently exposed?  On many default Apache setups, for example, .json files are readable.  (I have noticed some comment to the effect that they should not be readable, but perhaps it might be useful to take the emphasis up a notch).  Many thanks!

**Comment by jdpedrie** [comment]
Thanks for the suggestions! All good ideas. I'll pass them along to the team.

**Comment by jdpedrie** [comment]
> does the existing update() method do PATCH automatically?

The clients in this library mirror the REST API specification. So for instance, if you wish to know what the HTTP method or semantics are for updating a file using the Drive API, you can refer to the [API reference documentation](https://developers.google.com/drive/api/v3/reference/files/update) for detailed information including the underlying HTTP method used by this client.

**Comment by briancoogan** [comment]
Thanks John, appreciate you getting back!  Having the basic use cases
covered by tested examples is sensationally helpful, even if they're
excerpts rather than an entire working example.

Have a happy and relaxing break,
Cheers,
Brian

**Comment by briancoogan** [comment]
Although I did find an example in the end, it's still hard to work out what
the actual PHP code usng the library would look like without that.  We're
talking about normal slightly dumb mortals like myself, not you guys :)

eg:  $service->events->PatchEvents($calendarId, $eventId, $optParams);

eg: Linda's example here:
https://github.com/LindaLawton/Google-APIs-PHP-Samples/blob/master/Samples/Calendar%20API/v3/EventsPatchSample.php
her main website: https://www.daimto.com/google-apis-samples/

**Comment by meredithslota** [comment]
The basic PHP samples can be found in the Quickstart, here: https://developers.google.com/calendar/api/quickstart/php (this is relatively recently added). More GSuite/Workspace code examples can be found here: https://github.com/googleworkspace/php-samples Requests for new samples can also be filed in that repo, so I'm going to go ahead and close this one for now.
