### ISSUE TITLE
google-api-php-client auto-refresh does not update internal access_token and created fields

### ISSUE THREAD

**Issue by briancoogan** [googleapis/google-api-php-client#1758]
_[Apologies if this is not an actual bug, but it seems to me it should work this way, and the quickstart.php example seems to suggest it should.]_

Version: 2.4.0   google/apiclient

After the library does an auto-refresh of the access token, it seems that the internal [access_token] and [created] values as returned via the ```getAccessToken()``` method do not update.  This results in the pre-refresh values being used and returned by subsequent calls, something that is going to be unnecessarily hiking load values on the Google side.

Unless I'm missing something, I would intuitively expect these to be updated to the latest value, so that subsequent calls do not repeat the refresh operation, and so that the new values are available via the ```getAccessToken()``` method.

The values do update correctly, and are returned correctly, when using ```$client->fetchAccessTokenWithRefreshToken()``` when tested as of 2.4.0.

I expect that few people are using the auto-refresh functionality so far, but as time goes on you will see access tokens being refreshed on every access as a symptom of this problem.

Current workaround code in a ```setTokenCallback()``` function is:
```
$tokenCallback = function ($cacheKey, $newAccessToken)
  use (&$accesstoken, $TOKEN_FILE, &$client) {
    $accesstoken['access_token'] = $newAccessToken; // workaround 2.4.0
    $accesstoken['created'] = time(); // workaround 2.4.0
    file_put_contents($TOKEN_FILE, json_encode($accesstoken, JSON_PRETTY_PRINT));
    $client->setAccessToken($accesstoken); // workaround 2.4.0
    echo "callback: New access token obtained ck=$cacheKey - ".print_r($newAccessToken, 1)."<br />\n";
};
$client->setTokenCallback($tokenCallback);
```
Version from composer.lock:
  "name": "google/apiclient",
  "version": "v2.4.0",

**Comment by jdpedrie** [comment]
Hi Brian, thanks for the report. We'll look into this further. Could you share an example of the code and configuration you are using to setup token refreshing?

**Comment by briancoogan** [comment]
Hi John,

This is the callback code I used to workaround and ensure the refresh token
is saved:

>     $tokenCallback = function ($cacheKey, $new_access_token)
>       use (&$accesstoken, $TOKEN_FILE, &$gclient) {
>       // auto-refreshed token is not correctly exposed
>
>
> *      $accesstoken['access_token'] = $new_access_token; // workaround
> 2.4.0         $accesstoken['created'] = time() - 2; // workaround 2.4.0 bug*
>      saveToken($accesstoken);
>
> *       $gclient->setAccessToken($accesstoken); // workaround 2.4.0 bug*
>      echo "callback: New access token obtained ck=$cacheKey - "
>                . print_r($new_access_token, 1) . "<br />\n";
>     };
>     $gclient->setTokenCallback($tokenCallback);
>

Everything else is pretty much standard code as provided; the bold lines
were the change required to make it work.

If the access token isn't saved at that point, you lose the refresh_token
(and possibly the id_token, but haven't investigated) and can't get it
offered again unless you force it with setPrompt or setAccessPrompt (?).

Should be only a few lines fix.

Cheers,

Brian

**Comment by lsnider** [comment]
Have same issue and also had to put in a workaround

**Comment by bshaffer** [comment]
This is indeed a bug. Some ways to fix it:

 - Add a default token callback which updates the local token when a new one is fetched. 
 - have `getAccessToken` pull from the cache using the cache key when `$this->token` is null, and set `$this->token` to null when it's expired.

**Comment by danoscarmike** [comment]
@bshaffer @jdpedrie is there a fix in the works?

**Comment by bshaffer** [comment]
@danoscarmike sorry for the delay. Please check out https://github.com/googleapis/google-api-php-client/pull/1926 and see if this fix works for you! Feel free to leave a review, and hopefully we'll have this merged and released soon.

You can test by using `dev-fix-caching` as the version of this library in composer.
