### ISSUE TITLE
 Legacy People API has not been used in project

### ISSUE THREAD

**Issue by thameemk612** [googleapis/google-api-php-client#1759]
**Google OAuth shows below error** 
403 -  Legacy People API has not been used in project <project_id> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=<project_id> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by jdpedrie** [comment]
Did you visit the linked page and enable the API as instructed?

**Comment by thameemk612** [comment]
> Did you visit the linked page and enable the API as instructed?

**Yes, but it shows as below** 
"Failed to load."
"There was an error while loading /apis/api/legacypeople.googleapis.com/overview?project=<project_id>. Please try again."

**Comment by jdpedrie** [comment]
Hi @thameemk612,

According to [the documentation](https://developers.google.com/people/legacy), the legacy People API cannot be enabled for new projects. It is automatically available for users of the now shutdown Google+ APIs.

You can use the [People API v1](https://developers.google.com/people/api/rest/v1/people) instead. [Click here](https://console.developers.google.com/apis/library/people.googleapis.com) to enable the API.

**Comment by thameemk612** [comment]
> Hi @thameemk612,
> 
> According to [the documentation](https://developers.google.com/people/legacy), the legacy People API cannot be enabled for new projects. It is automatically available for users of the now shutdown Google+ APIs.
> 
> You can use the [People API v1](https://developers.google.com/people/api/rest/v1/people) instead. [Click here](https://console.developers.google.com/apis/library/people.googleapis.com) to enable the API.

Thanks @jdpedrie

**Comment by alviandaniel2109** [comment]
Message: Error calling GET https://www.googleapis.com/plus/v1/people/me: (403) Legacy People API has not been used in project 986391836060 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=986391836060 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Filename: C:\xampp\htdocs\ci_login_app\application\libraries\Google\Http\REST.php

Line Number: 110

**Comment by kenzotenma016** [comment]
I still have this issue even after enabling the Google People API

**Comment by abinhho** [comment]
@jdpedrie I already enabled People api and wait for 12 hours but nothing change.
```
Activation status
Enabled
```

Log error
```
{
    "code": 403,
    "message": "Legacy People API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.Help",
            "links": [
                {
                    "description": "Google developers console API activation",
                    "url": "https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=xxxx"
                }
            ]
        }
    ]
}

```

**Comment by jdpedrie** [comment]
@alviandaniel2109 @abinhho make sure you're using [`Google_Service_PeopleService`](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/PeopleService.php), not `Google_Service_People`.

**Comment by abinhho** [comment]
@jdpedrie I am using `https://www.googleapis.com/plus/v1/people/me`. Is that right api?

**Comment by abinhho** [comment]
@jdpedrie I am using `https://www.googleapis.com/plus/v1/people/me`. So what's things I have to config or enable in google api console? I am using nodejs.

**Comment by jdpedrie** [comment]
Please direct questions about the Node clients to [`google-api-nodejs-client`](https://github.com/googleapis/google-api-nodejs-client).

**Comment by doduythinh** [comment]
I still error when enable people API still error  this my api: https://www.googleapis.com/plus/v1/people/me?access_token=
help me
{
    "code": 403,
    "message": "Legacy People API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.Help",
            "links": [
                {
                    "description": "Google developers console API activation",
                    "url": "https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=xxxx"
                }
            ]
        }
    ]
}
