### ISSUE TITLE
500 - Internal error encountered - On Google Analytics Management Goals PATCH Request

### ISSUE THREAD

**Issue by judahnator** [googleapis/google-api-php-client#1764]
#### Environment details

  - OS: Linux
  - PHP version: 7.4.0
  - Package name and version: google/apiclient v2.4.0

#### Steps to reproduce

  1. Create a Google Analytics goal.
  1. Attempt to update it.

There have been no code changes on our end when these issues started coming up, aside from maybe a minor version bump in this package. These issues started suddenly, after several months of no trouble at all.

We are seeing this issue on about a half dozen properties, more are likely affected but we have no reason to send goal updates their way for now.

#### Code example

```php
$googleAnalytics->management_goals->patch(
  $googleGoal->getAccountId(),
  $googleGoal->getWebPropertyId(),
  $profile->getId(),
  $googleGoal->getId(),
  $localGoal
);
```
#### Expected Result

No error, the goal is updated.

#### Actual Result

A `Google_Service_Exception` is thrown with the following message:
```json
{ 
  "error": { 
    "code": 500, 
    "message": "Internal error encountered.", 
    "errors": [ 
      {
         "message": "Internal error encountered.", 
         "domain": "global", 
         "reason": "backendError"
      }
    ], 
    "status": "INTERNAL" 
  } 
} 
```

**Comment by jdpedrie** [comment]
Looks like you created a [bug report](https://issuetracker.google.com/issues/146448308) and it was accepted. Let's continue tracking the issue there.

Best of luck! If it turns out to be an issue with the client library (the Googler working the case should tell you if that is the case), please re-open and we'll work on figuring it out here.
