### ISSUE TITLE
Why do the methods to call "list" use a different naming convention?

### ISSUE THREAD

**Issue by billynoah** [googleapis/google-api-php-client#1765]
Most methods use the same name as the service itself, e.g., "get", "delete", "create".  But for some reason most of the "list" service are named things like:

    listUsersMessages
    listUsersLabels

What is the reason for this? Since these are class methods, I'd assume there is no conflict with php built-in function `list()` and `$service->users_labels->listUsersLabels()` seems a bit redundant.

**Comment by jdpedrie** [comment]
`list` is a PHP [keyword](https://www.php.net/manual/en/reserved.keywords.php) and until PHP 7 could not be used as a method name. Since we still support PHP 5, we cannot use `list`.

Hope this answers the question! Happy to continue the discussion if not. :)

**Comment by billynoah** [comment]
Thanks, that makes sense.  I thought it was a regular function and didn't realize it was a keyword.
