### ISSUE TITLE
Yet another composer update question

### ISSUE THREAD

**Issue by sglessard** [googleapis/google-api-php-client#1766]
Hello,

To support Google API v3, i'm trying to update the google/apiclient package in my project.

To do so I've accordingly edited composer.json :

```json
    "require": {
        
        "google/apiclient": "^2.0",

    }
```

The composer output is confusing me :

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for google/apiclient == 2.9999999.9999999.9999999-dev
    - Conclusion: don't install google/apiclient v2.4.0
    - Conclusion: don't install google/apiclient v2.3.0
    - Conclusion: don't install google/apiclient v2.2.4
    - Conclusion: don't install google/apiclient v2.2.3
    - Conclusion: don't install google/apiclient v2.2.2
    - Conclusion: don't install google/apiclient v2.2.1
    - Conclusion: don't install google/apiclient v2.2.0
    - Conclusion: don't install google/apiclient v2.1.3
    - Conclusion: don't install google/apiclient v2.1.2
    - Conclusion: don't install google/apiclient v2.1.1
    - Conclusion: don't install google/apiclient v2.1.0
    - google/apiclient v2.0.3 requires google/auth 0.10 -> satisfiable by google/auth[v0.10].
    - Conclusion: don't install google/auth v0.10
    - google/apiclient v2.0.1 requires google/auth 0.9 -> satisfiable by google/auth[v0.9].
    - google/apiclient v2.0.2 requires google/auth 0.9 -> satisfiable by google/auth[v0.9].
    - Conclusion: don't install google/auth v0.9
    - Can only install one of: google/auth[v0.8, v0.5].
    - Can only install one of: google/auth[v0.8, v0.5].
    - Can only install one of: google/auth[v0.8, v0.5].
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Installation request for google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.2.4, v2.3.0, v2.4.0, 2.x-dev].
    - Installation request for google/auth (locked at v0.5) -> satisfiable by google/auth[v0.5].
```

When I change the minimum-stability from `stable` to `dev`, it does not complained anymore, but I get subsequent error when calling `composer install`.

Any help on understanding the problem would be appreciated.
Thanks

**Comment by danielabyan** [comment]
I have the same problem
The `composer require google/apiclient 2.4.0` returns following message

> ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for google/apiclient 2.4.0 -> satisfiable by google/apiclient[v2.4.0].
    - Conclusion: remove google/auth v0.5
    - Conclusion: don't install google/auth v0.5
    - google/apiclient v2.4.0 requires google/auth ^1.0 -> satisfiable by google/auth[v1.0, v1.0.1, v1.1.0, v1.2.0, v1.2.1, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.4.0, v1.5.0, v1.5.1, v1.5.2, v1.6.0, v1.6.1].
    - Can only install one of: google/auth[v1.0, v0.5].
    - Can only install one of: google/auth[v1.0.1, v0.5].
    - Can only install one of: google/auth[v1.1.0, v0.5].
    - Can only install one of: google/auth[v1.2.0, v0.5].
    - Can only install one of: google/auth[v1.2.1, v0.5].
    - Can only install one of: google/auth[v1.3.0, v0.5].
    - Can only install one of: google/auth[v1.3.1, v0.5].
    - Can only install one of: google/auth[v1.3.2, v0.5].
    - Can only install one of: google/auth[v1.3.3, v0.5].
    - Can only install one of: google/auth[v1.4.0, v0.5].
    - Can only install one of: google/auth[v1.5.0, v0.5].
    - Can only install one of: google/auth[v1.5.1, v0.5].
    - Can only install one of: google/auth[v1.5.2, v0.5].
    - Can only install one of: google/auth[v1.6.0, v0.5].
    - Can only install one of: google/auth[v1.6.1, v0.5].
    - Installation request for google/auth (locked at v0.5) -> satisfiable by google/auth[v0.5].

For a quick solution to this problem, I deleted the vendor folder and the file “composer.lock” and then ran the “composer install” command, which was successful.

**Comment by sglessard** [comment]
@danielabyan you are correct, i've simply deleted `composer.lock` file, then call `composer install` and everything went fine.

Wish you best

**Comment by sglessard** [comment]
> i've simply deleted `composer.lock` file, then call `composer install` and everything went fine.

Was awkward to delete `composer.lock` , i've resolved the issue uninstall/reinstall the package

```bash
$ composer remove google/apiclient
$ composer require google/apiclient
```
