### ISSUE TITLE
How to set curl timeout in Google API PHP client version 2.4.0

### ISSUE THREAD

**Issue by savoy-wang** [googleapis/google-api-php-client#1767]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
$client = new Google_Client();
$client->useApplicationDefaultCredentials();

$client->setConfig('timeout', 0.0001);
I use like this, but it not work. how can I solve it?

**Comment by jdpedrie** [comment]
You may configure the underlying HTTP client in the following manner:

```php
use Google_Client;
use GuzzleHttp\Client as Guzzle;

$http = new Guzzle([
    'timeout' => 1 // provide value in seconds
]);

$google = new Google_Client();
$google->setHttpClient($http);
```

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!

**Comment by paultan63** [comment]
Google_Client->createDefaultHttpClient() sets some default parameters, and replacing the default httpClient may not be the best choice. It is better to provide an interface for setting guzzle default parameters.
