### ISSUE TITLE
Addon domain is an issue for google oauth

### ISSUE THREAD

**Issue by vk011** [googleapis/google-api-php-client#1770]
PHP 7.something (latest), Laravel framework / Socialite package

I've created a website locally which works fine with google oauth, however the live website that is supposed to use it uses an addon domain, which I guess is the issue as there is nothing else "out of the ordinary".

The `state` gets lost in the process.

So the addon domain points to a folder inside the www folder of the main domain as it normally would, and this for some reaosn seems to be an issue.

The funny thing is, if I don't use the `profile` scope then it works, but I actually need the profile scope and even if I didn't I should be able to use it if I wanted to.

Are you guys aware of this and why is this a problem? For other providers this isn't an issue.

**Comment by jdpedrie** [comment]
Socialite appears to implement their own OAuth flow, not relying on the implementations provided by Google. As we're not closely familiar with how that library works, I believe that this would be a [question for the maintainers of that package](https://github.com/laravel/socialite/issues).

If you find it is specific to this library, feel free to re-open. :)
