### ISSUE TITLE
PHP Warning:  Unsupported declare 'strict_types'.  Is the minimum supported PHP version 7.1?

### ISSUE THREAD

**Issue by cesarvn2010** [googleapis/google-api-php-client#1771]
Is the minimum required version not PHP 5.4? Why then on my server with PHP 5.6 is the error below appearing? From what I researched, the solution is to upgrade PHP to version 7.1.

PHP Warning:  Unsupported declare 'strict_types' in /opt/gmail-check/vendor/monolog/monolog/src/Monolog/Logger.php on line 1
PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /opt/gmail-check/vendor/monolog/monolog/src/Monolog/Logger.php on line 33

**Comment by jdpedrie** [comment]
Are you using the downloadable package or installing via composer?

**Comment by cesarvn2010** [comment]
> Are you using the downloadable package or installing via composer?

downloadable package

**Comment by cesarvn2010** [comment]
It is not a mistake. I apologize, is that in my inattention, I had not seen that there is the version supported for PHP 5.6, and look that it was well in my dear time I went to download it.

**Comment by Joel-James** [comment]
@jdpedrie I'm installing via Composer. Is there any way I can use the latest version with PHP 5.4 support?

**Comment by jdpedrie** [comment]
@Joel-James yes, the latest version should support PHP 5.4 with no problems. Just require it and install. Composer should detect your PHP version and install dependencies which support that version of PHP.

**Comment by Joel-James** [comment]
@jdpedrie For some reason it doesn't work and installed the latest version which required PHP7. As a workaround I manually added `"monolog/monolog": "^1.17"` to my project's `composer.json` file. Any issues?

**Comment by jdpedrie** [comment]
That should be fine.

**Comment by anthonytr** [comment]
hi, i have the same error, Unsupported declare 'strict_types'.
did you know how I can solve this problem? thanks
