### ISSUE TITLE
YouTube Analytics API: 404 Not Found Exception while sending query

### ISSUE THREAD

**Issue by Incher25** [googleapis/google-api-php-client#1774]
Hi all,

I try to send targeted query via YouTube Analytics API but I receive "[Google_Service_Exception (404)]   Not Found" exception. I'm using googleapis/google-api-php-client v2.4.0 and PHP v7.1.19. Here is my code:

```
$this->client = new Google_Client();
$this->client->setAuthConfig($credentials);
$this->client->addScope(Google_Service_YouTube::YOUTUBE);
$this->client->addScope(Google_Service_YouTubeAnalytics::YT_ANALYTICS_MONETARY_READONLY);
$this->client->setAccessType('offline');
$this->client->setIncludeGrantedScopes(true);

$service = new \Google_Service_YouTubeAnalytics($this->client);

$report = $service->reports->query('channel==' . $channelId, '2020-01-11', '2020-01-13', 
'views,likes,dislikes', ['dimensions' => 'day']);
```
Thanks for help in advance!

**Comment by jdpedrie** [comment]
Hi @Incher25,

I'm not sure about the parameters you're using to call the method. `Google_Service_YoutubeAnalytics_Resource_Reports::query()` accepts a single array argument. I'd suggest taking a close look at the documented array parameters on that method.

```php
$report = $service->reports->query([
    'ids' => 'channel==' . $channelId,
    'startDate' => '2020-01-11',
    'endDate' => '2020-01-13',
    'metrics' => 'views,likes,dislikes',
    'dimensions' => 'day'
]);
```

I've not tested this, just based off looking at the documentation. Give it a shot and let me know.

**Comment by Incher25** [comment]
Hi @jdpedrie, 

Thanks for help! I updated googleapis/google-api-php-client to v2.4.0 but still used an old version (v0.41) of googleapis/google-api-php-client-services. So after updating it to v0.121 it works just fine with single array argument.
