### ISSUE TITLE
Is it possible to return the category ID of a video when using the listSearch() function?

### ISSUE THREAD

**Issue by montrealks** [googleapis/google-api-php-client#1775]
I don't know why, but in order to use the API update to update the description of a video in your library you have to provide more than just the ID, you have to provide: the title, the ID, and the category ID. Why you need more than just the unique video ID is beyond me. 

When I request a list of videos using the following parameters:

```
$queryParams = [
        'forMine' => true,
        'q' => $q,
         // 'fields' => 'items(id,snippet/title,snippet/description)', <- would like to specify categoryId here
        'type' => 'video',
        'maxResults' => 50
    ];
$response = $service->search->listSearch('snippet', $queryParams);
```
The returned list provides the Title and the ID but not the Category ID. Actually I don't know of any way of getting the category ID besides opening the video in your YouTube dashboard, looking at the category, and the comparing it to a[ list like this one](https://gist.github.com/dgp/1b24bf2961521bd75d6c) 

So, is their a way of updating a video's description without needing the category ID, or is there a way of acquiring that category ID using the API?

Here is how I am attempting to update the description.
```
	// Auth the client
    $service = new Google_Service_YouTube($client);
    
    // Define the $video object, which will be uploaded as the request body.
    $video = new Google_Service_YouTube_Video();
	// Set the ID
    $video->setId($video_id);
    
    // Add 'snippet' object to the $video object.
    $videoSnippet = new Google_Service_YouTube_VideoSnippet();
    $videoSnippet->setCategoryId('<HOW TO GET THIS?>');
    $videoSnippet->setDescription('Test Description');
    $videoSnippet->setTitle($video_title);
    $video->setSnippet($videoSnippet);

    $response = $service->videos->update('snippet', $video);
```

**Comment by jdpedrie** [comment]
Reviewing the API documentation, I see that `update` requires you to provide all the mutable fields when calling the method. Partial updates are unfortunately not available.

Rather than use search, you can use list to fetch the video, modify the description, and update:

```php
$client = new Google_Client();
$service = new Google_Service_Youtube($client);

$videos = $service->videos->listVideos('snippet', [
	'id' => $videoId
]);

$video = current($videos->getItems());
$video->getSnippet()->setDescription($description);

$service->videos->update('snippet', $video);
```

**Comment by montrealks** [comment]
> Reviewing the API documentation, I see that `update` requires you to provide all the mutable fields when calling the method. Partial updates are unfortunately not available.
> 
> Rather than use search, you can use list to fetch the video, modify the description, then update:
> 
> ```
> $client = new Google_Client();
> $service = new Google_Service_Youtube($client);
> 
> $videos = $service->videos->listVideos('snippet', [
> 	'id' => $videoId
> ]);
> 
> $video = current($videos->getItems());
> $video->getSnippet()->setDescription($description);
> 
> $service->videos->update('snippet', $video);
> ```

Great, thanks. I was hoping to avoid having to use both the search and list APIs but I can see that it's not possible.
