### ISSUE TITLE
Keep getting "Rate Limit Exceeded" for webmasters.searchanalytics.query

### ISSUE THREAD

**Issue by AroundtheGlobe** [googleapis/google-api-php-client#1778]
We keep getting "Rate Limit Exceeded" errors, mainly for webmasters.searchanalytics.query. I am using the most up to date version of the google-api-php-client . Our users connect via OAuth with the service. Our app status in console.developers.google.com shows "published" and from what I understand the app and scopes are all validated by Google. The Metrics tab in de console shows I am never over 0.08 queries/s when an error occurs. The errors by API methods usually shows a 100% error rate pretty randomly when errors occur. We don't receive the error messages for all accounts. This is the exact error message we get: 

`{ "error": { "errors": [ { "domain": "usageLimits", "reason": "rateLimitExceeded", "message": "Rate Limit Exceeded" } ], "code": 429, "message": "Rate Limit Exceeded" } }` 

Once we received this error message we stop the API calls. The developer console never shows we reached the limit, or what error exactly caused us to hit the API limit. I currently request 10 urls per 5 minutes via a cronjob with a 2 sec delay per request and I still get the API Limit errors. We're able to have 100.000.000 per day and 2.000 queries per 100 second per user. De data we request is the keywords per url with a limit of 200. When trying to replicate the error by starting our script manually don't get the error messages. 

I've got no idea anymore how to fix this, so hopefully someone can assist me to help me move forward.

**Comment by jdpedrie** [comment]
Are you using batch request? If so, make sure your batch sizes are limited to remain within the quota.

**Comment by AroundtheGlobe** [comment]
I am not using the batch requests. After some more testing I seem to be able to reduce the number of errors to only a few accounts. I now only check 300 urls per 2 hours at most. That works for most of the websites that I am querying the data from. But not for a handful of domains. They keep giving the error messages. This is the code I am using (and is causing the problems)

       ```
        $service = new \Google_Service_Webmasters($client);
        $q = new \Google_Service_Webmasters_SearchAnalyticsQueryRequest();

        $q->setStartDate(date( 'Y-m-d', strtotime( '1 month ago' ) ));
        $q->setEndDate(date( 'Y-m-d', strtotime( 'now' ) ));
        $q->setDimensions(array('query'));

        $q->setRowLimit("200");

        $filter = new \Google_Service_Webmasters_ApiDimensionFilter();
        $filter->setDimension("page");
        $filter->setOperator("equals");
        $filter->setExpression($url);
        $filters = new \Google_Service_Webmasters_ApiDimensionFilterGroup();
        $filters->setFilters(array($filter));

        $q->setDimensionFilterGroups(array($filters));

        $q->setSearchType('web');
        $arrResult= array();
        try {
            $u = $service->searchanalytics->query($url, $q);
            $i = 0;
            foreach($u->rows as $row)
            {
               //do stuff
            }
        }
        catch(\Google_Service_Exception $e )
        {
        }
```

**Comment by qiyang0221** [comment]
Have you solved you problems? I have the same problem. I slept [2, 4] secs for every request. I checked my google cloud platform and the peak queries per user per 100 secs is 50, but my quota is 2k. It makes fairly confused.

**Comment by AroundtheGlobe** [comment]
No, unfortunately I haven't been able to solve the problem. I've got a different process running with almost the exact same code but now retrieving the data per day and strangely enough that process isn't giving any problems at all. It also seems some sites / access tokens cause more problems than others. But I still haven't found the root cause of the error messages. Just like you said the Google Cloud Platform isn't reporting any problems at all and the error messages vary.

**Comment by qiyang0221** [comment]
Hey, friend,
I just solved the problem. I thing the error log might be wrong. I catch the error and sleep 30 secs. After that, we send the query again, it works!

**Comment by AroundtheGlobe** [comment]
So you only add the sleep for 30 seconds after you catch the error? I've added a sleep of 5 sec between each API call but that still triggers the error.

**Comment by qiyang0221** [comment]
I think its ok to get the error. Actually I use [exponential backoff retry](https://en.wikipedia.org/wiki/Exponential_backoff) here. My initial sleeping time is 30 secs and it always succeed after sleeping 30 secs.

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!

**Comment by airobot60** [comment]
> We keep getting "Rate Limit Exceeded" errors, mainly for webmasters.searchanalytics.query. I am using the most up to date version of the google-api-php-client . Our users connect via OAuth with the service. Our app status in console.developers.google.com shows "published" and from what I understand the app and scopes are all validated by Google. The Metrics tab in de console shows I am never over 0.08 queries/s when an error occurs. The errors by API methods usually shows a 100% error rate pretty randomly when errors occur. We don't receive the error messages for all accounts. This is the exact error message we get: 
> 
> 
> 
> `{ "error": { "errors": [ { "domain": "usageLimits", "reason": "rateLimitExceeded", "message": "Rate Limit Exceeded" } ], "code": 429, "message": "Rate Limit Exceeded" } }` 
> 
> 
> 
> Once we received this error message we stop the API calls. The developer console never shows we reached the limit, or what error exactly caused us to hit the API limit. I currently request 10 urls per 5 minutes via a cronjob with a 2 sec delay per request and I still get the API Limit errors. We're able to have 100.000.000 per day and 2.000 queries per 100 second per user. De data we request is the keywords per url with a limit of 200. When trying to replicate the error by starting our script manually don't get the error messages. 
> 
> 
> 
> I've got no idea anymore how to fix this, so hopefully someone can assist me to help me move forward.
