### ISSUE TITLE
token : null using new Google_Client();

### ISSUE THREAD

**Issue by dmsherazi** [googleapis/google-api-php-client#1780]
I am unable to get token from Google_Client(),  I want to implement Google HomeGraph  for request sync. I am using laravel as my PHP framework. In the code below I load the json config file but it always fails to get a proper token. I am unable to find a documentation that I can follow to solve this issue 

```

       $path = storage_path() . "/gapi_key.json";
        putenv('GOOGLE_APPLICATION_CREDENTIALS='.$path);
        $client = new Google_Client();
        $client->useApplicationDefaultCredentials();
        $client->setAuthConfig($path);
        $client->authorize();
        dd($client);
```

This results in the response as shown below

![image](https://user-images.githubusercontent.com/6149070/73608921-db741f00-45e1-11ea-91ed-3df65af3b423.png)

**Comment by jdpedrie** [comment]
What happens when you try to make a request using the client? Do you get an error?

**Comment by p7Rck** [comment]
Hi @jdpedrie ! im working together with @dmsherazi. I tried to make a request im having this error
``{ "error": { "code": 400, "message": "Request contains an invalid argument.", "errors": [ { "message": "Request contains an invalid argument.", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } }``

**Comment by jdpedrie** [comment]
I don't believe that there are specific examples for PHP, however if you follow the [API reference](https://developers.google.com/assistant/smarthome/reference/rest/v1/devices/requestSync) closely, you should find that it maps well to the PHP client.

`agentUserId` is required, so we must set it in the request.

```php
$request = Google_Service_HomeGraphService_RequestSyncDevicesRequest;
$request->setAgentUserId(Auth::user()->id);

$homegraph = new Google_Service_HomeGraphService($client);
$response = $homegraph->devices->requestSync($request);
```

**Comment by p7Rck** [comment]
Thank you so much! i got it now.
