### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Google_Client' not found in...

### ISSUE THREAD

**Issue by JJimenez15** [googleapis/google-api-php-client#1784]
Hi, I am getting this error when trying to use Google_Client class:

`Fatal error: Uncaught Error: Class 'Google_Client' not found in ... Stack trace: #0 ...(4): require_once() #1 {main} thrown in ... on line 12`

Details:
PHP 7.2
Release 2.4.0
**Not** using composer

Code:
```
require_once 'google-api-php-client/autoload.php';
$gClient = new Google_Client(); // Line 12
```

**Comment by jdpedrie** [comment]
There is no `autoload.php` in the root of the v2 branch. If you are using the downloadable release, include `google-api-php-client/vendor/autoload.php` instead. If you're cloning the repository, this will not work unless you run `composer install`.

**Comment by JJimenez15** [comment]
Thanks, It worked.

**Comment by marzuq-aamir** [comment]
Thanks, It worked
