### ISSUE TITLE
Missing Google Play Movie,Tv Show support

### ISSUE THREAD

**Issue by kork341** [googleapis/google-api-php-client#1787]
Hello,
in the examples it is possible to find books with `new \Google_Service_Books($client);` to get the price.
But after hours of searching I have not found a method to search for movies or TV shows. 

In the API documentation of google I only find a old example:
http://playaffiliates.googleapis.com/v1/documents?searchQuery=Jaws&type=Movie
I would like to find out the prices of certain films by id and by title with the google-api-php-client.

**Comment by jdpedrie** [comment]
I am not aware of any Google APIs which provide this information. If you can find any more information about an active API which does, we can see about making sure it's included in the client.

**Comment by kork341** [comment]
google has published an example here: https://support.google.com/affiliate/answer/7188086
Under "Get movies by string search"

**Comment by jdpedrie** [comment]
Unfortunately we will likely not be able to publish a client for this API. You can call it directly using Guzzle and the Google Auth library for PHP. Take a look at [this example](https://github.com/googleapis/google-auth-library-php#call-the-apis) for details on how to authenticate your calls.
