### ISSUE TITLE
Get list of sheet

### ISSUE THREAD

**Issue by whatido1** [googleapis/google-api-php-client#1789]
How to retrive list of my sheets?
i try using
`Google_Service_Sheets::spreadsheets->get(spreadsheet_id, optParams)`
but it only return 2 which is:
`spreadsheetId & spreadsheetUrl `

i want do it like [this ](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get?apix_params=%7B%22spreadsheetId%22%3A%221oLPdPqI9wbW1b-aE1LKiPZVfgiNNXIYxN28BEoYKKzk%22%7D)

**Comment by jdpedrie** [comment]
Hello,

Are you trying to retrieve the sheet data along with the spreadsheet? You should be able to set `$optParams.includeGridData` to `true`:

```php
$sheets->spreadsheets->get($sheetId, ['includeGridData' => true]);
```

Alternatively, if you're trying to list all the sheets in your account, you may use the Drive API to list files with a query:

```php
$client = new Google_Client();
$drive = new Google_Service_Drive($client);
$sheetsList = $drive->files->listFiles([
	'q' => "mimeType='application/vnd.google-apps.spreadsheet'",
	'fields' => 'nextPageToken, files(id, name)'
]);
```

For this latter option, refer to the [API reference](https://developers.google.com/drive/api/v3/reference/files/list) for a full detailing of available options.

**Comment by whatido1** [comment]
![image](https://user-images.githubusercontent.com/42728829/74853561-ae10ca80-5370-11ea-8a66-76f4c2301330.png)
i want to get this sheetname, not spreadsheet file.

i do `$sheets->spreadsheets->get($sheetId, ['includeGridData' => true]);` but it only return this 
![image](https://user-images.githubusercontent.com/42728829/74853884-1c558d00-5371-11ea-8e69-fc3428e3e597.png)

**Comment by jdpedrie** [comment]
You can find this value at `sheets[sheet_index].properties.title`.

**Comment by eboujlal** [comment]
> hello can i get all lists of spread sheet with their title and id? for suppose i have 5 different spread sheets so i want to retrieve all list of that spread sheets with their title and id using PHP?

Hey, did you found a solution for this ?

**Comment by zahidgopang** [comment]
No still finding can u help
