### ISSUE TITLE
GoogleCloudStorage, object->exists throws exception instead of returning false

### ISSUE THREAD

**Issue by chrissachs** [googleapis/google-api-php-client#1791]
I'm trying to check if an object already exists inside of a bucket, before generating an upload url. The bucket has "fine grained access control" enabled. The check fails with "Forbidden" instead of returning false.

#### Environment details

  - OS: Ubuntu 18.04.4 LTS
  - PHP version: PHP 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
  - Package name and version: google/apiclient 2.4.0

#### Steps to reproduce

  1. see code below

#### Code example

```php 
$bucket = $client->bucket('mybucket');
$bucket->object('exists')->exists(); // returns true
$bucket->object('doesnotexist')->exists(); // expected: returns false, but throws exception
```

it throws this exception instead of a "NotFoundException":
```
^ Google\Cloud\Core\Exception\ServiceException^ {#504
  -serviceException: GuzzleHttp\Exception\ClientException^ {#512
    -request: GuzzleHttp\Psr7\Request^ {#499
      -method: "GET"
      -requestTarget: null
      -uri: GuzzleHttp\Psr7\Uri^ {#526
...
```

> Client error: `GET https://storage.googleapis.com/storage/v1/b/...?fields=name` resulted in a `403 Forbidden`

Probably because it returns with status code 403 instead of 404.

Thanks!

**Comment by jdpedrie** [comment]
If the account you are authenticating with does not have permissions on the bucket, you will see this error.

To test this, I created a bucket and uploaded a file. I granted Owner permissions on the file to a different service account than the one with bucket permissions, then called `exists()` on that object. I got the expected `true` result. Then I called `exists()` on a non-existent object and received a 403 exception.

If you are unsure whether your service account has reader permission at the bucket level, you should catch the `ServiceException`.
