### ISSUE TITLE
Filtering locations does not work for MyBusiness API

### ISSUE THREAD

**Issue by nekromoff** [googleapis/google-api-php-client#1792]
E.g. trying to filter out locations using:
```
// @TODO filter does not work:
$filter = ['filter' => 'locationName:' . urlencode($location_name) . '*'];
```
I have also tried without URL encoding, but this does not work either. All locations are returned.

See: https://developers.google.com/my-business/content/location-data#filter_results_when_listing_locations

**Comment by BillNyeTheRussianSpies** [comment]
Confused as to why this is in my Account....

**Comment by jdpedrie** [comment]
To confirm, your API looks something like this?

```php
$locations = $mybusiness->accounts_locations->listAccountsLocations($parent, [
	'filter' => ['filter' => 'locationName:' . urlencode($location_name) . '*']
]);
```

If so, then it appears correct. I checked that the field is available, and it is. If you are unable to get it working, I believe it is not an issue in the client library. I suggest trying some of the [support resources](https://developers.google.com/my-business/content/support) available for the My Business API. They will be more equipped to assist further.
