### ISSUE TITLE
Class 'Google\Auth\OAuth2' not found

### ISSUE THREAD

**Issue by cschroederhidalgo** [googleapis/google-api-php-client#1793]
please . I can't find the class 'Google \ Auth \ OAuth2'. Does anyone know where to download the class Google \ Auth \ OAuth2.php ???

When I try to test the google drive API ( https://developers.google.com/drive/api/v3/quickstart/php ), I get the error:
PHP Warning:  include_once(Google\Auth\OAuth2.php): failed to open stream: No such file or directory in /public_html/manager/library/Zend/Loader.php on line 83

Warning: include_once(Google\Auth\OAuth2.php): failed to open stream: No such file or directory in /public_html/manager/library/Zend/Loader.php on line 83
PHP Warning:  include_once(): Failed opening 'Google\Auth\OAuth2.php' for inclusion (include_path='/public_html/manager/library:/public_html/manager/application/models:.:/usr/share/pear:/usr/share/php') in /public_html/manager/library/Zend/Loader.php on line 83

Warning: include_once(): Failed opening 'Google\Auth\OAuth2.php' for inclusion (include_path='/public_html/manager/library:/public_html/manager/application/models:.:/usr/share/pear:/usr/share/php') in /public_html/manager/library/Zend/Loader.php on line 83
PHP Fatal error:  Class 'Google\Auth\OAuth2' not found in /public_html/manager/library/Google/Client.php on line 988

Fatal error: Class 'Google\Auth\OAuth2' not found in /public_html/manager/library/Google/Client.php on line 988

I searched the internet for the class Google/Auth/OAuth2.php . But I can't find it

**Comment by jdpedrie** [comment]
`Google\Auth\OAuth2` is part of [`google/auth`](https://github.com/googleapis/google-auth-library-php).

You can install it via `composer require google/auth`. If you've installed this library, it will be automatically installed.

You should not directly include any of the library files. Instead you should include the composer autoloader. Please refer to the [Installation Guide](https://github.com/googleapis/google-api-php-client#installation) for this library for more information. If you are not using Composer, you can download a release and include the files directly in your project.

**Comment by jdpedrie** [comment]
Please re-open if you have further questions.
