### ISSUE TITLE
Usage of Cloud Function v1beta2

### ISSUE THREAD

**Issue by rac-andreharry** [googleapis/google-api-php-client#1794]
Hi, not sure if this is should be categorised as a bug. I'm working on the project that reads Google Drive folders and files. Recently I have been notified that my application is using v1beta2 Cloud Functions which will be shut down on 15th April. 

I've been investigation what could cause this warning as I don't have any Cloud Functions created for this project. I've noticed that below packages still reference to the version of Cloud Functions that will be soon shut down such as google/apiclient-services. My version of this package is v0.127 which is latest version available.

#### Found in:
Google_Service_Autoscaler
Google_Service_Taskqueue
Google_Service_Manager
Google_Service_Resourceviews

#### Services that I'm using in my application:
Google_Client
- To initialise the Google Client API using key file and adding related scopes.

Google_Service_Drive
- To find files within Google Drive.

Google_Service_Drive_FileList 
- Files collection response.

Google_Service_Drive_DriveFile
- To get details about a file by file ID.

#### Environment details
- GCP App Engine
- Runtime: php72
- Package info: "google/apiclient": "^2.4"

Is this something that will be updated soon? Or is there any other way I can work on my end to avoid calling deprecated version of Cloud Functions?

Thank you!

**Comment by bshaffer** [comment]
Hi there! 
By notified do you mean via email? If so, it could have nothing to do with your PHP app and could be that you enabled the Cloud Functions API via cloud console or gcloud. 

If this is the case, I would recommend going to the Cloud Functions part of Cloud Console and see if you have anything running there.

**Comment by rac-andreharry** [comment]
Hi Brent!

Thanks for the reply.

You're correct it was an email notification and the Cloud Functions API is enabled, however, we don't create any Cloud Functions at all. 

But when I go to Cloud Console > APIs & Services > Cloud Functions API > Metrics we can see the following methods have been invoked

google.cloud.functions.v1.CloudFunctionsService.GenerateUploadUrl 
google.cloud.functions.v1.CloudFunctionsService.ListFunctions 
google.cloud.functions.v1beta2.CloudFunctionsService.ListFunctions 
google.cloud.location.Locations.ListLocations

Since we don't use Cloud Function directly, we thought it could be this library calling them behind the scene for Auth or Gdrive functionality?

**Comment by bshaffer** [comment]
There's no "behind the scenes" calls made from our client libraries to those APIs, so it must be something else. They could have been invoked from someone running a `gcloud` command, or from the Cloud Console UI. 

I'd suggest checking the Audit Log to see if that shines any light on where the calls are coming from. And once you're confident nothing relies on Cloud Functions you can disable the API.

**Comment by bshaffer** [comment]
Also, for clarification, when an API (such as Autoscaler) is marked as `v1beta2`, this is independent of the Cloud Functions API, which is having version `v1beta2` shut down. So the "references" you mentioned are not referencing GCF. I hope this makes sense.

**Comment by rac-andreharry** [comment]
Hi Brent!

Many thanks for explaining all of this. It makes sense! On further test, we noticed that some of those Cloud Function APIs were invoked when no one's visiting the site. So yeah, it must be something else.

Thanks again for the swift responses!

Cheers!

**Comment by bshaffer** [comment]
No problem @rac-andreharry ! Glad to help!
