### ISSUE TITLE
How to create folders recursively?

### ISSUE THREAD

**Issue by xiebruce** [googleapis/google-api-php-client#1800]
For example, I'm going to upload a file `scenery.jpg` to `/images/2020/03/18/` directory, if I upload to OneDrive, the upload url going to be like this:
```
https://graph.microsoft.com/v1.0/me/drive/root:/images/2020/03/18/scenery.jpg
```
I don't have to know if the `images` folder, the `2020`, `03` and `18` folder exists or not, OneDrive will auto create it recursively, acting like Object-based Storage.

---

But now, I'm going to upload it to GoogleDrive and GoogleDrive seems can't create folders recursively(as far as I know, see [Create and populate folders](https://developers.google.com/drive/api/v3/folder)), now I have 2 questions:

1、Is that I have to check if these folders exists one by one to make sure if I have to create these folders?  
`/images/`  
`/images/2020/`  
`/images/2020/03/`
`/images/2020/03/18/`  
2、If none of above folder exists, is that I have to create these four folders one by one(means request api four times)?

Anyone who did this before? I hope what I assume is wrong, because it's too complicated to do it in this way.

**Comment by jdpedrie** [comment]
It appears that yes, you'll need to recurse in order to create the nested folder. I found an [example](https://github.com/Toan/php-gdrive-stream-wrapper/blob/master/GoogleDriveStreamWrapper.php#L323-L362) of recursive directory creation for Google Drive in a PHP stream wrapper implementation. Hopefully this will give you some idea of what is involved.

**Comment by xiebruce** [comment]
@jdpedrie OK, I got it, thank you for your [example](https://github.com/Toan/php-gdrive-stream-wrapper/blob/master/GoogleDriveStreamWrapper.php#L323-L362).
