### ISSUE TITLE
Example request: Indexing API

### ISSUE THREAD

**Issue by elantonov** [googleapis/google-api-php-client#1801]
Hi! 

I wanna use Indexing API to update a URL (https://developers.google.com/search/apis/indexing-api/v3/using-api)

> Send a HTTP POST request to https://indexing.googleapis.com/v3/urlNotifications:publish
> {
>   "url": "content_location",
>   "type": "URL_UPDATED"
> }

But I haven't found names of classes. Can you give me an example?

**Comment by jdpedrie** [comment]
You should be able to use `Google_Service_Indexing`.

Something like the following should work. I haven't tested it, so you may need to adjust slightly.

```php
$client = new Google_Client();
$client->setScopes(Google_Service_Indexing::INDEXING);

$service = new Google_Service_Indexing($client);
$service->urlNotifications->publish(new Google_Service_Indexing_UrlNotification([
	'url' => $pageUrl,
	'type' => 'URL_UPDATED'
]));
```

**Comment by elantonov** [comment]
Thanks, it works, but with error in response: 

> Permission denied. Failed to verify the URL ownership. 

But if I try to use Service Webmasters API with same URL and with same aunthefication parameters, there are no errors. This example work without any errors.

```
$client = new Google_Client();
$client->addScope( 'https://www.googleapis.com/auth/webmasters' );
$serviceWebmasters = new Google_Service_Webmasters( $client );
$postBody = new Google_Service_Webmasters_SearchAnalyticsQueryRequest( [
	'startDate'  => '2020-01-01',
	'endDate'    => '2020-01-30',
	'dimensions' => [
		'query'
	],
	'rowLimit' => 500,
	'startRow' => 0
] );
$response = $serviceWebmasters->searchanalytics->query( $pageUrl , $postBody );
var_dump($response);
```

**Comment by jdpedrie** [comment]
Try [this](https://support.google.com/webmasters/thread/4763732?hl=en&msgid=6359270) solution.

**Comment by elantonov** [comment]
Thank you. Problem has solved.
