### ISSUE TITLE
Create / update contact Birthday google People

### ISSUE THREAD

**Issue by juancer** [googleapis/google-api-php-client#1804]
I'm trying to update the birthday field of my contacts but i got error. 
I can not set the date to the person resource.
Anyone can help me?

Thanks

```
$person = new Google_Service_PeopleService_Person();
$birthday = new Google_Service_PeopleService_Birthday();
$birthday->setText('1987/07/26');
$person->setDate($birthday);
```

**Comment by jdpedrie** [comment]
What is the error?

**Comment by juancer** [comment]
Hi @jdpedrie,
This is the error:

```
An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined method Google_Service_PeopleService_Person::setDate()
```

**Comment by jdpedrie** [comment]
Use `Google_Service_PeopleService_Person::setBirthdays()`. Note that despite the docblock, the correct argument to this method is `Google_Service_PeopleService_Birthday[]` (an array of objects).

**Comment by juancer** [comment]
It works, thank you very much.
Regards,
