### ISSUE TITLE
Latest downloadable package (v2.4.0) is outdated

### ISSUE THREAD

**Issue by kungufli** [googleapis/google-api-php-client#1805]
The latest downloadable zip package [v2.4.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.4.0) is outdated. It misses some new functionalities from the latest version of the [Google PHP API Client Services](https://github.com/googleapis/google-api-php-client-services). 

For example it doesn't support freeze periods for the Android Management's [SystemUpdate](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/AndroidManagement/SystemUpdate.php) class.

The issue can be easily bypassed by installing the library with composer, however it would be nice to also have updated downloadable packages, since they are provided as an alternative to composer in the documentation.

**Comment by jdpedrie** [comment]
Hi @kungufli, I'll work on getting a new release out this week.

**Comment by kungufli** [comment]
@jdpedrie Many thanks!

**Comment by jdpedrie** [comment]
https://github.com/googleapis/google-api-php-client/releases/tag/v2.4.1
