### ISSUE TITLE
Temporarily Close Location

### ISSUE THREAD

**Issue by socialRanvir** [googleapis/google-api-php-client#1807]
Google just released the ability to temporarily close a location from the GMB dashboard. Will the API be updated to support this or there an existing way for doing this?

I looked through the API response of a temporarily closed location and the API returns it as permanently closed.

**Comment by jdpedrie** [comment]
It does not appear that temporarily closed is yet an option in the API. [See here](https://developers.google.com/my-business/reference/rest/v4/accounts.locations#Location.OpenForBusiness) for more detail on available options.

You may want to keep an eye on the [change log](https://developers.google.com/my-business/content/change-log) for new information!

**Comment by socialRanvir** [comment]
Thanks @jdpedrie for your quick response
