### ISSUE TITLE
Drive file getName() method not defined?

### ISSUE THREAD

**Issue by FrankEBailey** [googleapis/google-api-php-client#1812]
I am reading in Google Drive links to images from a Google sheet. The links contain the file IDs and the images are shared to anyone with the link. I am able to retrieve and download the images without a problem.

However I would like to name the images with the same filename that they have in the Google Drive folder, but using the getName() method doesn't return the file's name and throws the error

    Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Psr7\Response::getName()

My code is as follows:

    $service = new Google_Service_Drive($client);
    $file = $service->files->get( $fileID, array("alt" => "media") );
    echo $file->getName();

I seem to be missing something to be able to get the filename.

**Comment by inside83** [comment]
It would be really nice if you explained how did you solve it before closing the issue 😃 
It would be a great help to me as I'm facing the same problem.

**Comment by FrankEBailey** [comment]
I pulled the name out in a slightly different way:

```
$result = $service->files->get($fileID, ['fields' => 'name,md5Checksum,size']);
$fn = $result->name;
```
