### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_sign()

### ISSUE THREAD

**Issue by achuet** [googleapis/google-api-php-client#1814]
I try to post form data to sheet. I got this error
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_sign() in C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\firebase\php-jwt\src\JWT.php:209
Stack trace:
#0 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\firebase\php-jwt\src\JWT.php(180): Firebase\JWT\JWT::sign()
#1 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\OAuth2.php(1321): Firebase\JWT\JWT::encode()
#2 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\OAuth2.php(428): Google\Auth\OAuth2->jwtEncode()
#3 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\OAuth2.php(461): Google\Auth\OAuth2->toJwt()
#4 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\OAuth2.php(502): Google\Auth\OAuth2->generateCredentialsRequest()
#5 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\Credentials\ServiceAccountCredentials.php(135): Google\Auth\OAuth2->fetchAuthToken()
#6 C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\google\auth\src\FetchAuthTokenCach in C:\inetpub\wwwroot\google-api-php-client-2.4.1\vendor\firebase\php-jwt\src\JWT.php on line 209

**Comment by Shail28** [comment]
Did you figure it out?
I'm having the same problem.
