### ISSUE TITLE
Update sites for Custom Search with api ?

### ISSUE THREAD

**Issue by foremtehan** [googleapis/google-api-php-client#1817]
Is it possible to update the sites for Custom Search via api ? I mean this section : 

![Capture](https://user-images.githubusercontent.com/53290883/79353818-d2dc8500-7f50-11ea-87b6-7c4d0cf29c86.PNG)

Every time i have to go to console and update the site manually.

**Comment by jdpedrie** [comment]
Hi @foremtehan,

This forum can only really assist with specific questions about the client library. We're not well equipped to answer product questions. I suggest you refer to the [custom search](https://developers.google.com/custom-search) homepage (the API reference would be a great place to start). If you can't find an answer, the link I provided includes a couple of support resources which would be better positioned to assist.

Good luck!
