### ISSUE TITLE
Direct upload to youtube

### ISSUE THREAD

**Issue by neosin** [googleapis/google-api-php-client#182]
Hi I can't find any example of "Direct upload" to youtube in the examples.

According to the google documentation here
developers.google.com/youtube/2.0/developers_guide_php#Direct_Upload

In that link, there is a method to "direct upload" but in the example they use zend instead of this php client code.

Is it possible to add an example of direct upload to youtube?
We want to direct upload from our server to youtube.

thanks!

**Comment by NeoCsatornaja** [comment]
Can I get solution for this problem?
http://stackoverflow.com/questions/36958669/upload-video-to-youtube-with-one-single-button-using-javascript

**Comment by bshaffer** [comment]
@NeoCsatornaja This repository is for PHP, so it is not relevant to your SO question.
