### ISSUE TITLE
Try to create auto post php scripts with the Blogger V3 API 

### ISSUE THREAD

**Issue by hfrance** [googleapis/google-api-php-client#1820]
hello everybody,

At this moment my problem is for generate the authtoken...

I have allready the php scripts to post on my blogger account.

Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.

I have tried to generate the accesstoken with the quickstart php scripts but is look to old ....

do you have a php scripts for generate the access token if I have allready the credentials.json file ?

Thank you

**Comment by hfrance** [comment]
I have found this website for generate my  access token online https://developers.google.com/oauthplayground/ but I refresh any 24 hours

**Comment by hfrance** [comment]
Lol after 2 hours i found the solution.

generate the Authentcation code from authorization link by curl

https://accounts.google.com/o/oauth2/auth?client_id=[Application Client Id]&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=[Scopes]&response_type=code

after 
Exchanging Authentication code
curl \
–request POST \
–data “code=[Authentcation code from authorization link]&client_id=[Application Client Id]&client_secret=[Application Client Secret]&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=authorization_code” \
https://accounts.google.com/o/oauth2/token

**Comment by hfrance** [comment]
Use Refresh Token
If your access token expires you can use the following command to refresh it using the Refresh token.

curl \
–request POST \
–data ‘client_id=[Application Client Id]&client_secret=[Application Client Secret]&refresh_token=[Refresh token granted by second step]&grant_type=refresh_token’ \
https://accounts.google.com/o/oauth2/token

**Comment by appimatic** [comment]
you had asked about PHP code that instantiated with the JSON key.

I have example code that uses that method to purge Google Drive files greater than 30 days old.

Let me know if any interest, I can provide that PHP code example offline.

**Comment by hfrance** [comment]
I found the option to generate access token directly with simple curl command.

thank you everything is ok now.

**Comment by mlb4428675** [comment]
Hi hfrance,

Could you give me a PHP demo to get the access token and refresh it?

Thanks a lot.

**Comment by DavidBui1979** [comment]
Hi hfrance,

Please give me a PHP demo to get the access token and refresh it!

Thanks a lot.

**Comment by darkufo** [comment]
Hi hfrance, I would be very interested in the code as well.  You can email me at darkufo@spoilertv.com
