### ISSUE TITLE
Gettting php syntax error im monolog/logger.php

### ISSUE THREAD

**Issue by theprakashchandra** [googleapis/google-api-php-client#1826]
I got this error while using the google client API for login
Type: ParseError
Message: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)
Filename: ..............................vendor/google/google-api/vendor/monolog/monolog/src/Monolog/Logger.php
Line Number: 33

how to deal with this issue?

**Comment by jdpedrie** [comment]
Monolog 2 requires PHP 7.2 or above. It appears you are using the downloadable package. I recommend installing the API client via composer (`composer require google/apiclient`), but if this is not possible, upgrade your server to at least PHP 7.2 or use the `PHP54` release archive available from the [releases](https://github.com/googleapis/google-api-php-client/releases) page.

**Comment by theprakashchandra** [comment]
thankyou! @jdpedrie  I just upgraded the PHP version to latest v7.4 and it worked.

**Comment by vikasprogrammer** [comment]
I found another trick to solve this. If you are not going to use `monolog` or ok with monolog `1.17`. Then use this composer.json file. 

```
{
    "require": {
        "google/apiclient": "^2.2",
        "monolog/monolog": "^1.17"
    }
}
```
