### ISSUE TITLE
Date missing milliseconds if they are exactly 0 which causes server error

### ISSUE THREAD

**Issue by steffenweber** [googleapis/google-api-php-client#1827]
#### Environment details

  - OS: Gentoo Linux
  - PHP version: 7.4.5
  - Package name and version: google-api-php-client v2.4.1

#### Steps to reproduce

Two days ago I got the following error from an API call that usually works totally flawlessly:

```
"error": {
   "errors": [
     {
      "domain": "global",
      "reason": "invalid",
      "message": "Invalid value for: Invalid format: \"2020-05-02T09:13:32Z\" is malformed at \"Z\""
     }
   ],
   "code": 400,
   "message": "Invalid value for: Invalid format: \"2020-05-02T09:13:32Z\" is malformed at \"Z\""
  }
}

Stack trace:
#0 /vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse()
#1 /vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute()
#2 /vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
#3 /vendor/google/apiclient/src/Google/Client.php(842): Google_Http_REST::execute()
#4 /vendor/google/apiclient/src/Google/Service/Resource.php(232): Google_Client->execute()
#5 /vendor/google/apiclient-services/src/Google/Service/YouTube/Resource/Videos.php(313): Google_Service_Resource->call()
#6 Video.php(545): Google_Service_YouTube_Resource_Videos->update()
…
```

The error seems to indicate that the microseconds are missing.

My code itself does not format any dates when using the YouTube API. Could it be that google-api-php-client omits the milliseconds when formatting ISO 8601 dates if they are exactly 0? This is very unlikely to happen but seems to have happend here.

I've been trying to find out where google-api-php-client formats dates but have been unable to find such places.

**Comment by jdpedrie** [comment]
The API client does not transform dates. It accepts them in any format and leaves it up to the user and the upstream API to control for errors. If you've only seen the error once, it's possible there was just a transient error in the API.

If you continue to see the error, share the code that triggers it and we'll take a look.

**Comment by steffenweber** [comment]
I've dug a little deeper. The issue happens more or less reliably since about one week when you try to update a video immediately after it has been uploaded. To update a video, you have to have to first fetch it (using `listVideos`). If you do this immediately after uploading, the YouTube API sometimes returns a `publishedAt` date without milliseconds (i.e. `2020-05-07T08:48:22Z` instead of `2020-05-07T08:48:22.000Z`). Such a `publishedAt` value is then refused by the YouTube API when updating the video.

So this is not an issue in google-api-php-client but a YouTube API server issue. I'm not sure where to report that. A possible client-side workaround is:

```php
if (preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/', $snippet->publishedAt))
{
	$snippet->publishedAt = str_replace('Z', '.000Z', $snippet->publishedAt);
}```

**Comment by jdpedrie** [comment]
Nice find! That does seem like a problem they should know about. You can report it in the public [issue tracker](https://issuetracker.google.com/issues/new?component=186600&template=874803).

Since we seem to have discovered that this isn't a bug in the client library, I'm going to close it out.

I haven't tested this, but you could probably also do something like this:

```php
if (!DateTime::createFromFormat(DateTime::RFC3339, $snippet->publishedAt)) {
	$snippet->publishedAt = str_replace('Z', '.000Z', $snippet->publishedAt);
}
```
