### ISSUE TITLE
Authentication on google drive using Guzzle HTTP POST request

### ISSUE THREAD

**Issue by panfil3** [googleapis/google-api-php-client#1831]
I am writing a script, and in it I need authentication on Google drive, I try to do it with the help of Guzzle, I send a POST http request to `https://accounts.google.com/o/oauth2/auth`. The documentation says that the `$_GET['code']` should come in response, but how will I get it if I send a POST request?

**Comment by jdpedrie** [comment]
Have you reviewed the [PHP Quickstart](https://developers.google.com/drive/api/v3/quickstart/php) for Google Drive? It has a complete authentication example.

**Comment by panfil3** [comment]
> Have you reviewed the [PHP Quickstart](https://developers.google.com/drive/api/v3/quickstart/php) for Google Drive? It has a complete authentication example.

Yes, but what should I do with this code if my script runs without a browser?
` // Request authorization from the user.`
`$authUrl = $client->createAuthUrl();`
`printf("Open the following link in your browser:\n%s\n", $authUrl);`
`print 'Enter verification code: ';`
`$authCode = trim(fgets(STDIN));`

Also from my debugger I get an error
"Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)"

**Comment by jdpedrie** [comment]
Authenticating without user interaction requires a service account. [Here's](https://stackoverflow.com/a/41218081/324307) a sample of what that looks like.

**Comment by panfil3** [comment]
Yes, I tried this method, but I want to go into my Google Drive account to create files. The disadvantage of this method is that during the script the file is not created from my account, and I need to provide access

**Comment by jdpedrie** [comment]
Unfortunately, for security purposes, authenticating as a real user requires the OAuth flow. As suggested [here](https://stackoverflow.com/a/49664501/324307), you could share a directory on your person drive with the service account and allow the upload to be placed in your personal drive.
