### ISSUE TITLE
function revokeToken() on null in /path/www/XXXXXXXXXXX

### ISSUE THREAD

**Issue by eborguezao** [googleapis/google-api-php-client#1832]
Hello, after calling the function to revoke the Oauth session, an error is displayed:

"Fatal error: Uncaught Error: Call to a member function revokeToken () on null in '/ path / www / my_path / xxxxxxxxxxx' ...."

I have called the function like this:
$google_client->revokeToken ();

For having created it like this:
$google_client->setAccessToken($token['access_token']);

Thank you!

**Comment by jdpedrie** [comment]
This error indicates that `$google_client` does not contain an instance of `Google_Client` like you expect that it does. Often that can be an issue of [variable scope](https://www.php.net/manual/en/language.variables.scope.php), where the variable is used in a context where it does not exist. Also check that you haven't accidentally unset the variable or perhaps even forgot to define it.

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
