### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extendedProps' of undefined at Calendar.select

### ISSUE THREAD

**Issue by than2557** [googleapis/google-api-php-client#1837]
I try to use info.event.extendedProps.time_period to get   variable on time_period on select:function(info).

this my code
`select:function(info){

var check = info.startStr;
var tp =info.event.extendedProps.time_period;

var today = new Date();
var dd = String(today.getDate()).padStart(2, '0');
var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
var yyyy = today.getFullYear();
today = yyyy + '-' + mm + '-' + dd;
// alert('select'+check);
if(check < today)
    {
        Swal.fire({
          title: 'ไม่สามารถเพิ่มการประชุมได้',
              icon: 'warning',
              confirmButtonColor: '#3085d6',
            })
    }
    else
    {
      // Its a right date
      var Eventform = $("#basicModal").modal(); 
 }
 }`

**Comment by jdpedrie** [comment]
This forum is for questions regarding the Google PHP API Client. It doesn't appear your question pertains either to Google APIs nor PHP. :)

You may be able to get assistance at [Stackoverflow](https://stackoverflow.com/). Best of luck!
