### ISSUE TITLE
Uninstall this package

### ISSUE THREAD

**Issue by pra9shinde** [googleapis/google-api-php-client#1838]
Hi, 
I want to remove this package and its dependencies via the composer because I am using these API using Vanilla Javascript.

or list of folders to be deleted?

**Comment by jdpedrie** [comment]
You can run `composer remove google/apiclient` to remove a package from your composer.json file and uninstall the package.

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
