### ISSUE TITLE
PHP 7.3 is not supported

### ISSUE THREAD

**Issue by johnish** [googleapis/google-api-php-client#1840]
Hi - I ran the composer command and it showed this error

composer require google/apiclient:"^2.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php 5.6.*|7.0.*|7.1.*|7.2.* but your PHP version (7.3.18) does not satisfy that requirement.

Installation failed, reverting ./composer.json to its original content.

**Comment by jdpedrie** [comment]
I don't believe this is related to `google/apiclient`. We require php >= 5.4. The error you shared doesn't show 5.4 or 5.5. Additionally, I do most of my day to day work on 7.3 and have not had any trouble installing the library! When you run `composer require`, composer merges all your dependency requirements, so you can get an error from anywhere, not just the new package. Take a look at what you're requiring and see if there's anything else which could be causing the problem.

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
