### ISSUE TITLE
Send message to Google Chat room as a real user

### ISSUE THREAD

**Issue by madonzy** [googleapis/google-api-php-client#1842]
Is it possible to send message into the google chat room as a real user (not like a bot)? If yes, can you please give me an example?

**Comment by jdpedrie** [comment]
My investigation suggests that you cannot send messages from non-bots. The scope required to create a message is `https://www.googleapis.com/auth/chat.bot`, which gives us a clue, and cannot be used via OAuth.

You may try asking via one of the [recommended support channels](https://developers.google.com/hangouts/chat/support), as this repository is intended for API client questions and we are not experts on every API.
