### ISSUE TITLE
Curl PHP

### ISSUE THREAD

**Issue by JavierVassallo** [googleapis/google-api-php-client#1843]
Hello, with the following code I call the API v4 to print the values ​​of a spreadsheet. It is going very well.
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL,"https://sheets.googleapis.com/v4/spreadsheets/
spreadsheetID/values/PHP?valueRenderOption=UNFORMATTED_VALUE&key=yourKeyId");
$result = curl_exec ($curl);
curl_close ($curl);

What I can't achieve is to do an insert or update on it, I can't manage to put the PHP curl together for this. Some help? Please try as below but it doesn't work.

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL,"https://sheets.googleapis.com/v4/spreadsheets/
spreadsheetID/append/PHP?InsertDataOption=INSERT_ROWS&key=yourKeyId");
$jvalues=array(array("5869","35685987","Ema","2020-05-29","no brinda","3563430423"));

$jsonData = array(
    'values' => $jvalues
);

$jsonDataEncoded = json_encode($jsonData);

curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
$result = curl_exec ($curl);
curl_close ($curl);

![image](https://user-images.githubusercontent.com/54564164/83081523-4b0d8e80-a057-11ea-9487-dc391fbad995.png)

Some help, I found no examples anywhere.
Thanks.

**Comment by jdpedrie** [comment]
Hi @JavierVassallo,

This forum is for issues related to the Google API Client library. We can't really help debug issues unrelated to that. You could try [Stackoverflow](https://stackoverflow.com/tagged/php) or [Reddit](https://www.reddit.com/r/PHPhelp/) though.
