### ISSUE TITLE
How to get Google Account Data without Google Plus

### ISSUE THREAD

**Issue by AJULCAB** [googleapis/google-api-php-client#1844]
> 
> 
> What is the alternative to?
> 
> ```
> $plus = new Google_Service_Plus($client);
> $me = $plus->people->get('me');
> ```

@nacesprin, here is alternative that I use to get user profile data:
```
$account = new Google_Service_Oauth2($client);
$me = $account->userinfo->get();
```

_Originally posted by @BlazL in https://github.com/googleapis/google-api-php-client/issues/1570#issuecomment-476006672_

**Comment by jdpedrie** [comment]
Thanks for highlighting this @AJULCAB. I modified the title to help others find it in the future. Since I don't think there's any action to be taken, I'll close this. It'll of course remain visible for others.
