### ISSUE TITLE
SSL operation failed with code 1

### ISSUE THREAD

**Issue by auahmed** [googleapis/google-api-php-client#1845]
#### Environment details

  - OS: Windows 10 Pro
  - PHP version: PHP 7.3.17
  - Package name and version: google-api-php-client-2.4.1

#### Steps to reproduce
1. Create a service account on GCP and get credentials json
2. Enable Analytics API on GCP for service account
3. add service account to google analytics users
4. execute code below with `php accessToken.php`
5. Will get a access token created successfully as expected but will always get the following warning message to:
```
PHP Warning:  fread(): SSL operation failed with code 1. OpenSSL Error messages:
error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading in C:\.......\google-api-php-client-2.4.1\vendor\guzzlehttp\psr7\src\Stream.php on line 225
```
Is this because i am running this locally? need to confirm this before i make changes onto my service and push it forward.

#### Code example

```php
# accessToken.php
<?php
// Load the Google API PHP Client Library.
require_once __DIR__ . '/../google-api-php-client-2.4.1/vendor/autoload.php';

// Create and configure a new client object.
$client = new Google_Client();
$client->setAuthConfig(__DIR__ . '/../client_credentials.json');
$client->setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
$client->refreshTokenWithAssertion();
$token = $client->getAccessToken();
echo $token['access_token'];
?>
```

**Comment by jdpedrie** [comment]
According to [this bug report](https://bugs.php.net/bug.php?id=79589), you should be able to resolve this by upgrading to PHP 7.3.18.

**Comment by auahmed** [comment]
thank you, that resolved it
