### ISSUE TITLE
Support with PHP 5.6.40

### ISSUE THREAD

**Issue by auahmed** [googleapis/google-api-php-client#1846]
#### Environment details

  - OS: Windows 10 Pro
  - PHP version: PHP 5.6.40
  - Package name and version: google-api-php-client-2.4.1

#### Steps to reproduce
1. Create a service account on GCP and get credentials json
2. Enable Analytics API on GCP for service account
3. add service account to google analytics users
4. execute code below with `php accessToken.php`
5. will get the following error:
```

Warning: Unsupported declare 'strict_types' in C:\........\google-api-php-client-2.4.1\vendor\monolog\monolog\src\Monolog\Logger.php on line 1

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in C:\........\google-api-php-client-2.4.1\vendor\monolog\monolog\src\Monolog\Logger.php on line 33
```

just wanted to confirm if it was actually completely supported by 5.6.X version of PHP.
I was just downloading the release and it seems to include monolog version 2.x which is supported with PHP7.2 or higher only. would i just need to replace the folder under vendor with the 1.x version of monolog to make it compatible or any other changes required? or if i download the zip manually and then go into the folder for the client, will i be able to just run `composer install`?

#### Code example

```php
# accessToken.php
<?php
// Load the Google API PHP Client Library.
require_once __DIR__ . '/../google-api-php-client-2.4.1/vendor/autoload.php';

// Create and configure a new client object.
$client = new Google_Client();
$client->setAuthConfig(__DIR__ . '/../client_credentials.json');
$client->setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
$client->refreshTokenWithAssertion();
$token = $client->getAccessToken();
echo $token['access_token'];
?>
```

**Comment by mbaumgartl** [comment]
I think the Monolog dependency is wrong: https://github.com/googleapis/google-api-php-client/blob/master/composer.json#L13

No idea what Composer is doing in that case.

**Comment by jdpedrie** [comment]
Hi @auahmed sorry for the delay,

Yes, you should be able to run `composer update` from the unzipped release package.

We'll look into ways to address this issue going forward.

**Comment by flyinRyan00** [comment]
For anyone else in this situation the newest release compatible with PHP5.5 is 2.2.4

**Comment by jdpedrie** [comment]
The next version release will include downloadable archives compatible with PHP 5.4, 5.6, 7.0 and 7.4.
