### ISSUE TITLE
Error 500 on setAuthConfig()

### ISSUE THREAD

**Issue by idzczakp** [googleapis/google-api-php-client#1849]
Hey.
So I'm trying to set up a Google APIs to get data from google sheets, but after this line, I'm getting error 500 if I comment it - App is not working but I didn't get any error.

I worked on it with [this tutorial](https://youtu.be/iTZyuszEkxI) - besides I didn't use the composer.

**Troubleshooting:**

- the file location is fine
- I checked the permissions
- require('./modules/Google/googleApisCredentials.json'); shows me contents of this file

I have no clue what do I did wrong.

```
require('./modules/Google/autoload.php');

$client = new Google_Client();
$client->setApplicationName('importtest');
$client->setScopes([Google_Service_Sheets::SPREADSHEETS]);
$client->setAccessType('online');
$client->setAuthConfig('./modules/Google/googleApisCredentials.json'); //here appears err500

$service = new Google_Service_Sheets($client);
$spreadsheetID = '1HrRpjYL2v4o****************E7xoEps';

$range = 'Requests!J2:AF';
$response = $service->spreadsheets_values->get($spreadsheetID, $range);

$values = $response->getValues();
if(empty($values)){
    print ("no data found");
} else {
    foreach($values as $row){
        echo sprintf($row);
    }
    
}
```

**Comment by jdpedrie** [comment]
If you're in a development environment, make sure to turn on [error reporting](https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display). That should give you more information.

1. You should use the composer autoloader included in the downloadable package. `/path/to/library/vendor/autoload.php`.
2. Use an absolute path to your credentials file. When you provide a relative path as a string, it will be relative to the directory where the file is loaded. In other words, you are expecting it to look in the current directory plus `modules/Google`, but instead it's looking in whichever path the `Google_Client` class exists in plus `modules/Google`.

Try this: `__DIR__ . '/modules/Google/googleApisCredentials.json`.

If you have trouble getting error reporting working and the other tips don't help, you can catch any exceptions from that call and print the error message:

```php
try {
    $client->setAuthConfig('...');
} catch (Exception $e) {
    echo $e->getMessage();
    exit;
}
```

**Comment by idzczakp** [comment]
Thanks for your reply @jdpedrie.
So try/catch showed me Invalid client secret JSON file.

The file is downloaded from google APIs dashboard.

**Comment by jdpedrie** [comment]
The error text is "Invalid client secret JSON file."? I'm not sure where that comes from.

**Comment by idzczakp** [comment]
It's an output of

```
try {
    $client->setAuthConfig('./modules/Google/googleApisCredentials.json');
} catch (Exception $e) {
    echo $e->getMessage();
    exit;
}
```

I checked the path of this file with _scandir()_ and it should work. 

Maybe my credentials googleApisCredentials.json is misconfigured. Can I check it somehow?

**Comment by jdpedrie** [comment]
I don't understand where you're getting the paths to those files. You shouldn't be directly requiring the API. If you're not using composer, go to the [releases](https://github.com/googleapis/google-api-php-client/releases) page and download one of the .zip files from assets (the latest version doesn't include them at the moment, I'll get that fixed).

Once you've downloaded and unzipped that file, remove all requires and includes and simply include the bundled autoloader: `require /path/to/client/vendor/autoload.php`. Do not move or modify library files as you will encounter errors and unexpected behavior which I cannot debug.

Once all of that is done, try it again, *using absolute paths to your credentials file* and let me know what happens.

**Comment by oleg972** [comment]
deploy windows

чт, 11 июн. 2020 г. в 17:11, Przemyslaw Idzczak <notifications@github.com>:

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
