### ISSUE TITLE
Set Additional cURL Options

### ISSUE THREAD

**Issue by murzid** [googleapis/google-api-php-client#1850]
How to set additional cURL options using Google APIs Client Library?

```php
curl_setopt_array($curl, array(
  CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
);
```

on our server, without IPv4 resolves API requests become very slow.

Thanks

**Comment by jdpedrie** [comment]
```php
use GuzzleHttp\Client;

$client = new Google_Client();

$guzzle = new Client([
    'curl.options' => [
        CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
    ]
]);

$client->setHttpClient($guzzle);
```

You may also set other [request options](http://docs.guzzlephp.org/en/stable/request-options.html) via this method as well.

**Comment by murzid** [comment]
Thank you for the help 😄

**Comment by ezekiel747** [comment]
> ```
> use GuzzleHttp\Client;
> 
> $client = new Google_Client();
> 
> $guzzle = new Client([
>     'curl.options' => [
>         CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
>     ]
> ]);
> 
> $client->setHttpClient($guzzle);
> ```
> 
> You may also set other [request options](http://docs.guzzlephp.org/en/stable/request-options.html) via this method as well. Guzzle provides [`force_ip_resolve`](http://docs.guzzlephp.org/en/stable/request-options.html#force-ip-resolve), which may meet your needs.

Thanks a lot!
I had an issue with the actual page running very slow (took a long time, around 40 seconds, to validate the login w Google sign-in).
Using this code you provided, the loading time reduced to normal, acceptable interval (~1 second).

If someone encounters issues like: "Use of undefined constant CURLOPT_IPRESOLVE"
You need to install php-curl and restart your webserver.
For example, on debian with apache2:
```
apt-get update
apt-get install php-curl
systemctl restart apache2

```
Should be fixed now.
