### ISSUE TITLE
How to Get Long Lived Access Token?

### ISSUE THREAD

**Issue by UVLabs** [googleapis/google-api-php-client#1853]
Creating an app which would allow users to make posts to their Google My Business listings, I've successfully ran some tests using: https://github.com/googleapis/google-api-php-client/blob/master/examples/idtoken.php

But I am seeing that the access token expires in 1 hour? 

![image](https://user-images.githubusercontent.com/10324144/85075668-af21ff00-b18c-11ea-8f39-4b36937a6227.png)

How do I get an access token that would have a longer life span? 

LinkedIn doesn't create long-lived access tokens like Facebook, but LinkedIn tokens expire every 90 days, that's not a big bother on users since it's just basically reauthenticating their account with an app once every 3 months, but I can't imagine having to reauthenticate every hour being practical.

 How would I go about getting an access token with a longer life span?

**Comment by jdpedrie** [comment]
What you're looking for is a [refresh token](https://developers.google.com/identity/protocols/oauth2/web-server#offline). Once you have a refresh token, you can use [`Google_Client::fetchAccessTokenWithRefreshToken()`](https://github.com/googleapis/google-api-php-client/blob/9ab9cc07f66e2c7274ea2753f102ae24d1271410/src/Google/Client.php#L287) to get a new access token as needed.

**Comment by UVLabs** [comment]
@jdpedrie Thank you for the response. I just added `$client->setAccessType("offline");` and I see i get a refresh token and can use it to get a new access token using the fetchAccessTokenWithRefreshToken() method.

Questions: 

- Does this refresh token expire? 
- So is it fine to simply always call this method whenever I'm about to do a call to the API? Basically(PHP):

```
$refresh_token = '...';
$access_token =  $client->fetchAccessTokenWithRefreshToken($refresh_token)['access_token'];
// Use this access_token (which would always be unique) for API call
```

**Comment by jdpedrie** [comment]
They don’t have a scheduled expiration, but you should [write your app with the expectation that refresh tokens will periodically become invalidated](https://developers.google.com/identity/protocols/oauth2#expiration).

Rather than using the refresh token all the time, it would be much better to cache the token along with its expiration and only issue a refresh once the previous access token is expired.

**Comment by UVLabs** [comment]
@jdpedrie Another thing..I think i'm misunderstanding google's implementation here...

Think of the product I am working on as a piece of software that lets users create posts on their Google My Business listings.

The users authenticate on my website, through a my Google console project which has been approved to use the Google My Business API.

So: 

- User has piece of software on their own computer(or other independent environments that I don't have control of.)
- On software dashboard, user clicks "Authenticate"
- Software sends user to my website here: https://example.com/gmb_auth 
- On that path I have the GMB library redirecting the user to the google auth endpoint
- Once the user has authenticated, google will send the user back to  https://example.com/gmb_auth because I have that URL set as the authorized **redirect uri**
- Once  https://example.com/gmb_auth receives the response from google's auth, it will send the user's access token, refresh token etc. back to the software dashboard and the process is complete.

This is all fine...and would work just fine, except, the access token isn't long-lived, and even though I send back the refresh token to the user...I'd also [need to send back my Client ID and Client Secret](https://github.com/googleapis/google-api-php-client/blob/master/src/Google/Client.php#L299) if I'm to use the **fetchAccessTokenWithRefreshToken()** method

On the distributed software, if I don't set the Client ID and Client Secret, I get the error:

```Array ( [error] => invalid_request [error_description] => Could not determine client ID from request. )```

My question is, how can I refresh access tokens without having to send the Client Secret to the application? (seems like a security flaw)

Or how else can I go about this so the user can create posts on their GMB locations without authenticating every hour?

**Comment by jdpedrie** [comment]
If I'm understanding correctly, couldn't your application make a call to, say, `example.com/refresh_token` with the client's refresh token? Then `example.com` could make the auth call with your ID and secret, get an access token, and pass it back to the app.

It's difficult to answer in my position since I don't have enough information and I'm wary of giving advice which may not lead in a totally secure direction. I definitely advise seeing more specific help from someone who has a good understanding of OAuth and who is in a position to more fully understand your use case.

**Comment by UVLabs** [comment]
@jdpedrie Thanks again for your response. Your workflow makes much more sense than sending the client secret back to the distributed app.

It just seems like having to do this hourly doesn't seem ideal. Is there no other way with Google to receive longer-lived access tokens for such distributed applications?

If not then I'll have to go with your workflow

**Comment by oleg972** [comment]
do make

сб, 20 июн. 2020 г. в 20:15, Uriahs Victor <notifications@github.com>:

**Comment by jdpedrie** [comment]
@UVLabs To the best of my knowledge, you cannot extend the lifetime of an access token, only renew credentials using the refresh token.

**Comment by UVLabs** [comment]
Thank you @jdpedrie

**Comment by oleg972** [comment]
create folder how active directory as services and as registry

пн, 22 июн. 2020 г. в 19:23, John Pedrie <notifications@github.com>:

**Comment by AdamMiltonBarker** [comment]
> Creating an app which would allow users to make posts to their Google My Business listings, I've successfully ran some tests using: https://github.com/googleapis/google-api-php-client/blob/master/examples/idtoken.php
> 
> But I am seeing that the access token expires in 1 hour?
> 
> ![image](https://user-images.githubusercontent.com/10324144/85075668-af21ff00-b18c-11ea-8f39-4b36937a6227.png)
> 
> How do I get an access token that would have a longer life span?
> 
> LinkedIn doesn't create long-lived access tokens like Facebook, but LinkedIn tokens expire every 90 days, that's not a big bother on users since it's just basically reauthenticating their account with an app once every 3 months, but I can't imagine having to reauthenticate every hour being practical.
> 
> How would I go about getting an access token with a longer life span?

It's not practical, it is an absolute joke navigating Google's apis.
