### ISSUE TITLE
Dose Google My Business API support?

### ISSUE THREAD

**Issue by allgrowsm** [googleapis/google-api-php-client#1854]
Hello there,

I would like to access my google my business account by use of your client library.

However, I can not find one from your source code.

So, I want you to tell me which service I should use if supported.

I was looking at followind directory.

vendor/google/apiclient-services/src/Google/Service

But, I cannot find one that I need.

Best regards,

**Comment by jdpedrie** [comment]
My Business distributes their API clients separately. You can download it [here](https://developers.google.com/my-business/samples).

**Comment by allgrowsm** [comment]
@jdpedrie 
Thanks for your help.
I will look into it :)

**Comment by oleg972** [comment]
upload media

пн, 22 июн. 2020 г. в 08:24, masao soseki <notifications@github.com>:
