### ISSUE TITLE
Monolog error

### ISSUE THREAD

**Issue by anvilzephyr** [googleapis/google-api-php-client#1855]
I found the error. It is a conflict with an older library used by a plugin (Gravity PDF).
I'll alert the plugin author. 
Is there a way for me to prevent this from happening in the future? Maybe namespace monolog with the version number? 
I'm still interested in disabling the logger altogether as the odds of another conflict is greater than any other type of error.
Thank you

Fatal error: Declaration of Monolog\Handler\ProcessableHandlerTrait::pushProcessor(callable $callback): Monolog\Handler\HandlerInterface must be compatible with Monolog\Handler\AbstractHandler::pushProcessor($callback) in /path/lib/google-api-php-client-2.4.0/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php on line 22

Environment
Linux m51.siteground.biz 3.12.18-clouder0 #1 SMP Tue Oct 9 18:14:47 EEST 2018 x86_64
PHP version 7.3 (also tried 7.2 and 7.4)
Package name and version: google-api-php-client-2.4.0

Steps to reproduce:
$token = $client->fetchAccessTokenWithRefreshToken($packet['refresh_token']);

I had no problems with the library when obtaining the original access token response (which included the refresh token).  $client was the same object and builds fine without issue until this point. 
For the record, I also have no issue testing this code on two other servers. 
I've tried uploading Monolog again. 

**How do I disable logging?**
UPDATE:
I can confirm that the issue rears it's head anytime a log is attempted. 
Thank you

**Comment by anvilzephyr** [comment]
Update: Gravity PDF is namespacing Monolog since they want to support PHP 5.6. A lot of plugins want to support 5.6.
I am trying to do something similar. I cannot namespace the entire lib because some dependencies are calling classes inline with \Classname instead of use statements.

**Comment by jdpedrie** [comment]
You could provide a different `Psr\Log\LoggerInterface` implementation (perhaps one that doesn't do anything) to `Google_Client::setLogger`.

For instance, if you're using PHP 7:

```php
$client = new Google_Client;

$client->setLogger(new class implements Psr\Log\LoggerInterface {
    public function emergency($message, array $context = array()) {}
    public function alert($message, array $context = array()) {}
    public function critical($message, array $context = array()) {}
    public function error($message, array $context = array()) {}
    public function warning($message, array $context = array()) {}
    public function notice($message, array $context = array()) {}
    public function info($message, array $context = array()) {}
    public function debug($message, array $context = array()) {}
    public function log($level, $message, array $context = array()) {}
});
```

**Comment by oleg972** [comment]
match p :Private person

вт, 23 июн. 2020 г. в 21:43, Amy Hill <notifications@github.com>:

**Comment by anvilzephyr** [comment]
I will give it a try. Thank you for the example.

Amy

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
