### ISSUE TITLE
Can't find the way to authenticate with server code

### ISSUE THREAD

**Issue by bylbaboy** [googleapis/google-api-php-client#1856]
Hello everyone!

I am trying to save files to Google Cloud on android client (Unity) and read these files on the web server.

I already used id token, but it doesn't provide necessary access.
I'm trying to use [server authentication codes](https://github.com/playgameservices/play-games-plugin-for-unity#retrieving-server-authentication-codes). I successfully get them on the client and send to the server, but then can't exchange the tokens for the access to the account, because the [code in the documentation](https://developers.google.com/identity/sign-in/web/server-side-flow#step_6_send_the_authorization_code_to_the_server) isn't for php based server, so isn't for google API php client 
But I can't find something suitable in this solution. 
Can you prompt me something usable?

Thanks!

**Comment by oleg972** [comment]
may google card,may spend server

вс, 21 июн. 2020 г. в 06:26, bylbaboy <notifications@github.com>:

**Comment by oleg972** [comment]
may be off platform as services
may google cloud as services~infrastructura as services

вс, 21 июн. 2020 г. в 16:24, Aleksey Lozhkin <citadellozhkin@gmail.com>:

**Comment by bylbaboy** [comment]
I don't understand you(
Can you describe your solution in more detail?

**Comment by jdpedrie** [comment]
@bylbaboy have you reviewed the [Authentication with OAuth](https://github.com/googleapis/google-api-php-client#authentication-with-oauth) and [Authentication with Service Accounts](https://github.com/googleapis/google-api-php-client#authentication-with-service-accounts) documentation? You may also find useful information in the [cross-client identity](https://developers.google.com/identity/protocols/oauth2/cross-client-identity) documentation and its linked pages.

**Comment by bylbaboy** [comment]
Thanks @jdpedrie! The [Authentication with OAuth](https://github.com/googleapis/google-api-php-client#authentication-with-oauth) is suitable for me. I overlooked it in some way and started looking in other documentation.
