### ISSUE TITLE
Huge composer dependencies

### ISSUE THREAD

**Issue by UVLabs** [googleapis/google-api-php-client#1858]
I'm using this library to make calls and requests to the Google My Business API. I've already downloaded the standalone API file for Google My Business: https://developers.google.com/my-business/samples

Everything works fine when I use it in tangent with this library installed via composer. The thing I noticed is that this library downloads https://github.com/googleapis/google-api-php-client-services/ which adds like 20MB+ worth of files

Is there any way to make this smaller so I could distribute my integration more easily with a small file size?

**Comment by jdpedrie** [comment]
If you're not using any APIs in `google/apiclient-services`, you can prevent it from being installed by adding the following to your root `composer.json` file:

```json
{
	"replace": {
		"google/apiclient-services": "self.version"
	}
}
```

If you're using the downloadable package, or need some but not all of the included clients, you could simply delete the unnecessary files and directories from `vendor/google/apiclient-services/src`.

**Comment by UVLabs** [comment]
Thank you, that reduced the size significantly. If I understand that library correctly, the apiclient-services it's a list of the APIs Google Provides? If so, then why did I have to download the Google My Business file separately?

**Comment by jdpedrie** [comment]
Yes that is correct. The My Business team distributes their client separately at this time.

**Comment by UVLabs** [comment]
Thanks for all your help so far @jdpedrie !! Last question, the refresh token returned by Google when a user is authenticating, can this be cached and used to retrieve new access tokens for other users when their previous access token is about to expire? Or is the refresh token limited to one user(the user it was returned for)?

**Comment by jdpedrie** [comment]
Refresh tokens are specific to each user. If you use a refresh token from user A to generate an access token for user B, user B will end up authenticated as user A.

**Comment by UVLabs** [comment]
Awesome thanks for the details
