### ISSUE TITLE
There was an error signing in to Youtube Using OAuth2

### ISSUE THREAD

**Issue by malik-umair** [googleapis/google-api-php-client#1859]
I'm getting following issue while submitting video on YouTube using Google Client API PHP.

    "token": "*****_5pNR0HX3nRi", "error_details": "Error refreshing the OAuth2 token, message: '{\n \"error\": \"invalid_grant\",\n \"error_description\": \"Bad Request\"\n}'"

I've tried several solutions but my issue isn't resolved yet. I'm using below code:

    $this->client = new Google_Client();  
    $this->client->setClientId($id);
    $this->client->setClientSecret($secret);
    $this->client->setAccessType("offline");
    $this->client->setApplicationName('Shopper Approved Testimonials');
    if ($redirecturl) {
         $this->client->setRedirectUri($redirecturl);
    }
        
    $this->youTubeService = new Google_YoutubeService($this->client);
    $this->client->refreshToken($this->dbsite->YoutubeEmail); //where $this->dbsite->YoutubeEmail is = $google_token->refresh_token

What is missing in it, if anyone can guide, many thanks!

**Comment by oleg972** [comment]
i am self

пт, 26 июн. 2020 г. в 20:26, malik-umair <notifications@github.com>:

**Comment by jdpedrie** [comment]
Have you set the authentication scopes?

```php
$this->client->setScopes(Google_Service_YouTube::YOUTUBE);
```

**Comment by malik-umair** [comment]
@jdpedrie I added it now but got 500 error that: Class 'Google_Service_YouTube' not found

**Comment by malik-umair** [comment]
@jdpedrie  i tried by adding this:

    $this->client->setScopes('https://www.googleapis.com/auth/youtube');

but still no success.

**Comment by oleg972** [comment]
youtube need css;java;html
scope of css :<css syntax@scope>;<css include@scope>

пн, 29 июн. 2020 г. в 23:50, John Pedrie <notifications@github.com>:

**Comment by bshaffer** [comment]
@malik-umair the class `Google_Service_YouTube` needs to be autoloaded via composer or by downloading a packaged version of this library. Are you including `vendor/autoload.php` in the root of your project?

**Comment by jdpedrie** [comment]
As we don't have enough information to assist in resolving this issue, I'm going to close it. If you're still having trouble, please feel free to reopen, providing the information requested, and we'll be happy to continue assisting!
