### ISSUE TITLE
Support PSR-18

### ISSUE THREAD

**Issue by Nyholm** [googleapis/google-api-php-client#1861]
A few year ago, [I suggested](https://github.com/googleapis/google-api-php-client/issues/719) to move to HTTPlug. HTTPlug is an abstraction over HTTP clients and let the user decide if they want to use Guzzle, Buzz, Symfony HTTP client or any other. 

HTTPlug has since then become PSR-18. PSR-18 is a simple interface to send a PSR-7 request and get back ad PSR-7 response. 

HTTPlug was maybe too young and unreliable 2015. I understand why that idea was not merged then. Implementing PSR-18 in 2020 is definitely the way forward for an open source library. 

I've made a PR to support Guzzle7 (#1860). Guzzle7 supports PSR-18. I know that Guzzle8 will have a lot of breaking changes. It will be difficult to depend on both Guzzle7 and Guzzle8. I suggest to start planning for a future where we depend on PSR-18 (and other PSRs like PSR-17) instead of a concrete implementation. Or I'll fear that we will have a Guzzle5/6 issue like we had a few years ago.

**Comment by bshaffer** [comment]
Hi Nyholm! Thanks for opening this discussion.
The main issue we have with PSR-18 is that it does not support per-request options, as we support in our API methods and as is also supported in Guzzle 5, 6, and 7.

**Comment by bshaffer** [comment]
added in #1868
