### ISSUE TITLE
how use calendar feature

### ISSUE THREAD

**Issue by pws2016** [googleapis/google-api-php-client#1862]
Hello,
have an example to use calendar API ?

**Comment by jdpedrie** [comment]
Please refer to the [PHP quickstart](https://developers.google.com/calendar/quickstart/php) for Google Calendar. If you still have questions, we advise searching or asking on [Stackoverflow](https://stackoverflow.com).

**Comment by oleg972** [comment]
how sky


пн, 29 июн. 2020 г. в 20:12, John Pedrie <notifications@github.com>:
