### ISSUE TITLE
I am getting Google_Service_Exception [ 404 ]:

### ISSUE THREAD

**Issue by allgrowsm** [googleapis/google-api-php-client#1870]
When I call Google My Business API, I got following error.

Google_Service_Exception [ 404 ]:
{ "error": { "code": 404, "message": "Method not found.", "errors": [ { "message": "Method not found.", "domain": "global", "reason": "notFound" } ], "status": "NOT_FOUND" } }

It seems the there is no such a API available.

Here is my source code.

```php
    $client = new \Google_Client();
    $client->setApplicationName($this->name);       // app name
    $client->setApprovalPrompt('force');
    $client->setAccessType('offline');
    $client->setAccessToken($credential);
    $client->addScope("https://www.googleapis.com/auth/business.manage");                                                                                        
    $client->addScope("https://www.googleapis.com/auth/plus.business.manage");
    $gmbService = new \Google_Service_MyBusiness($client);
    $results = $gmbService->accounts->listAccounts();   
```

Thanks!

**Comment by allgrowsm** [comment]
I am using following source code.

https://developers.google.com/my-business/samples

It seems I am accessing wrong domain?

**Comment by jdpedrie** [comment]
How long has it been since you activated your GMB account? It seems as though the initial setup may take some time before the API becomes available to your account.

**Comment by allgrowsm** [comment]
I guess I activated the gmb account more than 1 year ago. I just ask api support team and am waiting for their reply.

**Comment by allgrowsm** [comment]
@jdpedrie My company already has a whitelisted project to access the Google My Business API. At this time, they are only whitelisting one project per business. Therefore, I could not call API.
