### ISSUE TITLE
This package is not auto-updated @packagist

### ISSUE THREAD

**Issue by mynameisbogdan** [googleapis/google-api-php-client#1874]
On https://packagist.org/packages/google/apiclient this client is currently not auto-updated and as a result it's not possible to use the latest modifications from the `master` branch with `dev-master` which ATM includes support for Guzzle 7 but in composer it's still stuck at Guzzle 6.

**Comment by jdpedrie** [comment]
Thanks for the heads up @mynameisbogdan, I've updated it so the latest version is now available. I'm going to keep this open to track as we work on getting that auto-update working properly.

**Comment by jdpedrie** [comment]
This should be resolved going forward! Thanks again. :)
