### ISSUE TITLE
Empty response after upload large file

### ISSUE THREAD

**Issue by neko-fire** [googleapis/google-api-php-client#1878]
#### Environment details

  - PHP version: 7.4.5
  - Package name and version: google/apiclient 2.5.0 & 2.6.0 + Guzzle 6

#### Steps to reproduce
After uploading a large video file (<100MB) to youtube class Google_Http_MediaFileUpload does not provide a response anymore since a couple of days. There is no Exception/Error/Message/Object - I have tried using version 2.5 & 2.6 of the SDK installed via composer. Before it worked fine with 2.5 past couple of weeks.

My code is very similar to the examples. The upload is partially successful but the new item on Youtube remains on status "processing" indefinetly. $result, $status, $response return empty.

#### Code example

```php
protected function uploadPart($requesttype,$file,$mime,$data,$insertDetailsAddons=""){
		$status=FALSE;
		$response="";
		$chunkSizeBytes = 1 * 1024 * 1024 * 10;
		if($this->client){
			$this->client->setDefer(TRUE);
		}
		$request=NULL;

		if($this->service){
			switch($requesttype){
				case 'video':
					$request=$this->service->videos->insert("status,snippet,contentDetails".$insertDetailsAddons,$data);
				break;
				case 'thumb':
					$request=$this->service->thumbnails->set($data);
				break;
				case 'caption':
					$request=$this->service->captions->insert('snippet',$data);
				break;
				case 'captionUpdate':
					$request=$this->service->captions->update('snippet',$data);
				break;
			}
		}

		try{
			if($request){
				$media=new \Google_Http_MediaFileUpload($this->client,$request,$mime,NULL,TRUE,$chunkSizeBytes);
				$media->setFileSize(filesize($file));
				$media->setChunkSize($chunkSizeBytes);

               //  START UPLOADING CHUNKS
				$handle=fopen($file,"rb");
				$i = 0;

				while(!$status&&!feof($handle)){
                    // track chunks
                   // UPLOAD CHUNK".$i++

                    			$chunk=fread($handle,$chunkSizeBytes);
					$status = $media->nextChunk($chunk);
				}
			

                $result = false;
                if($status != false){
                    $result = $status;
                }
// NOTE: It appears all chunks were uploaded but no repsonse is filled afterwards in $status

				fclose($handle);
                 // FINISHED UPLOADING CHUNKS
			}else{
				\engine::debug("NO REQUEST, ABORTING","YOUTUBE",\base\enums\color::COLOR_RED);
			}
		}catch(\Google_Service_Exception $e){
			$response=$e->getMessage();
			\engine::debug("SERVICE EXCEPTION: ".$response,"YOUTUBE",\base\enums\color::COLOR_RED);
		}catch(\Google_Exception $e){
			$response=$e->getMessage();
			\engine::debug("GOOGLE EXCEPTION: ".$response,"YOUTUBE",\base\enums\color::COLOR_RED);
		}finally{
			\engine::debug("RELEASING CLIENT","YOUTUBE");
			if($this->client){
				$this->client->setDefer(FALSE);
			}
		}

		return([$status,$response,$result]);
	}
```

Update:
Setting chunksize to 262144 (as documented) gives me following response. I think the error dropped on last chunk interation.

```
Invalid request. The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144). The received request contained 133514 bytes, which does not meet this requirement.
```

Using a multiple of 262144 (as recomended) like in the example above provides no response at all.

**Comment by neko-fire** [comment]
Still happening with v2.7

**Comment by neko-fire** [comment]
Still happening with v2.7.2
There is also an additional Error occuring sometimes with the same files. After the first chunk is uploaded Google Service Exception throws 404 not found for the next chunk. A few minutes/hours later it works as inteded, but this is happening way too often recently. Might this be connected to this previous issue?

**Comment by neko-fire** [comment]
This issue still persists, any updates on this?

**Comment by neko-fire** [comment]
This issue still persists

**Comment by bshaffer** [comment]
I found a solution here but I do not think it applies to your issue

https://stackoverflow.com/questions/56618142/400-invalid-request-the-number-of-bytes-uploaded-is-required-to-be-equal-or-g

**Comment by saranshdhingra** [comment]
Hi @neko-fire 
Let me start by apologising that it took a long time for us to give attention to this issue.

Is this issue still happening? If we're able to reproduce it now, we will definitely be able to look more into it.

If it's still happening, it would be great if we could see the function calls with the exact values you're passing to the function.

Let's also try to find the minimum code that we need to reproduce the issue, it will help us focus on the parts that the issue might be contained in.

**Comment by saranshdhingra** [comment]
Closing the issue for now.

Please feel free to reopen if this is reproducable.
