### ISSUE TITLE
backendError : 503

### ISSUE THREAD

**Issue by gokulmhegde** [googleapis/google-api-php-client#1879]
I am getting this Error **Occasionally** this is the **4th time** in **last 12 days**

{
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "errors": [
      {
        "message": "The service is currently unavailable.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "UNAVAILABLE"
  }
}

Because of this i have to run the script multiple time

**Comment by LindaLawton** [comment]
For which api for which request?

**Comment by gokulmhegde** [comment]
> For which api for which request?

Google Analytics API.

**Comment by jdpedrie** [comment]
Please see the [documentation](https://developers.google.com/analytics/devguides/reporting/core/v3/errors#handling_500_or_503_responses) regarding handling 500 and 503 responses. In short, if your request is not requesting too much data, you should consider implementing exponential backoff to retry requests in the case of transient errors.

If you like, you could use the backoff implementation from [`google/cloud-core`](https://github.com/googleapis/google-cloud-php/blob/master/Core/src/ExponentialBackoff.php). Here's a sample of how it's used: https://github.com/googleapis/google-cloud-php/blob/master/Core/src/RequestWrapper.php#L186-L207
