### ISSUE TITLE
Calendar API cannot add calendar with Service Account

### ISSUE THREAD

**Issue by ARtheboss** [googleapis/google-api-php-client#1880]
I'm currently trying to use this API to allow users of my website to add an event to a Google Calendar that I myself own, but it does not work. 

This is what my code looks like:
```php
require_once 'google-api/vendor/autoload.php';

$client = new Google_Client();
$client->setApplicationName("House Events");
$client->setAuthConfig("MY AUTH CONFIG FILE");
$client->setScopes(Google_Service_Calendar::CALENDAR);
$client->setAccessType('offline');

$service = new Google_Service_Calendar($client);

$event = new Google_Service_Calendar_Event(array(
  'summary' => $title,
  'description' => $html,
  'start' => array(
    'dateTime' => $start
  ),
  'end' => array(
    'dateTime' => $end
  )
));

$calendarId = 'MY CALENDAR ID';
$event = $service->events->insert($calendarId, $event);

$calendarListEntry = new Google_Service_Calendar_CalendarListEntry();
$calendarListEntry->setId($calendarId);

$createdCalendarListEntry = $service->calendarList->insert($calendarListEntry);

printf('Event created: %s\n', $event->htmlLink);
```

It gives me the error "You need to have writer access to this calendar", but I can't give it read/write access inside the calendar sharing page.

Just to be clear, I want to use a service account and not OAuth because this is a Google Calendar I myself own and I don't want access to user's Google Calendars. How do I fix this?

**Comment by jdpedrie** [comment]
Have you [shared](https://support.google.com/calendar/answer/37082?hl=en&authuser=1) your calendar with the service account email?

**Comment by ARtheboss** [comment]
I shared it but the option to give read/write access is grayed out

**Comment by jdpedrie** [comment]
Is the calendar owned by a GSuite account? It may be that the administrator has limited sharing permissions.

**Comment by ARtheboss** [comment]
Yes it is. Should I try to contact the administrator?

**Comment by jdpedrie** [comment]
Yep. Send them [this](https://support.google.com/a/answer/60765?hl=en) link. It should have the information they will need.
