### ISSUE TITLE
Pagination on Google_Service_Calendar getEvents

### ISSUE THREAD

**Issue by WilliamChang80** [googleapis/google-api-php-client#1898]
I've been using google calendar on my application and i'm implementing pagination on the events from calendar but as written in documentation in https://developers.google.com/calendar/v3/pagination there is only a way to get a page token and next page token, but it seems there is no way to get specific page.

I also found an solution from https://stackoverflow.com/questions/27396516/gmail-calender-pagination-for-asp-net where they iterate through all of the events and get all of the page tokens. But i know its not an optimal solution for this issue, maybe it can be a consideration to get specific page directly from the params in ``Google_Service_Calendar_Resource_Events`` specifically in this function

 ```
public function listEvents($calendarId, $optParams = array())
  {
    $params = array('calendarId' => $calendarId);
    $params = array_merge($params, $optParams);
    return $this->call('list', array($params), "Google_Service_Calendar_Events");
  }
```

**Comment by jdpedrie** [comment]
It's not an issue in this library -- the API itself does not support offset pagination. We can't ask the API for page 12, because that's not a concept the API understands. If you cannot iterate over the pages, you should look at other means of limiting the results returned.
