### ISSUE TITLE
GMAIL API EMAIL BODY

### ISSUE THREAD

**Issue by ashishkmishra95** [googleapis/google-api-php-client#1899]
Hey can anyone explain me how to.unwrap word text ![Screenshot_20200803-233708.png](https://user-images.githubusercontent.com/64477627/89213447-ba1cdb80-d5e2-11ea-8fe6-aa4e278017c9.png) this image main send someone email perfectly but when user receives the email [Uploading Screenshot_20200803-233718.png …]() format changes to this one using PHP API please solve this issue 

Thanks & Regards
Ashish

**Comment by jdpedrie** [comment]
I don't understand what the issue is. Please share a code sample and more detail of what you intend to happen.

**Comment by ashishkmishra95** [comment]
> I don't understand what the issue is. Please share a code sample and more detail of what you intend to happen.

I want my message in this form![Screenshot_20200804-160048.png](https://user-images.githubusercontent.com/64477627/89291177-b0918300-d677-11ea-8bd0-d098aa850d92.png) 

But when i send my message through Gmail api I get this![Screenshot_20200804-114548.png](https://user-images.githubusercontent.com/64477627/89291213-c2732600-d677-11ea-9658-a674d8bfa578.png)

**Comment by jdpedrie** [comment]
Please share a sample of the code you're using to call the API.
