### ISSUE TITLE
Preload Supported?

### ISSUE THREAD

**Issue by xvzf** [googleapis/google-api-php-client#1911]
Does the library support preloading in PHP7.4?

**Comment by jdpedrie** [comment]
We do not offer a single file you can include, but there should be nothing preventing you from preloading the library yourself. Note that `google/apiclient-services` contains a very large number of files, so you may want to take care to exclude files which are not needed, or consider using the [cleanup hook](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services) to remove files which are not needed by your application.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
