### ISSUE TITLE
Guzzle version is updated to 7.0.1 (6.5.5 being used)

### ISSUE THREAD

**Issue by wparslan** [googleapis/google-api-php-client#1912]
#### Environment details

  - OS: Windows 10 64-Bit
  - PHP version: 7.4
  - Package name and version: Guzzle and Google API PHP 2.7

The Guzzle API has been updated to 7.0.1
When composer require google/apiclient:"^2.7" is run 
it gets the older version of Guzzle 6.5.5 while the current version of Guzzle is being used is 7.0.1 (https://github.com/guzzle/guzzle)

Please update the Guzzle queries and methods accordingly! 

Thanks!

**Comment by dwsupplee** [comment]
@wparslan executing  a fresh `composer require google/apiclient:^2.7` installs Guzzle 7.0.1 for me, are you using a lock file or have other dependencies that might cause composer to resolve an older version of guzzle?
