### ISSUE TITLE
Undefined class constant VERSION error on AWS

### ISSUE THREAD

**Issue by malwarebo** [googleapis/google-api-php-client#1915]
The API client is throwing a fatal error on AWS when invoked. 
```
PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in /var/app/current/web/app/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Client.php:
```

**Comment by malwarebo** [comment]
`PHP Fatal error:  Uncaught Error: Undefined class constant 'MAJOR_VERSION' in /var/app/current/vendor/guzzlehttp/guzzle/src/Utils.php:121\nStack trace:\n#0 /var/app/current/vendor/guzzlehttp/guzzle/src/functions.php(61): GuzzleHttp\\Utils::defaultUserAgent()\n#1 /var/app/current/web/app/plugins/cf7-google-sheets-connector/lib/vendor/guzzlehttp/guzzle/src/Client.php`

**Comment by nikmartin** [comment]
This is an issue with wp-mail-smtp, not the google api. The plugin you're using is using an outdated version of the Google API.

**Comment by jdpedrie** [comment]
As @nikmartin said, you'll need to take this up with the plugin maintainer. :)

**Comment by malwarebo** [comment]
Thanks!
