### ISSUE TITLE
Google_Service_Compute_AttachedDisk getInitializeParams() returns empty values

### ISSUE THREAD

**Issue by rameshvenk** [googleapis/google-api-php-client#1920]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: OSX Catalina 10.15.6
  - PHP version: PHP 7.4.9
  - Package name and version: "google/apiclient": "^2.7"

#### Steps to reproduce

Identify a GCP project with running VMs
Ensure you have a GCP service account with the correct access
Example function below (scoped specific to issue)

#### Code example

```php
function list_instances(Google_Service_Compute $compute, string $project, string $zone) {
    $optParams = [];
    $instances = $compute->instances->listInstances($project, $zone, $optParams);
    foreach ($instances->items as $instance) {
        printf("%-50s %10s\n", $instance->name, $instance->status);
        $disks = $instance->disks;
        foreach ($disks as $disk) {
## THIS SHOULD RETURN A Google_Service_Compute_AttachedDiskInitializeParams
            print_r($disk->getInitializeParams()); 
## IT DOES NOT RETURN ANYTHNG
            printf("\tName = %-35s DiskSizeGb = %5s\n",
                $disk->deviceName,
                $disk->diskSizeGb
            );
        }
    }
}


```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by rameshvenk** [comment]
I noticed a bit later that there is another project called `https://github.com/googleapis/google-api-php-client-services`, so my apologies if I filed this issue in the wrong place. Please let me know the correct location to file this issue. Thank you

**Comment by rameshvenk** [comment]
Additional, possibly related information : I tried this with the Java API client, and the result is the same. The `com.google.api.services.compute.model.AttachedDisk`'s `getInitializeParams()` method also returns `null`.

**Comment by jdpedrie** [comment]
According to the [Compute API reference](https://cloud.google.com/compute/docs/reference/rest/v1/instances/list), `items[].disks[].initializeParams` is input-only:

> [Input Only] Specifies the parameters for a new disk that will be created alongside the new instance. Use initialization parameters to create boot disks or local SSDs attached to the new instance.

This means that it will not be populated when fetching an existing resource.

**Comment by rameshvenk** [comment]
That's good to know, but now, it seems like finding out the source image that a disk is using isn't possible? That causes some issues. Is there an alternative way to obtain the same information (i.e what source image is being used by a VM)?

**Comment by jdpedrie** [comment]
Unfortunately I do not have any special knowledge of the Compute API. I suggest checking the reference linked above, or you could review the available [support resources](https://cloud.google.com/compute/docs/getting-support).

Does `items[].disks[].source` contain what you're looking for?

**Comment by rameshvenk** [comment]
Unfortunately no. That returns the source to the disk (like this) `https://www.googleapis.com/compute/v1/projects/<gcp-project-name>/zones/us-central1-c/disks/ads-adsvm-dev-vm-mysql-1` 
I can try to open a case with Support as you suggested.

**Comment by rameshvenk** [comment]
Thanks for putting me in the right direction @jdpedrie . Once you mentioned that the method wouldn't return anything, I was able to use the [disks.get,](https://cloud.google.com/compute/docs/reference/rest/v1/disks/get) pass in the project id, zone and disk name and get the source image that way. A bit more work, but all is good in the end. This issue can be closed.
