### ISSUE TITLE
We use a paid g-Suite account. Google writes that you can use it to allow apps to access source documents. How is this supposed to work if the token changes constantly?

### ISSUE THREAD

**Issue by nhamphap2002** [googleapis/google-api-php-client#1923]
I use api library to connect to g-Suite and these are notify errors. I have downloaded file is successful. but when token is expired
https://prnt.sc/u8vgn0
Notice: Undefined index: expires_in in D:\www\php\api-g-drive\src\Google\Client.php on line 520

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `401 Unauthorized` response: { "error": "unauthorized_client", "error_description": "Unauthorized" } in D:\www\php\api-g-drive\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:111 Stack trace: #0 D:\www\php\api-g-drive\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 D:\www\php\api-g-drive\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 D:\www\php\api-g-drive\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 D:\www\php\api-g-drive\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 D:\www\php\api-g-drive\vendor\guzzlehttp\promises\src\Promi in D:\www\php\api-g-drive\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 111

Thanks for the help

**Comment by jdpedrie** [comment]
You could use a service account to authenticate, as described [here](https://github.com/googleapis/google-api-php-client#authentication-with-service-accounts). Alternatively, you can store the refresh token returned with your auth token and use that to gain a new access token when the old one expires.

**Comment by nhamphap2002** [comment]
Thanks John Pedrie,
I have followed the documentation but I still cannot get the file information from my g-Suite account.
https://prnt.sc/u9btmi
https://prnt.sc/u9bu1a
include_once __DIR__ . '/vendor/autoload.php';

putenv('GOOGLE_APPLICATION_CREDENTIALS=evident-scion-287809-2a846660163d.json');
//$credentials_file = 'evident-scion-287809-2a846660163d.json';
$client = new Google_Client();
//$client->setAuthConfig($credentials_file);
$client->useApplicationDefaultCredentials();
$client->addScope(Google_Service_Drive::DRIVE);
$service = new Google_Service_Drive($client);

$files = $service->files->listFiles();
echo '<pre>';
print_r($files);
exit;

**Comment by jdpedrie** [comment]
When using service accounts, you'll need to either share the file with the service account or, in the case of G-Suite, you can configure [domain-wide delegation](https://developers.google.com/admin-sdk/directory/v1/guides/delegation).

**Comment by nhamphap2002** [comment]
I have enabled it. but I still can not get files.
https://prnt.sc/uaxvyt
