### ISSUE TITLE
Symphony is considered a virus attack on WordPress

### ISSUE THREAD

**Issue by wparslan** [googleapis/google-api-php-client#1934]
Google sign in method uses
![image](https://user-images.githubusercontent.com/66727492/92987267-5c7d8800-f4da-11ea-9d45-14758a5dd021.png)
which is causing security issues on checking and blocks many sites.

It uses ASCII values in which one can easily enter any piece of code and execute it somewhere.

Please Solve this ASAP.

**Comment by jdpedrie** [comment]
Symfony is a very widely used set and well tested set of PHP libraries. Could you provide additional detail as to the suspected issue?

**Comment by bshaffer** [comment]
Yes, I am not clear on the issue. Try logging an issue in the [symfony/polyfill](https://github.com/symfony/polyfill) repo regarding this error for `symfony/polyfill-intl-normalizer`. I expect this is a false positive, as the [Normalizer class](https://github.com/symfony/polyfill/blob/master/src/Intl/Normalizer/Normalizer.php) detects ASCII, but as there's no user input, I do not see a vector for attack.

**Comment by bshaffer** [comment]
Closing because there is nothing actionable for our library here
