### ISSUE TITLE
503: The service is currently unavailable

### ISSUE THREAD

**Issue by carpusmedia** [googleapis/google-api-php-client#1945]
Hello,

Since early this morning I have been getting the following error on all requests:

```
{
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "errors": [
      {
        "message": "The service is currently unavailable.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "UNAVAILABLE"
  }
}
```

I'm using the `Google_Service_Sheets` class

I've ran the code on multiple servers, with PHP 5.6 and PHP 7.3 all returning the same error.

Is this a problem with this API implementation or is it something on Google's end?

Many thanks for the help.

**Comment by jdpedrie** [comment]
Hi @carpusmedia, are you still experiencing problems?

**Comment by carpusmedia** [comment]
This is now working again for some reason, must have an an issue on the other end. 

Thanks for checking with me.
