### ISSUE TITLE
google-api-php-client/Google_Client.php Not Found

### ISSUE THREAD

**Issue by hk1155** [googleapis/google-api-php-client#1948]
Warning: require_once(google-api-php-client/Google_Client.php): failed to open stream: No such file or directory in C:\xampp\htdocs\New_demo\config.php on line 24

Fatal error: require_once(): Failed opening required 'google-api-php-client/Google_Client.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\New_demo\config.php on line 24

How to download google-api-php-client library

**Comment by jdpedrie** [comment]
Have you followed the [Installation instructions](https://github.com/googleapis/google-api-php-client#installation)? There is a section there for installing via composer and via direct download.

**Comment by hk1155** [comment]
yes i followed the installation instruction but i could not found google-api-php-client library.
please tell me the composer command for installing this library

**Comment by jdpedrie** [comment]
```sh
composer require google/apiclient
```

**Comment by hk1155** [comment]
> ```shell
> composer require google/apiclient
> ```

Okay Thanks
