### ISSUE TITLE
Good Analytics Http Batch process error.

### ISSUE THREAD

**Issue by arula1583** [googleapis/google-api-php-client#1949]
Hi
Past couple of years , I have been using version 1.0.5 (https://github.com/googleapis/google-api-php-client/releases/tag/1.0.5-beta)

Recently I had issues in http batch process  error ( https://imgur.com/a/yeNKDt4 ) " The request did not match the specified API. "

As per the https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html  URL, I have changed below endpoints . but noting didnt solved my issues

https://www.googleapis.com/batch/compute/v1
https://content.googleapis.com/batch/compute/v1
https://clients6.google.com/batch/compute/v1
https://compute.googleapis.com/batch
https://content-compute.googleapis.com/batch
https://compute.clients6.google.com/batch

**Comment by jdpedrie** [comment]
The version of the library you are using is extremely old. Have you tried upgrading to the latest release?

**Comment by arula1583** [comment]
I tried .but it leads to rewrite my whole application from scratch again. I am trying to solve with this 1.0.5 version only

**Comment by LindaLawton** [comment]
Google analytics reporting api has its own type of batching and will not support the batching method within this library.  

If you are still having an issue i think you should post your code.

**Comment by dwsupplee** [comment]
@arula1583 it will be hard for us to support such an old release. If you have some code to share please do and and we can see how we can help within reason, I will be closing this out now though.

**Comment by LindaLawton** [comment]
Note for future:  If you are using the new Google analytics GA4 account as opposed to universal analytics.  Then you should be using [Google analytics data API](https://developers.google.com/analytics/devguides/reporting/data/v1/client-libraries#php)  There is a client library built specifically for that.  This library will not work with Analytics Data api.
