### ISSUE TITLE
Pass string to setAuthConfig instead of a file (path)

### ISSUE THREAD

**Issue by tonyellow** [googleapis/google-api-php-client#1952]
I have a situation where I can not pass a file to setAuthConfig. Curently this is required as setAuthConfig is doing a file_exist on the input. I am working in a docker environment and it would really be a nice feature if I could pass the authentication key as a (base64) encoded string. This way we can load the key through an environment variable without the need of saving the key in a file on the server.

**Comment by tonyellow** [comment]
this can be closed as you can also pass an array to setAuthConfig.  My bad...

**Comment by chadgit** [comment]
In php how can i format the json object to an array that will be accepted.  I have the same issue, I do not wish to write a file, rather I have it in string variable.    Ive tried a few things, and could use a pointer on what the Array must be like using php.     using a json credentials file from disk, all connects fine, but when converting to using the variable value version converted to var_dumps .. json_decode... i am getting file not found, or attribute does not match.

**Comment by feras29** [comment]
json_decode('json string', true)
