### ISSUE TITLE
Error when try to remove youtube watermarks 

### ISSUE THREAD

**Issue by jmmedel** [googleapis/google-api-php-client#1955]
#### Environment details

  - OS: Windows 10
  - PHP version: PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
  - Package name and version: "google/apiclient": "^2.7"

#### Code example

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';
$client = new Google_Client();
$client->setScopes([
    'https://www.googleapis.com/auth/youtube.force-ssl',
]);

$credentialsFile = './client_secret.json';
$client->setAuthConfig($credentialsFile);
$client->setAccessType('offline');

// Request authorization from the user.
$authUrl = $client->createAuthUrl();
printf("Open this link in your browser:\n%s\n", $authUrl);
print('Enter verification code: ');
$authCode = trim(fgets(STDIN));

// Exchange authorization code for an access token.
$accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
$client->setAccessToken($accessToken);

// Define service object for making API requests.
$service = new Google_Service_YouTube($client);
try{
$service->watermarks->unset('UCiBfuUreTbKvBKtQbb6SIWQ');
}catch(Exception $e){
	echo ($e->getMessage());
}


```

Error 
Fatal error: Uncaught Error: Call to undefined method Google_Service_YouTube_Resource_Watermarks::unset() in C:\laragon\www\How-to-remove-Youtube-watermarks-using-php-\main.php:26
Stack trace:
#0 {main}
  thrown in C:\laragon\www\How-to-remove-Youtube-watermarks-using-php-\main.php on line 26

Thanks!

**Comment by jdpedrie** [comment]
The method name is [`unsetWatermarks()`](https://github.com/googleapis/google-api-php-client-services/blob/62310a1d0b7701ed874bbcaf3687b0c05d6917fb/src/Google/Service/YouTube/Resource/Watermarks.php#L70).

**Comment by jmmedel** [comment]
Thanks its work .  but can you put it back to unset the youtube api tell that use unset not unsetWatermarks().
 fell free close this thanks you .

**Comment by jdpedrie** [comment]
Unset is a reserved word in PHP versions prior to PHP 7.0. It cannot be used as a method name.
