### ISSUE TITLE
Error when try to set watermarks 

### ISSUE THREAD

**Issue by jmmedel** [googleapis/google-api-php-client#1958]
#### Environment details

  - OS: Windows 10
  - PHP version: PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
  - Package name and version: "google/apiclient": "^2.7"

#### Code example

```php
<?php


require_once __DIR__ . '/vendor/autoload.php';

$client = new Google_Client();
$client->setApplicationName('API code samples');
$client->setScopes([
    'https://www.googleapis.com/auth/youtube.force-ssl',
]);


$client->setAuthConfig('./client_secret.json');
$client->setAccessType('offline');

// Request authorization from the user.
$authUrl = $client->createAuthUrl();
printf("Open this link in your browser:\n%s\n", $authUrl);
print('Enter verification code: ');
$authCode = trim(fgets(STDIN));

// Exchange authorization code for an access token.
$accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
$client->setAccessToken($accessToken);

// Define service object for making API requests.
$service = new Google_Service_YouTube($client);

// Define the $invideoBranding object, which will be uploaded as the request body.
$invideoBranding = new Google_Service_YouTube_InvideoBranding();

// Add 'position' object to the $invideoBranding object.
$invideoPosition = new Google_Service_YouTube_InvideoPosition();
$invideoPosition->setCornerPosition('bottomRight');
$invideoPosition->setType('corner');
$invideoBranding->setPosition($invideoPosition);

// Add 'timing' object to the $invideoBranding object.
$invideoTiming = new Google_Service_YouTube_InvideoTiming();
$invideoTiming->setOffsetMs(60);
$invideoTiming->setType('offsetFromStart');
$invideoBranding->setTiming($invideoTiming);
try{
$service->watermarks->set('UCiBfuUreTbKvBKtQbb6SIWQ', $invideoBranding);
}catch(Expception $e){
	echo $e->getMessage();
}
```

ERROR:
```php

Fatal error: Uncaught Google_Service_Exception: {
  "error": {
    "code": 400,
    "message": "The request does not include the image content.",
    "errors": [
      {
        "message": "The request does not include the image content.",
        "domain": "youtube.watermark",
        "reason": "mediaBodyRequired",
        "location": "body",
        "locationType": "other"
      }
    ]
  }
}
 in C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php:123
Stack trace:
#0 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php(98): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), NULL)
#1 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), NULL)
#2 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google in C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php on line 123
```

Thanks!

**Comment by jdpedrie** [comment]
As the error message states, you must provide an image to set as the watermark.

```php
$invideoBranding = new Google_Service_YouTube_InvideoBranding();
$invideoBranding->setImageBytes(file_get_contents('/path/to/image.jpg'));
// or...
$invideoBranding->setImageUrl('http://example.com/myimage.jpg');
```

Future usage issues should be directed to a more proper forum. This repository is for problems related to the client library itself, not for general usage assistance for specific APIs. Please refer to the [YouTube API support page](https://developers.google.com/youtube/v3/support) for a list of resources.

**Comment by jmmedel** [comment]
Adding  the  setimagebytes solve the other problem but 
i get another error No filter selected. Expected one of: resource
i read the documentation there is no filter selected something like thats . 

``
$invideoBranding->setImageBytes(file_get_contents('/path/to/image.jpg'));
``


Error : 

Fatal error: Uncaught Google_Service_Exception: {
  "error": {
    "code": 400,
    "message": "No filter selected. Expected one of: resource",
    "errors": [
      {
        "message": "No filter selected. Expected one of: resource",
        "domain": "youtube.parameter",
        "reason": "missingRequiredParameter",
        "location": "parameters.",
        "locationType": "other"
      }
    ]
  }
}

 in C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php:123
Stack trace:
#0 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php(98): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), NULL)
#1 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), NULL)
#2 C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\ven in C:\laragon\www\How-to-Add-watermarks-in-youtube-using-php\vendor\google\apiclient\src\Google\Http\REST.php on line 123
