### ISSUE TITLE
simple-query.php example returns 'HTTP Error: Unable to connect: '0''

### ISSUE THREAD

**Issue by rowanrh** [googleapis/google-api-php-client#196]
Hi -

I am newish to PHP and very new to the Google API's, so my apologies in advance if I am making an idiot of myself.

As mentioned, I am new to the Google API's, so after downloading the source I decided to start with the simple-query example. 

I created a Simple API key - with no restrictions on the URI's - inserted it in the code, ran the code and promptly received the above error message, i.e. "HTTP Error: Unable to connect: '0'".

After some playing I was able to identify the problem line as being line #117 in the module IO\Abstract, i.e.: 

"list($responseData, $responseHeaders, $respHttpCode) = $this->executeRequest($request);"

A var_dump of $request returned the following:
    class Google_Http_Request#21 (14) {
  private $batchHeaders =>
  array(3) {
    'Content-Type' =>
    string(16) "application/http"
    'Content-Transfer-Encoding' =>
    string(6) "binary"
    'MIME-Version' =>
    string(3) "1.0"
  }
  protected $queryParams =>
  array(3) {
    'q' =>
    string(19) "Henry David Thoreau"
    'filter' =>
    string(11) "free-ebooks"
    'key' =>
    string(39) "****_yCo0**_****************_Jvima**_**"
  }
  protected $requestMethod =>
  string(3) "GET"
  protected $requestHeaders =>
  array(0) {
  }
  protected $baseComponent =>
  string(26) "https://www.googleapis.com"
  protected $path =>
  string(17) "/books/v1/volumes"
  protected $postBody =>
  NULL
  protected $userAgent =>
  string(56) "Client_Library_Examples google-api-php-client/1.0.5-beta"
  protected $canGzip =>
  NULL
  protected $responseHttpCode =>
  NULL
  protected $responseHeaders =>
  NULL
  protected $responseBody =>
  NULL
  protected $expectedClass =>
  string(28) "Google_Service_Books_Volumes"
  public $accessKey =>
  NULL
}

A try-catch block around the offending line returned the following:
I/O Abstract call error: HTTP Error: Unable to connect: '0'
#0 C:\srv\GoogleApi\Google\IO\Abstract.php(120): Google_IO_Stream->executeRequest(Object(Google_Http_Request))
#1 C:\srv\GoogleApi\Google\Http\REST.php(42): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 C:\srv\GoogleApi\Google\Client.php(499): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#3 C:\srv\GoogleApi\Google\Service\Resource.php(195): Google_Client->execute(Object(Google_Http_Request))
#4 C:\srv\GoogleApi\Google\Service\Books.php(2304): Google_Service_Resource->call('list', Array, 'Google_Service_...')
#5 C:\srv\GoogleApi\simple-query.php(68): Google_Service_Books_Volumes_Resource->listVolumes('Henry David Tho...', Array)
#6 {main}

NB: The line number shown above is 120, i.e. original line number #117 plus three lines for the var_dump and the try-catch.

Technical stuff: Windows 7 Ultimate / PHP 5.5.11 / Apache 2.4

Tested using PhpStorm version 7 / IE version 11 / Firefox version 29

Any assistance greatly appreciated ...

**Comment by alexylem** [comment]
I had the same error with nginx/php-fpm which got fixed by [installing & enabling curl php extension](https://stackoverflow.com/questions/23233460/how-do-i-enable-curl-for-php).
