### ISSUE TITLE
Install no google api client libraries

### ISSUE THREAD

**Issue by 4nik3t** [googleapis/google-api-php-client#1961]
I am installing the library using the composer as shown in the documentation. It's working as expected but the problem is that I don't need any of the API-client-services libraries. I am only using the HTTP  client for making requests and thus the overall size of the installation is increased. 

I saw the  use of the extra key in the composer JSON file 
```
"extra": {
        "google/apiclient-services": [
            "Drive",
            "YouTube"
        ]
 }
```

But I don't want to use any of these API-client-services at all. If I do `" google/apiclient-services": [ ]` it doesn't work it instead installs all the packages

**Comment by jdpedrie** [comment]
If I understand correctly, you're using the API Client to authenticate a Guzzle client? If that is the case, you should just install [`google/auth`](https://github.com/googleapis/google-auth-library-php). The [README](https://github.com/googleapis/google-auth-library-php#call-the-apis) has a guide to authenticating an HTTP client that can be used to call the APIs.

**Comment by 4nik3t** [comment]
@jdpedrie This looks good thanks

**Comment by frankforte** [comment]
This also seems to work (empty string):
```
    "scripts": {
        "post-update-cmd": "Google\\Task\\Composer::cleanup"
    },
    "extra": {
        "google/apiclient-services": [
            ""
        ]
    },
```
