### ISSUE TITLE
simplet download on php

### ISSUE THREAD

**Issue by amidevous** [googleapis/google-api-php-client#1962]
please post easy code for simple download google drive file link using php

your project is far too complicated to understand it's gibberish for beginners so please go to the most

like downloading a file to send it back to users in php

and why you don't give direct links directly

example

https://drive.google.com/file/d/fileid/directdownloadnotconfirmrequiredplease

for direct integrate on apps

**Comment by dwsupplee** [comment]
Here are a few resources I hope you find helpful:

https://github.com/googleapis/google-api-php-client/blob/master/examples/large-file-download.php
https://stackoverflow.com/questions/57449923/how-to-write-a-google-drive-download-file-to-a-directory-using-php
