### ISSUE TITLE
“Different Billing Address?” checkbox instead of “Ship to a different address” woocommerce checkout? 

### ISSUE THREAD

**Issue by pratibhaprajapati** [googleapis/google-api-php-client#1963]
I need to show the delivery address first and then billing address. 

There should be checkbox same like "Ship to a different address?" checkbox which say "**Different Billing Address?**". Complete billing section should be optional and enable only if "Different Billing Address?" checkbox is checked, all validations should work if billing section  is enabled.

I have researched a lot on web for this, but didn't find any working solution.

Please guide me.  
Thanks in advance.

**Comment by jdpedrie** [comment]
This repository is for questions related to the Google API Client library. We can't help with specific problems related to other products. Have you tried the support and documentation resources on the [Woocommerce website](https://woocommerce.com/)?

**Comment by pratibhaprajapati** [comment]
Sorry for posting wrong content.
