### ISSUE TITLE
How do I group multiple dimensions together?

### ISSUE THREAD

**Issue by NeoTechni** [googleapis/google-api-php-client#1965]
Lets say I want latitude and longitude.
When I make an array of Google_Service_AnalyticsReporting_Dimension, I get these dimensions as separate lists. Meaning I don't get a list of latitude,longitude=visitors, I get a list of latitudes, and another list of longitudes, and all their values are zero. Which is doubly useless... I've tried a comma delimited list of them together, but I get an "unknown dimension(s)" error (Unknown dimension(s): ga:continent,ga:subContinent,ga:country,ga:region,ga:city,ga:latitude,ga:longitude)

**Comment by jdpedrie** [comment]
These issues are intended for help with usage and problems with the client library. As we are not experts on all the APIs supported, it's difficult for us to answer usage questions specific to an API. I suggest you review the available support resources [here](https://developers.google.com/analytics/devguides/reporting/core/v4/help).

Best of luck!

**Comment by NeoTechni** [comment]
Unfortunately I've read that already. And it suggests using JSON

**Comment by jdpedrie** [comment]
Did you try Stackoverflow?

**Comment by NeoTechni** [comment]
I figured it out. Google's example code is garbage! I actually had the results I wanted, but Google's example printResults() code was discarding most of the data!

Here is better code:

`function printResults($reports, $source = false) {
		$RET = [];
		for ( $reportIndex = 0; $reportIndex < count( $reports ); $reportIndex++ ) {
			$report = $reports[ $reportIndex ];
			$header = $report->getColumnHeader();
			$dimensionHeaders = $header->getDimensions();
			if(is_null($dimensionHeaders)){
				$RET = null;
			} else {
				$metricHeaders = $header->getMetricHeader()->getMetricHeaderEntries();
				$rows = $report->getData()->getRows();
				for ( $rowIndex = 0; $rowIndex < count($rows); $rowIndex++) {
					$RETROW = [];
					
					$row = $rows[ $rowIndex ];
					$dimensions = $row->getDimensions();
					$metrics = $row->getMetrics();					
					for ($i = 0; $i < count($dimensionHeaders) && $i < count($dimensions); $i++) {
						$dimension = str_replace("ga:", "", $dimensionHeaders[$i]);
						$value = $dimensions[$i];
						$RETROW[$dimension] = $value;
					}

					for ($j = 0; $j < count($metrics); $j++) {
						$values = $metrics[$j]->getValues();
						for ($k = 0; $k < count($values); $k++) {
							$entry = $metricHeaders[$k];
							$metric = str_replace("ga:", "", $entry->getName());
							$RETROW[$metric] = $values[$k];
						}
					}
					
					$RET[] = $RETROW;
				}
			}
		}
		return $RET;
	}`

**Comment by bshaffer** [comment]
Glad to hear you were able to get the data you need!
