### ISSUE TITLE
sensitive category targeting not working in display Video 360

### ISSUE THREAD

**Issue by devYadigar** [googleapis/google-api-php-client#1967]
I recently found that when I tried to add a sensitive category to line item targeting with bulkEditLineItemAssignedTargetingOptions  
  function even if request returned created targeting successfully   I could not find it in the interface and get created targeting with bulkList function. Oddly when I added one sensitive category exclusion manually from the interface and tried to add another sensitive exclusion targeting with API, that time it worked just fine. I could not find any reasonable explanation of why it happened in that strange way. I did not face that kind of problem before. Thank you for your answer in advance.

**Comment by jdpedrie** [comment]
Can you share a code sample? I may be able to verify whether you've made any easy-to-fix mistakes, but unfortunately this repository isn't monitored by anyone with expertise on this API. I'm happy to take a look and try to help with my basic understanding of the API, but you may have better luck reviewing the [support resources](https://developers.google.com/display-video/api/support) or posting on Stackoverflow!

If you're confident in your usage, feel free to close this and move on to the other channels. If you want me to review your usage, post the code here and I'll take a look. :)
