### ISSUE TITLE
Support for GA4 reporting

### ISSUE THREAD

**Issue by Joel-James** [googleapis/google-api-php-client#1969]
Google API PHP client doesn't support reporting for GA4 properties yet. Are you planning to add GA4 support soon?

[This ](https://developers.google.com/analytics/trusted-testing/analytics-data)is the only info I could find.

**Comment by jdpedrie** [comment]
I don't believe this library offers a wrapper for the Analytics Data API. You can make use of the Google Auth library to construct authenticated HTTP clients and interact directly with the API as described [here in the README](https://github.com/googleapis/google-auth-library-php#call-the-apis).

**Comment by chiragvels** [comment]
Hi @jdpedrie ,

[Here](https://developers.google.com/analytics/trusted-testing/analytics-data/rest) it is recommended that we can use google provided client libraries.

Does this cover in future?

@Joel-James, You are able to get any success for GA4 reporting data?

Thanks,

**Comment by Joel-James** [comment]
@chiragvels Not yet. I didn't try that. I will be working on it soon, will update you after that.

**Comment by LindaLawton** [comment]
I believe the team is still working on a PHP library for Analytics Data API  which will allow you to request data from a Google analytics ga4 account.  As GA4 is still very early beta, you need to keep an eye on the documentation to see when its released.  I dont think it will be part of this library is its a completely different request system.

Google analytics reporting API will only give you data back from universal analytics accounts.

**Comment by Joel-James** [comment]
@LindaLawton That's okay. We can use a different library if it uses a different request system. Any idea where can we see the progress of PHP library for GA4?

**Comment by LindaLawton** [comment]
I was told by the team last month that it was coming.    I can't give you a date, and due to NDA i can't be more than vaguely say keep checking.

**Comment by Joel-James** [comment]
Thanks @LindaLawton. I guess [this is the repo](https://github.com/googleapis/php-analytics-data).

**Comment by LindaLawton** [comment]
Yup that looks like it!

**Comment by TheCrowned** [comment]
Is there any ETA on when [the official PHP SDK](https://github.com/googleapis/php-analytics-data) will be released as a stable version @LindaLawton ? I find it a bit odd that current GA views will be entirely retired within a year and the SDK are still in beta :/

**Comment by firmlab** [comment]
It's 2023 now, any news about GA4 support on this library?

**Comment by LindaLawton** [comment]
The [Google analytics Data](https://developers.google.com/analytics/devguides/reporting/data/v1) I think is technically out of Bata, by the note on the screen it looks like its a combo of alphas and beta channels.  That being said the team as far as i know is still in the process of moving over dimensions and metrics from the UA so no its not done yet.

As for the [php-analytics-data](https://github.com/googleapis/php-analytics-data) as far as i know that's is also reasonably stable, it may be affected by any changes coming to the api itself but the cloud team should deal with them relatively swiftly. 

TBH most of the Google aps libraries this one included were in beta for more then ten years, until i mentioned it to someone at google then they finally decided to move them all from beta to maintained mode.    🤷‍♀️

**Comment by TheCrowned** [comment]
Hi @LindaLawton , thanks for your input here. If you want to know what the developer experience for GA4 is, [I have written something](https://thecrowned.org/the-shit-show-of-google-analytics-4-ga4). I would be very happy if somebody would answer, but so far everybody I brought it up to just dropped the conversation.

**Comment by bshaffer** [comment]
This library is in maintenance mode. Please take a look at https://cloud.google.com/php/docs/reference/analytics-data/latest, as this is the proper library to be using for this API.

**Comment by LindaLawton** [comment]
@TheCrowned nice article would love to have a chat with you about it.

**Comment by TheCrowned** [comment]
@LindaLawton feel free to reach out! There's contact info in the About page of the website.
