### ISSUE TITLE
{ "error": { "errors": [ { "domain": "usageLimits", "reason": "dailyLimitExceededUnreg", "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.", "extendedHelp": "https://code.google.com/apis/console" } ], "code": 403, "message"

### ISSUE THREAD

**Issue by FahadTariq476-dev** [googleapis/google-api-php-client#1975]
Fatal error: Uncaught Google_Service_Exception: { "error": { "errors": [ { "domain": "usageLimits", "reason": "dailyLimitExceededUnreg", "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.", "extendedHelp": "https://code.google.com/apis/console" } ], "code": 403, "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup." } } in C:\xampp\htdocs\test-example\google-drive-api\vendor\google\apiclient\src\Google\Http\REST.php:118 Stack trace: #0 C:\xampp\htdocs\test-example\google-drive-api\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 C:\xampp\htdocs\test-example\google-drive-api\vendor\google\apiclient\src\Google\Task\Runner.php(181): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 C:\xampp\htdocs\test-example\google-drive-api\ in C:\xampp\htdocs\test-example\google-drive-api\vendor\google\apiclient\src\Google\Http\REST.php on line 118

**Comment by FahadTariq476-dev** [comment]
if ($client->isAccessTokenExpired()) {
        // Refresh the token if possible, else fetch a new one.
        if ($client->getRefreshToken()) {
            $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
        } else {
            // Request authorization from the user.
            $authUrl = $client->createAuthUrl();
            printf("Open the following link in your browser:\n%s\n", $authUrl);
            print 'Enter verification code: ';
            $authCode = trim(fgets(STDIN));

            // Exchange authorization code for an access token.
            $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
            $client->setAccessToken($accessToken);

            // Check to see if there was an error.
            if (array_key_exists('error', $accessToken)) {
                throw new Exception(join(', ', $accessToken));
            }
        }
        // Save the token to a file.
        if (!file_exists(dirname($tokenPath))) {
            mkdir(dirname($tokenPath), 0700, true);
        }
        file_put_contents($tokenPath, json_encode($client->getAccessToken()));
    }


i am using this code for google drive api

**Comment by bshaffer** [comment]
Looks like the requests you're making are not authorized. Were you able to successfully go through the authorization flow? This would mean being prompted in your browser to authorize your application, and pasting an authorization code back on the command line.

**Comment by bshaffer** [comment]
See the examples in the examples directory for more help on how to do this. Specifically, check out the [simple-file-upload](https://github.com/googleapis/google-api-php-client/blob/master/examples/simple-file-upload.php) example, which uses the Drive API.

**Comment by FahadTariq476-dev** [comment]
sir now i am getting the invalid json token in codeigniter. because the token.js file has null no access token in it. Plz tell me what i doing wrong.

**Comment by ashraffahim** [comment]
Hello @FahadTariq476-dev

This is because the scope you use for Drive API is labelled restricted.
You can make a limited number of requests to get file data/content.
Once you have reached the limit you have to get another access_token for the existing session. It is like having refresh_token.

You can wrap your code that sends requests to get files in `try...catch`
If that error is thrown you can `requestAccessToken`.

NOTE: For refreshing the access token in an existing session, you do not need to ask for content again.

**Comment by neoacevedo** [comment]
Question: what if I'm not using credentials but else API key?

**Comment by ashraffahim** [comment]
@neoacevedo Your question is not clear
