### ISSUE TITLE
Google_Client no longer exist since v2.8

### ISSUE THREAD

**Issue by UserNameIsWrong** [googleapis/google-api-php-client#1983]
#### Environment details

  - OS: mac Os Catalina 10.15.7
  - PHP version: 7.4.11
  - Package name and version: googleapis/google-api-php-client v2.8.1 and 2.8.2

#### Code example

`Google_Service_Gmail` `__construct()` requires `Google_Client` but this Class no longer exist since v2.8.
I See Google_Client it replaced by `Google\Client`

```php
   /**
   * Constructs the internal representation of the Gmail service.
   *
   * @param Google_Client $client The client used to deliver requests.
   * @param string $rootUrl The root URL used for requests to the service.
   */
  public function __construct(Google_Client $client, $rootUrl = null)
  {
    parent::__construct($client);
```

```php
namespace Google;

use ...

/**
 * The Google API Client
 * https://github.com/google/google-api-php-client
 */
class Client
{
   ```

**Comment by bshaffer** [comment]
Hello! Are you using `composer` as your autoloader? If so, then the aliases in [`src/aliases.php`](https://github.com/googleapis/google-api-php-client/blob/master/src/aliases.php) will be defined, and you will not get this error. If not, include `src/aliases.php` manually before creating `Google_Service_Gmail`.

**Comment by UserNameIsWrong** [comment]
Yes You're right. I haven't noticed aliases.

**Comment by bshaffer** [comment]
Please re-open or file a new bug if you encounter any other issues!
