### ISSUE TITLE
implode error 

### ISSUE THREAD

**Issue by FahadTariq476-dev** [googleapis/google-api-php-client#1987]
![Capture](https://user-images.githubusercontent.com/71066043/97835859-e7ba1380-1cfc-11eb-9a89-1ea7041224d1.JPG)

**Comment by mfn** [comment]
You're using an outdated version of the library, this was fixed over a year ago => https://github.com/googleapis/google-api-php-client/commit/5f98e13a007644d8faac97ea931e08e2a57c5d0b but in the meantime you upgraded your PHP version.

Please upgrade to a newer version of this library, too!

**Comment by FahadTariq476-dev** [comment]
thanks man
