### ISSUE TITLE
I have downloaded google-api-php-client-2.8.1 there is no any autoload.php

### ISSUE THREAD

**Issue by mevsme** [googleapis/google-api-php-client#1989]
I have followed https://github.com/googleapis/google-api-php-client/blob/master/docs/install.md and there is no any `require_once '/path/to/google-api-php-client/vendor/autoload.php';` file!

I tried composer and it downloaded 30 MB of different stuff but google-api-php-client-2.8.1 is only 154 KB, why is that?
Is it really necessary those 30 MB of composer files?

Why are you talking about manual download and why do you say the download contains all necessary dependencies if there is no way not to use composer?

**Comment by bshaffer** [comment]
Thank you for reporting this! It looks like our asset publisher [did not succeed](https://github.com/googleapis/google-api-php-client/runs/1322806378?check_suite_focus=true) for v2.8.1.

Please download the assets for [v2.8.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.8.0) and we will have a version for v2.8.1 (and soon v2.8.2) shortly.

**Comment by bshaffer** [comment]
This should be fixed in https://github.com/googleapis/google-api-php-client/pull/1993

**Comment by bshaffer** [comment]
Please see the latest version [v2.8.2](https://github.com/googleapis/google-api-php-client/releases/tag/v2.8.2) for the latest complete assets!
