### ISSUE TITLE
40 MB to be able to upload to google drive? Google API php library is too big

### ISSUE THREAD

**Issue by mevsme** [googleapis/google-api-php-client#1990]
No really, I made `composer install` in google-api-php-client-2.8.1 and it downloaded 40 MB of libraries on top of my 300 KB project, it can't work like that, can it?

**Comment by mevsme** [comment]
Ok, I am not a composer expert but I've figured out that you should

1) run `composer install --no-dev`

2) edit `composer.json`
Do what this part says: https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services

3) run `composer update --no-dev`

???

4) the files are 3 MB now

**Comment by jdpedrie** [comment]
Glad you figured it out!
