### ISSUE TITLE
Error when using Google\Client in yii2 framework

### ISSUE THREAD

**Issue by bastomiadi** [googleapis/google-api-php-client#1994]
![FB_IMG_1605375417101](https://user-images.githubusercontent.com/13336571/99153453-33949180-26db-11eb-9b94-425dfaea3aa5.jpg)

How to solve this.?

**Comment by igorsuhinin** [comment]
Please see https://github.com/googleapis/google-api-php-client/issues/1986#issuecomment-727274795

**Comment by bshaffer** [comment]
I believe this is an IDE error and not an actual error when the code is run. Try running the code and see if you get an error.

If that is the case, it'll be fixed in https://github.com/googleapis/google-api-php-client/pull/1984

**Comment by bshaffer** [comment]
@bastomiadi try upgrading to the latest version of this library ([v2.8.3](https://github.com/googleapis/google-api-php-client/releases/tag/v2.8.3)) and see if that fixes the issue!

**Comment by bastomiadi** [comment]
Yes, its fixed when upgrade to latest, thank you.
