### ISSUE TITLE
Redirect after logging in with Google gets stuck, does not complete with a forms error

### ISSUE THREAD

**Issue by themarketechgroup-us** [googleapis/google-api-php-client#1997]
I've been using the google-api-php-client for quite some time now and recently I returned to use it and found when my php code redirects to the oauth page, it gets stuck. The url is shown in the browser below:

https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=online&client_id=<clientid>&redirect_uri=http%3A%2F%2Flocalhost%2Fkdb%2Fgoogle_oauth_config.php&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&approval_prompt=auto

The error in the console is:

Uncaught TypeError: document.forms[0].submit is not a function

The html in the page is:

<body bgcolor="#ffffff" text="#000000" link="#0000cc" vlink="#551a8b" alink="#ff0000">
<form jsname="RimvDb" action="https://accounts.google.com/o/oauth2/auth?trampoline=1&amp;as=S-1476171880%3A1605758027123444" method="POST">
<input type="hidden" name="access_type" value="online">
<input type="hidden" name="approval_prompt" value="auto">
<input type="hidden" name="submit" value="Login with Google">
<input type="hidden" name="scope" value="https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile">
<input type="hidden" name="response_type" value="code">
<input type="hidden" name="redirect_uri" value="http://localhost/kdb/google_oauth_config.php">
<input type="hidden" name="state" value="">
<input type="hidden" name="client_id" value="clientid">
</form>
<script nonce="">document.forms[0].submit();</script>
</body>

If i place my cursor in the browsers url bar and hit enter, the page continues and I am able to enter into my site logged in.

I can't seem to track down the cause. Any help is appreciated.

**Comment by dwsupplee** [comment]
Hey there @themarketechgroup-us, this question seems a little out of the scope of what we can offer here with our libraries - I'd suggest giving it a shot over at https://stackoverflow.com/ and providing as much detail as possible to help reproduce. Best of luck!
