### ISSUE TITLE
PHP 7.4 Notice on Client.php

### ISSUE THREAD

**Issue by TakTaki** [googleapis/google-api-php-client#1998]
#### Environment details

  - OS: Mac OS
  - PHP version: 7.4.12
  - Package name and version: "google/apiclient" : 2.8.3

I recently updated my project from PHP 7.3 to PHP 7.4 and I'm now receiving the PHP Notice : 

```
In Client.php line 970:

  Notice: Trying to access array offset on value of type null
```

**Comment by jdpedrie** [comment]
I'm having trouble duplicating this. [Line 970](https://github.com/googleapis/google-api-php-client/blob/81696e6206322e38c643cfcc96c4494ccfef8a32/src/Client.php#L970) does access an array, but it's in an `isset` call, which should not raise any errors.

Do you have a full stack trace available?
