### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: Invalid token format 

### ISSUE THREAD

**Issue by RahatSaqib** [googleapis/google-api-php-client#2000]
#### Environment details

  - OS:Windows
  - PHP version:7.3
  - Package name and version:

#### Steps to reproduce

  1. ...Fatal error: Uncaught InvalidArgumentException: Invalid token format in C:\xampp\htdocs\project\vendor\google\apiclient\src\Client.php:503 Stack trace: #0 C:\xampp\htdocs\project\join.php(20): Google\Client->setAccessToken(Array) #1 {main} thrown in C:\xampp\htdocs\project\vendor\google\apiclient\src\Client.php on line 503

#### Code example

		$client = new Google\Client();
		$client->setAuthConfig('client_secret.json');

		$client->addScope(Google_Service_Drive::DRIVE);
		$client->setRedirectUri('http://localhost/project/join.php');
		$client->setAccessType('offline'); 
		$client->setApprovalPrompt('force');       // offline access
		$client->setIncludeGrantedScopes(true); 

		$client->addScope('email');

		$client->addScope('profile');

I have tried so many solution in stackoverflow and github but didn't work for me. After some refreshes it occurs . when I delete the cookies and history it works but after some refreshes it happens again.
If anybody give me the solution.It will be helpful.

Thanks!

**Comment by RahatSaqib** [comment]
Any kind of solution?

**Comment by bshaffer** [comment]
It looks like you're calling `Google\Client->setAccessToken(Array)` in a file called `join.php`, which is not part of your code sample. And in this call, if the array that you're passing to `setAccessToken` does not have a key `"access_token"`, then this exception is thrown:

https://github.com/googleapis/google-api-php-client/blob/e48449e1c06e46e46267e09dd12d6b921c6a1bf0/src/Client.php#L525-L527

So, the error is not in the code example you've provided, but in your `join.php` file where you're calling `setAccessToken` with an array that is invalid.
