### ISSUE TITLE
Trying Google API it's a mess

### ISSUE THREAD

**Issue by mevsme** [googleapis/google-api-php-client#2001]
I passed 7 circles of hell and figured out how to do anything, now I get this

````
Authorization Error
Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (blabla@gmail.com).
Learn more
Request Details

    access_type=online
    response_type=code
    redirect_uri=http://localhost:8000/simple-file-upload.php
    client_id=934053423208-avr87bbg7pcqh330elauhot9edjv3i3f.apps.googleusercontent.com
    scope=https://www.googleapis.com/auth/drive

````

How do I overcome this????????

**Comment by mevsme** [comment]
1) upload logo
2) add emails
3) add scopes
4) add user - your email

**Comment by IanMkoll** [comment]
In my case, it was much simpler - I had to publish application from test to production.

**Comment by bshaffer** [comment]
Looks like you were able to get it working! Sorry to hear you had such a difficult time.

**Comment by bshaffer** [comment]
Did you follow the [instructions here](https://github.com/googleapis/google-api-php-client#authentication-with-oauth) for integrating with OAuth, or some other instructions?

**Comment by bikrambox** [comment]
Just got the Error and Fixed it myself. 
When creating the API Creds 
https://console.cloud.google.com/apis/credentials/consent?project={PROJECT NAME}
Got to ---> API--> Credentials and then in consent ---->ADD test users, (USING THEIR EMAIL ID) and save it and Voila! it works

**Comment by bikrambox** [comment]
BTW I was testing the Gmail API, will let you know with Drive API

**Comment by tomstafford** [comment]
> BTW I was testing the Gmail API, will let you know with Drive API

This is what fixed it for me with Drive API

**Comment by Benevolent** [comment]
Same , specifically creating the **Test User** solved the issue in my case.
