### ISSUE TITLE
Invalid annotations

### ISSUE THREAD

**Issue by kirya-dev** [googleapis/google-api-php-client#2004]
Im using this pakage and found broken annotation of `Google_Service_PeopleService_ListConnectionsResponse::getConnections()`

Actually annotation:
```php
@return Google_Service_PeopleService_Person
```

Expected annotation: 
```php
@return Google_Service_PeopleService_Person[]
```

**Comment by jdpedrie** [comment]
Duplicate of https://github.com/googleapis/google-api-php-client-services/pull/238

A fix for this is in the works.
