### ISSUE TITLE
Google Shopping Actions Promotion Benefit Tax Impact Value Incorrect

### ISSUE THREAD

**Issue by ckouris84** [googleapis/google-api-php-client#2005]
#### Environment details
  - OS: Centos 7
  - PHP version: 5.6
  - Package name and version: googleapis/google-api-php-client v2.8.3
#### Steps to reproduce
  1. For any Google Shopping Actions order that shows a taxImpact for a promotional discount in the Merchant Center, get the order and then get promotions for the order and you will see a 0.00 taxImpact value from the API which does not match.

#### Code example

```php
// Replace **MASKED** values with the path to credentials json, merchant id, and Google Shopping Actions order

    require "/google/includes/api/autoload.php";
    putenv('GOOGLE_APPLICATION_CREDENTIALS=**MASKED**.json');
    $GoogleClient = new Google_Client();
    $GoogleClient->useApplicationDefaultCredentials();
    $GoogleClient->setScopes(Google_Service_ShoppingContent::CONTENT);		
    $GoogleShoppingService = new Google_Service_ShoppingContent($GoogleClient);		

    $merchant_id        = '**MASKED**';
    $gs_order_id        = '**MASKED**';
    
    $gs_current_order = $GoogleShoppingService->orders->get($merchant_id, $gs_order_id);
    foreach($gs_current_order->getPromotions() as $gs_order_promotion){
        foreach($gs_order_promotion['benefits'] as $gs_order_promotion_benefit) {
            $promo_tax_impact = $gs_order_promotion_benefit['taxImpact']['value'];
            echo "\n Google Shopping Order: " . $gs_order_id . " Promotion Tax Impact: " . $promo_tax_impact;
        }
    }
```

Please address ASAP!

**Comment by jdpedrie** [comment]
Hi @ckouris84,

Unfortunately we can't help much here with API issues or potential bugs. We only handle the client libraries. I suggest you explore one of the following resources, which will give you a better opportunity to get in touch with the team maintaining the API.

* [Support Forum](https://groups.google.com/g/google-content-api-for-shopping?pli=1)
* [Public Issue Tracker](https://issuetracker.google.com/issues)

Best of luck!
