### ISSUE TITLE
Please include scope constants for HangoutsChat

### ISSUE THREAD

**Issue by stecca21** [googleapis/google-api-php-client#2008]
It looks like many of the services include constants for their scopes, but none are set for hangouts/chat. I'd love to see these added in.

**Comment by jdpedrie** [comment]
Hi @stecca21,

The services here are autogenerated, so we're not able to add it ourselves. I suggest you report this to the Hangouts Chat team using the [public issue tracker](https://issuetracker.google.com/issues/new?component=350158&template=1047346). Ask them to provide the available service scopes in the API discovery document. Once they've done that, they'll appear in this library like magic. 🌟
