### ISSUE TITLE
Google Calendar unable to trace "child" events after "child" time update

### ISSUE THREAD

**Issue by zendrax** [googleapis/google-api-php-client#2009]
Steps to reproduce:
- Create an event that starts on Monday at 1pm and it repeats daily
- Edit the event from that series that is scheduled for Wednesday and set it to start at 2pm and select to update `This and following events`

Once updated events from Monday and Tuesday will have one `recurringEventId` while Wednesday and following will have another `recurringEventId`. Is there a way to track down events from Wednesday forward with the data like `recurringEventId` I have from the event from Monday and Tuesday?

Hope that makes sense.

Thanks in advance.

**Comment by jdpedrie** [comment]
Hi @zendrax,

Have you taken a look at the [support resources](https://developers.google.com/calendar/support) page for Calendar? Unfortunately, those of us who handle issues on this library are experts in the client libraries, but not necessarily on the specific APIs. For help with API usage, it's recommended you take a look at one of the available support resources, which are monitored both by community members with a lot of knowledge and by the people who build and maintain the Calendar API.

Best of luck!
