### ISSUE TITLE
File sharing/permissions

### ISSUE THREAD

**Issue by ildarius** [googleapis/google-api-php-client#2011]
I scanned the repo, but still not sure if it allows sharing of files / changing permissions such as what's described here:
https://developers.google.com/drive/api/v3/manage-sharing

**Comment by jdpedrie** [comment]
Which action specifically are you looking for? There are a number described on that page.

**Comment by ildarius** [comment]
> Which action specifically are you looking for? There are a number described on that page.

Thank you for the reply I'd like to be able to set the "role => reader, type=> anyone"

**Comment by jdpedrie** [comment]
On which resource? A file, folder or drive?

**Comment by ildarius** [comment]
> On which resource? A file, folder or drive?

Hi, on folder and file

**Comment by ildarius** [comment]
think there's a way to make HTTP requests to the API as well, right? So I would authenticate with the API, then using the object make an HTTP request with required changes. Would that work?

**Comment by jdpedrie** [comment]
Yes, it certainly would. There's a sample of that [here](https://github.com/googleapis/google-auth-library-php#call-the-apis).

**Comment by jdpedrie** [comment]
To answer the original question, you should be able to accomplish the same using this client with the [`Google_Drive_Resource_Permissions::create()`](https://github.com/googleapis/google-api-php-client-services/blob/62310a1d0b7701ed874bbcaf3687b0c05d6917fb/src/Google/Service/Drive/Resource/Permissions.php#L67) method.

**Comment by Hatchberries** [comment]
can you able to add permission to anyone ??

**Comment by saranshdhingra** [comment]
> can you able to add permission to anyone ??

I tried to run the API from the [REST API reference](https://developers.google.com/drive/api/reference/rest/v3/permissions/create) with a gmail ID and everything worked as expected, so I think the answer is, "Yes, you can add the permission to any valid email".
