### ISSUE TITLE
Copy Folder and all Sub Folders/Files

### ISSUE THREAD

**Issue by dankurfirst** [googleapis/google-api-php-client#2013]
Hi, I am trying to write code that will copy a folder and all of it's folders/sub folders and files. 

I currently have this code:

`$origin = <parent_folder_id>
$optParams = array(

        'q' => "'".$origin."' in parents"
        );

    $folder = $service->files->listFiles($optParams); 

return($folder);`

This only give me the first level children, the particular folder I am trying top copy has 4 levels of children. I have seen examples of this that work with recursion but I am wondering if there is really no easier way to just copy an folder and all levels of children?

Thank you

**Comment by LindaLawton** [comment]
Its only going to give you the first level because the parent for the child folder is the current folder

Your going to have to create a recursive method which will look for folders within the current folder and then recall the method to get the files within the child folder.
