### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by netwons** [googleapis/google-api-php-client#2016]
this is mycode

Route::post('/upload',function(\Illuminate\Http\Request $request){
    dd( $request->file('thing')->store('google'));
});
but not save to googledrive & not error

**Comment by jdpedrie** [comment]
Hi @netwons,

These issues are for bugs and problems relating specifically to the client library. Take a look at the [Support](https://developers.google.com/drive/api/v3/support) page for Drive. You can find resources for usage assistance there.

If you think this is a problem with the client library, let us know and we'll continue.
