### ISSUE TITLE
Problem with the example idtoken.php

### ISSUE THREAD

**Issue by rowanrh** [googleapis/google-api-php-client#202]
When running the example "idtoken,php" I received the following error 

"Undefined index: id_token in ...\Google\Auth\OAuth2.php on line 446" 

I changed "id_token" to "access_token" (the only element containing data) only to receive the following error:

Fatal error: Uncaught exception 'Google_Auth_Exception' with message 'Wrong number of segments in token: ' in ...\Google\Auth\OAuth2.php on line 480

Any assistance much appreciated.

**Comment by msrumon** [comment]
> Hmm, I am wondering if we have insufficient scopes in that example. Can you change "email" in the scopes string to "profile" and see if that helps (and revert your id token -> access token change).

@ianbarber, Setting `profile` scope throws a 403 error for me. Any idea? P.S.: Every other thing works as usual.
