### ISSUE TITLE
Interface alias 'Google_Task_Retryable' shouldn't have a class definition

### ISSUE THREAD

**Issue by nerbiz** [googleapis/google-api-php-client#2024]
#### Environment details

  - OS: any
  - PHP version: any
  - Package name and version: google/apiclient 2.8.3

#### Steps to reproduce

  1. Make a new dummy class: `class A implements Google_Task_Retryable {}`
  2. No errors at runtime, but it does show an error in an IDE, which expects the `extends` keyword, because `Google_Task_Retryable` has a class definition
  3. Change `implements` to `extends`
  4. Fatal runtime error: 'Class A cannot extend from interface Google\Task\Retryable'

The problem is on line 62 in aliases.php:
https://github.com/googleapis/google-api-php-client/blob/master/src/aliases.php#L62
```php
class Google_Task_Retryable extends \Google\Task\Retryable {}
```

`Google_Task_Retryable` shouldn't have a class definition, because it's an alias of an interface.

#### Proposed solution

Remove line 62 from aliases.php.

**Comment by bshaffer** [comment]
@nerbiz thank you for reporting this! It'll be fixed in the next release.
