### ISSUE TITLE
How to get autoloader.php without composer?

### ISSUE THREAD

**Issue by andrewpolemeni** [googleapis/google-api-php-client#2025]
So I downloaded the source code as followed from the [releases](https://github.com/googleapis/google-api-php-client/releases) page. How is the autoload.php file generated without composer? There is only a /src folder that doesn't have the following"/google-api-php-client/vendor/autoload.php". Just would like someone to explain how to use the google-api-php-client without composer, I'm mainly using it to get page views from google analytics.

**Comment by matthewmcvickar** [comment]
If you go to the [Releases page](https://github.com/googleapis/google-api-php-client/releases), you'll see that some of the releases have more assets than others—if you expand the 'Assets' section, you’ll see a number of packaged `google-api-php-client-VERSION-PHP_VERSION.zip` files generated for different versions of PHP.  *That's* what you need for running the code without Composer.

The recently released v2.8.3 and v2.8.1 do not have those packages. v.2.8.2 does. This seems like an oversight, but I'm not sure.

You can see which versions have downloadable packages more easily by going to the [Tags page](https://github.com/googleapis/google-api-php-client/tags) and clicking on the 'Downloads' section next to the most recent version that has a 'Downloads' section.

Hope that's helpful as a workaround until packages are provided for the most recent version.

**Comment by jdpedrie** [comment]
Thanks for the helpful guide @matthewmcvickar. We fixed the automated asset release in master, and I've opened #2029 to get a new release tagged. Hope to :ship: it soon.

**Comment by jdpedrie** [comment]
Hi everybody!

[v2.9.1](https://github.com/googleapis/google-api-php-client/releases/tag/v2.9.1) has release assets available again. Sorry for the inconvenience!
