### ISSUE TITLE
PHP 7.4 error in implode call

### ISSUE THREAD

**Issue by eco747** [googleapis/google-api-php-client#2038]
#### Environment details

  - OS: ALL
  - PHP version: 7.4
  - Package name and version: google/apiclient/src/Google/Service/Resource.php

```php
290    if (count($queryVars)) {
291       $requestUrl .= '?' . implode($queryVars, '&');   // <<<<<<< here php 7.4 complains about parameter inversion
292     }
```

ErrorException
implode(): Passing glue string after array is deprecated. Swap the parameters

**Comment by jdpedrie** [comment]
This was fixed in [v2.2.4](https://github.com/googleapis/google-api-php-client/releases/tag/v2.2.4), released in April 2019. Upgrade to a more recent version of the client and you should be all set.
