### ISSUE TITLE
php 7.4 error 

### ISSUE THREAD

**Issue by eco747** [googleapis/google-api-php-client#2039]
#### Environment details

  - OS: all
  - PHP version: 7.4
  - Package name and version: guzzlehttp/guzzle/src/Handler/CurlFactory.php at line 67

```php
62 public function release(EasyHandle $easy)
63     {
64        $resource = $easy->handle;
65        unset($easy->handle);
66
67        if (count($this->handles) >= $this->maxHandles) { //<<<<<<<< here $this->handles is undefined the 1st time
68            curl_close($resource);
```

this line should be replaced by
```php
67        if ( $this->handles && count($this->handles) >= $this->maxHandles) {
```

**Comment by jdpedrie** [comment]
What version of `google/apiclient` and `guzzlehttp/guzzle` are you using? You can see this by running `composer show`.

**Comment by eco747** [comment]
Arg, i'm so sad to have missed that.
Thanks
