### ISSUE TITLE
Partial download - drive API

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-php-client#204]
Are we missing Partial download support in Google / Service / Drive.php?  

Partial download documentation : https://developers.google.com/drive/web/manage-downloads#partial_download

**Comment by bkahlert** [comment]
Looking for this feature myself. I tried to set the Range header but if I do so I don't get any response at all.
$request = new Google_Http_Request($downloadUrl, 'GET', array('Range' => 'bytes=0-100'), null);

**Comment by hugohuynh** [comment]
I have tried  Partial download by setting Range in header. It's not working. Please advise. Thanks
