### ISSUE TITLE
How to install only shopping content api Google\\Task\\Composer::cleanup

### ISSUE THREAD

**Issue by rsyscraft** [googleapis/google-api-php-client#2040]
I want to install only shopping content api. Please guide me what is the name of shopping content api in composer json file in place of Drive Or youtube  -
{
    "require": {
        "google/apiclient": "^2.7"
    },
    "scripts": {
        "post-update-cmd": "Google\\Task\\Composer::cleanup"
    },
    "extra": {
        "google/apiclient-services": [
            "Drive",
            "YouTube"
        ]
    }
}

**Comment by jdpedrie** [comment]
It's called [`ShoppingContent`](https://github.com/googleapis/google-api-php-client-services/tree/master/src/Google/Service/ShoppingContent). 😃 

```json
{
	"extra": {
		"google/apiclient-services": [
			"ShoppingContent"
		]
	}
}
```

**Comment by rsyscraft** [comment]
@jdpedrie  thanks
