### ISSUE TITLE
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'file does not exist' in C:\xampp\htdocs\calendar\vendor\google\apiclient\src\Google\Client.php on line 839

### ISSUE THREAD

**Issue by guptarishabh15** [googleapis/google-api-php-client#2044]
C:\xampp\htdocs\calendar>php quickstart.php
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'file does not exist' in C:\xampp\htdocs\calendar\vendor\google\apiclient\src\Google\Client.php:839
Stack trace:
#0 C:\xampp\htdocs\calendar\quickstart.php(17): Google_Client->setAuthConfig('credentials.jso...')
#1 C:\xampp\htdocs\calendar\quickstart.php(63): getClient()
#2 {main}
  thrown in C:\xampp\htdocs\calendar\vendor\google\apiclient\src\Google\Client.php on line 839

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'file does not exist' in C:\xampp\htdocs\calendar\vendor\google\apiclient\src\Google\Client.php on line 839

InvalidArgumentException: file does not exist in C:\xampp\htdocs\calendar\vendor\google\apiclient\src\Google\Client.php on line 839

Call Stack:
    0.0017     132968   1. {main}() C:\xampp\htdocs\calendar\quickstart.php:0
    0.0315     403944   2. getClient() C:\xampp\htdocs\calendar\quickstart.php:63
    0.0374     605584   3. Google_Client->setAuthConfig() C:\xampp\htdocs\calendar\quickstart.php:17

**Comment by jdpedrie** [comment]
The path you are providing to the credentials.json file is incorrect. Take a look at the answer I gave yesterday for more information on the same issue: https://github.com/googleapis/google-api-php-client/issues/2043#issuecomment-775336111
