### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant "STDIN" in C:\xampp\htdocs\test\google-drive.php:40 Stack trace: #0 C:\xampp\htdocs\test\google-drive.php(61): getClient() #1 {main} thrown in C:\xampp\htdocs\test\google-drive.php on line 40

### ISSUE THREAD

**Issue by shuja007** [googleapis/google-api-php-client#2047]
![image part  1](https://user-images.githubusercontent.com/59730907/107936216-33d74e00-6fa4-11eb-92fa-6ee49c1eabe6.jpg)
![image part 2](https://user-images.githubusercontent.com/59730907/107936226-38036b80-6fa4-11eb-9260-a106a5e3cbed.jpg)
![image part 3](https://user-images.githubusercontent.com/59730907/107936233-39cd2f00-6fa4-11eb-95e9-77b52b8846f2.jpg)

**Comment by dwsupplee** [comment]
@shuja007 Adding `define('STDIN', fopen('php://stdin', 'rb'));` to the top of your script should help.
