### ISSUE TITLE
Hide gridlines in export

### ISSUE THREAD

**Issue by NielsKnaap** [googleapis/google-api-php-client#2050]
Hi,

I want to export an google sheets as PDF. I have it working wright now with the method: `$this->service->files->export($uid, 'application/pdf', ['alt' => 'media']);`

The only problem I have is that I want to hide the gridlines, is that possible?

**Comment by saranshdhingra** [comment]
Hi @NielsKnaap 
Sorry for the extremely late reply on this issue.

I don't think the [export API](https://developers.google.com/drive/api/reference/rest/v3/files/export) natively supports an option to hide grid lines.

I was able to find a solution on [Stackoverflow](https://stackoverflow.com/questions/67765413/cannot-hide-gridlines-google-spreadsheet-api-php) which uses  `BatchUpdateSpreadsheetRequest` which essentially updates the sheet's proprty first to hide the grid lines, then we proceed with the export and the result is intended.
Here is the sample I used and tested:
```
function downloadSheetAsPdf($client) {
    $sheetId = "";
    $sheetService = new Sheets($client);
    $requests = $requests = [
        new \Google_Service_Sheets_Request([
            'updateSheetProperties' => [
                'properties' => [
                    'sheetId' => 0,
                    'gridProperties' => [
                        'hideGridlines' => true
                    ],
                ],
                'fields' => 'gridProperties.hideGridlines'
            ],
        ])
    ];

    $batchUpdateRequest = new \Google_Service_Sheets_BatchUpdateSpreadsheetRequest(['requests' => $requests]);
    $sheetService->spreadsheets->batchUpdate($sheetId, $batchUpdateRequest); 

    $driveService = new Drive($client);
    $response = $driveService->files->export($sheetId, 'application/pdf', ['alt' => 'media']);
    file_put_contents("test.pdf", $response->getBody()->getContents());
}
```

Of course, this has a side effect of changing the source's properties, but that can be undone after the download if it suits anyone reading this.

Thanks for your patience on this, I'll be closing this issue now.
