### ISSUE TITLE
You tube Video upload using php

### ISSUE THREAD

**Issue by mukul-escion** [googleapis/google-api-php-client#2054]
How to make sure whenever any guest uploads the video it directly saved into the youtube channel, without any authentication or authorization and it will list on the youtube channel

**Comment by dwsupplee** [comment]
@mukul-escion we can help answer some broad questions regarding the client libraries here, but this one seems very specific to YouTube's API. I'd recommend checking out the product specific support page [here](https://developers.google.com/youtube/v3/support).
