### ISSUE TITLE
Quota Exceed when uploading youtube video 

### ISSUE THREAD

**Issue by mukul-escion** [googleapis/google-api-php-client#2055]
When I try to upload the video it shows me your quota exceed, without uploading any video can anyone help me to solve the issue 
I am getting this error

{ "error": { "code": 403, "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.", "errors": [ { "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.", "domain": "youtube.quota", "reason": "quotaExceeded" } ] } }

How do I increase the quota for uploading the video

**Comment by jdpedrie** [comment]
As David mentioned in #2054, the [support resources](https://developers.google.com/youtube/v3/support) for youtube is the best place for this. We don't have the ability to help much with questions related to specific API questions here.
