### ISSUE TITLE
Long-process on web-server: delay of 15 min before getting new oauth token 

### ISSUE THREAD

**Issue by Kocal** [googleapis/google-api-php-client#2056]
Hi :wave: 

We have web-server process which lasts ~1h25. We run it automatically at the beginning of each month but those two last months we had a _delay issue_ of 15 min with Google before getting a new access token.

The process starts at 11pm and ends at 0h25 of the next day. At midnight, 1h after the process start, we have Google OAuth issues during 15 minutes, then everyting is going fine for the last 10 minutes:
![image](https://user-images.githubusercontent.com/2103975/110231939-ef8ffb80-7f1a-11eb-92d6-413c606bf61b.png)

And this is the error we have: 
![image](https://user-images.githubusercontent.com/2103975/110231875-a9d33300-7f1a-11eb-97f2-c23b9998b9de.png)
```
{ "error": { "code": 401, "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "errors": [ { "message": "Invalid Credentials", "domain": "global", "reason": "authError", "location": "Authorization", "locationType": "header" } ], "status": "UNAUTHENTICATED" } }
```

#### Code example

This is our `ClientFactory` which allows us to create Google `Client` and keep them in runtime cache. Each time we need a `Client` we call `$clientFactory->getGoogleClient()`. 
This also allows us to manually refresh the access token if it's expired, but I don't think this is the right way to do. 

```php
<?php

declare(strict_types=1);

namespace App\Admin\AnalyticsBundle\API;

use Google_Client;
use Psr\Log\LoggerInterface;

class ClientFactory implements ClientFactoryInterface
{
    private string $applicationName;
    private string $authConfig;
    private string $developerKey;
    private string $refreshToken;
    private ?LoggerInterface $logger;
    /** @var array<string, Google_Client> */
    private array $clients = [];

    public function __construct(string $applicationName, string $authConfig, string $developerKey, string $refreshToken, ?LoggerInterface $logger = null)
    {
        $this->applicationName = $applicationName;
        $this->authConfig      = $authConfig;
        $this->developerKey    = $developerKey;
        $this->refreshToken    = $refreshToken;
        $this->logger          = $logger;
    }

    public function getGoogleClient(array $options = []): Google_Client
    {
        $clientId = serialize($options);

        if (!\array_key_exists($clientId, $this->clients)) {
            $this->clients[$clientId] = $client = $this->createGoogleClient($options);
        }

        $client = $this->clients[$clientId];

        // Since we had issues with refreshing access token, we manually check+refresh it
        if ($client->isAccessTokenExpired()) {
            $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
        }

        return $client;
    }

    /**
     * @param GoogleClient_Options $options
     */
    private function createGoogleClient(array $options): Google_Client
    {
        $client = new Google_Client([
            'use_objects' => true,
            'retry'       => [
                'max_delay' => 10, // in seconds
                'retries'   => 3,
            ],
        ]);

        if (null !== $this->logger) {
            $client->setLogger($this->logger);
        }

        $client->setAuthConfig($this->authConfig); // path to a .json which looks like `{"web": {"client_id": "....", "project_id": "...", ...}`
        $client->setAccessType('offline'); // as documented at https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient
        $client->setApprovalPrompt('consent'); // as documented at https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient
        $client->setApplicationName($this->applicationName); // our app name in API console
        $client->setDeveloperKey($this->developerKey); // AIzaSyDGr...........
        $client->setIncludeGrantedScopes(true); // as documented at https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient
        $client->fetchAccessTokenWithRefreshToken($this->refreshToken); // a refresh token a previous developer got a log time ago

        $httpClient = new \GuzzleHttp\Client(array_merge(
            [
                'timeout' => 10,
            ],
            $options['guzzle'] ?? [],
            // Options that are normally handled by Google, in \Google_Client::createDefaultHttpClient() method.
            [
                'exceptions' => false,
                'base_uri'   => $client->getConfig('base_path'),
            ]
        ));
        $client->setHttpClient($httpClient);

        return $client;
    }
}
```

And we use it like this:
```php
$gaData = (new Google_Service_Analytics($this->clientFactory->getGoogleClient()))->data_ga->get(...);
```

#### Environment details

  - OS: Debian GNU/Linux 10 (buster)
  - PHP version: 7.4.15
  - Package name and version: google/apiclient@2.9.1

---

Do you know what happens? Is our implementation bad or there is really an issue with Google servers?
Thanks!

**Comment by Sciecha** [comment]
any update?

**Comment by thanhtoan1196** [comment]
any update?

**Comment by andont** [comment]
For google/apiclient v2.11.0 this is what works for me:

```php
$client = new Google_Client(
    [
        'api_format_v2'  => true,
        'token_callback' => function ($cacheKey, $newAccessToken) {
            $token = array_merge(
                $client->getAccessToken(),
                [
                    'access_token' => $newAccessToken,
                    'expires_in'   => 3600,
                    'created'      => time(),
                ]
            );
            $client->setAccessToken($token);
        },
        'cache_config'   => [
            'lifetime' => 10
        ]
    ]
);
```
They broke it after some version, no idea if it is fixed yet. **cache_config** part is important, IIRC by default it is 3600(s) - it is what breaks the authentication after an hour. Using it in 4+ hours script.

**Comment by bshaffer** [comment]
I'm not sure what the `use_objects` option is supposed to do in your implementation, but I don't see anything else wrong in your implementation.

This behavior would indicate that the access token is expired (after an hour), but the auth library continues using for 15 minutes after it's expired, but then refreshes the token as expected. 

The default behavior of the auth library cache is to refresh the token after 1500 seconds (25 minutes), so this behavior would only happen if a custom cache configuration (via `cache_config` was being provided to the client library). So I would suggest ensuring that the default cache lifetime is less than what you have here. 

Another issue I see is that you are fetching a new access token ONE TIME by calling `fetchAccessTokenWithRefreshToken`, but this does not tell the client library how to refresh another once this one is expired. The way to do that would be to ensure that the file passed to `setAuthConfig` contains the refresh token in the `refresh_token` field of the JSON credentials (along with the `client_id` and `client_secret` associated with the refresh token).
