### ISSUE TITLE
Get email message which have attachments throw 404 error

### ISSUE THREAD

**Issue by abhimanusharma** [googleapis/google-api-php-client#2058]
I am implementing this on Laravel 6, using google-api-php-client

I have tried all the possible debug and searched the google but this is not mentioned anywhere.

Receiving below error if try to fetch an email which have an attachment.

```
{ "error": { "code": 404, "message": "Requested entity was not found.", "errors": [ { "message": "Requested entity was not found.", "domain": "global", "reason": "notFound" } ], "status": "NOT_FOUND" } }
```

Tried to run the same request here with same message id and userId, everything is work [here](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get) but not working with this package.

**Comment by dwsupplee** [comment]
Odd, let's see what we can do to figure this out here. As for your debugging journey, did you attempt to put some statements [here](https://github.com/googleapis/google-api-php-client/blob/master/src/Http/REST.php#L79-L104)? If you could output the request so we see what is going over the wire that would help us determine if there is an issue with the client or not.

**Comment by abhimanusharma** [comment]
@dwsupplee I found a solution, If you use message id instead of thread id to fetch a message, it will show error requested entity not found for the mail which have attachments in it. If you attach a file from outside of your application.
