### ISSUE TITLE
Is it possible to send stuff to google drive in an automated fashion? 

### ISSUE THREAD

**Issue by hunkeelin** [googleapis/google-api-php-client#2060]
Is it possible to send stuff to google drive in an automated fashion like in an aws lambda? 

It seems I can't really do that in https://developers.google.com/drive/api/v3/quickstart/go an automated fashion because of credentials.json and token.json. It doesnt' seem google api allow static web token (for obvious security reasons). What other options I have?

**Comment by yash30201** [comment]
Hi @hunkeelin, thanks for asking this question.

Can you please help me understand the exact thing which you were trying to do? Is it something like doing things with google API once something is triggered somewhere else?

**Comment by yash30201** [comment]
Closing this issue due to lack of information. Please reopen incase this is required.
