### ISSUE TITLE
Laravel 8, where do I put require_once '/path/to/your-project/vendor/autoload.php';

### ISSUE THREAD

**Issue by eduardonwa** [googleapis/google-api-php-client#2064]
I am using Laravel 8, it's a fresh project and just installed the dependency through composer. I have a few questions:

Where do I put this:
```
require_once '/path/to/your-project/vendor/autoload.php';
```

On the ```.env``` file I added this line: 

```YOUTUBE_TOKEN=googlecloudplatformapikey```

Is that where you're supposed to place that? Im trying to make this work just by reading the documention in this repo and using this documentation: https://developers.google.com/youtube/v3 , if anyone knows of a video-tutorial or something else that might help my case, please share here as im new to this API. 

Thanks!

**Comment by gilsongabriel** [comment]
Using laravel, you doesn't need put `require_once '/path/to/your-project/vendor/autoload.php';`, because laravel automatically load vendor autoload in /public/index.php.

**Comment by saranshdhingra** [comment]
Closing as this is answered.
