### ISSUE TITLE
Exclude some services to reduce package size

### ISSUE THREAD

**Issue by TheCrowned** [googleapis/google-api-php-client#2065]
Hello there!
Is there any way to only retain the API files for some Google services only? For example, I only need Analytics (and all the authentication stuff, of course). I could go an try to delete folder by folder until it breaks, but maybe there is a smarter way?

I wanted to upgrade from v1 to v2, but not if this bumps the package size from 6MB to 40MB. It would be a pain to ship such a big zip, unnecessarily :)

**Comment by jdpedrie** [comment]
You can configure post-install cleanup! See [instructions here](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services).

**Comment by TheCrowned** [comment]
Oh, now I feel dumb I missed that! Thanks a lot for the pointer! :)
