### ISSUE TITLE
Download private attachments?

### ISSUE THREAD

**Issue by hanoii** [googleapis/google-api-php-client#2067]
We are attaching images to the events, but the only way we can download the events is if we set the images public after uploading to drive. Is there a way for use to use the Google Calendar API credentials to fetch the attachments from the account's Drive without making them public?

**Comment by saranshdhingra** [comment]
Hey @hanoii 
First of all, I would like to apologize for the delay in the response from our end.

Perhaps you have already moved on/fixed the issue. But I will still answer if anyone else stumbles upon this.

The attachments in Google calendar events are attached as a drive file(I tried uploading from my desktop and that was the case). So, it can be downloaded like any other drive file if the caller has the required permissions.

This is the code snippet I used and was able to download the file without making it public. Note, that I am the creator of the event, so I had the necessary permissions to view/download the file.

```php
    $calendarId = ""; // You can get this from the calendar list API, if you're not sure
    $eventId = "";  // You can get this from the events list API, https://developers.google.com/calendar/api/v3/reference/events/list

    $calendarService = new Calendar($client);
    $event = $calendarService->events->get($calendarId, $eventId);
    $fileName = $event->attachments[0]->title;
    $fileId = $event->attachments[0]->fileId;

    // Use the file as you would use any other Drive file.
    $driveService = new Drive($client);
    $response = $driveService->files->get($fileId, ['alt' => 'media']);
    $content = $response->getBody()->getContents();
    file_put_contents($fileName, $content);
```

Thanks for the patience on this, I will be closing this issue now, but feel free to open this, if there is something else.
Thanks.
