### ISSUE TITLE
PHP Warning:  Trying to access array offset on value of type null in /var/www/google/gax/src/Transport/RestTransport.php on line 161

### ISSUE THREAD

**Issue by cappadaan** [googleapis/google-api-php-client#2082]
- OS: CentOS7
  - PHP version: 8.0.6
  - Package name and version: 2.9.1

Found this one in my logs

PHP Warning:  Trying to access array offset on value of type null in /var/www/google/gax/src/Transport/RestTransport.php on line 161

I have no steps to reproduce.

**Comment by jdpedrie** [comment]
Hi @cappadaan,

GAX is used by https://github.com/googleapis/google-cloud-php, not this library. However, without more detail on the call that raised the error, I'm not sure there's a lot we can do. Do you have a stack trace?

Please feel free to open an issue on the repository I linked above. Information on the APIs you use and again, any detail on calls you make or error information will be crucial to helping track down the problem.
