### ISSUE TITLE
Google api php client lib latest release(2.9.2) not downloading via composer.

### ISSUE THREAD

**Issue by safiyullahmohideen** [googleapis/google-api-php-client#2089]
#### Environment details

  - OS:Windows
  - PHP version:7.3
  - Package name and version:

 Using composer  I downloaded Google api php client lib latest version(2.92), but still I am getting 2.9.1 version only. Please resolve my issue.  

Thanks!

**Comment by DHANDAPANISATTANATHAN** [comment]
Google Plz most of the time after release a new version, We cant see the released version in Client.php.
Help us to solve, or at least put some comments in the release notes. We will understand.

**Comment by bshaffer** [comment]
The correct version is downloading, we just forgot to update the `VERSION` constant in `Google\Client`.

This will be fixed in https://github.com/googleapis/google-api-php-client/pull/2090 when we release v2.10.0
