### ISSUE TITLE
SSL Error:0909006C:PEM routines:get_name:no start line during sync

### ISSUE THREAD

**Issue by maverickvn360** [googleapis/google-api-php-client#2095]
#### Environment details

  - OS: Ubuntu 20.04 VMWare Workstation Pro 15.5.6
  - PHP version: 7.4.3 (cli)
  - Package name and version: MISP 2.4.144

#### Steps to reproduce

It's a normal sync scenario
I have 2 MISP Instances, A and B. A has been setup as a DMZ instace, B a local instance (hypothetically). They're within the same network, currently. I've setup a sync user and a local org on A, with a server on B - sync of server B with A. The server certificate (A's public certificate) uploads just fine. The problem arises with uploading B's private key ('pem'/'key'/'csr' formats) to client certificate field.

OpenSSL Version: 1.1.1f - 31 Mar 2020

I've tried regenerating the key and viewed the error logs:

`Warning: Warning (2): openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate! in [/var/www/MISP/app/Lib/Tools/SyncTool.php, line 131]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
openssl_x509_read - [internal], line ??
SyncTool::getClientCertificateInfo() - APP/Lib/Tools/SyncTool.php, line 131
SyncTool::getServerClientCertificateInfo() - APP/Lib/Tools/SyncTool.php, line 92
Server::runConnectionTest() - APP/Model/Server.php, line 2379
ServersController::testConnection() - APP/Controller/ServersController.php, line 1669
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
`
Also I noticed this:
`Notice: Error during GPG signing.
[Crypt_GPG_BadPassphraseException] Cannot sign data. Incorrect passphrase provided.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(1824): Crypt_GPG_ProcessHandler->throwException()
#1 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(861): Crypt_GPG_Engine->_closeSubprocess()
#2 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1792): Crypt_GPG_Engine->run()
#3 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1024): Crypt_GPG->_sign()
#4 /var/www/MISP/app/Model/Server.php(3311): Crypt_GPG->sign()
#5 /var/www/MISP/app/Controller/ServersController.php(1110): Server->gpgDiagnostics()
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#11 {main}`

Thanks!

P.S.: I'm a bit new to MISP, please bear with the novicity..

**Comment by bshaffer** [comment]
This library does not handle MISP, and your stack trace doesn't include any classes from this library. I think you opened this issue in the wrong repository.

**Comment by maverickvn360** [comment]
Apologies for the inconvenience! Incorrect repo! 🙁
