### ISSUE TITLE
Reference docs not found

### ISSUE THREAD

**Issue by gusdecool** [googleapis/google-api-php-client#2102]
The URL to reference docs that point to URL https://googleapis.github.io/google-api-php-client/master/ are 404

![CleanShot 2021-07-14 at 08 32 10@2x](https://user-images.githubusercontent.com/223657/125542387-3dffb30d-dfd0-4415-b578-ace1b342937c.png)

**Comment by bshaffer** [comment]
I'm not sure what happened to the `master` directory it but I added it back

**Comment by fredericgboutin-yapla** [comment]
FYI @bshaffer @gusdecool I think it's broken again.

**Comment by bshaffer** [comment]
I'm trying to track this down, in the meantime you can look at https://googleapis.github.io/google-api-php-client/v2.12.3/

**Comment by bshaffer** [comment]
Okay I figured it out. The docs are now visible again at https://googleapis.github.io/google-api-php-client/main/
