### ISSUE TITLE
PHP Google_Service_Docs_UpdateTextStyleRequest not working

### ISSUE THREAD

**Issue by bionan** [googleapis/google-api-php-client#2104]
#### Environment details

  - OS: Fedora 33
  - PHP version: 7.4.21
  - Package name and version: google-api-php-client-2.10

#### Code example

        `        
        $request = [];
        $request[] = new Google_Service_Docs_UpdateTextStyleRequest(
            [
                'updateTextStyle' => [
                    'fields' => 'bold',
                    'range' => [
                        'startIndex' => 30,
                        'endIndex' => 60,
                    ],
                    'textStyle' => [
                        'bold' => true
                    ]
                ],
            ]
        );

        $batchUpdateRequest = new Google_Service_Docs_BatchUpdateDocumentRequest(array(
            'requests' => $request
        ));

        $this->docService->documents->batchUpdate($iddoc, $batchUpdateRequest);
        `
Results an exception:

**An uncaught Exception was encountered
Type: Google\Service\Exception

Message: { "error": { "code": 400, "message": "Invalid requests[0]: No request set.", "errors": [ { "message": "Invalid requests[0]: No request set.", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } }

Filename: /opt/lampp/htdocs/gestao_atas/application/libraries/google-api-php-client-2.10/src/Http/REST.php**

**Comment by saranshdhingra** [comment]
Hi @bionan 
Apologies for the delayed response on this issue.

I tried your code snippet and I was able to replicate the error, however, changing the use of `Google_Service_Docs_UpdateTextStyleRequest` class to `Google_Service_Docs_Request` made the snippet work as expected.

The motivation to explore this was the [REST API reference](https://developers.google.com/docs/api/reference/rest/v1/documents/batchUpdate) where we simply pass an array of objects and the object contains a key of `updateTextStyle`.

Another way I reached at this conclusion was that the `BatchUpdateDocumentRequest` class expects the `Google\Service\Docs\Request` class whose alias is `Google_Service_Docs_Request` not `Google_Service_Docs_UpdateTextStyleRequest`.

Hope this helps anyone reading this.

I'll be closing this issue now, but please feel free to reopen this if needed.
