### ISSUE TITLE
i have a bug to show, how do i to resolve?

### ISSUE THREAD

**Issue by ChenghuaMi** [googleapis/google-api-php-client#2105]
to show the error:
PHP Fatal error:  Uncaught Google\Service\Exception: {
  "error": {
    "code": 400,
    "message": "Invalid value 'ga:'. Values must match the following regular expression: 'ga:[0-9]+'",
    "errors": [
      {
        "message": "Invalid value 'ga:'. Values must match the following regular expression: 'ga:[0-9]+'",
        "domain": "global",
        "reason": "invalidParameter"
      }
    ]
  }
}
,how do i to resolve the problem?

**Comment by yash30201** [comment]
Hi @ChenghuaMi, It has been a long time so this issue may have become obsolete for you, thus closing this issue.

If you still encounter this issue then please give more info regarding this and how to reproduce this. Thank you.
