### ISSUE TITLE
Wrong parameter approval_prompt

### ISSUE THREAD

**Issue by nextflex** [googleapis/google-api-php-client#2108]
With referrer to the documentation https://developers.google.com/identity/protocols/oauth2/web-server#httprest
the Parameter must be 'prompt' instead of 'approval_prompt'. Please fix this, because 'prompt' is not accepted by the server. 

https://github.com/googleapis/google-api-php-client/blob/11871e94006ce7a419bb6124d51b6f9ace3f679b/src/Client.php#L646

**Comment by bshaffer** [comment]
We've updated the OAuth2 URL to V2, which accepts `prompt=force`. See https://github.com/googleapis/google-api-php-client/pull/2275.
