### ISSUE TITLE
Get Token for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by theusccruz** [googleapis/google-api-php-client#2109]
I'm trying to get a Firebase Cloud Message access token. Is there any tutorial in this repository that can help me?

I'm using Laravel 6x

**Comment by saranshdhingra** [comment]
Hi @theusccruz 
Sorry for the late reply on this, perhaps you've solved the issue long back.

But could you give more context about what is it that you're trying to do?
Different options that you've tried would be very helpful.

**Comment by saranshdhingra** [comment]
I'll be closing this issue for now as there hasn't been any reply.

But please feel free to reopen this with more details.

Thanks :)
