### ISSUE TITLE
Tag order with setTags is being ignored? 

### ISSUE THREAD

**Issue by mdanso** [googleapis/google-api-php-client#2112]
I'm using the youtube data api to update video tags.  When i check the tags on Youtube, they are in ascending order and ignore the order i used with setTags.  For example;

`$keywords = array();
$keywords[0] = "one";
$keywords[1] = "two";
$keywords[2] = "three";
$snippet->setTags($keywords);`

On youtube this will display as `one,three,two`.  Tag order affects ranking, what options do i have to solve this, as we have many videos being uploaded with API?

**Comment by saranshdhingra** [comment]
Hi @mdanso 
I apologize for the delay in response from our side.

But I tried the same using the [video:update](https://developers.google.com/youtube/v3/docs/videos/update) API directly and setting the tags as `["one","two","three"]` does put `three` first even via the API.

So, I don't think there is much we can do from the PHP library's side.
If you want to understand the rationale behind it or want to raise a concern, I suggest you open a support ticket in youtube.

**Comment by bshaffer** [comment]
Take a look at [this post](https://tuberanker.com/blog/does-the-order-of-tags-matter-on-youtube#:~:text=The%20answer%2C%20of%20course%2C%20is,does%20not%20matter%20on%20YouTube.) which states:

```
Does the order of YouTube tags matter? Or, can you order your tags however you'd like? The answer, of course, is no. Tag order does not matter on YouTube. While it might have mattered in the past (nobody knows), it does not matter nowadays. So, you have the complete freedom to order your video tags as you please.
```
