### ISSUE TITLE
[BUG] Youtube LiveBroadCasts Transition Not works only with this PHP Client

### ISSUE THREAD

**Issue by rohitcoder** [googleapis/google-api-php-client#2114]
#### Environment details

  - OS: MAC OS Big Sur 11.2.2
  - PHP version: 8.0.0
  - Package name and version: "google/apiclient": "^2.1",

#### Steps to reproduce

From this API playGround https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition?apix=true&apix_params=%7B%22broadcastStatus%22%3A%22complete%22%2C%22id%22%3A%22UMaikej2yMU%22%7D , We can see it's mentioned that we can use `$response = $service->liveBroadcasts->transition('complete', 'NoBKeVEanL4', '');` to Mark a video as complete, but it doesn't work **"on My PC / Server"** and throws an error, but when i click on cURL tab from below shown window to get the cURL code and when i modify only my "Access Token" then it works!

In, Simple words, i don't think the above-mentioned method is working properly in PHP client, I am also adding my error output below

![image](https://user-images.githubusercontent.com/17665703/128595370-35241a5a-ec45-446a-8300-b9d59e0632cc.png)

Error
```json
{
  "error": {
    "code": 400,
    "message": "Invalid value at 'broadcast_status' (type.googleapis.com/youtube.api.v3.LiveBroadcastTransitionRequest.BroadcastStatus), \"VnEkvWJ0fe0\"",
    "errors": [
      {
        "message": "Invalid value at 'broadcast_status' (type.googleapis.com/youtube.api.v3.LiveBroadcastTransitionRequest.BroadcastStatus), \"VnEkvWJ0fe0\"",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

#### Steps to reproduce this issue.

1. Get Ready with basic setup of this youtube client, access Tokens fetched and 1 video created from your testing youtube channel
2. Now, run this below code
```php
<?php
$client = new Google_Client(); 
$access_token = "YOUR_ACCESS_TOKEN_HERE";
$client->setAccessToken($access_token);
$youtube = new Google_Service_YouTube($client);
$client->setAccessToken($accessToken);
$service = new Google_Service_YouTube($client);
$response = $youtube->liveBroadcasts->transition('complete', 'YOUTUBE-VIDEO-ID-HERE', '');
print_r($response);
```
3. Run the above code, and you'll get same error as me.

For now, I am sending a custom HTTP Request from my PHP just to achieve this feature, hope someone looks at this issue. I  tried so hard debugged a lot then i noticed this isn't working as expected, but works with the below cURL

```curl
curl --request POST \
  'https://youtube.googleapis.com/youtube/v3/liveBroadcasts/transition?broadcastStatus=complete&id=YOUTUBE-VIDEO-ID-HERE' \
  --header 'Authorization: Bearer ACCESS-TOKEN-HERE' \
  --header 'Accept: application/json' \
  --compressed
```
Thanks!

**Comment by saranshdhingra** [comment]
Hi @rohitcoder 
Apologies for the delay in response in this issue.

But I would like to tell you, I followed the exact same process, i.e.
1. Started a live stream.
2. Went to the [REST API reference](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition), put in the `video id`, `broadcastStatus` and `part`. When I executed the request, the live stream ended immediately.
3. I clicked on `Show code` and then the `PHP` tab to get the PHP equivalent code, used that in a script, started a completely new stream, used the new id and executed the PHP script.
4. The new stream also ended immediately, without any error.

It possible that you missed a parameter like `part`(as I see in your screenshot) or there was an intermediate error which got resolved soon after.

But I can't really replicate this right now and hence I will be closing this issue now.

But if you encounter the issue again, please feel free to reopen this with more details.

Thanks :)

**Comment by rohitcodergroww** [comment]
@saranshdhingra Bro, The Project on which i was working is dead since last 2 years, you replied after 2 years 🤣

**Comment by InternGoUser** [comment]
@saranshdhingra Bro, The Project on which i was working is dead since last 2 years, you replied after 2 years 🤣

**Comment by rohitcoder** [comment]
@saranshdhingra Bro, The Project on which i was working is dead since last 2 years, you replied after 2 years 🤣

**Comment by saranshdhingra** [comment]
Yeah, we're certainly trying to get better at this. Hopefully at the very least someone searching for issues might get some clarity if they stumble upon this.

Cheers!
