### ISSUE TITLE
Class 'Google_Auth_AssertionCredentials' not found

### ISSUE THREAD

**Issue by kingrootid** [googleapis/google-api-php-client#2117]
An uncaught Exception was encountered
Type: Error

Message: Class 'Google_Auth_AssertionCredentials' not found

please help me i want to show analytics data

**Comment by kingrootid** [comment]
i solve this

> An uncaught Exception was encountered
> Type: Error
> 
> Message: Class 'Google_Auth_AssertionCredentials' not found
> 
> please help me i want to show analytics data


but i had another issue 
`An uncaught Exception was encountered
Type: Google\Service\Exception

Message: { "error": { "code": 403, "message": "User does not have any Google Analytics account.", "errors": [ { "message": "User does not have any Google Analytics account.", "domain": "global", "reason": "insufficientPermissions" } ] } }`

**Comment by bshaffer** [comment]
This one seems like it's in the error message- you're trying to access a Google Analytics account your authenticated user does not have access to.
