### ISSUE TITLE
pay   404  error

### ISSUE THREAD

**Issue by guoweibo** [googleapis/google-api-php-client#2118]
#### Environment details

  - OS: win10
  - PHP version: 5.4
  - Package name and version: 2.0

![企业微信截图_20210818181855](https://user-images.githubusercontent.com/19238970/129881806-b545e444-3c09-41b3-9465-1015e46b841b.png)

![企业微信截图_20210818182013](https://user-images.githubusercontent.com/19238970/129881976-9b31b60f-ada6-4b7f-8993-195adf9e321d.png)

Thanks!

**Comment by bshaffer** [comment]
Closing this as I believe it's been resolved
