### ISSUE TITLE
Peoples batch

### ISSUE THREAD

**Issue by rodrigojob** [googleapis/google-api-php-client#2119]
Hello,
the batch to delete contacts don't work
Error
Fatal error: Uncaught Error: Call to undefined method Google_Service_PeopleService_Resource_People::batchDeleteContacts()

$client = new Google_Client();
 ....
$service = new Google_Service_PeopleService($client);
$chk = $service->people->batchDeleteContacts($contacts);

**Comment by ajupazhamayil** [comment]
Let me have a look at this.

**Comment by ajupazhamayil** [comment]
I see that function, are you still facing this issue?

**Comment by ajupazhamayil** [comment]
I simply ran the following code and managed to get the error saying parameter is not correct:

```
<?php
require __DIR__ . '/vendor/autoload.php';

$client = new Google_Client();
$service = new Google_Service_PeopleService($client);
$chk = $service->people->batchDeleteContacts(null);
```

Error I received is:
```
PHP Fatal error:  Uncaught TypeError: Google\Service\PeopleService\Resource\People::batchDeleteContacts(): Argument #1 ($postBody) must be of type Google\Service\PeopleService\BatchDeleteContactsRequest, null given, called in ...
```

This error is sufficient show that the function exists.

are you still facing this issue?

**Comment by ajupazhamayil** [comment]
I hope the user is not facing this issue anymore. Thank you!
