### ISSUE TITLE
Support for BusinessMessage API and BusinessInformation

### ISSUE THREAD

**Issue by mtx-z** [googleapis/google-api-php-client#2123]
Hello,

I wanted to know if you plan to add support for [BusinessMessage API](https://developers.google.com/business-communications/business-messages) (businessmessages.googleapis.com), and [My Business Business Information API](https://developers.google.com/my-business/reference/businessinformation/rest?hl=fr) (mybusinessbusinessinformation.googleapis.com).

https://developers.google.com/business-communications/business-messages/reference

Thanks a lot

**Comment by jqr108** [comment]
Yeah this is a bit of a blocker as we need to upgrade the GMB Account API calls by end of Sept.

Looks like MyBusinessLocationLocation was added to the services report a week ago in v0.210 but current version of this repo has ~0.200.0 so composer doesn't allow upgrade yet.

https://github.com/googleapis/google-api-php-client-services/tree/v0.210.0/src

I think this recent update may be unintentionally blocking this?
https://github.com/googleapis/google-api-php-client/pull/2093

**Comment by ThibaultVlacich** [comment]
Run `composer update google/apiclient-services`, there's no reason for it to not update to 0.210, `~0.200` requirement should allow it.

**Comment by jqr108** [comment]
🤦‍♂️ had v2.10.0 in my composer.json instead of 2.10.1. thanks @ThibaultVlacich !

@mtx-z you might check this also, might solve your issue as well!

**Comment by ajcerqueti** [comment]
> Yeah this is a bit of a blocker as we need to upgrade the GMB Account API calls by end of Sept.

Will this involve updating to the v4 endpoints?
