### ISSUE TITLE
Wrong calandar ColorID

### ISSUE THREAD

**Issue by Artxlv** [googleapis/google-api-php-client#2124]
I have 12 calendars in my calendar list. When using PHP API, for some of those calendars I get wrong colorId and backgrounColor values in calendarList response.

```
$calendarList  = $service->calendarList->listCalendarList();
  print("<pre>".print_r($calendarList,true)."</pre>");
```

However, if I make test in APIs Explorer (Calendar API v3 > calendar.calendarList.get: https://developers.google.com/apis-explorer/#s/calendar/v3/calendar.calendarList.get ) , the response is correct.

**Comment by bshaffer** [comment]
Can you give us more information on how these responses differ? Without that information, we can't debug what could potentially be happening here.

As this issue is very old, I'm going to assume the problem has been fixed. Please open a new bug if that isn't the case.
