### ISSUE TITLE
Allow Users to Supply Additional Guzzle Client's Options

### ISSUE THREAD

**Issue by iastate-zuo** [googleapis/google-api-php-client#2155]
At our organization, all server-initiated requests are routed through a reverse-proxy server, which means we need to set the `proxy` options for the HTTP client to properly send outbound HTTP requests. 

Unfortunately, the [`Google\Client`](https://github.com/googleapis/google-api-php-client/blob/master/src/Client.php) class does not support supplying additional Guzzle options when setting it up, and the usual workaround to supply a custom HTTP client to the `Google\Client` is out of the question because we do not have direct control of the `google-api-php-client` package -- it's been used as a dependency of a 3rd party package. Consequently, we can't create a Guzzle Client with reverse-proxy settings and hand it over to the `Google\Client` because there is more than one layer of abstractions between our server code and `google-api-php-client`.

A possible solution to this problem is to add a `guzzle_option` config item to the `$config` variable, such that when creating the default [HTTP client](https://github.com/googleapis/google-api-php-client/blob/master/src/Client.php), we can merge the guzzle options with the `$options`, and supply the updated options to the Guzzle client constructor. Since most of the 3rd party packages will pass through `$config` variables, our server code will be able to hand over the desired Guzzle settings to the `Google\Client`.

For example, I'm thinking of some code like this:

```
protected function createDefaultHttpClient()
{
    // ... code to initiatialize $opions 
    $options = array_merge($options, $this->config['guzzle_options']);
    return new GuzzleClient($options);
}
``` 

I will summarize the solution to a PR to better illustrate this idea.

**Comment by bshaffer** [comment]
There is no need for this as an option, when you can set the client to a custom Guzzle Client at any time using `Google\Client::setHttpClient`:
```php
$client = new Google\Client();
$client->setHttpClient(new GuzzleHttp\Client($myGuzzleOptions));
```
