### ISSUE TITLE
Error: Call to undefined method Google\Client::isUsingJwtWithScope()

### ISSUE THREAD

**Issue by stephanvierkant** [googleapis/google-api-php-client#2162]
#2153 created an issue because `\Google\Client` doesn't have a method called `isUsingJwtWithScope`:

> Error: Call to undefined method Google\Client::isUsingJwtWithScope()

https://github.com/googleapis/google-api-php-client/blob/8865cab2efbd63b40f88552886865f31bd7f3edd/src/Client.php#L1258

Ping @bshaffer 

Maybe some kind of static analysis should be added to the test suite?

**Comment by realtebo** [comment]
[2021-12-02 00:59:21] production.ERROR: Call to undefined method Google\Client::isUsingJwtWithScope() {"userId":"d25d0506-8a96-3675-99b1-92dd4843dc06","exception":"[object] (Error(code: 0): Call to undefined method Google\\Client::isUsingJwtWithScope() at /vendor/google/apiclient/src/Client.php:1258)
[stacktrace]
#0 /vendor/google/apiclient/src/Client.php(436): Google\\Client->createApplicationDefaultCredentials()
#1 /vendor/google/apiclient/src/Client.php(911): Google\\Client->authorize()


Same problem here.
Don't you run at least a basic test suite before release ?! You broke our code

**Comment by jdevinemt** [comment]
I also have this issue. I'm also seeing `#[\ReturnTypeWillChange]` sprinkled throughout the code, which appears to be specific to php 8.1+. But in the package description it should work with older php versions.

**Comment by sheyDev** [comment]
Call to undefined method Google\Client::isUsingJwtWithScope();

Running into the same problem. Any fix for this?

**Comment by jdevinemt** [comment]
> 

You can just revert to v2.11.0 until it's fixed.

**Comment by bshaffer** [comment]
Fixed in [v2.12.1](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.1)

**Comment by stephanvierkant** [comment]
> Fixed in [v2.12.1](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.1)

Thanks for fixing this quickly!

Will there be any measures taken to prevent this kind of bugs? Even the most simple kind of static analysis would have found this.

**Comment by bshaffer** [comment]
I agree, and am also surprised it slipped through, since we have an extensive testing suite... there must be something unexpected happening with regards to this error, unfortunately.

**Comment by stephanvierkant** [comment]
Can I help with implementing static analysis, like phpstan?

**Comment by bshaffer** [comment]
@stephanvierkant If you wanted to submit a Pr for that, that would be super great!
