### ISSUE TITLE
v1-master disapeared

### ISSUE THREAD

**Issue by jamaral21** [googleapis/google-api-php-client#2174]
Hi, Im using the v1-master branch and yesterday when I tried to build my project it broke, what happened to the v1-master branch?

Thanks in advance,
Jose Amaral

**Comment by danoscarmike** [comment]
Default branch name has been switched to "main" in https://github.com/googleapis/google-api-php-client/pull/2159

@bshaffer for vis

**Comment by bshaffer** [comment]
Hello @jamaral21 

Yes, we removed `v1-master`, as it hasn't received an update in almost 5 years, and we do not expect any further updates from it.

Please upgrade to v2 of this library, or if you need to use `v1` for whatever reason (such as running this library on PHP 5.3) you can use the latest release of the v1 library, which is [`v1.1.7`](https://github.com/googleapis/google-api-php-client/releases/tag/1.1.7)
