### ISSUE TITLE
Google\Service\Datastore\ReadOnly class is a parse error in PHP 8.1

### ISSUE THREAD

**Issue by pcuser42** [googleapis/google-api-php-client#2175]
#### Environment details

  - OS: Ubuntu 20.04 (in WSL)
  - PHP version: 8.1.0
  - Package name and version: google/apiclient v2.12.1

#### Steps to reproduce

  1. Upgrade to PHP 8.1

A class named `ReadOnly` is no longer possible in PHP 8.1 as `readonly` is now a reserved word.

**Comment by danoscarmike** [comment]
@dwsupplee @bshaffer for vis

**Comment by bshaffer** [comment]
This is tricky as renaming `ReadOnly` will constitute a BC-breaking change.

**Comment by bshaffer** [comment]
This has been fixed in https://github.com/googleapis/google-api-php-client-services/pull/925 and the new clients have been released and tagged in https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.245.0
