### ISSUE TITLE
Install of google/apiclient-services failed when I run composer require google/apiclient

### ISSUE THREAD

**Issue by ziagit** [googleapis/google-api-php-client#2177]
In Laravel 7.0 Windows environment, I want to integrate google calendar. When I run `composer require google/apiclient` my installation stucks on `- Downloading google/apiclient-services (v0.224.1)` after long time waiting it shows the following error in the cmd.

>    Install of google/apiclient-services failed
>  - Installing google/apiclient (v2.12.1): Extracting archive
    0 [>---------------------------]
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

 > [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone --no-checkout -- "https://github.com/googleapis/google-api-php-client-services.git" "C:\User
  s\amu\Desktop\projects\laravel google calendar integration\blog\vendor\google\apiclient-services" && cd /D "C:\User
  s\amu\Desktop\projects\laravel google calendar integration\blog\vendor\google\apiclient-services" && git remote add
   composer -- "https://github.com/googleapis/google-api-php-client-services.git" && git fetch composer && git remote
   set-url origin -- "https://github.com/googleapis/google-api-php-client-services.git" && git remote set-url compose
  r -- "https://github.com/googleapis/google-api-php-client-services.git"" exceeded the timeout of 300 seconds.

>require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...`

It seems `google/apiclient-services` cannot be installed. does anyone know what should I do?

**Comment by itsAnuga** [comment]
How long does it take for it to timeout? 30 sec / 300 sec? behind proxy?

**Comment by touqeershafi** [comment]
Same is happening with me on windows 10, ubuntu

OS: Windows 10
Using ubuntu with docker and PHP 8

![image](https://user-images.githubusercontent.com/4585116/157505323-2e491c78-b2b8-4d70-9643-fe53dc915fc9.png)

**Comment by bshaffer** [comment]
The solution appears to be to disable "real-time protection" on Windows 10

**Comment by fredmanxu** [comment]
I disabled "real-time protection" on the Windows 10 machine, and my composer install worked.
like he said: https://stackoverflow.com/a/54137138/1635676

**Comment by Zh4rsiest** [comment]
In the documentation in the "[Cleaning up unused services](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services)" section it mentions the following

> There are over 200 Google API services. The chances are good that you will not want them all. In order to avoid shipping these dependencies with your code, you can run the Google\Task\Composer::cleanup task and specify the services you want to keep in composer.json:

```json
{
    "require": {
        "google/apiclient": "^2.12.1"
    },
    "scripts": {
        "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
    },
    "extra": {
        "google/apiclient-services": [
            "Drive",
            "YouTube"
        ]
    }
}
```

Therefor, include only the ones you actually need and it should run without error. It will still be super slow, but at least it won't fail. Or it didn't fail for us like this 🍾

**Comment by Art4** [comment]
I've solved this problem by temporarily increasing composer's process-timeout:

```bash
composer config process-timeout 3600
```
