### ISSUE TITLE
Deprecated since Symfony 5.4 and PHP 8.0

### ISSUE THREAD

**Issue by ArtemBurykin** [googleapis/google-api-php-client#2178]
After an app is updated to Symfony 5.4 there are few deprecations added, which are connected with Google\Model and Google\Collection.

These deprecations are:

1. Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Google\Model" now to avoid errors or add an explicit @return annotation to suppress this message.
2. Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Google\Model" now to avoid errors or add an explicit @return annotation to suppress this message
3. Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Model" now to avoid errors or add an explicit @return annotation to suppress this message.
4. Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Model" now to avoid errors or add an explicit @return annotation to suppress this message.
5.  Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
6. Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
7. Method "Iterator::key()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
8. Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
9. Method "Iterator::valid()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
10. Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
11. Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
12. Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
13. Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
14. Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by 3PSY0N** [comment]
@ArtemBurykin Hello, which version do you use?

**Comment by ArtemBurykin** [comment]
> @ArtemBurykin Hello, which version of the package do you use?

@3PSY0N Hello, I use 2.12.1

**Comment by maciejzgadzaj** [comment]
Sane issue here on Symfony 5.4.1 on PHP 7.4.26 with version 2.12.1.

**Comment by bshaffer** [comment]
This has been fixed since https://github.com/googleapis/google-api-php-client/pull/2200
