### ISSUE TITLE
I want to get a specific cell position on the spreadsheet, or update the value of a cell at a specific position.

### ISSUE THREAD

**Issue by renhagino** [googleapis/google-api-php-client#2179]
# Overview
- I have inserted order data into a spreadsheet through spureadsheets api.
- After that, I need to update the order data once inserted in the spreadsheet so that the customer can transfer the fee and the administration can process the shipment.
- I would like to get the cell range where the updated order data exists and update the values in the corresponding cell range.
- Can someone please help me with this?

## The problem that is happening
- Here I want to insert the following data into the range A5 to G5 on my spreadsheet. => (Wednesday, 12004, paid, 2021-11-05, jolly, 0145)
- However, I want to get the cell range A5-G5, which is the cell position where the updated order data exists, but I don't know how to get the cell range using the API.
## Processing test that I did
- I was not able to get the cell location where the updated order data was located, so I tried to test by passing the range I wanted to update directly to the $range variable. However, it did not update correctly in the cell position A5-G5 where the updated order data was located.
```php
1.$range = $sheet_ym.'!A1:""'; //I specified column A1 and an empty string, but got an error message.
```
```php
2. $range = $sheet_ym.''; //No column and only an empty string forced the top row to be overwritten instead of the row with the updated order.
```
```php
3. $range = $sheet_ym.'; !A1:A1000 //I got an error message when I specified column A1 + row A1000 => "Requested writing within range ['202112'!A1:A1000], but tried writing to column [B]" ["domain"]=> string(6) "global" ["reason"]=> string(10) "badRequest' }
```
```php
4. $range = $sheet_ym.'!A1:O1000'; //Specifying A1 and O1000 forced the top row to be overwritten instead of the row where the updated order exists.
```

## What I need support for.
- Can you please tell me how to get the position of the cell where the updated order data exists, or how to specify a value for $range and automatically update the data in the appropriate cell range according to the updated order data?

## Structure of the spreadsheet
- sheet name = 202111

|| A | B | C | D | E | F | G |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 1 | week | order_id | is_paid | paid_day | send | name | account_id |
| 2 | Monday | 12001 |  |  |  | mercy | 0123 |
| 3 | Monday | 12002 | paid | 2021-11-02 | send | kate | 0153 |
| 4 | Tuesday | 12003 | paid | 2021-11-5 |  | tarkey | 0097 |
| 5 | Wednesday | 12004 |  |  |  | jolly | 0145 |
| 6 | Thursday | 12005 | paid | 2021-11-06 | send | rashford | 0083 |
| 7 | Thursday | 12006 | paid | 2021-11-05 | send | jean | 0016 |
| 8 | Friday | 12007 | paid | 2021-11-05 | send | sedwild | 0195 |

## SourceCode
```php
function　api_insertif($sheet_name=NULL,$current_date=NULL,$where=NULL,$input_data=array()){
$sheet_name=isset($sheet_name)?$sheet_name:'monthly';
$current_date=isset($current_date)?$current_date:date('Y-m-d');
$where=isset($where)?$where:'';
//The $input_data contains the customer order information.
$input_data=isset($input_data)?$input_data:array();
//A flag to separate insert and update operations on the spreadsheet
$insert=false;

//Set the new insertion flag to true
$insert = true;

//Sheet name (taken from the current year, e.g. 202110,202111)
$sheet_ym=isset($sheet_ym)?$sheet_ym:date('Ym');

//Receipt number of the order customer is trying to confirm
$duplicate_check_id = $input_data[0]['orderid'];

//Extracting order information from the worksheet
$worksheet_order_val = $worksheet['values'];

//Check that there are no duplicate orderids in the worksheet.￥￥
foreach($worksheet_order_val as $sheet_val){

　if($sheet_val[2] == $duplicate_check_id){

	var_dump('There is a duplicate order ID.');

　　   $insert = false;

　}

}

var_dump('The insertion or update process has been checked.');

//If it is a new order and not an update of the order data
if($insert){

  
//The $inputdata contains the data of the order when the order is actually placed or when the management confirms the payment.
foreach($input_data as $row_data){

//Exception handling starts
try{

$client = $this->google_client;
$service = new  Google_Service_Sheets($client);
$spreadsheetId = 'myspreadsheetid';
//202109, 202110, 202111, etc. The year and month are used as the sheet name.
$sheet_ym=isset($sheet_ym)?$sheet_ym:date('Ym');
$range = $sheet_ym.'!$A1';
$option = [
'valueInputOption' => 'USER_ENTERED'
];

$requestBody = new  Google_Service_Sheets_ValueRange([

'values' => [

[　　
$row_data['week'],
$row_data['order_id'],
$row_data['is_paid'],
$row_data['paid_day'],
$row_data['send'],
$row_data['name'],
$row_data['account_id']
]
],

//Inserting new order data into a spreadsheet
$service->spreadsheets_values->append($spreadsheetId, $range, $requestBody,$option);

var_dump('Order number has been successfully completed and inserted');

}catch(Exception  $e){

 //Handling data insertion failures
 var_dump('function api_insertif() : Failed to insert some data');
 var_dump($e);

 return  false;
 }
}
//===============================================================================
//From here on down is not an insertion, but a process to update the spreadsheets
//===============================================================================
}else{
	
	
	foreach($input_data as $row_data){

	　　　　　　　//Exception handling starts
	　　　　　　　try{
	　　　　　　 　　var_dump('The same order number as the current order exists in the 	spreadsheet, so update it.')
	　　　　　　 　　
	　　　　　　 　　$client = $this->google_client;　
　　　　　　　　　　　
	　　　　　　　　　　$service = new  Google_Service_Sheets($client);

	　　　　　　　　　　$spreadsheetId = 'myspreadsheetid';
	 
		 $option_1 = [
	　　　　　　　　　　　　　　　　　　　'valueInputOption' => 'USER_ENTERED'
		 ];
		 $option_2 = 'USER_ENTERED';
		
		//Define the RequestBody
		 $updateBody = new  Google_Service_Sheets_ValueRange([

		 'values' => [
					[
						$row_data['week'],
						$row_data['order_id'],
						$row_data['is_paid'],
						$row_data['paid_day'],
						$row_data['send'],
						$row_data['name'],
						$row_data['account_id']
                     ]
				],
			]);

	//Update process
	$service->spreadsheets_values->update($spreadsheetId, $range, $updateBody, 		$option_1);

	var_dump('The insertif update process is now complete.');
  
}catch(Exception  $e){

	var_dump('The update process of insertif could not be performed.');
	var_dump($e);
	exit;

return  false;

}

}


}
```
##  Libraries and external services used
- google-api-php-client--PHP5.6  v2.11.0
https://github.com/googleapis/google-api-php-client/releases
- Google Cloud Platform
https://console.cloud.google.com/

##  The page I am referring to
- php google api client
https://github.com/googleapis/google-api-php-client
- Migrate from Sheets API  from  v3 https://developers.google.com/sheets/api/guides/migration#v4-api_5
- PHP QuickStart
https://developers.google.com/sheets/api/quickstart/php

**Comment by saranshdhingra** [comment]
Hi @renhagino 
Sorry for the extremely late reply on this.

Hopefully this has been resolved, but for anyone going through this, here's what I did.

I created a spreadsheet with the same structure as yours(cells A-G). Added some dummy data and tried the [spreadsheet.values.update](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update) method.

The range that I used was `3:3` which signifies the whole 3rd row(`valueInputOption` that I used was `USER_ENTERED` ). The data that I passed was simply the following format:
```
{
  "values": [
    [
      "Monday",
      "123",
      "",
      "",
      "",
      "Name",
      1234
    ]
  ]
}
```
The empty cells signify the absence of data in the specific cells.

The PHP equivalent would be:
```
$values = new ValueRange([
        'values' => [
            [
                "Monday",
                "123",
                "",
                "",
                "",
                "Some name",
                123456
            ]
        ]
]);

$service->spreadsheets_values->update(
        "SHEET_ID",
        "3:3",
        $values,
        ['valueInputOption' => 'USER_ENTERED']
);
```

The above 2 methods work for me, if they don't then please feel free to reopen this issue.
