### ISSUE TITLE
URL in README.md is 404

### ISSUE THREAD

**Issue by jtullett** [googleapis/google-api-php-client#2181]
README.md's first URL is "https://googleapis.github.io/google-api-php-client/main/" - it's a 404 error.

**Comment by bshaffer** [comment]
THank you for pointing this out. While I fix it, you can use this link: https://googleapis.github.io/google-api-php-client/v2.12.1/

**Comment by danoscarmike** [comment]
This appears to be working now. @bshaffer can you link the fix and close please?

**Comment by bshaffer** [comment]
I re-ran the docs generation job to fix it. I am not sure what caused the problem in the first place, so we'll have to keep an eye on this for the next release.
