### ISSUE TITLE
Does it support Google Chat API?

### ISSUE THREAD

**Issue by mattprado21** [googleapis/google-api-php-client#2192]
I'm trying to implement Google Chat API but I cant seem to find the class for it. I only found Google\Service\Hangouts which is no longer supported on google. Thanks

**Comment by nekromoff** [comment]
No, it does not.

However, coding chat is quite easy, it is basic JSON:
```
$json = json_encode(['text' => $text], JSON_UNESCAPED_SLASHES); // basic text, but you can use cards as well: https://developers.google.com/chat/api/reference/rest/v1/spaces.messages#Message
            $ch = curl_init($space_id); // change to space ID, e.g. https://chat.googleapis.com/v1/spaces/...
            curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            $result = curl_exec($ch);
            curl_close($ch);
```

**Comment by dwsupplee** [comment]
@mattprado21 after taking a look at the `HangoutsChat` set of classes, I think they have been updated to support Google Chat. You'll need to use the spaces set of calls as dms/rooms are deprecated. Let me know if you find otherwise and we can re-open, thanks!
