### ISSUE TITLE
New version "^3.0" for "psr/cache"

### ISSUE THREAD

**Issue by huynguyen93** [googleapis/google-api-php-client#2193]
**Is your feature request related to a problem? Please describe.**
My project is using Symfony which requires "symfony/cache-contracts v3.0.0", which requires "psr/cache ^3.0", 

but "google/apiclient" requires "google/auth", which requires "psr/cache ^1.0|^2.0"

So, when I run "composer require google/apiclient", it failed:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - google/apiclient[v2.12.0, ..., v2.12.1] require google/auth ^1.10 -> satisfiable by google/auth[v1.10.0, ..., v1.18.0].
    - google/auth[v1.16.0, ..., v1.18.0] require psr/cache ^1.0|^2.0 -> satisfiable by psr/cache[1.0.0, 1.0.1, 2.0.0].
    - google/auth[v1.10.0, ..., v1.15.2] require psr/cache ^1.0 -> satisfiable by psr/cache[1.0.0, 1.0.1].
    - You can only install one version of a package, so only one of these can be installed: psr/cache[1.0.0, 1.0.1, 2.0.0, 3.0.0].
    - symfony/cache-contracts v3.0.0 requires psr/cache ^3.0 -> satisfiable by psr/cache[3.0.0].
    - symfony/cache v6.0.2 requires symfony/cache-contracts ^1.1.7|^2|^3 -> satisfiable by symfony/cache-contracts[v3.0.0].
    - doctrine/doctrine-bundle 2.5.4 requires symfony/cache ^4.3.3|^5.0|^6.0 -> satisfiable by symfony/cache[v6.0.2].
    - doctrine/doctrine-bundle is locked to version 2.5.4 and an update of this package was not requested.
    - Root composer.json requires google/apiclient ^2.12 -> satisfiable by google/apiclient[v2.12.0, v2.12.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require google/apiclient:*" to figure out if any version is installable, or "composer require google/apiclient:^2.1" if you know which you need.
```

**Describe the solution you'd like**
Maybe could you please update google/auth so it's compatible with psr/cache v3.0?

 **Describe alternatives you've considered**
Currently, I have to use google/apiclient v1.1.9

Thanks!

**Comment by RuSS-B** [comment]
Upvote

**Comment by SirFaenor** [comment]
Upvote. In the meantime, unless v3 of symfony/cache-contracts is strictly required, you can downgrade both  symfony/cache-contracts and psr/cache to ^2. (symfony/cache v6.0.2 is compatible with symfony/cache-contracts v2)

**Comment by bshaffer** [comment]
Support for PSR cache 3.0 has been added in [google/auth v1.12.0](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.20.0), and is immediately compatible by this library.
