### ISSUE TITLE
Google Client class cannot create a default logger using Monolog

### ISSUE THREAD

**Issue by sashi-geeks** [googleapis/google-api-php-client#2196]
#### Environment details

  - OS: Linux
  - PHP version: 7.4
  - Package name and version: Google Api client Google\Client v2.12.11

#### Steps to reproduce

  1. When google Client class tries to build a Default Logger using method createDefaultLogger() at line 1124 the monolog StreamHandler class constructor cannot find expandIniShorthandBytes() in Monolog\Utils class.

Following is the stacktrace from 
Error: Call to undefined method Monolog\Utils::expandIniShorthandBytes() in /home/portalgeek/public_html/modules/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:58
Stack trace:
#0 /home/portalgeek/public_html/modules/vendor/google/apiclient/src/Client.php(1136): Monolog\Handler\StreamHandler->__construct('php://stderr', 250)
#1 /home/portalgeek/public_html/modules/vendor/google/apiclient/src/Client.php(1124): Google\Client->createDefaultLogger()
#2 /home/portalgeek/public_html/modules/vendor/google/apiclient/src/Service/Resource.php(162): Google\Client->getLogger()
#3 /home/portalgeek/public_html/modules/vendor/google/apiclient-services/src/Directory/Resource/Users.php(70): Google\Service\Resource->call('get', Array, 'Google\\Service\\...')
#4 /home/portalgeek/public_html/modules/addons/merlin_module/GClient2.php(65): Google\Service\Directory\Resource\Users->get(NULL)

There seems to be some lib conflict between Google and Monolog on expandIniShorthandBytes(). Did anyone have this same issue? I tried looking on the internet for something but no clues.

**Comment by sashi-geeks** [comment]
Does anyone have experienced such a thing?

**Comment by bshaffer** [comment]
This is not a method being called directly by our client libraries, so this seems to be an error in the `monolog` clients. I would suggest filing an issue over there, but [the function appears to be in the Utils class](https://github.com/Seldaek/monolog/blob/2.x/src/Monolog/Utils.php#L236), so my guess is this has already been resolved.
