### ISSUE TITLE
Some resources don't accomplish with PSR-4

### ISSUE THREAD

**Issue by juanparati** [googleapis/google-api-php-client#2201]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: `Debian GNU/Linux 10 (Linux homestead 4.19.0-18-arm64 #1 SMP Debian 4.19.208-1 (2021-09-29) aarch64` GNU/Linux)
  - PHP version: PHP 8.0.12 (cli) (built: Oct 22 2021 12:37:40) ( NTS )
  - Package name and version: google/apiclient 2.12.1

#### Steps to reproduce

  1. Create PSR-4 project
  2. composer require google/apiclient

#### Output

```
Class Google\Service\ArtifactRegistry\Resource\ProjectsLocationsRepositoriesGoogetartifacts located in ./vendor/google/apiclient-services/src/ArtifactRegistry/Resource/ProjectsLocationsRepositoriesGooGetArtifacts.php does not comply wi$h psr-4 autoloading standard. Skipping.
Class Google\Service\ArtifactRegistry\Resource\ProjectsLocationsRepositoriesAptartifacts located in ./vendor/google/a$iclient-services/src/ArtifactRegistry/Resource/ProjectsLocationsRepositoriesAptArtifacts.php does not comply with psr$4 autoloading standard. Skipping.
Class Google\Service\ArtifactRegistry\Resource\ProjectsLocationsRepositoriesYumartifacts located in ./vendor/google/a$iclient-services/src/ArtifactRegistry/Resource/ProjectsLocationsRepositoriesYumArtifacts.php does not comply with psr$4 autoloading standard. Skipping.
```

**Comment by matthewmnewman** [comment]
Can confirm this does not comply with PSR-4 👍🏻

**Comment by itsAnuga** [comment]
https://github.com/googleapis/google-api-php-client-services/issues/592

**Comment by dwsupplee** [comment]
I believe this was solved here: https://github.com/googleapis/google-api-php-client-services/pull/606 please let me know if you find otherwise, thanks!
