### ISSUE TITLE
Does this API support URLInspection from Google Search Console

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#2204]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
Support for URL Inspection.
https://developers.google.com/webmaster-tools/v1/api_reference_index#Inspection_tools

 **Describe the solution you'd like**
Need Support for URL Inspection under webmasters.php file.

 **Describe alternatives you've considered**
NA

 **Additional context**
NA

**Comment by dwsupplee** [comment]
Yes, it looks like we do: https://github.com/googleapis/google-api-php-client-services/blob/main/src/SearchConsole/Resource/UrlInspectionIndex.php#L40
