### ISSUE TITLE
Get custom event data

### ISSUE THREAD

**Issue by anthonythorne** [googleapis/google-api-php-client#2206]
Hi, 

First, I am unsure how to flag this as a question.

As for the question.

I currently use this library to get page view data, however now I have a more advanced use case where I need to get numbers/data from a custom event. My current use case, uses, `Google\Service\Analytics\Resource\DataGa::get`

By looking in GA, I know the event action and the event category, and the data I want can be easily seen in GA under the action and category.

Are there any examples to help demonstrate how I can pull custom event data using this library?

Thanks

Anthony

**Comment by anthonythorne** [comment]
For example the GA URL has some info that may help me construct the get request

```
analytics.eventAction:impression
analytics.eventCategory:Trending%20Articles%20Section
analytics.eventLabel:watch-can-you-conquer-this-90s-pop-culture-trivia (this is subject to change based on the article)
```

**Comment by LindaLawton** [comment]
The library for the [Google analytics data api ](https://developers.google.com/analytics/devguides/reporting/data/v1) is [php-analytics-data](https://github.com/googleapis/php-analytics-data)

This is the wrong repo.

**Comment by saranshdhingra** [comment]
Thanks @LindaLawton 
I'll be closing this now.
