### ISSUE TITLE
dependencies crash guzzlehttp/guzzle

### ISSUE THREAD

**Issue by frozt86** [googleapis/google-api-php-client#2208]
your package dependecies crash. i'm currently using laravel 8 

- irazasyed/telegram-bot-sdk v2.0.0 requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1)

thanks.

**Comment by dmitryuk** [comment]
You have set `guzzlehttp/guzzle`: "^7.0.1"  in your composer.json, but `irazasyed/telegram-bot-sdk` requires guzzle "~6.0". 

So you need to require the latest version of `irazasyed/telegram-bot-sdk` (^v3.4), that supports guzzle 7. And look deeper for major version changes.

**Comment by bshaffer** [comment]
This is not an issue with our library, but with a dependency.
