### ISSUE TITLE
Voided Purchases API BUG returning blank 

### ISSUE THREAD

**Issue by alexvibealex** [googleapis/google-api-php-client#2211]
Hi we are trying to get the voidedpurchases using php sdk : 

#### Environment details

  - MAcOS:
  - php version : 8.0.3:
  - package name : com.wplms.io

#### Steps to reproduce

  1. ran the below code 
  2. only gets this response no voided purchase : 
`
Google\Service\AndroidPublisher\VoidedPurchasesListResponse Object
(
    [collection_key:protected] => voidedPurchases
    [pageInfoType:protected] => Google\Service\AndroidPublisher\PageInfo
    [pageInfoDataType:protected] => 
    [tokenPaginationType:protected] => Google\Service\AndroidPublisher\TokenPagination
    [tokenPaginationDataType:protected] => 
    [voidedPurchasesType:protected] => Google\Service\AndroidPublisher\VoidedPurchase
    [voidedPurchasesDataType:protected] => array
    [internal_gapi_mappings:protected] => Array
        (
        )

    [modelData:protected] => Array
        (
        )

    [processed:protected] => Array
        (
        )

)
`
THIS IS THE CODE WE ARE RUNNING : 

``$client = new \Google\Client();
  $client->setAuthConfig($creds);
  $client->addScope("https://www.googleapis.com/auth/androidpublisher");
  if ($client->isAccessTokenExpired()) {
      $client->fetchAccessTokenWithAssertion();
  }

  if ($client->getAccessToken()) {
      $service = new \Google\Service\AndroidPublisher($client);
      $results = $service->purchases_voidedpurchases->listPurchasesVoidedpurchases('com.wplms.io', []);
      print_r($results);die(); //GETTING ABOVE RESPONSE HERE
     
  }else{
      return false;
  }``

Obviously there are many refunded and cancelled orders : https://prnt.sc/26tr872
Thanks!

**Comment by greezen** [comment]
hello,I have the same problem,do you solved it

**Comment by greezen** [comment]
I am find the question, refund must check revoke, if not checked it , the order not show in voidedpurchases

**Comment by alexvibealex** [comment]
Hi thanks for replying , can you please share what exactly do you mean by " refund must check revoke "?

**Comment by greezen** [comment]
1. api refund https://developers.google.com/android-publisher/api-ref/rest/v3/orders/refund
you must set revoke=true
2. google console refund,must check the item
![image](https://user-images.githubusercontent.com/6023468/160050897-aacf615b-e4cb-4034-8439-d3c099925f65.png)

**Comment by bshaffer** [comment]
thank you for your responses, sounds like there's nothing more to do on this issue.
