### ISSUE TITLE
cURL error 28: Failed to connect to oauth2.googleapis.com port 443: Timed out

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [googleapis/google-api-php-client#2212]
When I m using [goo](https://github.com/googleapis/google-api-php-client), it worked fine, But now I m getting this issue

cURL error 28: Failed to connect to oauth2.googleapis.com port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token

**Comment by bshaffer** [comment]
This appears to be a networking issue on your end, as that API serves all of google authentication, and its uptime is very solid.

**Comment by wenshan** [comment]
I have the same problem。

**Comment by hcweb** [comment]
I have the same problem
