### ISSUE TITLE
PERMISSION_DENIED -> SERVICE_DISABLED to get all reviews of Google My Business Information

### ISSUE THREAD

**Issue by luanhduarte** [googleapis/google-api-php-client#2215]
I'm trying to get all reviews of an account at GMB (Google My Business Information) and i'm getting an error of permission_denied and service_disabled... but, im my project in Google Console, the services at GMB are enabled...

my code:

$access_token = $token["access_token"]; 
$request_uri = "https://mybusiness.googleapis.com/v4/$name/locations:batchGetReviews?access_token=" . $access_token; 

$curinit = curl_init($request_uri);
curl_setopt($curinit, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curinit, CURLOPT_CUSTOMREQUEST, 'GET'); 
curl_setopt($curinit, CURLOPT_RETURNTRANSFER, true);

$json = curl_exec($curinit);
$phpObj = json_decode($json, true);
var_dump($json);

My Answer:

string(1045) "{ "error": { "code": 403, "message": "Google My Business API has not been used in project 83172312488 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mybusiness.googleapis.com/overview?project=83172312488 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "status": "PERMISSION_DENIED", "details": [ { "@type": "type.googleapis.com/google.rpc.Help", "links": [ { "description": "Google developers console API activation", "url": "https://console.developers.google.com/apis/api/mybusiness.googleapis.com/overview?project=83172312488" } ] }, { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "reason": "SERVICE_DISABLED", "domain": "googleapis.com", "metadata": { "service": "mybusiness.googleapis.com", "consumer": "projects/83172312488" } } ] } } "

OBS: THIS IS NOT MY PROJECT ID.... "projects/83172312488" is not my project... my correct project id is "gmail-123XXX"

i'm using PHP library of GMB.. 

OBS2: the library of GMB to PHP, there isn't resources to get reviews...

Can you help me, guys?

**Comment by bshaffer** [comment]
You need to enable the "Google My Business" API by going to the URL provided in the error message. Your project ID may be `gmail-123XXX`, but your project NUMBER is `83172312488`. And if THAT isn't correct, then you've configured the wrong project ID somehow.

**Comment by loveheenavasu** [comment]
Hi I am also facing the same issue and checked my configuration but can you please help with more elaborate steps.
getting this error
 "Google My Business API has not been used in project 407408718192 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mybusiness.googleapis.com/overview?project=407408718192 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 when trying to get all the reviews for my business account 
 And this is not my project number checked in my google console

**Comment by jan-grosser** [comment]
For everyone else getting this issue: Your are probably using the [Google Developer OAuth Playground](https://developers.google.com/oauthplayground/), which has the project id **407408718192**. You cannot use the oauth token generated by the playground, but need to use an access token generated using your projects credentials instead.

**Comment by Chetan-bhagat98** [comment]
You need to fill the https://docs.google.com/forms/d/e/1FAIpQLSdoCw8P5JJsJ-taCH2i8w8B69sGsZfoRhacQOe7FTWArWZ-SQ/viewform to get the access to the reviews
