### ISSUE TITLE
API stucks at fetchAccessTokenWithAuthCode()

### ISSUE THREAD

**Issue by ehsanquddusi** [googleapis/google-api-php-client#2216]
#### Environment details

  - OS: Ubuntu 20
  - PHP version: 7.3.33
  - Package name and version: api-client v2.12.1 / 2.10.0 / 2.9.2

#### Steps to reproduce

After redirection to `callback url` with `auth code` from google, I am trying to fetch the access token using auth code by calling `fetchAccessTokenWithAuthCode('auth code')` but it gets stuck and nothing comes after. It basically returns a request `timeout` as no response is returned from Google even after 05 minutes.

#### Code example

```php
$client = new Google\Client;
$client->setApplicationName("CM");
$client->setScopes(Google_Service_Sheets::SPREADSHEETS_READONLY);
$client->setAuthConfig('client_secret.json');
if ($_GET['code']) {
    $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
    $client->setAccessToken($token);
    // Check to see if there was an error.
    if (array_key_exists('error', $token)) {
        throw new Exception(join(', ', $token));
    }
}
```
Thanks!

**Comment by nikolinmajmari** [comment]
I have the same problem also. Sometimes the google api responds with the access token and sometimes no. A friend of mine that is using HWIoauth-bundle for symfony does not have any problem with it.

**Comment by nikolinmajmari** [comment]
This is the error that apears on the console after not taking the access token from google after a long time. 
http: TLS handshake error from 127.0.0.1:49912: EOF

**Comment by bshaffer** [comment]
It sounds like the error you're receiving was caused by the API endpoint and there's nothing this library can do about it.
