### ISSUE TITLE
Google Social Login requires 8.0.2 with composer dependencies.

### ISSUE THREAD

**Issue by wparslan** [googleapis/google-api-php-client#2220]
Hi Everyone,
So I ran the composer and got the files set up my social application and received an error message that my PHP version is lower than 8.0.2 while it should be above.
I tried to overcome it by changing its condition of it which be found in SDK/google-client/vendor/composer/platform_check.php
However, then I got the error of a function being used that only came with PHP 8.0 **stringables** which is used in the PSR 
![image](https://user-images.githubusercontent.com/66727492/156868517-171480da-7222-445b-9ee2-7df139d994a3.png)

Any insights on this?

**Comment by mfn** [comment]
Maybe your PHP version on the command line is different from the web server, I've seen this a lot. People then install it with a higher version on CLI but run in an older version in apache/nginx and 💥

**Comment by wparslan** [comment]
My PHP version is 8.0.15 and the same is on my CLI.

**Comment by bshaffer** [comment]
This appears to be an issue with the PHP version on your server. The error message indicates it isn't understanding the union types which were added in PHP 8.0 (you can see [the line in question](https://github.com/php-fig/log/blob/master/src/LoggerInterface.php#L30) is using Union Types).

This is definitely not an issue with this library, so I'm closing this.

**Comment by wparslan** [comment]
@bshaffer I was using PHP 8.0 on my server and used Google Social Login service when it gave me this error.
What should be the PHP version for this in order for it to work?

**Comment by bshaffer** [comment]
PHP 8 and above are the correct versions, but the error you've provided indicates you are not using PHP 8.
