### ISSUE TITLE
Following install without composer directions - Fatal error: require(): /google-api-php-client/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php'

### ISSUE THREAD

**Issue by Morgscode** [googleapis/google-api-php-client#2224]
I'm following the 'install without composer instructions and have downloaded both v2.12.1 AND v 2.12.0

https://github.com/googleapis/google-api-php-client/releases

it seems the dependancies are not shipped with the package. 

Warning: require(/Applications/MAMP/htdocs/fuzion4-wp-site/wp-content/themes/fuzion4/inc/google-api-php-client/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/fuzion4-wp-site/wp-content/themes/fuzion4/inc/google-api-php-client/vendor/composer/autoload_real.php on line 71

Fatal error: require(): Failed opening required '/Applications/MAMP/htdocs/fuzion4-wp-site/wp-content/themes/fuzion4/inc/google-api-php-client/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.12/lib/php') in /Applications/MAMP/htdocs/fuzion4-wp-site/wp-content/themes/fuzion4/inc/google-api-php-client/vendor/composer/autoload_real.php on line 71

**Comment by appimatic** [comment]
I don't like composer in dev or production environments either.

my suggestion: spin up a virtual machine, install composer, install your
dependency using composer, copy the directory contents from the composer
dependency installation, restore that directory to your non-composer
environment, point the require statement to the copied autoload.php
dependency file in the copied dependency directory

**Comment by bshaffer** [comment]
I downloaded PHP 7.4 for the latest release and was able to verify the file `vendor/ralouphie/getallheaders/src/getallheaders.php` exists. I think the issue you are encountering is probably an issue with your environment and potentially the server's ability to read and write files.
