### ISSUE TITLE
Revoke One Tap ID token?

### ISSUE THREAD

**Issue by Sir-Will** [googleapis/google-api-php-client#2226]
Hello,

is it not possible to revoke the ID token provided by Google One Tap via PHP?
The only option I could find is via JavaScript (https://developers.google.com/identity/gsi/web/guides/revoke) but this would require the user to visit the site.

Deleting the user without revoking the token would cause the user to get automatically registered again with auto select enabled.

**Comment by bshaffer** [comment]
We do not support revoking ID tokens in this client library, only refresh tokens and access tokens. I do not think any of our client libraries support this (I cannot find any documentation for how this is done).

Debugging the javascript revoke HTTP request, it seems like you may be able to make a POST to https://accounts.google.com/gsi/revoke, and populate the form parameters `client_id`, `hint` (which is "the email address or unique ID of the user's Google Account" see [here](https://developers.google.com/identity/gsi/web/reference/js-reference#google.accounts.id.revoke)), and `as` (which, your guess is as good as mine there).
