### ISSUE TITLE
[JavaScript API] One Tap - No cancel cookie being set for native Credential Management API

### ISSUE THREAD

**Issue by Sir-Will** [googleapis/google-api-php-client#2229]
The issue involves the JavaScript One Tap API, located at https://accounts.google.com/gsi/client
Unfortunately, I couldn't find the right place to report this bug. If there is a better place to report this, then please let me know.

When the One Tap prompt is being closed by the user, the `g_state` cookie is being set/updated to remember the decision.

When the native login prompt from the Credential Management API is being closed/canceled by the user, there is no cookie being set, resulting in it showing the prompt on every page load.

The JavaScript client should also set and check the `g_state` cookie when the native prompt is canceled.

#### Steps to reproduce

  1. Add the HTML code to a website
  2. Add credentials to the Chrome credential manager
  3. Open the site and click on cancel in the "login as" prompt
  4. Reload the page

#### Code example

```html
<script src="https://accounts.google.com/gsi/client"></script>
<div id="g_id_onload"
      data-client_id="..."
      data-login_uri="..."
      data-native_login_uri="..."
      data-auto_select="true"
      data-cancel_on_tap_outside="false"
      data-prompt_parent_id="g_id_onload"
</div>
```

**Comment by bshaffer** [comment]
This repository is for the PHP client library. Please file this issue in the repo for the JavaScript client library here: https://github.com/google/google-api-javascript-client

**Comment by Sir-Will** [comment]
Thank you, even through I searched through all google repos, I couldn't find your linked repo for some reason.
