### ISSUE TITLE
Request: New Version Tag to support URL Inspection API

### ISSUE THREAD

**Issue by nitishsurana** [googleapis/google-api-php-client#2232]
I am trying to use the URL Inspection API via the the PHP client, but the latest tag does not have the support for it. On digging deeper, it looks like the support for it was added last month, but a new tag was not created to facilitate download of the latest version. Is it possible to create a new tag so that we can download the latest version of the client and use it via composer?

**Comment by bshaffer** [comment]
We have a latest release of the services library (`google/apiclient-services`) from 3 days ago: https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.240.0

It looks like the API you want is in there: https://github.com/googleapis/google-api-php-client-services/blob/v0.240.0/src/SearchConsole/Resource/UrlInspectionIndex.php

Just run `composer update` and you'll get the latest version of the downstream generated client services (`google/apiclient-services`)
