### ISSUE TITLE
Unsupported Output Format when trying to download any Caption

### ISSUE THREAD

**Issue by rubobaquero** [googleapis/google-api-php-client#2239]
#### Environment details
  - OS: MAC OSX Catalina 10.15.6
  - PHP version: 8.1.0
  - Package name and version: google/apiclient  v2.12.2

#### Steps to reproduce

  1. Ask user for https://www.googleapis.com/auth/youtubepartner permission
  2. Obtain list of owned channels using https://developers.google.com/youtube/v3/docs/channels/list?part=contentDetails&mine=true and get the uploads playlistId from relatedPlaylists
  3. Obtain uploads videos list using https://developers.google.com/youtube/v3/docs/playlistItems/list?part=contentDetails,snippet&playlistId=XXXXXXX
  4. For any of the videos, list the captions and obtain the id of any of them using https://developers.google.com/youtube/v3/docs/captions/list?part=id,snippet&videoId=XXXXXXX
  5. Try to download it using https://developers.google.com/youtube/v3/docs/captions/download endpoint, either passing tfmt parameter or not.

#### Code example

```php
// Setup client
$client = new Google_Client();
$client->setScopes([
    "https://www.googleapis.com/auth/youtubepartner",
]);
$client->setAccessType('offline');
$client->setAuthConfig('XXXXXXXXX');
$client->setRedirectUri("http://localhost:8080");

// Load access token from file
$accessToken = json_decode(file_get_contents($tokenFile), true);
$client->setAccessToken($accessToken);

// Refresh the token if it's expired.
if ($client->isAccessTokenExpired()) {
    $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
    file_put_contents($tokenFile, json_encode($client->getAccessToken()));
}

// Try to download first caption file from last video uploaded to the channel
$youtube = new Google_Service_YouTube($client);
$channel = $youtube->channels->listChannels('contentDetails', array('mine' => true))[0];
$uploadsList = $channel->getContentDetails()->getRelatedPlaylists()->uploads;
$video = $youtube->playlistItems->listPlaylistItems('contentDetails,snippet', ['playlistId' => $uploadsList])[0];
$caption = $youtube->captions->listCaptions('id,snippet', $video->getSnippet()->getResourceId()->videoId)[0];

// This fails whatever the caption and video I try to download, even when setting the parameter tfmt using any of the valid values
$youtube->captions->download($caption->id);
```

#### Response

```
Fatal error: Uncaught Google\Service\Exception: {
  "error": {
    "code": 400,
    "message": "Unsupported Output Format",
    "errors": [
      {
        "message": "Unsupported Output Format",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

Thanks in advance!

**Comment by bshaffer** [comment]
This seems like a question with how to use an API, and not a bug in this library. 

Have you tried setting the format via the `optParams` array?

https://github.com/googleapis/google-api-php-client-services/blob/main/src/YouTube/Resource/Captions.php#L77

```php
$youtube->captions->download($caption->id, [
    'tfmt' => 'vtt'
]);
```
