### ISSUE TITLE
Invalid argument supplied for foreach() in firebase/php-jwt/src/JWT.php:422

### ISSUE THREAD

**Issue by bstanleynep** [googleapis/google-api-php-client#2243]
Pull request https://github.com/googleapis/google-api-php-client/pull/2235 updated this package's `composer.json` file to allow `firebase/php-jwt` v6.

`firebase/php-jwt` v6 changed the method signatures for both `JWT::encode()` and `JWT::decode()`. It seems that the calls in this library to this method were not updated accordingly.

From the [firebase/php-jwt change log](https://github.com/firebase/php-jwt/releases/tag/v6.0.0)

> The second argument of JWT::decode now must be Firebase\JWT\Key or array<string, Firebase\JWT\Key> (see https://github.com/firebase/php-jwt/pull/376)
> JWT::encode requires third argument $alg (see https://github.com/firebase/php-jwt/pull/376)

The offending decode call is in `src/AccessToken/Verify.php(106): Firebase\\JWT\\JWT::decode()`

I will follow up this issue with a PR.

#### Environment details

  - OS: Ubuntu 20.04
  - PHP version: 7.4.28
  - Package name and version: 2.12.2

**Comment by alansory** [comment]
please review this pr

**Comment by goyavo** [comment]
+1 - please merge

**Comment by slaci** [comment]
Seems like `composer require firebase/php-jwt:^5.5.1` "fixes" this critical bug meanwhile.

**Comment by bshaffer** [comment]
Fixed in [v2.12.3](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.3)
