### ISSUE TITLE
PHP 7.4.1 PSR Syntax Error

### ISSUE THREAD

**Issue by sharukhkhanajm** [googleapis/google-api-php-client#2246]
#### Environment details

  - OS: macOS Big Sur
  - PHP version:  7.4.1
  - Package name and version:  google/apiclient: ^2.12.3

Whenever I switch the PHP version to 7.4.1 I get this error 

`Parse error: syntax error, unexpected 'static' (T_STATIC) in /Users/webtechstreet4/Local Sites/fvtest/app/public/wp-content/plugins/form-vibes-pro/vendor/psr/cache/src/CacheItemInterface.php on line 75`

The library works great on PHP 8 but gives the above error when switching to PHP 7.

Screenshot
![image](https://user-images.githubusercontent.com/47321682/164206749-7237e1f6-2dfb-4c07-973f-fc3b45012c79.png)

**Comment by bshaffer** [comment]
Did you run `composer update` on PHP 8 and then switch to PHP 7.4? The error you're getting is in a dependency, and if you install the package via composer, or using one of our pre-packaged [releases](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.4) for your appropriate PHP version, you will not get this error.

**Comment by sharukhkhanajm** [comment]
@bshaffer I am using this library for WordPress plugin. 
Say if I shipped my WP plugin with PHP 8 or 7, so in that case the end users may have different PHP version on their website.
so, in that case it will still throw this error on PHP 7 or below.

**Comment by bshaffer** [comment]
If that's the case then you'll want to ship your library for the lowest compatible php version.

**Comment by sharukhkhanajm** [comment]
@bshaffer thanks for the quick response.
Is there any method or command which I can use in order to install PHP 7 compatible client library?
And if I have to download and put it manually then how would I strip out the other library which I am not using from this client library?

My current `composer.json` file look something like this.

    {
    	"config": {
    		"platform-check": false
    	},
    	"require": {
    		"nesbot/carbon": "^1.39.1",
    		"firebase/php-jwt": "^5.4",
    		"google/apiclient": "^2.12.3"
    	},
    	"autoload": {
    		"classmap": [
    			"inc/"
    		],
    		"exclude-from-classmap": [
    			"inc/bootstrap.php"
    		]
    	},
    	"scripts": {
            "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
        },
        "extra": {
            "google/apiclient-services": [
                "Drive",
    	        "Sheets"
            ]
        }
    }

**Comment by bshaffer** [comment]
Our release page has [packages for PHP 7.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.4) with prebuilt dependencies for that version. However, that's not the recommended approach. The recommended approach would be to run `composer install` locally with the version of PHP you want to support. But I'm not as sure what it is the WordPress community would do in a situation like this, so you'd be better off asking in one of their forums.

**Comment by sharukhkhanajm** [comment]
@bshaffer Thank you for your time and quick response. I really appreciate it.
Actually, I sorted it out by changing the system PHP version and running `composer update`.
I thought I needed to change the site PHP version but it was actually the system PHP version.
Thanks again :)
