### ISSUE TITLE
NULL Values are unreadable in spreadsheet_values->append()

### ISSUE THREAD

**Issue by MegaSpaceHamlet** [googleapis/google-api-php-client#2260]
When writing rows to a Google Sheets using the api, the documentation specifies that by passing NULL values, the API will pass over the value. In practice however, the code throws the following error:

`Uncaught Google_Service_Exception: { "error": { "code": 400, "message": "Invalid JSON payload received.`

#### Environment details

  - OS: Windows 10
  - PHP version: 7.3.33
  - Package name and version: google/apiclient 2.0

#### Steps to reproduce

  1. Create a row e.g [ 'Value', NULL, 9 ]
  2. Form ValueRange and other data as specified in documentation
  3. Call `$service->spreadsheets_values->append(.....);

#### Code example

```
$values = [
    ['Values', NULL, 9]
];
		$body = new Google_Service_Sheets_ValueRange([
			'values' => $values,
			'majorDimension' =>  'ROWS'
		]);
		$params = [
			'valueInputOption' => 'USER_ENTERED',
			'insertDataOption' => 'INSERT_ROWS' 
                ];
		$range = 'Sheet1!A:C';
		$result = $service->spreadsheets_values->append(SPREADSHEET_ID, $range, $body, $params );
```

To note, when using the Google Sheets API in JavaScript, passing in a NULL value processes with no error.

**Comment by bshaffer** [comment]
Hello @MegaSpaceHamlet 
Try using `Google\Model::NULL_VALUE` as defined in the README under ["How do I set a field to null"](https://github.com/googleapis/google-api-php-client#how-do-i-set-a-field-to-null):

```php
$values = [
    ['Values', Google\Model::NULL_VALUE, 9]
];
```
