### ISSUE TITLE
Add new AndroidPublisher API

### ISSUE THREAD

**Issue by leearmstrong** [googleapis/google-api-php-client#2262]
I can see that the services repo was updated to include [this](https://github.com/googleapis/google-api-php-client-services/pull/1028)

How can I get the google-api-php-client to use this?

**Comment by bshaffer** [comment]
Run `composer update` and ensure you have at least [v0.249.0](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.249.0) of `google/apiclient-services` and you will be able to access the AndroidPublisher API

**Comment by bshaffer** [comment]
For future reference, releases are automatically created every week on Monday for the `google/apiclient-services` repo
