### ISSUE TITLE
Access token being returned contains a lot of dots/periods/fullstops 

### ISSUE THREAD

**Issue by codinglife456** [googleapis/google-api-php-client#2265]
I am trying to get OAuth 2.0 token by using google-api-php-client library however the access token being returned is filled with periods.

**Example of results obtained**
{"access_token":"ya29.*.b*************r1FYWFz***CCg3v8VYHTlu*******************hiMIDhSX******6UfwvazfOcuV***********ewuo-c87WgM-ir
S5unipu0goCl3RtC_0g7hkjqNwQ2pcZjmJCZIr7JM5VwD4........................................................................................................................................................................................
......................................................................................................................................................................................................................................
......................................................................................................................................................................................................................................
....................................................................................................................................................","expires_in":3599,"token_type":"Bearer","created":1652776589}

**Code used**
 ```
      $credentialsFilePath = (__DIR__ . '/service-account-key.json'); //replace this with your actual path and file name
        $client = new \Google_Client();
        $client->setAuthConfig($credentialsFilePath);
        $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
        $client->refreshTokenWithAssertion();
        $token = $client->getAccessToken();
        error_log($token['access_token']);
        return $token['access_token'];
```

#### Environment details

  - OS: windows
  - PHP version: 7.4.25
  - Package name and version: latest version

#### Steps to reproduce

  1. Download service account json from firebase console
  2. Put service account json into php project
  3. Use google api php client to obtain token 

#### Code example

php laravel

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bshaffer** [comment]
These dots are placeholders to pad the tokens because Google will be increasing the token size (see https://github.com/oauth2-proxy/oauth2-proxy/issues/1218):

> On August 23, 2021, we will roll out security and reliability improvements that will increase the sizes of OAuth 2.0 access tokens for all projects.

The padding does not affect the verification of the token (e.g. you can remove them), but it's recommended not to, so that you can verify your application will work when the token size increases. From the linked issue: 

> We strongly recommend that you use the documented token size limits of 2048 bytes and to remove any logic in your services/code that restricts its ability to process access tokens of certain sizes.
