### ISSUE TITLE
How to obtain the refreshToken?

### ISSUE THREAD

**Issue by VapiSoft** [googleapis/google-api-php-client#2273]
The new Client() third parameter is: refreshToken 
My app is an application for teachers, and I want the app to connect to the teacher's classroom (in his account).
Is it possible?
How do I do it?

**Comment by bshaffer** [comment]
See the [examples README](https://github.com/googleapis/google-api-php-client/tree/main/examples) for running the examples. It sounds like you want 3-legged authentication, which can be found in [`simple-file-upload.php`](https://github.com/googleapis/google-api-php-client/blob/main/examples/simple-file-upload.php)
