### ISSUE TITLE
Got same 'nextPageToken' on each iteration | MyBusiness API v4

### ISSUE THREAD

**Issue by YevhenKovalevskyi** [googleapis/google-api-php-client#2280]
I'm trying to get all OWNER images from a location(it's still only on v4):

![Screenshot_1](https://user-images.githubusercontent.com/39699067/173869216-58d4492d-f43c-4979-9edb-3e18bd1dd4d3.png)

Location has 1000+ owner images and what is strange - I'm getting **same** nextPageToken and correspondingly **same** content on each page iteration.

![Screenshot_2](https://user-images.githubusercontent.com/39699067/173872882-2993b2f0-5d9c-430f-9b6e-7c1dc5371b9f.png)

What am I doing wrong?

P.S.: I have such situation only with media.

Thanks.

Upd.: I received the same **nextPageToken** (literally) at other locations.

**Comment by YevhenKovalevskyi** [comment]
solved

**Comment by YevhenKovalevskyi** [comment]
solved

**Comment by bogdanGR** [comment]
@YevhenKovalevskyi how did you solve this issue?
