### ISSUE TITLE
generated shared link | Permission

### ISSUE THREAD

**Issue by McCdama** [googleapis/google-api-php-client#2283]
When I grant permission to a (non-Google domain) email, a notification email is fired off and sent to the user.
This email contains a link to access the document that is unique to that user and different from the webview link.
Is there any way to get this (generated) link

![Permission](https://user-images.githubusercontent.com/44600908/174282576-9e3310ec-3747-4ff8-8365-50209c548560.jpg)
.

**Comment by bshaffer** [comment]
This repository is for questions related to the Google Client Libraries for PHP only. This question is off-topic.

However, I'll try to answer your question. If you go to the spreadsheet and click the "Share" button at the top right, there's a "Copy Link" button in the bottom left, which should give you the same link, which you can share with anyone.
<img width="495" alt="Screen Shot 2022-06-17 at 12 04 16 PM" src="https://user-images.githubusercontent.com/103941/174387139-20dea100-8ad2-43ea-a62d-cf4f88529a55.png">

As for a specific link generated for inviting someone, there's no way that I am aware of to capture that invite link.

**Comment by McCdama** [comment]
Well, thank you for replying. I should've be more specific.
Actually I'm working with 'google-api-php-client-services' in Php. 
I'll rephrase and open up a new issue there.
