### ISSUE TITLE
bidmanager query comes without googleCloudStoragePathForLatestReport

### ISSUE THREAD

**Issue by farrusete** [googleapis/google-api-php-client#2284]
Hi,

Since last friday (2022-06-17) request to Google_Service_DoubleClickBidManager on queries->get(queryId) returns metadata without the  googleCloudStoragePathForLatestReport field.

Was it removed from the response?

Thank you in advance,

**Comment by bshaffer** [comment]
Hello! It looks like you're trying to call the now-unavailable [DisplayAndVideo 360 API](https://developers.google.com/bid-manager/v1/queries). The services in this library call V2 of Bid Manager. Reading the [the API documentation](https://developers.google.com/bid-manager/reference/rest/v2/queries/get), you can see that [QueryMetadata](https://developers.google.com/bid-manager/reference/rest/v2/queries#QueryMetadata) does not include the field you've mentioned.
