### ISSUE TITLE
How to insert featured comments with Youtube API

### ISSUE THREAD

**Issue by mvneobux** [googleapis/google-api-php-client#2285]
I've searched and posted this question on other forums, but I didn't get an answer. Hope someone here has worked with the youtube API and can help me...

I'm inserting videos on youtube using API in PHP version. But I'm not able to include a highlight comment in the videos. In the youtube documentation the example is in json , and as I'm doing it in php it just doesn't work.

See part of my code is like this:

```
// Create a snippet with title, description, tags and category ID
    // Create an asset resource and set its snippet metadata and type.
    // This example sets the video's title, description, keyword tags, and
    // video category.
    $snippet = new Google_Service_YouTube_VideoSnippet();

    $snippet->setTitle("Cats are cute #".$filme['Data ID']);


    $snippet->setDescription($filme['titulo']);

    $snippet->setTags('cats','cutecats','cute');

    

    // Numeric video category. See
    // https://developers.google.com/youtube/v3/docs/videoCategories/list
    $snippet->setCategoryId("19");

    // Set the video's status to "public". Valid statuses are "public",
    // "private" and "unlisted".
    $status = new Google_Service_YouTube_VideoStatus();
    $status->privacyStatus = "public";

    // Associate the snippet and status objects with a new video resource.
    $video = new Google_Service_YouTube_Video();
    $video->setSnippet($snippet);
    $video->setStatus($status);
```

And the youtube suggestion to include comments using the API is this:

```
{
  "snippet": {
   "channelId": "UC_x5XG1OV2P6uZZ5FSM9Ttw",
   "topLevelComment": {
    "snippet": {
      "textOriginal": "This video is awesome!"
    }
   },
   "videoId": "MILSirUni5E"
  }
 }
```

I tried like this and it didn't work: $snippet->textOriginal('My comment');

How can I submit a featured comment using youtube API in php?

**Comment by bshaffer** [comment]
Hello there!
 
Unfortunately, I don't know much about the YouTube API, and I imagine you're much more knowledgeable. However, looking at the JSON, I think you are using the incorrect Snippet object, and you want to do something like this: 

```php
$commentSnippet = new Google_Service_YouTube_CommentSnippet();
$commentSnippet->setTextOriginal('This video is awesome');

$threadSnippet = new Google_Service_YouTube_CommentThreadSnippet();
$threadSnippet->setChannelId('UC_x5XG1OV2P6uZZ5FSM9Ttw');
$threadSnippet->setVideoId('MILSirUni5E');
$threadSnippet->setTopLevelComment($commentSnippet);
```

Now, how you get from there to the video, or if what you're trying to do is even possible, I cannot possibly say. Good luck!

**Comment by mvneobux** [comment]
> Hello there!
> 
> Unfortunately, I don't know much about the YouTube API, and I imagine you're much more knowledgeable. However, looking at the JSON, I think you are using the incorrect Snippet object, and you want to do something like this:
> 
> ```
> $commentSnippet = new Google_Service_YouTube_CommentSnippet();
> $commentSnippet->setTextOriginal('This video is awesome');
> 
> $threadSnippet = new Google_Service_YouTube_CommentThreadSnippet();
> $threadSnippet->setChannelId('UC_x5XG1OV2P6uZZ5FSM9Ttw');
> $threadSnippet->setVideoId('MILSirUni5E');
> $threadSnippet->setTopLevelComment($commentSnippet);
> ```
> 
> Now, how you get from there to the video, or if what you're trying to do is even possible, I cannot possibly say. Good luck!

Very very thankss :))))))))

**Comment by mvneobux** [comment]
I found this solution and it seems to work:

`$commentSnippet = new Google_Service_YouTube_CommentSnippet();
    $commentSnippet->setTextOriginal('TESTE');
    $topLevelComment = new Google_Service_YouTube_Comment();
    $topLevelComment->setSnippet($commentSnippet);
    $commentThreadSnippet = new Google_Service_YouTube_CommentThreadSnippet();
    $commentThreadSnippet->setTopLevelComment($topLevelComment);
    $commentThread = new Google_Service_YouTube_CommentThread();
    $commentThread->setSnippet($commentThreadSnippet);
    $commentThreadSnippet->setVideoId($videoId);
    $videoCommentInsertResponse = $youtube->commentThreads->insert('snippet', $commentThread);`

But it asks for ssl scope, which I requested from google on the api scopes configuration screen. It takes up to 2 months for him to approve

**Comment by mvneobux** [comment]
I found this solution and it seems to work:

`$commentSnippet = new Google_Service_YouTube_CommentSnippet();
    $commentSnippet->setTextOriginal('TESTE');
    $topLevelComment = new Google_Service_YouTube_Comment();
    $topLevelComment->setSnippet($commentSnippet);
    $commentThreadSnippet = new Google_Service_YouTube_CommentThreadSnippet();
    $commentThreadSnippet->setTopLevelComment($topLevelComment);
    $commentThread = new Google_Service_YouTube_CommentThread();
    $commentThread->setSnippet($commentThreadSnippet);
    $commentThreadSnippet->setVideoId($videoId);
    $videoCommentInsertResponse = $youtube->commentThreads->insert('snippet', $commentThread);`

But it asks for ssl scope, which I requested from google on the api scopes configuration screen. It takes up to 2 months for him to approve

**Comment by bshaffer** [comment]
Glad you figured it out! I'm not sure what you mean by approving scopes, but what you have there looks correct. Nice job.

**Comment by mvneobux** [comment]
https://developers.google.com/youtube/v3/docs/comments/insert

necessary scope: https://www.googleapis.com/auth/youtube.force-ssl

In case anyone needs it, they have to enter the Oauth settings of the api to edit, there will be a screen to add scopes, so just put this scope url and wait for approval.
