### ISSUE TITLE
No-body request to YT api fails with supplied content-type header

### ISSUE THREAD

**Issue by kkopachev** [googleapis/google-api-php-client#2287]
I am trying to download YT captions for a given video. 

```php
$client = // client is configured with service account credentials or oauth2 token.
$response = (new Google_Service_YouTube($client))->captions->download($caption['id'])->getBody();
```

However this throws exception and YT response looks like this:
```
{
  "error": {
    "code": 400,
    "message": "Unsupported Output Format",
    "errors": [
      {
        "message": "Unsupported Output Format",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```
I traced issue down to this line https://github.com/googleapis/google-api-php-client/blob/1530583a711f4414407112c4068464bcbace1c71/src/Service/Resource.php#L206 
Apparently, setting `content-type` header makes YT api break.

I'd suggest adding this header conditionally as it seems like [that was the case](https://github.com/googleapis/google-api-php-client/commit/6dc8190553988377554d54048bd086b89c57a37b#diff-c42742883e8032aa0b5735c831478483a43d7ad2a2a8e3fa32b188ca4ec579d8L203) before upgrading to Guzzle6

**Comment by bshaffer** [comment]
Hi @kkopachev! Thanks for reporting this!
I don't see any evidence in the PR you provided that the `Content-Type: application/json` header used to be conditional. I see that the request used to set the `json` option (which no longer exists in Guzzle), which under the hood would set the content type. That is now done explicitly. 

One thing you could try is to get the Guzzle Request object from the Google Client by setting `defer` to `true`, and then update the request by removing the content type:

```php
$client = // client is configured with service account credentials or oauth2 token.

// set "defer" to true so the Guzzle Request object is returned instead of executing the request
$client->setDefer(true);

// this will be a Guzzle Request object
$request = (new Google_Service_YouTube($client))->captions->download($caption['id']);

// remove the content type header from the request
$request = $request->withoutHeader('Content-Type');

// this will be a Guzzle Client object
$http = $client->authorize();

// get the response
$binaryFile = Google\Http\REST::execute($http, $request);
```

I am not sure what the response will look like since [the YouTube API](https://developers.google.com/youtube/v3/docs/captions/download) says this returns a binary file, but in theory this should work.

**Comment by kkopachev** [comment]
I looked deeper into the header been conditional in guzzle5. 
When `postBody` is not passed, it's [defaulted to null](https://github.com/googleapis/google-api-php-client/commit/6dc8190553988377554d54048bd086b89c57a37b#diff-c42742883e8032aa0b5735c831478483a43d7ad2a2a8e3fa32b188ca4ec579d8L100). Then it was set as value to [json request option](https://github.com/googleapis/google-api-php-client/commit/6dc8190553988377554d54048bd086b89c57a37b#diff-c42742883e8032aa0b5735c831478483a43d7ad2a2a8e3fa32b188ca4ec579d8L203) in Guzzle5. In turns, Guzzle5 [filters out](https://github.com/guzzle/guzzle/blob/5.3/src/Client.php#L113) any [null options](https://github.com/guzzle/guzzle/blob/d59d5293b4a804d6436d64fec71a8c75110a3165/src/Client.php#L329-L332). So json option is never made it to message factory which is responsible for [setting Content-Type header](https://github.com/guzzle/guzzle/blob/5.3/src/Message/MessageFactory.php#L347). In result, if there is no postBody (or it's null), previous version of api client did not set Content-Type header.

Workaround works, I overcome this with slightly different approach:

```php
$authorizedClient = $client->authorize();

$response = $authorizedClient->get(
  '/youtube/v3/captions/' . urlencode($caption['id']),
);
```

Nonetheless, seems wrong to send Content-Type header with GET request an no body.
