### ISSUE TITLE
500 - Internal error encountered - On MyBusinessQA PATCH Request

### ISSUE THREAD

**Issue by jok3rcito0** [googleapis/google-api-php-client#2289]
**Environment details**

OS: macOs 12.4
PHP version: 8.1
Nginx

Package name and version: google/apiclient v2.12

**Steps to reproduce**
1.- Get ouath token with valid scopes to Admin Locations
2.- Create a question using this token to allowed to edit this one
3.- Edit Question

**Code Exampple**

- Create

```php
    $service new MyBusinessQA($this->client);
    $service->locations_questions->create("{$location}/questions/", $question);
```
You get the "name" something like location/0979868/question/Alkhadkhasdk
then
```php
       $service = new MyBusinessQA($this->client);

        $question = new \Google\Service\MyBusinessQA\Question();
        $question->setText($data->data['text']);

        $option = [ 'updateMask' => 'text' ]; // I use as simple array and with ['updateMask' => ['text]]; with both return same error

        $store = $service->locations_questions->patch("location/0979868/question/Alkhadkhasdk", $question, $option);
```

**Expected Result**
No error, the goal is updated.

**Actual Result**
A Google_Service_Exception is thrown with the following message:
```json
{ 
  "error": { 
    "code": 500, 
    "message": "Internal error encountered.", 
    "errors": [ 
      {
         "message": "Internal error encountered.", 
         "domain": "global", 
         "reason": "backendError"
      }
    ], 
    "status": "INTERNAL" 
  } 
} 
```

**Comment by bshaffer** [comment]
An internal error (HTTP status code 500) is an indication that something is wrong with the service, and not necessarily wrong with your code. These types of errors should be temporary, so I suggest trying again. 

Your request looks good to me, judging by [the API reference](https://developers.google.com/my-business/reference/qanda/rest/v1/locations.questions/patch) and [FieldMask syntax](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.FieldMask), so I suggest trying again and logging an issue with the service's issue tracker if your problem persists.
