### ISSUE TITLE
OAuth session duration

### ISSUE THREAD

**Issue by elshobokshy** [googleapis/google-api-php-client#2293]
How to set the duration of the OAuth session? Currently, by default, it's asking me several times per day to reconnect.

Thanks !

**Comment by bshaffer** [comment]
Hi @elshobokshy ! Have you tried using the refresh tokens? You can add a [cache](https://github.com/googleapis/google-api-php-client#caching) to accomplish this. Also, when you authenticate your OAuth session, make sure "access_type" is set to "offline", which will return a refresh token with the access token. And the library should automatically use this to request a new one if you follow [this example](https://github.com/googleapis/google-api-php-client/blob/main/examples/simple-file-upload.php)
