### ISSUE TITLE
Indexing API Batch Request API Quota Issue

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#2296]
Hi,

I am using Batch service to Publish URLs to indexing API. But It is count each Urls as single request, but It should be 1 request for 1 batch?

My issue is If I Publish 20 URls in single batch request it is counting as 20 Publish requests per day instead 1 request.

```
$client = new \Google_Client();

$client->setAuthConfig('/var/www/html/privateKey.json');
$client->addScope('https://www.googleapis.com/auth/indexing');
$client->setUseBatch(true);

$service = new \Google_Service_Indexing($client);
$batch = $service->createBatch();

// add request
$postBody = new \Google_Service_Indexing_UrlNotification();
foreach ($urlList as $url) {
    $postBody->setType('URL_UPDATED');
    $postBody->setUrl($url);
    $batch ->add($service->urlNotifications->publish($postBody));
}
// ---- add request

$results = $batch->execute(); // it does authorize in execute()
```

**Comment by vishwarajanand** [comment]
Hi @chiragvels, the batching quota is counted at the URL level. For example, if you combine 20 requests into a single HTTP request, it still counts as 20 requests for your quota. [ref](https://developers.google.com/search/apis/indexing-api/v3/using-api#batching).

**Comment by chiragvels** [comment]
@vishwarajanand ,

Thanks for your response. Got it.
 I know this question is not related to the library, but I’m not able to see the Quota increase page on Google cloud console as suggested in this guide.
Any idea how I can connect with team to increase quota?
https://developers.google.com/search/apis/indexing-api/v3/quota-pricing#request-more-quota

**Comment by vishwarajanand** [comment]
@chiragvels  do you not see the following screen on [this link](https://console.cloud.google.com/apis/api/indexing.googleapis.com/quotas) ?
<img width="1230" alt="Screenshot 2022-08-10 at 14 27 13" src="https://user-images.githubusercontent.com/7369612/183861164-93f69e09-8f61-43ac-b7ec-950495c01825.png">

Once you click, `EDIT OUOTAS` you'll see this:
<img width="528" alt="Screenshot 2022-08-10 at 14 29 21" src="https://user-images.githubusercontent.com/7369612/183861318-1f4f25bb-a666-4784-a292-59510745687b.png">

And the links will take you to a google form where you can submit your case.

**Comment by chiragvels** [comment]
Hi @vishwarajanand ,

I am seeing First Image, but not seeing second option which is 

> Once you click, EDIT OUOTAS you'll see this:

Not seeing this screen.

**Comment by chiragvels** [comment]
Also There is no way we can handle error if batch request fails.
It is giving all-together different Obj. 
So If it successful it will provide Google\Service\Indexing\PublishUrlNotificationResponse Object
But when fails It provides Google\Service\Exception Object.

So how I can manage?

If I use Google\Service\Exception::getError() it handles fail request but at the time successful request fails with Call to undefined method Google\Service\Exception::getUrlNotificationMetadata() 

Same way for successful request Call to undefined method Google\Service\Indexing\PublishUrlNotificationResponse::getErrors()

Thanks,

**Comment by chiragvels** [comment]
Hi @vishwarajanand 

I am seeing this
![Screenshot](https://user-images.githubusercontent.com/74514/184064123-597cca48-158c-4a7f-bb83-9a9aa9c61f2d.png)

**Comment by vishwarajanand** [comment]
@chiragvels you should follow the link `contact our Sales Team`, I do not have visibility into that.

If you get `Service\Exception`, you could use `getErrors` to see HTTP responses. Then retry individual requests to get past that error.

One more thing, you should do use the URL `https://indexing.googleapis.com/batch` instead of `https://www.googleapis.com/auth/indexing` while editing scope. [ref](https://developers.google.com/search/apis/indexing-api/v3/using-api#batching)

**Comment by chiragvels** [comment]
Hi @vishwarajanand ,

> you should follow the link contact our Sales Team, I do not have visibility into that.

I tried contacting them by call and even by email, but no response yet by them. Is it because I am on Basic support?

> If you get Service\Exception, you could use getErrors to see HTTP responses. Then retry individual requests to get past that error.

I have handled this incase on error by doing under try
```
if ($result instanceof Google_Service_Exception) {
       $error_arr      = $result->getErrors();
}
```

> One more thing, you should do use the URL https://indexing.googleapis.com/batch instead of https://www.googleapis.com/auth/indexing while editing scope, [ref](https://developers.google.com/search/apis/indexing-api/v3/using-api#batching). Its discussed in https://github.com/googleapis/google-api-php-client/issues/1567

Ok, I changed this as per ref.

**Comment by vishwarajanand** [comment]
Glad it helped. Closing the issue. 
Not sure whether it’s “because” of you being on basic support.

**Comment by dinhhuuthanh** [comment]
hi
