### ISSUE TITLE
How can I retrieve contacts using this?

### ISSUE THREAD

**Issue by benswinburne** [googleapis/google-api-php-client#23]
I have been looking through all of the examples

here https://developers.google.com/api-client-library/php/
and here https://github.com/google/google-api-php-client/tree/master/examples

and the services https://github.com/google/google-api-php-client/tree/master/src/Google/Service

but there doesn't appear to be any services which use the scopes which the api documentation states to use.

This may not be the right place to ask but I'm struggling to find any useful documentation or working tutorials which relate to this.

Cheers

**Comment by kyogaraj** [comment]
Is there any contacts service  to get google contacts from gmail and export back to gmail working in google-api-php-client? I could

I don't see any google contact service still, should we gohead and use zend framework? 
I'm creating a new entry in a very very weird way,
