### ISSUE TITLE
google api allow users to connect when 3P cookies are not available

### ISSUE THREAD

**Issue by mabaied** [googleapis/google-api-php-client#2300]
I use google/apiclient and version 2.12 for develop authentification system with google but in private navigation I found button blocked cookies enabled for default and this button blocked authentification and acces , where is solution with google api to allow user connect with gmail when blocked cookies in private navigation

**Comment by vishwarajanand** [comment]
Hi @mabaied, thanks for raising this issue. 

I think if you should be able to use backend authentication: https://developers.google.com/identity/sign-in/web/backend-auth if your backend auth server is on the same TLD. Lemme know how that goes.

**Comment by vishwarajanand** [comment]
@mabaied closing this issue, looks like there's no more update to share.
