### ISSUE TITLE
PHP 5.4 support

### ISSUE THREAD

**Issue by lukowskipl** [googleapis/google-api-php-client#2305]
Hello, how can I run live on php5.4? We have the app in this version and cannot upgrade to 5.6. What should I change, or maybe there is a repository working somewhere?

**Comment by bshaffer** [comment]
Hello @lukowskipl ! We dropped support for PHP 5.4 and PHP 5.5 in [v2.9.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.9.0). You can download the previous version [v2.8.3](https://github.com/googleapis/google-api-php-client/releases/tag/v2.8.3) for compatibility with PHP 5.4 and PHP 5.5, and you'll be able to use the services which were supported by PHP 5.4 at that time.

Simply running `composer install google/apiclient` on PHP 5.4 will also pull the most up-to-date dependencies possible for that version of PHP.
