### ISSUE TITLE
[question] Is there an index of the services this api library provide?

### ISSUE THREAD

**Issue by ideiasfrescas** [googleapis/google-api-php-client#2308]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
We are building an automated composer generator ( think yeoman ) and we would like to add Google Services to that generator, but since we have need to filter out unused services, we would like to have an index of sorts in order to select which ones to keep.

 **Describe the solution you'd like**
A json file with a structure like this: 

```json
{
    'provided_services' : [
       'name' : 'Drive',
      'type': 'provided | other'
      'otherUrl': 'https://anotherlibrarythatprovidesthisservice'
    ]
}
```

 **Describe alternatives you've considered**
Scan a fresh copy of the folder in order to find service names

 **Additional context**
none.

**Comment by bshaffer** [comment]
Check out this repository: https://github.com/googleapis/discovery-artifact-manager/tree/master/discoveries

**Comment by bshaffer** [comment]
Here is another reference https://discovery.googleapis.com/discovery/v1/apis

You can read more about it here: https://developers.google.com/discovery

**Comment by ideiasfrescas** [comment]
Thank you.
Will take a look :)
