### ISSUE TITLE
Download file on the version 2.82 for php 5.4

### ISSUE THREAD

**Issue by lukowskipl** [googleapis/google-api-php-client#2311]
Hello, I have a problem with downloading files from the drive  because if I tried do this via 

```
        $response = $drive->files->get('1ORHql87AfGvBzISuzPyktecTKDa5wjl8', array([
            'alt' => 'media']));

        $content = $response->getBody()->getContent();
```

I get a message error, that the getBody method does not exist.  I tried also using getWebContentLink() but it is always empty. What I should use to download files?

**Comment by saranshdhingra** [comment]
Hi @lukowskipl 
Thanks for filling the issue.

I think you're trying to call the `getBody` function on the wrong object.
You can checkout the [examples](https://github.com/googleapis/google-api-php-client/tree/main/examples/large-file-download.php) to see how to download the file.

In short, you need to call the `getBody()->getContents()` on the response object which is fetched from the http client.

I haven't checked the same for `PHP 5.4`, but if it doesn't work feel free to reopen this thread and I will look at it more closely.
