### ISSUE TITLE
> There are definitely ways to mock these calls out. Here is one way that should work:

### ISSUE THREAD

**Issue by xcode93** [googleapis/google-api-php-client#2318]
Mock Gmail batch request fail

Hi, I having issue to mock batch requests, here is my code that I need to test :
```php
class SomeController exetend Controllers {
  public $client  = false;
  function __construct(Google_Client $client){
    $this->client = $client;
  }
  function getBatch($token, $message_ids ){
    $this->client->setAccessToken($token);
    $this->client->setUseBatch(true);

    $gmail_service = new Google\Service\Gmail($this->client);
  
    $batch = $gmail_service->createBatch();
  
    $batch->add( $gmail_service->users_messages->get( 'me', $message_ids[0] ), '01' );
    $batch->add( $gmail_service->users_messages->get( 'me', $message_ids[1] ), '02' );
    $response = $batch->execute();
    $this->client->setUseBatch(false);
    return $response;
  }
}
```

My test :
```php
 class Google_Gmail_Test extends PHPUnit_Framework_TestCase
 {
 public $client;
  function setUp(){
     parent::setUp();
     $this->client = $this->createMock(Google\Client());
     // set the controller to use mock client
     Helper::bootController($this->client); // now it success to set SomeController class  to use the mock client instead.
  }
  function testBatch(){

    // visit endpoint that trigger `getBatch` method
    visit(/api/v1/getBatch?token=someAccessToken&ids=1,2);
    $mock_response = new GuzzleHttp\Psr7\Response(
            200,
            [],
            $some_mock_messages_details
     );
    $this->expects($this->any())->method('execute')->willReturn($mock_response);

  }
}
```

the test return error: `TypeError: Argument 1 passed to Google\Http\Batch::add() must implement interface Psr\Http\Message\RequestInterface, instance of GuzzleHttp\Psr7\Response given`

_Originally posted by @xcode93 in https://github.com/googleapis/google-api-php-client/issues/1302#issuecomment-1250091651_

**Comment by bshaffer** [comment]
As `GuzzleHttp\Psr7\Response` does implement `Psr\Http\Message\RequestInterface`, this says to me there's some autoload error, or maybe you're using an old and unsupported version of Guzzle.

**Comment by bshaffer** [comment]
As I mentioned in the other bug, you're creating a mock, which needs you need to mock it's methods. You are not mocking all it's methods, so it doesn't realize that it's in batch mode, and is returning a Response instead of a Request object. You'll need to mock out `shouldDefer` to return `true` as well.
