### ISSUE TITLE
Google Analytics Admin API (GA4) - Returns Property but when request data It is giving error

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#2320]
#### Environment details

  - OS: Ubuntu 18.04.5 LTS
  - PHP version: PHP 7.4.14
  - Package name and version:[google/analytics-data v0.8.6](https://github.com/googleapis/php-analytics-data/releases/tag/v0.8.6)
  [google/analytics-admin v0.6.4](https://github.com/googleapis/php-analytics-admin/releases/tag/v0.6.4)

#### Steps to reproduce

I can get the properties using Google Analytics Admin API which has no use when try to get data using DATA API.
I am getting error when try to get data using DATA API
Error:

> "message": "User does not have sufficient permissions for this property. To learn more about Property ID, see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/data\/v1\/property-id.",
>     "code": 7,
>     "status": "PERMISSION_DENIED",
>     "details": []

The error is self explanatory, but my question is when Property has no access to data then why it is returning using Admin API, and If its returning then we must have way to identify such properties  where it does not having permission.

Thanks!

**Comment by sajadsaadat** [comment]
> It was solved now.

Hello
How did you solve this problem? Is it possible to explain?

I have a problem with property id while receiving information from Google Analytics 4.

**Comment by vishwarajanand** [comment]
@sajadsaadat Ref to [this link](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id#google_analytics) to understand how to fetch property id
