### ISSUE TITLE
Long running job loses refresh token

### ISSUE THREAD

**Issue by rickselby** [googleapis/google-api-php-client#2326]
#### Environment details

  - OS: Ubuntu 20.04
  - PHP version: 7.3
  - Package name and version: google/apiclient: 2.12.6

#### Steps to reproduce

  1. Set up Oauth2 authentication and start a long running job in PHP
  2. The first time the token refreshes, the returned token will not have a refresh token
  3. When the token next needs to refresh, it can't, and the job fails

#### Code example

This is my client setup:

```php
$client = new Google\Service\Client(['retry' => ['retries' => 5]]);
$client->setApplicationName('app name');

$client->setAuthConfig('/path/to/config');
$client->setScopes($this->scopes);

$client->setAccessType('offline');
$client->setPrompt('select_account consent');
$client->setApprovalPrompt('force');
$client->setIncludeGrantedScopes(true);

if (self::hasTokenFile()) {
    $accessToken = json_decode(self::getTokenFile(), true);
    $client->setAccessToken($accessToken);
}

if ($client->isAccessTokenExpired()) {
    if ($client->getRefreshToken()) {
        $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
    } else {
        throw new Exception('No valid Google token found');
    }
}

self::updateTokenFile(json_encode($client->getAccessToken()));
```
This all works fine. Calling `fetchAccessTokenWithRefreshToken` returns a new access token with a refresh token so it can keep on refreshing itself.

However, we then run a job:
```php

$driveService = new Google\Service\Drive($client);

for(/* lots and lots of directories */)
{
    var_dump($client->getAccessToken());

    $driveService->files->get();
   // ... etc etc ...
}
```
After an hour the token has expired, and the library will refresh the token itself, but it does not add a refresh token to the new token. Before the first refresh, the token looks like:
```
array(6) {
  ["access_token"]=> string(210) "ya29..."
  ["expires_in"]=> int(3599)
  ["refresh_token"]=> string(103) "1//..."
  ["scope"]=> string(37) "https://www.googleapis.com/auth/drive"
  ["token_type"]=> string(6) "Bearer"
  ["created"]=> int(1664972168)
}
```

After the first refresh by the library, it looks like this:
```
array(3) {
  ["access_token"]=> string(210) "ya29..."
  ["expires_in"]=> int(3600)
  ["created"]=> int(1664975937)
}
```

The code performing the refresh is here: https://github.com/googleapis/google-api-php-client/blob/main/src/Client.php#L442-L458
I lose track of how the token gets back into the client, so can't trace this much further.

**Comment by B2rana** [comment]
Hi, I am facing a similar refresh token issue during long-run jobs such as fetching GMB reviews & media of each location. Did anybody find the solution to this issue?

**Comment by bshaffer** [comment]
@B2rana @rickselby This is because the `refresh_token` you had is still valid, and can be used more than once. So rather than overwriting the refresh token with the new access token response, you should save the refresh token in a different place than the access token, e.g:

```php
if (self::hasTokenFile()) {
    $accessToken = json_decode(self::getTokenFile(), true);
    $client->setAccessToken($accessToken);
}

if ($client->isAccessTokenExpired()) {
    if ($refreshToken = self::getStoredRefreshToken()) {
        $client->fetchAccessTokenWithRefreshToken($$refreshToken);
    } else {
        throw new Exception('No valid Google token found');
    }
}

self::updateTokenFile(json_encode($client->getAccessToken()));
```

**Comment by bshaffer** [comment]
On another note, I tried to replicate the issue and the access token that came back from `fetchAccessTokenWithRefreshToken` did contain the refresh token:

```
array(6) {
  ["access_token"]=>
  string(213) "ya29...."
  ["expires_in"]=>
  int(3599)
  ["scope"]=>
  string(37) "https://www.googleapis.com/auth/drive"
  ["token_type"]=>
  string(6) "Bearer"
  ["created"]=>
  int(1675745680)
  ["refresh_token"]=>
  string(103) "1//02..."
}

```

**Comment by B2rana** [comment]
Hi @bshaffer, I am little confuse. Every time when we call "getAccessToken" method after validating previous token by using "isAccessTokenExpired" method, it returns refresh token along with new access token. So, according to we have to use old refresh token instead of which we received with new access token. If is this the right procedure, then how can we validate old refresh token validity and when can we use "refresh token come along with new access token"? Please explain.
