### ISSUE TITLE
Breaking issue with monolog

### ISSUE THREAD

**Issue by kefniark** [googleapis/google-api-php-client#2330]
Got some working code in `2.12.1` which doesn't work anymore after upgrading to `2.12.6`.

Try to read from a google sheet, it now crash and throw me the following error

> CRITICAL Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in file.php

**Current workaround**
pin the version of `"google/apiclient": "2.12.1"` fix the problem

#### Environment details

  - OS: Docker `wordpress:php8.0`
  - PHP version: 8.0

#### Steps to reproduce

  1. Install with composer
```
{
    "platform": {
        "php": "8.0.23"
    },
    "require": {
        "google/apiclient": "^2.12.1"
    },
    "scripts": {
        "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
    },
    "extra": {
        "google/apiclient-services": [
            "Sheets"
        ]
    }
}
```
  2. Connect to a google sheet and try to read sheet data

#### Code example

```php
# using the sample to get a range from a google sheet
$rows = $service->spreadsheets_values->get($spreadsheetId, $range)->getValues();
```

**Comment by bshaffer** [comment]
Thanks for reporting this! It's a strange issue since the errors both reference classes in our dependencies, and not in this library. I imagine `monolog/monolog` may have tagged a version that allows for an incompatible `psr/log` version.

**Comment by bshaffer** [comment]
Are you using composer's `autoload.php`? If not, then I think that is the problem

**Comment by bshaffer** [comment]
@kefniark we will close this issue shortly if we don't hear from you

**Comment by kefniark** [comment]
I'm using composer, autoload and the problem still occurs with version 2.13.0

**Comment by valko-pro** [comment]
@bshaffer Hi, I have similar problem.
I am using autoload, google-api-php-client v 2.13, php 8.1

**Comment by valko-pro** [comment]
@kefniark I have resolved the problem after downgrading the monolog version from 3.3.1 to 2.7.0.

**"google/apiclient": "^2.13",
"monolog/monolog": "2.7.0"**

**Comment by bshaffer** [comment]
@kefniark @valko-pro Can you please provide the steps to duplicate the error? I think there must be some strange combination of dependencies which causes it. When the errors occurs, could you provide 
1. version of `google/apiclient`
1. version of `monolog/monolog`
1. version of `psr/log`
2. your PHP version

**Comment by valko-pro** [comment]
@bshaffer 
Google API client 2.13
Monolog 3.3.1
PRS log 3.0
PHP 8.1

But, I have resolved the problem after downgrading the monolog version from 3.3.1 to 2.7.0

**Comment by bshaffer** [comment]
Thank you for providing this info. I still think this must be a bug in `monolog/monolog` and not in this library.

**Comment by xtype1016** [comment]
> @kefniark I have resolved the problem after downgrading the monolog version from 3.3.1 to 2.7.0.
> 
> **"google/apiclient": "^2.13", "monolog/monolog": "2.7.0"**

Thank you so much. I'm trouble with this for hours.

**Comment by xtype1016** [comment]
> @bshaffer Google API client 2.13 Monolog 3.3.1 PRS log 3.0 PHP 8.1
> 
> But, I have resolved the problem after downgrading the monolog version from 3.3.1 to 2.7.0

Thank you so much. I'm trouble with this for hours.

**Comment by ccc-nghia-le** [comment]
Thank you very much, the version of 2.7.0 actually fixed the issue for me too.

**Comment by timofey-drozhzhin** [comment]
Downgrading monolog/monolog from `3.3.1` to `2.7` fixed it for me also.

Google API Client: `2.12.1`
PRS log: `3.0.0`
PHP: `8.1.14`

**Comment by yash30201** [comment]
Closing this issue as this bug seems to be related to monolog and not relevant to this repository.
