### ISSUE TITLE
Transferring subscriptions to another reseller doesn't work

### ISSUE THREAD

**Issue by voicecode-bv** [googleapis/google-api-php-client#2332]
Hi all, 

I am making an application where it should be possible to transfer existing subscriptions to another reseller.

First of all, I request the available subscriptions based on the main domain. Then I pass the subscription, which is a Subscription object, via the insert method.

Then, no matter what I try, I get a 400 error: Licensed number of seats field is read-only. I get this message when transferring 1 subscription as well as several in a batch.

Does anyone know where I should look to resolve this?

#### Environment details

  - OS: MacOS
  - PHP version: 8.1
  - Package name and version: google/apiclient v2.12

#### Steps to reproduce

  1. Get subscriptions by domain
  2. Transfer a single subscription to another reseller account

#### Code examples

Step 1: Getting subscriptions by domain.

```php

$google = new Reseller($this->client);
$data = $google->subscriptions->listSubscriptions([
    'customerId' => $domain,
    'customerAuthToken' => $token,
])->getSubscriptions();

```

Step 2: Getting subscriptions by domain.

```php

$google->subscriptions->insert($domain, $subscription, [
    'customerAuthToken' => $token,
]);

```

Subscription object (replaced some sensitive values with #)

```

Google\Service\Reseller\Subscription {#1859 ▼
  #internal_gapi_mappings: []
  #modelData: []
  #processed: []
  #collection_key: "suspensionReasons"
  +billingMethod: "ONLINE"
  +creationTime: "1658294337048"
  +customerDomain: "######.nl"
  +customerId: "######"
  +dealCode: null
  +kind: "reseller#subscription"
  #planType: "Google\Service\Reseller\SubscriptionPlan"
  #planDataType: ""
  +purchaseOrderId: null
  #renewalSettingsType: "Google\Service\Reseller\RenewalSettings"
  #renewalSettingsDataType: ""
  +resourceUiUrl: "https://admin.google.com/ac/billing/subscriptions?ecid=######"
  #seatsType: "Google\Service\Reseller\Seats"
  #seatsDataType: ""
  +skuId: "1010020027"
  +skuName: "Google Workspace Business Starter"
  +status: "ACTIVE"
  +subscriptionId: "4088233743"
  +suspensionReasons: null
  #transferInfoType: "Google\Service\Reseller\SubscriptionTransferInfo"
  #transferInfoDataType: ""
  #trialSettingsType: "Google\Service\Reseller\SubscriptionTrialSettings"
  #trialSettingsDataType: ""
  +"seats": Google\Service\Reseller\Seats {#1842 ▼
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
    +kind: "subscriptions#seats"
    +licensedNumberOfSeats: 5
    +maximumNumberOfSeats: 300
    +numberOfSeats: null
  }
  +"plan": Google\Service\Reseller\SubscriptionPlan {#1835 ▼
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
    #commitmentIntervalType: "Google\Service\Reseller\SubscriptionPlanCommitmentInterval"
    #commitmentIntervalDataType: ""
    +isCommitmentPlan: false
    +planName: "FLEXIBLE"
  }
  +"trialSettings": Google\Service\Reseller\SubscriptionTrialSettings {#1856 ▼
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
    +isInTrial: false
    +trialEndTime: null
  }
  +"transferInfo": Google\Service\Reseller\SubscriptionTransferInfo {#1857 ▼
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
    +currentLegacySkuId: null
    +minimumTransferableSeats: 5
    +transferabilityExpirationTime: "1667885493634"
  }
}

```

Step 2 response:

```json
{
   "error":{
      "code":400,
      "message":"Licensed number of seats field is read-only",
      "errors":[
         {
            "message":"Licensed number of seats field is read-only",
            "domain":"global",
            "reason":"invalid"
         }
    ]
}
```

**Comment by ajupazhamayil** [comment]
Could you please let me know what are the following in your code to triage this issue?
1. $this->client
2. function description of listSubscriptions
3. function description of getSubscriptions
4. function description of insert

**Comment by voicecode-bv** [comment]
@ajupazhamayil all of the above are functionalities from within this library, so I don't understand why you ask this question.

**Comment by ajupazhamayil** [comment]
@voicecode-bv Oh sorry I got wrong repository context, I was looking at one another repository which has more than one product. Thank you for the reply.

**Comment by yash30201** [comment]
Hi @voicecode-bv, can you please paste you stack trace when you get this error?

**Comment by voicecode-bv** [comment]
@yash30201 Thanks for your message. It has just been resolved. Apparently, you can't fetch the subscriptions from Google and use them directly with the transfer API calls. You have init a new Subscription model and cherry pick some details from the existing subscriptions, otherwise it just wont work. Very strange behaviour if you ask me.
