### ISSUE TITLE
I can't list all files/folders starting from a specific folder within a Shared Drive

### ISSUE THREAD

**Issue by MythodeaLoL** [googleapis/google-api-php-client#2335]
#### Environment details

  - OS: Windows x64
  - PHP version: 8.1.6.0
  - Package name and version: google/apiclient: 2.12.1, apiclient-services: Drive

#### Steps to reproduce

  1. 
Try to list all files from Shared Drive ID, in one folderID.

  2.
You will get only $folderID info, no subfolders/tree files

#### Code example

```php
$client = Google_getClient();
$service = new Google_Service_Drive($client);

$folderID = "1........................................................................4";

$files = array();
$pageToken = null;
do {
    $parameters = array(
        'pageSize' => 20,
        'q' => "mimeType='application/vnd.google-apps.folder' and '{$folderID}' in parents and trashed=false",
        'corpora' => 'drive',
        'driveId' => '0.........................................A',
        'includeItemsFromAllDrives' => true, 'supportsAllDrives' => true,
        'pageToken' => $pageToken,
        'fields' => '*'
    );
    $response = $service->files->listFiles($parameters);
    foreach ($response->files as $file) {
        printf("Found file: %s (%s)\n", $file->name, $file->id);
    }
    array_push($files, $response->files);

    $pageToken = $response->pageToken;
} while ($pageToken != null);
print_r($files);
```

1. I can't list all folders starting from a specific folder within the Shared Drive.
2. I can't list all files starting from a specific folder within a Shared Drive.

**Comment by yash30201** [comment]
Hi @MythodeaLoL, thanks for reaching out!

The API is desined in such a way that when a query of the type `{folderId} in parent is run`, it will list out all the contents only within that particular folder id, not a recurrsive search. Right now, the way to get all the files and folder within a folder is to recurrsively search: if a file is a folder (check if the `mimeType="application/vnd.google-apps.folder"`) in the metadata, recurr again.

> For reference, you can explore this stackoverflow [thread](https://stackoverflow.com/questions/59045664/how-to-list-also-files-inside-subfolders-in-google-drive).

Hope this solves your issue. Please re-open this issue if you still get problems doing this.
