### ISSUE TITLE
Uncaught LogicException: Could not find supported version of Guzzle

### ISSUE THREAD

**Issue by madanpraba** [googleapis/google-api-php-client#2341]
Hello,
I have installed the file without composer in wordpress.
```
function gapi_update_deleted_url($post_id, $post){
    
    // bail out if this is not an event item
	if ( 'job' !== $post->post_type ) {
		return;
	}
    //https://github.com/googleapis/google-api-php-client
    //https://developers.google.com/search/apis/indexing-api/v3/prereqs#php
    require_once __DIR__ .'/google-api-php-client-main-2.12.6/google-api-php-client-main/src/Client.php';
    
    //get deleted url
    $deleted_url = get_permalink($post_id);   

    $client = new Google\Client();

    // service_account_file.json is the private key that you created for your service account.
    $client->setAuthConfig( __DIR__.'/axial-history-294207-65cc9c0fd724.json');
    $client->addScope('https://www.googleapis.com/auth/indexing');

    // Get a Guzzle HTTP Client
    $httpClient = $client->authorize();
    $endpoint = 'https://indexing.googleapis.com/v3/urlNotifications:publish';

    // Define contents here. The structure of the content is described in the next step.
    // "URL_UPDATED"
    $content = '{
    "url": "'.$deleted_url.'",
    "type": "URL_DELETED"
    }';
    $response = $httpClient->post($endpoint, [ 'body' => $content ]);
    $status_code = $response->getStatusCode();
    
    error_log( print_r( $status_code, true ) );  

}
```
Im getting the error "PHP Fatal error: Uncaught LogicException: Could not find supported version of Guzzle. in /var/web/site/public_html/wp-content/plugins/nvs-instant-indexing/google-api-php-client-main-2.12.6/google-api-php-client-main/src/Client.php:1211"

**Comment by bshaffer** [comment]
It seems like you are not autoloading or including the Guzzle dependencies as expected. To do this, you'll need to do one of the following:

 1. (recommended) install this library [using composer](https://github.com/googleapis/google-api-php-client#composer)
 2. install this library [by downloading the release and including the autoloader](https://github.com/googleapis/google-api-php-client#download-the-release)
3. install v5, v6, or v7 of `guzzlehttp/guzzle` separately
