### ISSUE TITLE
Cannot Install on Windows Due to File Path Length Limit

### ISSUE THREAD

**Issue by PostAlmostAnything** [googleapis/google-api-php-client#2343]
Every time I have tried to install this using Composer in Visual Studio I get an error saying that one of the files exceeds the 260 character OS file name limit. The file in question is:

vendor\composer\2bacad05\googleapis-google-api-php-client-services-9a0bab5\src\Contactcenterinsights\GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentDialogflowSegmentMetadata.php

As you can see that file name is way too long. There is no acceptable reason for a professional developer to name any file in this manner. Please change the name of the PHP file to something like GCMetadata.php or something practical like that.

**Comment by bshaffer** [comment]
It looks like this was solved by @PostAlmostAnything by searching for "how to disable the 260 character limit using regedit on Windows"
