### ISSUE TITLE
GIS Google Identity Services API Deprecation

### ISSUE THREAD

**Issue by vielhuber** [googleapis/google-api-php-client#2344]
We're migrating to the new Google Identity Services API.
GIS is mandatory, since the old one will no longer be in use from March 2023.

I wonder if this library (using access_tokens, refresh_tokens, all server sided)
is also affected by the deprecation or will it work without any problems also after March 2023?

Also, can someone explain if and how this library can be used in the
Authorization Code Flow (see https://developers.google.com/identity/oauth2/web/guides/use-code-model)
if you really want to use the javascript client library?

**Comment by bshaffer** [comment]
We have a few examples that show the Authorization Code flow (here's [one of them](https://github.com/googleapis/google-api-php-client/blob/main/examples/simple-file-upload.php#L56).

As for the deprecation, I could be missing something, but you appear to be referring to the [Google Sign-In JavaScript platform library for Web ](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis). This is a separate library, so nothing from this library should be effected.

Please re-open the issue or file a new one if I misunderstood something.
