### ISSUE TITLE
Dynamic Property Deprecated for PHP v 8.2

### ISSUE THREAD

**Issue by drrhf** [googleapis/google-api-php-client#2347]
With PHP Version 8.2.0 I get an Internal Server Error:
"Creation of dynamic property Google\Service\Sheets\BatchUpdateValuesRequest::$data is deprecated"
when calling
 $body = new Google_Service_Sheets_BatchUpdateValuesRequest(['valueInputOption' => 'USER_ENTERED', 'data' => $d]);
I am using google-api-php-client--PHP8.0 on Windows 11.
The code works properly with PHP Version 8.1.7
Thanks

**Comment by bshaffer** [comment]
Thanks for reporting this! We will need to update [the generator](https://github.com/googleapis/google-api-php-client-services/tree/main/generator) to fix these warnings. Until then, this library is not compatible with PHP 8.2
