### ISSUE TITLE
Install of google/apiclient-services failed

### ISSUE THREAD

**Issue by abdu997** [googleapis/google-api-php-client#2357]
#### Environment details

  - OS: 5.15.49-linuxkit
  - PHP version: PHP 7.4.30
  - Package name and version: [google/](https://packagist.org/packages/google/)apiclient

#### Steps to reproduce

  1. running `composer require google/apiclient`

```
 - Installing google/apiclient (v2.13.0): Extracting archive
 4/5 [======================>-----]  80%    Install of google/apiclient-services failed

In Filesystem.php line 330:
                                                                                                                                   
  Could not delete /var/www/vendor/composer/b9de416e/googleapis-google-api-php-client-services-2105f08/src/SecurityCommandCenter:  
                                                                                                                                   

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

It's also taking up 120% of my CPU!

Is there a way I can cherry-pick the google analytics stuff?

**Comment by bshaffer** [comment]
Hi @abdu997 
It seems like you're already doing a [limited install](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services), so if this is failing then the only way I can think of would be to download the zip and prune the files yourself, or increase the resources available on your machine. 
We would love to be able to offer separate packages for these libraries (e.g. `google/apiclient-analytics`), but we cannot maintain 250 separate github repositories just for that purpose. Sorry for the inconvenience, and if you can think of a solution we are all ears.
