### ISSUE TITLE
New authorization URI is a breaking change

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-api-php-client#2361]
See https://github.com/googleapis/google-api-php-client/pull/2275

Updating to the v2 auth URL broke the behavior of using `setApprovalPrompt('force')`, which was deprecated in favor of instead of the newer `setPrompt('consent')`. 

In order to mitigate this breaking change, we could update the `setApprovalPrompt` function to call `setPrompt('consent')` instead.

**Comment by vishwarajanand** [comment]
Reduced priority since it doesn't block release and is only applicable to a scenario with force prompt.

**Comment by bshaffer** [comment]
As i haven't heard anyone complain or comment on this bug or it's fix, i am thinking we can just keep the current behavior. But we should update the phpdoc at the very least
