### ISSUE TITLE
Retrieve Form Details

### ISSUE THREAD

**Issue by anjanesh** [googleapis/google-api-php-client#2364]
How do I get form details ?

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Google\Client;

$client = new Google\Client();
$client->setApplicationName('Google Forms');
$client->setScopes(' https://www.googleapis.com/auth/forms.body.readonly');
$client->setAuthConfig('credentials.json');
$client->useApplicationDefaultCredentials();
$redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'];
$client->setRedirectUri($redirect_uri);

if (isset($_GET['code'])) {
    $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
}

// returns a Guzzle HTTP Client
$httpClient = $client->authorize();

$service = new Google\Service\Forms($client);

try
{    
    $response = $service->forms;
    print_r($response); # what here ?
}
catch(Exception $e)
{
    echo 'Message: ' .$e->getMessage();
}
?>
```

**Comment by bshaffer** [comment]
`$service->forms` does not call the service. You can see the [Forms resource](https://github.com/googleapis/google-api-php-client-services/blob/main/src/Forms/Resource/Forms.php) for methods you could call on it, e.g.

```php
// get an existing form
$form = $service->forms->get($formId);

// create a new form
$service->forms->create(new Google\Serivce\Forms\Form([/** populate form data here */]));
```

**Comment by anjanesh** [comment]
Thanks, but now I get Message :
```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "errors": [
      {
        "message": "The caller does not have permission",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```
Even though the form of $formId is created under myUsername@gmail.com but  credentials.json has `"client_email": "myUsername-forms@myUsername.iam.gserviceaccount.com",`

**Comment by bshaffer** [comment]
You'll need to do three-legged authentication as seen in [this example](https://github.com/googleapis/google-api-php-client/blob/main/examples/simple-file-upload.php) if you want to edit a form created by a user account (e.g. [myUsername@gmail.com](mailto:myUsername@gmail.com)). If you want to edit a form with service account in `credentials.json`, you'll need to also create the form with those credentials.

**Comment by anjanesh** [comment]
So - I don't want to **edit** a form - I want _n_ number of users to send in their formIDs and I should be able to read the form details (questions and options) since they are public anyway. I want to to give my users custom design (for their survey users to enter the form) while they continue using google forms for backend and data entry so that if they edit the question, then I wouldn't need to change front-end code. Since there isn't an option to retrieve the JSON format of the form URL directly like its possible in sheets (https://docs.google.com/spreadsheets/d/{SHEETID}/gviz/tq?tqx=out:json&tq&gid=0) I'm trying to use the forms API to fetch.

**Comment by bshaffer** [comment]
If you're getting that error message, then my guess is that even if a form is public, the response from the "get" API is not.

**Comment by anjanesh** [comment]
I got this almost working.

I just seem to figure out the equivalent of 

`$response = $service->files->listFiles();` for [forms](https://developers.google.com/forms/api/reference/rest).

Or do I have to treat forms as a list of drive files ?
