### ISSUE TITLE
After download google-api-php-client v2.13.0 via composer, I cant see v2.13.0 in Client.php file.

### ISSUE THREAD

**Issue by BalachandarNatarajan** [googleapis/google-api-php-client#2365]
Hi,
I downloaded google-api-php-client v2.13.0 via composer using composer command. But i cant see the latest downloaded version in Client.php file which resides src directory instead that i have v2.12.6 only.

Kindly update the current version of google-api-php-client in Client.php file.

**Comment by BalachandarNatarajan** [comment]
Still i cant see version 2.13.0 in Client.php file.
kindly reply.

**Comment by bshaffer** [comment]
You're correct that `const LIBVER` in `Google\Client` is out of date, and not getting updated by our release tools.

**Comment by BalachandarNatarajan** [comment]
Thanks for your reply. Then where to find the version of google-api-php-client after downloaded.

**Comment by bshaffer** [comment]
I would recommend just using composer to see the versions of the dependencies you have installed. You shouldn't need to be using that information in your production code

**Comment by saranshdhingra** [comment]
Hi @BalachandarNatarajan 
As Brent mentioned, this might be considered an anti pattern, but if you still intend to do it, you could just fetch the info from composer from within the scope of your script.

Something like `exec('composer show google/apiclient | grep versions');` might help you and you can do some string manipulation to strip the unwanted text.

However, this is obviously platform dependant and is probably _hacky_.

I'll be closing this for now. But we'll update here once the `LIBVER` issue is fixed.
