### ISSUE TITLE
GA4 Data API property quota issue

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-api-php-client#2366]
Hi,

GA4 Data API is providing [PropertyQuota] (https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/PropertyQuota) but API is not providing same.

My code:
```php
foreach ($summary_data->getPropertyQuota() as $quota) {
            foreach($quota->getQuotaStatus() as $quotaStatus){
}
}
```

**Comment by bshaffer** [comment]
This looks like a support issue for the GA4 Data API. I cannot help you debug this issue without more information on the request you're making

**Comment by chiragvels** [comment]
Hi @bshaffer ,

I am trying to get the quota when try to do API call.



    // Create a client.
    $betaAnalyticsDataClient = new BetaAnalyticsDataClient();

    // Call the API and handle any network failures.
    try {
        $response = $betaAnalyticsDataClient->runReport([
                'property' => 'properties/XXXXXX',
                'metrics' => $metrics,
                "returnPropertyQuota" => 'true'
            ]);
        printf('Response data: %s' . PHP_EOL, $response->serializeToJsonString());
    } catch (ApiException $ex) {
        printf('Call failed with message: %s' . PHP_EOL, $ex->getMessage());
    }

**Comment by chiragvels** [comment]
Hi @bshaffer ,

Please mark this as completed.

I am able to get quota now after API update to latest version.

Thanks,
