### ISSUE TITLE
Documentation links to dead quickstart links

### ISSUE THREAD

**Issue by musik92** [googleapis/google-api-php-client#2374]
Your documentation has link to this resource, which in turn links to dead php quickstart pages (that have since been removed by google I guess?):

https://github.com/googleworkspace/php-samples

**Comment by yash30201** [comment]
Hi @musik92, thanks for raising this issue.

I would like to point out that this is related to the workspace repository(https://github.com/googleworkspace) and that would be a proper platform to raise this issue. 

Thus, closing this here.
