### ISSUE TITLE
Google Drive API: "your computer or network may be sending automated queries" and "Error 502 (Server Error)!!1"

### ISSUE THREAD

**Issue by Stalinko** [googleapis/google-api-php-client#2375]
I have a simple PHP script which uploads backups to my Google Drive using this library.
The size of the backup files is ~20GB.
This script is running on 2 my Hetzner Servers, absolutely idential. On one of them it works smoothly, but on the other one it just started to receive the errors from the title. With no reason.

Any ideas how to unblock this script via console?

#### Environment details

  - OS: Ubuntu 20.04
  - PHP version: 7.4
  - Package name and version: google/apiclient v2.9.2

#### Code example

```php
        $file = new Google_Service_Drive_DriveFile([
            'name' => basename($this->file_to_upload),
            'parents' => [self::GDRIVE_FOLDER],
        ]);
        $chunkSizeBytes = 30 * 1024 * 1024; //upload in chunks of 30mb

        // Call the API with the media upload, defer so it doesn't immediately return.
        $this->client->setDefer(true);
        $request = $this->service->files->create($file);

        // Create a media file upload to represent our upload process.
        $media = new Google_Http_MediaFileUpload(
            $this->client,
            $request,
            'text/plain',
            null,
            true,
            $chunkSizeBytes
        );
        $media->setFileSize($this->size);

        // Upload the various chunks. $status will be false until the process is complete.
        $status = false;
        $handle = fopen($this->file_to_upload, "rb");
        $uploaded = 0;
        while (!$status && !feof($handle)) {
            $chunk = fread($handle, $chunkSizeBytes);
            // The final value of $status will be the data from the API for the object that has been uploaded.
            $status = $media->nextChunk($chunk);
        }
        fclose($handle);
        $this->client->setDefer(false);
```

**Comment by gaozhitw** [comment]
I encountered the same issue while using Hetzner's server. I have updated google/apiclient to version 2.13.1, but the problem still persists.

**Comment by Fma965** [comment]
Not 100% related and sorry for posting this here but this could be an interesting read? https://forum.rclone.org/t/429-google-drive-errors-back-for-anyone-using-hetzner-even-with-cloudflare-or-google-dns-used/36671

**Comment by saranshdhingra** [comment]
I tried to recreate the issue with the same code, chunk size and file size.
I wasn't able to recreate it.

Since the issue is happening only on a specific cloud provider, I don't think there's much as client library devs we can do here.
Perhaps the provider is using a shared network for multiple machines?

I would recommend you contact the support of the cloud provider instead. If this is generally reproducible, I would certainly look into it.

**Comment by Stalinko** [comment]
@saranshdhingra thanks for your check.
Actually it's very hard to reproduce this issue.
It appears only when you're using Google Drive for automatic daily backups. Then after a month or several months the API is getting blocked.
