### ISSUE TITLE
Supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by uceap-web** [googleapis/google-api-php-client#2381]
Trying to authenticate, using a service account, in order to add new members to a Google group. Authentication is failing with the following message:

`Warning: openssl_sign(): Supplied key param cannot be coerced into a private key in /vendor/firebase/php-jwt/src/JWT.php on line 238`

The json file with the private key was downloaded from https://console.cloud.google.com/iam-admin/serviceaccounts.

Any suggestions on how to fix this problem? the key should be formatted correctly if the file was downloaded directly from Google IAM. Thanks.

**Comment by bshaffer** [comment]
I would inspect the file you downloaded and make sure it looks correct. It should be a JSON file (not a P12, which is another possible format). Also make sure the path to the file that you've configured in your code points to a correct and accessible location on your computer.
