### ISSUE TITLE
How using the api that name 'monetization_subscriptions.archive'

### ISSUE THREAD

**Issue by bingeger** [googleapis/google-api-php-client#2385]
- PHP version: 5.6.34
  - Package name and version: 2.13.0

1. create a new subscription, has a available base plan
2. deactivate the base plan
3. archive the subscription

but the step 3 fail, and the response:

{
	"code": 400,
	"message": "Can only archive a subscription if all base plans are cancelled.",
	"errors": [{
		"message": "Can only archive a subscription if all base plans are cancelled.",
		"domain": "global",
		"reason": "failedPrecondition"
	}],
	"status": "FAILED_PRECONDITION"
}

I'm sure all base plans are INACTIVE

**Comment by bingeger** [comment]
[Developer API: monetization.subscriptions.archive](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions/archive)

**Comment by bshaffer** [comment]
```php
$client = new Google\Client();
$service = new Google\Service\AndroidPublisher($client);

// create subscription object (this is just an example)
$subscription = new Google\Service\AndroidPublisher\Subscription();
$subscription->setProductId($productId);
// create and set the base plan (this is just an example)
$basePlan = new Google\Service\AndroidPublisher\BasePlan();
$subscription->setBasePlans([$basePlan]);

// call the API to create the subscription
$service->monetization_subscriptions->create($packageName, $subscription)

// call the API to deactivate the base plan
// do something with $basePlan to deactivate it
$service->monetization_subscriptions->patch($packageName, $subscription)

// call the API to archive the service
$service->monetization_subscriptions->archive($packageName, $productId, new Google\Service\AndroidPublisher\ArchiveSubscriptionRequest())
