### ISSUE TITLE
google service account example returns "Error refreshing the OAuth2 token { “error” : “invalid_grant” }"

### ISSUE THREAD

**Issue by mappedinn** [googleapis/google-api-php-client#239]
My goal is to make the simplest query on `Google Fusion Tables` on behalf of my web app users. For that, I created a **service account** on google console. Here is the code:

```
    // Creating a google client
    $client = new \Google_Client();


    // setting the service acount credentials
    $serviceAccountName = 'XXXXX.apps.googleusercontent.com';
    $scopes= array(
                'https://www.googleapis.com/auth/fusiontables',
                'https://www.googleapis.com/auth/fusiontables.readonly',
                );
    $privateKey=file_get_contents('/path/to/privatekey.p12');
    $privateKeyPassword='notasecret'; // the default one when generated in the console

    $credential = new \Google_Auth_AssertionCredentials($serviceAccountName,
            $scopes, $privateKey, $privateKeyPassword);

    // setting assertion credentials
    $client->setAssertionCredentials($credential);

    $service = new \Google_Service_Fusiontables($client);
    $sql = 'select name from XXXXXXXX'; 
    $result = $service->query->sql($sql);
```

After running this code, I got this error:

```
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant"
}'
```

I googled that for days and most of answers are talking about refreshing the token. I made this refresh but still the same errors!

Any idea for solving this problem?
Thanks

**Comment by rafasashi** [comment]
I use Google_Auth_AssertionCredentials to access a gmail account from server to server. It was working well from both development and production servers but now the production one get the “error” : “invalid_grant”. As suggested by ianbarber I have implemented a new client id with new p12 key but the service remains unreachable on production. Is it due to a blocking mechanism by ip?

**Comment by rafasashi** [comment]
Apparently the problem was the system time being off. Worked by Resynchronizing via NTP with:

`sudo ntpdate pool.ntp.org`

http://stackoverflow.com/questions/11973162/google-analytics-api-oauth-exception-invalid-grant-with-service-account-same/30259766#30259766

**Comment by aacevedoday** [comment]
Perfecto, efectivamente el inconveniente esta en la hora de la maquina. Gracias!! rafasashi
