### ISSUE TITLE
From (sender email and name) ignored and not being set

### ISSUE THREAD

**Issue by jplevene** [googleapis/google-api-php-client#2393]
```
$mime_email = '. . . . .From: "Info" <info@company.com>......';

$objGMail = new Google_Service_Gmail($client);
$mime = rtrim(strtr(base64_encode($mime_email), '+/', '-_'), '=');
$gmail_msg = new Google_Service_Gmail_Message();
$gmail_msg->setRaw($mime);
$objGMail->users_messages->send('me', $gmail_msg);
```

The $client is lets say registered to "bob@company.com" and there is a general alias email "info@company.com".  Setting the "From" does nothing as it reverts to "bob@company.com", however I can set the from when sending using SMTP but not the API.

**Comment by LindaLawton** [comment]
I'm parity sure the client library automatically defaults from to the email address of the currently authenticated user.   Try logging in with info@company.com instead.

**Comment by jplevene** [comment]
> I'm parity sure the client library automatically defaults from to the email address of the currently authenticated user. Try logging in with [info@company.com](mailto:info@company.com) instead.

Please read the post, this is regarding the API and an alias email (one that is not an account).

**Comment by yash30201** [comment]
Hi @jplevene,

I tried doing the same after adding the alias email to my current account(You can do this via [UI](https://support.google.com/mail/answer/22370?hl=en) or via php client too) and then sending the mail with the `FROM` as one of the alias and it worked.

Can you confirm if you have your alias properly added in the `send as` settings?

**Comment by yash30201** [comment]
I guess I created a confusion here😅.

I'm asking that can you check if you have your required alias email registered in the sendAs settings? You can check like this via client-
```php
$gmail = new Gmail($this->client);
$sendAsList = $gmail->users_settings_sendAs
    ->listUsersSettingsSendAs('me')
    ->getSendAs();
foreach ($sendAsList as $sendAs) {
    echo 'Alias Name: ' . $sendAs->getDisplayName() . PHP_EOL;
    echo 'Email: ' . $sendAs->getSendAsEmail() . PHP_EOL;
}
```

Alternatively, you can also check in the UI as stated above.

Now what I observed is that, we don't get an exception if we try to use alias email but haven't registered the alias in the sendAs settings and in this case the email is sent by the actual user. But if we use an alias which is registered in the sendAs settings, it works as intended and we get the required results.

Thus @jplevene, can you please check your registered aliases and verify if the required alias(`info@email.com`) is present there?

**Comment by jplevene** [comment]
Yes it works doing this.  The confusion is that it works without doing this using the SMTP server.

Thanks
