### ISSUE TITLE
Class "Google\Client" not found

### ISSUE THREAD

**Issue by kimbosanz-dev** [googleapis/google-api-php-client#2394]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOS Ventura
  - PHP version: 5.6.40
  - Package name and version: google/apiclient:^2.12.1

#### Steps to reproduce

  1. When im trying to access the class on my php service and runs it on my server it throws me an error that the class was not found.

#### Code example

```php
# example
    require_once '/var/www/localhost/vendor/autoload.php';

    use Google\Client;

    public function getGoogleData($token)
    {
        $client_id = $_ENV['GOOGLE_CLIENT_ID'];
        $client_secret = $_ENV['GOOGLE_CLIENT_SECRET'];

        $client = new Client();
        $client->setAuthConfig('/var/www/localhost/client_credentials.json');
        $payload = $client->verifyIdToken($token);
    }
```

This is the structure of my installed google api
![image](https://user-images.githubusercontent.com/60734652/222637176-c8b71cb1-e163-4518-bb3d-40aecde7fadd.png)

For my composer.json
```json
     "require": {
        "google/apiclient": "^2.12.1"
      },
     "scripts": {
        "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
      },
     "extra": {
        "google/apiclient-services": [
            "Drive",
            "YouTube"
         ]
      },
     "autoload": {
         "classmap": [
             "vendor/google/apiclient/src"
         ]
      },
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ObedNyakundi** [comment]
It looks normal

**Comment by yash30201** [comment]
Hi @kimbosanz-dev, thanks for reaching out.

I tried doing the same and wasn't able to repro the error, can you confirm if the composer has been update using the `composer update` command after modifying the `composer.json` file? Also it would be great if you can verify that the director for the `autoload.php` file is correct.

**Comment by saranshdhingra** [comment]
Hi @kimbosanz-dev 
I'll be closing this ticket for now.

But please feel free to reopen this if you feel the issue still persists.
Thanks.

**Comment by bshaffer** [comment]
@kimbosanz-dev just chiming in to say this looks like an issue with your autoloading. Nothing obvious stands out to me as the problem, but I'm certain that you'd have the same error with any dependency you've installed. I'd guess that the application running on your web server does not contain the `autoload.php` file, or that the `vendor` directory for whatever reason is missing the required PHP files which make up this library.

**Comment by darshannv** [comment]
Please update the composer.json

     "google/apiclient": "^2.12.1"
    
Inside the composer.json file under the **extra** update this

     "extra": {
         "google/apiclient-services": [
            "Drive",
            "YouTube"
        ]
    }

under the **script** section at the bottom add this line

    "scripts": {
         "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
     }

After adding it, run the command 

    composer update
    composer dump-autoload 

It will work.
