### ISSUE TITLE
phpseclib/phpseclib - Infinite Loop vulnerability 

### ISSUE THREAD

**Issue by chbakouras** [googleapis/google-api-php-client#2403]
A new vulnerability is reported for phpseclib/phpseclib

`composer audit`

![image](https://user-images.githubusercontent.com/9432246/224114311-39636b49-a744-474e-ac8f-17fac08aabac.png)

`composer why phpseclib/phpseclib`
`google/apiclient        v2.13.0 requires  phpseclib/phpseclib (~2.0||^3.0.2) ` 

Is a new version with an upgrade planned?

**Comment by SuguruOoki** [comment]
What if you run the following command?
Unless there are special circumstances such as specifying the required version, I think there is no problem.

`composer update phpseclib/phpseclib:^3.0.19`
