### ISSUE TITLE
is this sdk supports PKCE?

### ISSUE THREAD

**Issue by idanbenezra** [googleapis/google-api-php-client#2406]
Hello,

My application is a web based application and is self hosted by my clients, this is why i can't use the app client secret.
Is there a way to use PKCE to authenticate and fetch the access and refresh token?

**Comment by yash30201** [comment]
Hi @idanbenezra , [this](https://developers.google.com/identity/protocols/oauth2/native-app#obtainingaccesstokens) section explains how we support PKCE to authenticate.

Hope this helps, thus closing this issue. Please reopen this incase you still encounter some issue.

**Comment by idanbenezra** [comment]
Hey @yash30201 

Thanks for the reply.

I did find this documentation before, However i didn't find any way to use it using this SDK.
Is this supported?
