### ISSUE TITLE
Open excel file from drive

### ISSUE THREAD

**Issue by nicocins** [googleapis/google-api-php-client#2407]
Dear,

I am testing to open an Excel file from my google drive.

It does not work and I have to convert my Excel file to Google Sheet format.

Are there any solutions to open an excel file ?

Thanks in advance.

**Comment by saranshdhingra** [comment]
Hi @nicocins 
Thanks for filing the issue.

Could you share some code that you're currently using and it's not working for you?

Thanks.

**Comment by localpost** [comment]
Hello! I also have troubles with working xlsx file in Drive. Code Ims using is alsmost straight from the documentation
https://developers.google.com/drive/api/guides/manage-downloads?hl=ru#php_1
Function getBody() returns empty json string

**Comment by saranshdhingra** [comment]
Hi @localpost 
As per [this link](https://developers.google.com/drive/api/guides/manage-downloads#export_document_content) you need to export a Google workspace document and not download them.

So, I tried the same link with the given code on a newly created Spreadsheet in a drive and I got the response as expected.


It is worth mentioning that when i tried the download code in the link that you gave, I got the following error:
`Only files with binary content can be downloaded. Use Export with Docs Editors files.` which pointed me to read more in the documentation.

Regarding the file's mimeType to pass, you can either refer to [this link](https://developers.google.com/drive/api/guides/ref-export-formats) or you can even call `$file->getMimeType()` in a list call. Something like this can help at a basic level:
```
$service = new Drive($client);

$list = $service->files->listFiles();

foreach($list->getFiles() as $file) {
    $name = $file->getName();
    $id = $file->getId();
    $mimeType = $file->getMimeType();
}
```

Hopefully this helps.
I'll be closing this for now, please feel free to reopen if there is more help needed.
Thanks.
