### ISSUE TITLE
Error: (list) unknown parameter: 'eventTypes'

### ISSUE THREAD

**Issue by siltn** [googleapis/google-api-php-client#2419]
#### Description 

I'm trying to get the [workingLocation](https://developers.google.com/calendar/api/guides/working-hours-and-location)
via a Laravel project. this is a new feature for the google developer program and works via a CURL.
But it doesn't work yet in this package.

This is because it's not listed in the stackParameters

#### Solution 
I've looked to resolve this locally and found that changing this resolves it,
but I'm not sure if this is a best practice.

In [Resource.php](https://github.com/googleapis/google-api-php-client/blob/bd7b138bbc1c5016b7e85ff85f0533ae3684b9ed/src/Service/Resource.php#L35) add eventTypes as $stackParameters[] add 
```php
'eventTypes' => ['type' => 'string', 'location' => 'query'],
```

#### Environment details

  - OS: MacOS
  - PHP version: 8.0.21
  - Package name and version: google/apiclient: v2.13.1

#### Steps to reproduce

  1. Call [listEvents](https://github.com/googleapis/google-api-php-client-services/blob/6f79073f022686461af2d1a95b4fe91caaf947ec/src/Calendar/Resource/Events.php#L271)
  *  with optParams = [ 'eventTypes' => 'workingLocation' ];

#### Code example

```php
# example

    public function getWorkingLocation( int $startWeekAdjustment, string $email): array
    {
            $calendar = new Google_Service_Calendar($this->client);

            $params = array(
                'singleEvents' => 'true',
                'orderBy' => 'startTime',
                'eventTypes' => 'workingLocation'
            );

            $workingLocations = $calendar->events->listEvents($email, $params);


            return $workingLocations;
    }
```

**Comment by bshaffer** [comment]
The `$stackParams` are related to options that are not service-specific. The option you're providing should be supported by the API itself in `$optParams`.

The [eventTypes parameter](https://github.com/googleapis/google-api-php-client-services/blob/3d52729e94fe41694593ffac275af03435142aa6/src/Calendar/Resource/Events.php#L200) is supported, but you need to upgrade your client library.
