### ISSUE TITLE
Error when trying to get userinfo from OAuth2 Service 

### ISSUE THREAD

**Issue by Lgamesdev** [googleapis/google-api-php-client#2420]
Hello, I have a mobile app and I'm trying to get the email address of my user by parsing his authorization code from the request of the mobile app, to my server : 

```
$content = json_decode($request->getContent(), true);

    if($content['code']) {
        $client = new Google_Client();
        //$client->useApplicationDefaultCredentials();
        $client->setAuthConfig($this->getParameter('app.googleclientconf'));
        $client->addScope(Google_Service_Oauth2::OPENID);
        $client->addScope(Google_Service_Oauth2::USERINFO_PROFILE);
        $client->addScope(Google_Service_Oauth2::USERINFO_EMAIL);
        $accessToken = $client->fetchAccessTokenWithAuthCode($content['code']);
        if(!isset($accessToken['error'])) {
            $client->setAccessToken($accessToken);
            $service = new Service\Oauth2($client);
            $user = $service->userinfo_v2_me->get();
        }
...
```

I can fetch the Auth code to Access token, but when I'm trying to get 'userinfo_v2' i get always the same error : 

`{ "error" : { 
        "code":401, 
         "message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie 
                            or other valid authentication credential. See https://... "
         ...
         "errors" : [
          {
               "domain":"global",
               "reason":"unauthorized"
          }]
          "status":"UNAUTHENTICATED"
    }
} `

**Comment by vpuentem** [comment]
Could you resolve this? I'm having the same issue
