### ISSUE TITLE
Error 502 (Server Error)!!1 with JetBackup

### ISSUE THREAD

**Issue by khalequzzaman17** [googleapis/google-api-php-client#2421]
I am using Google Drive API to generate the backup of cPanel accounts with JetBackup on my server. Yesterday, I found, the backups are not working fine anymore for the last 40+ days. I used to keep 60 days of backups (retains). The error I am getting at (from the log file of JetBackup):

[29 March 2023 01:21:35 AM +0600] [ERROR] 	Failed to prepare temporary snapshot folder. Error: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

This needs to be fixed fast, because, the backups are urgent. Thank you.

**Comment by Stalinko** [comment]
I'm getting the same error when uploading my large backups (50GB) every day :(

**Comment by Sak1s** [comment]
i am facing the some error.

Any tips ?

**Comment by bshaffer** [comment]
As this is a `Server Error`, it would be an issue with the API itself and not with this library. This repository is for issues with the PHP client libraries themselves, we do not support the APIs. 

My best bet is this is an intermittent error having to do with the service going down. I'd implement retries in your code in this situation.  If the problem persists, I would suggest filing an issue with JetBackup, or with the Drive API itself.
