### ISSUE TITLE
Youtube Api uploading to channel using php: "Invalid value at 'resource' (Map), Cannot bind a list to map for field 'localizations'

### ISSUE THREAD

**Issue by SimonvanDoorne** [googleapis/google-api-php-client#2423]
- OS: Windows 10
  - PHP version: 7.4.33
  - Package name and version: google-api-php-client release (not composer version) v2.13.1

#### Steps to reproduce

  1. Attempt to upload video using php 

`  // Define service object for making API requests.
        $this->client->setAccessToken($accessToken);
        $service = new \Google_Service_YouTube($this->client);

        // set the video's title, description
        $snippet = new \Google_Service_YouTube_VideoSnippet();
        $snippet->setTitle('test title');
        $snippet->setDescription('this is a test description');

        // Set the video's status to "private". 
        $status = new \Google_Service_YouTube_VideoStatus();
        $status->privacyStatus = 'private';

        // Associate the snippet and status objects with a new video resource.
        $video = new \Google_Service_YouTube_Video();
        $video->setSnippet($snippet);
        $video->setStatus($status);

        // Specify the size of each chunk of data
        $chunkSizeBytes = 1 * 1024 * 1024;

        // Setting the defer flag to true tells the client to return a request which can be called
        // with ->execute(); instead of making the API call immediately.
        $this->client->setDefer(true);

        // Create a request for the API's videos.insert method
        $insertRequest = $service->videos->insert("status,snippet", $video);

        $media = new \Google_Http_MediaFileUpload(
            $this->client,
            $insertRequest,
            'video/*',
            null,
            true,
            $chunkSizeBytes
        );
        $media->setFileSize(filesize($fileLocation));

        // Read the media file and upload it chunk by chunk.
        $status = false;
        $handle = fopen($fileLocation, "rb");
        while (!$status && !feof($handle)) {
            $chunk = fread($handle, $chunkSizeBytes);
            $status = $media->nextChunk($chunk);
        }
        fclose($handle); `

(code is taken mostly from the example docs and api documentation)

2. return error is the following: 
`{ "error": { "code": 400, "message": "Invalid value at 'resource' (Map), Cannot bind a list to map for field 'localizations'.", "errors": [ { "message": "Invalid value at 'resource' (Map), Cannot bind a list to map for field 'localizations'.", "reason": "invalid" } ], "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "field": "resource", "description": "Invalid value at 'resource' (Map), Cannot bind a list to map for field 'localizations'." } ] } ] } }`

This seems like a similar issue #2401 but with a different field and with the youtube service instead of the drive service (making the temp fix for that issue not a solution here). Setting the field 'localizationsDataType' to null doesn't fix it and since i have getting started quota for the youtube api i can't test easily how to fix it.

**Comment by danamira** [comment]
Having the exact same problem.

**Comment by SimonvanDoorne** [comment]
After looking some more: I did not see a set/get function for the localizations or the localizationdatatype field. Manually setting the localizationsdatatype to null instead of 'map' fixes the issue.

**Comment by saranshdhingra** [comment]
Hi @SimonvanDoorne 
Thanks for filling the issue.

I tried the exact code as yours with the scope `https://www.googleapis.com/auth/youtube.upload` and the video did upload successfully.

Could you try it again and see if the error persists? If it still persists, then please add the whole code(including the auth part).

**Comment by saranshdhingra** [comment]
Closing the issue for now.
Please feel free to reopen this if you are able to reproduce the error.
