### ISSUE TITLE
README.md incorrect

### ISSUE THREAD

**Issue by finicallegend** [googleapis/google-api-php-client#2425]
If downloaded release and do not want to use compose Uncompress the zip file you download, and include the autoloader in your project:.

Add the code:
require_once '/path/to/google-api-php-client/vendor/autoload.php';

This file does not exist. What files should we be using for 2.13.2 ?

**Comment by saranshdhingra** [comment]
Thanks for reporting this issue @finicallegend 

I do see that the latest release doesn't contain the assets for the different PHP versions.

@bshaffer What might have caused this difference from the previous releases as I see the workflow file [asset-release.yml](https://github.com/googleapis/google-api-php-client/blob/main/.github/workflows/asset-release.yml) hasn't been changed?

**Comment by saranshdhingra** [comment]
> @saranshdhingra I managed to get it working in the end. I didn't reallly fully understand composer how it works which generates the correct files. From there just move the generated files to a live server. I think the confusion is that maybe the readme.md just needs to be updated for others.

So, the recommended approach is by using composer, however, if someone doesn't want/can't use it, we provide these release zips, which can just be unpacked and used.

In this case, however, the `vendor` folder wasn't generated.

You can generate it by simply running `composer update` for your PHP version in the folder that contains the `composer.json` file. But it shouldn't be needed as this approach is for when composer can't be used.

So, I think it's more than just a readme error :)

**Comment by bshaffer** [comment]
The README isn't incorrect, it's just that the asset job [failed to install PHP](https://github.com/googleapis/google-api-php-client/actions/runs/4630251461/jobs/8191583023) (I have no clue why). I [reran it](https://github.com/googleapis/google-api-php-client/actions/runs/4630251461) and it worked. Now the latest release has the assets with the `vendor` directory included.
