### ISSUE TITLE
Insert video youtube error

### ISSUE THREAD

**Issue by padi-dev-lucvt** [googleapis/google-api-php-client#2443]
- I'am using: google/apiclient 2.13, YouTube Data API V3

- Video store on FTP server

- When insert video resumable error: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 8192 bytes, which does not meet this requirement

Code sample
![code](https://github.com/googleapis/google-api-php-client/assets/90737217/259bdfc3-dd3b-44b0-8046-b66962162ea6)

**Comment by LindaLawton** [comment]
Please edit your question and include your code and not an image of your code we cant test your image.

**Comment by saranshdhingra** [comment]
Closing this issue as there hasn't been any update from your side.
Please feel free to reopen this with the code snippet used.
Thanks.
