### ISSUE TITLE
google/apiclient-services 0.303.0 changes php version requirement

### ISSUE THREAD

**Issue by Gerben-T** [googleapis/google-api-php-client#2450]
google/apiclient v2.14.0 says it supports php `^5.6|^7.0|^8.0`, but requires google/apiclient-services `~0.200` which will translate to [`0.303.0`](https://packagist.org/packages/google/apiclient-services#v0.303.0), at time of writing this, and that version does **not** support php `^7.0` but instead `^7.4` which breaks on a system running php `7.2`

#### Environment details

  - OS: Linux
  - PHP version: 7.2
  - Package name and version: google/apiclient v2.14.0

#### Steps to reproduce

N/A

#### Code example

N/A

**Comment by vishwarajanand** [comment]
@Gerben we have migrated away from supporting php<7.4 versions. 
Like you said, it was done in [v0.303.0](https://github.com/googleapis/google-api-php-client-services/compare/v0.302.0...v0.303.0).

I'd recommend you to pin the dependency version, till we resolve it.
