### ISSUE TITLE
gmail api throwing error when sending email to more then 14 recipient

### ISSUE THREAD

**Issue by web95-moon** [googleapis/google-api-php-client#2451]
Thanks for stopping by to let us know something could be better!
#### Environment details

  - OS:windows
  - PHP version: ^8.0.2
  - Package name and version: "google/apiclient": "2.12.6",

#### Steps to reproduce

 N.A

#### Code example

```php
N.A
```
Error screenshot:-

https://prnt.sc/BDeMgM3jZLDj

While it's working if the number of recipients less then 14.

Also, I couldn't find anywhere in the documentation that gmail api has limits that it cannot send emails to more than 14 people at a time.

Thanks!

**Comment by yash30201** [comment]
Closing this. Please feel free to open if you still happen to face a issue.
