### ISSUE TITLE
management_uploads->uploadData return 503

### ISSUE THREAD

**Issue by araki-takahiro** [googleapis/google-api-php-client#2458]
```
$gaUpload = $analytics->management_uploads->uploadData(
                $accountId,
                $webPropertyId,
                $customDataSourceId,
                [
                    'data' => file_get_contents($csvFilePath),
                    'mimeType' => 'application/octet-stream',
                    'uploadType' => 'media',
                ]
            );
```

return 503 error.
I have been receiving errors continuously for about the past two weeks.
accountId, webPropertyId, customDataSourceId, csvFilePath are correct.
please help

**Comment by LindaLawton** [comment]
Considering that UA analytics will stop recording data in 10 days or so, im not sure why you are bothering.

**Comment by yash30201** [comment]
As UA analytics has been replaced by Google Analytics stating [July 1st, 2023](https://support.google.com/analytics/answer/11583528?hl=en), this issue has become obsolete.
