### ISSUE TITLE
nn

### ISSUE THREAD

**Issue by Cmsoe55** [googleapis/google-api-php-client#2463]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

 **Additional context**

**Comment by LindaLawton** [comment]
@Cmsoe55  this really isn't an issue for the issue forum.  The admins of this repo can add something like that directly in the git project so that when someone clicks new issue they get a message like that.
