### ISSUE TITLE
GTM - Missing endpoint for built-in triggers

### ISSUE THREAD

**Issue by psociety** [googleapis/google-api-php-client#2471]
Built-in triggers are not listed in `triggers/list` endpoint: 
https://developers.google.com/tag-platform/tag-manager/api/v2/reference/accounts/containers/workspaces/triggers/list

There's no parameter to make them show up or specific endpoint.

This is the ouput for v2:
```
Google\Service\TagManager\ListTriggersResponse Object
(
    [collection_key:protected] => trigger
    [nextPageToken] => 
    [triggerType:protected] => Google\Service\TagManager\Trigger
    [triggerDataType:protected] => array
    [internal_gapi_mappings:protected] => Array
        (
        )

    [modelData:protected] => Array
        (
        )

    [processed:protected] => Array
        (
        )
```

**Comment by bshaffer** [comment]
This seems to be an API question rather than a client library question. I'm closing this because there's nothing actionable for us to do on our end.
