### ISSUE TITLE
Google Analytics 4 API

### ISSUE THREAD

**Issue by sajadsaadat** [googleapis/google-api-php-client#2477]
Hello
I use this script to work with Google Analytics data.
Considering that in version 4, we don't have view id anymore and instead it has property id, how can this script be used?

Does this script support Google Analytics version 4?
I used property id instead of view id in the script several times but it didn't work.

**Comment by vishwarajanand** [comment]
@sajadsaadat I am unable to understand your requirement and where it falls short from the provided context. Some snippet will definitely help.

[This link](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id#google_analytics) provides how to fetch a property id. Using property id and the Data API, you should be able to fetch the analytics. [Quickstart sample](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-php)
