### ISSUE TITLE
AdMob v1beta library support

### ISSUE THREAD

**Issue by dmamchyts** [googleapis/google-api-php-client#2502]
According with page https://developers.google.com/admob/api/release-notes - looks like in `v1beta` we can make `CREATE` actions. It's very useful for us. 
Do you have any plans/eta about support of `v1beta`

**Comment by yash30201** [comment]
For a particular product, we only publish the "preferred" version which is marked by the backend product team.  I see that right now, AdMob v1 has been marked as preferred and hence that's the release version in this library.

_More on why we only publish preferred libraries as of now can be read [here](https://github.com/googleapis/google-api-php-client-services/issues/222#issuecomment-719752899)_
