### ISSUE TITLE
Gmail fetch attachment

### ISSUE THREAD

**Issue by EvanCoh** [googleapis/google-api-php-client#251]
Hello Guys,

ok I have a service account and I am using the gmail service and I am able to get all the details of an email from a user. Even the id of an attachment. But when I try this:

$attachment = $service->users_messages_attachments->get($subEmailAddress, $messageId, $attachmentId);

I get an empty response. 
object(Google_Service_Gmail_MessagePartBody)[76]
  public 'attachmentId' => null
  public 'data' => null
  public 'size' => null
  protected 'processed' => 
    array (size=0)
      empty

The above is also true for hardcoded values meaning that there are no encoding/decoding issues. I tried the above values on:
https://developers.google.com/gmail/api/v1/reference/users/messages/attachments/get#try-it

and it worked perfectly. Can you please verify that this part of the code is working? Thank you.

**Comment by skowron-line** [comment]
Im having similar problem, I see that attachments are in message but when I trying to download them through API I am getting empty response.
Message was sent from Apple mail, any other email is correctly downloaded

```
class Google_Service_Gmail_MessagePartHeader#672 (5) {
    public $name =>
    string(8) "X-Mailer"
    public $value =>
    string(23) "Apple Mail (2.3445.9.1)"
    protected $internal_gapi_mappings =>
    array(0) {
    }
    protected $modelData =>
    array(0) {
    }
    protected $processed =>
    array(0) {
    }
  }
```


```
google/apiclient                      v2.2.2             Client library for Google APIs
google/apiclient-services             v0.66              Client library for Google APIs
google/auth                           v1.3.2             Google Auth Library for PHP
```
