### ISSUE TITLE
Provide a way to either add an end screen to a youtube video or a way to "copy from another video"

### ISSUE THREAD

**Issue by abunch** [googleapis/google-api-php-client#2514]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
No.

 **Describe the solution you'd like**
Provide a way to either add an end screen to a youtube video or a way to "copy from another video"

 **Describe alternatives you've considered**
No alternatives exist.

 **Additional context**
No additional context is needed the request is simple.  Provide functionality in the SDK/API to allow adding an end screen to a youtube videoo.

**Comment by saranshdhingra** [comment]
Hi @abunch 
The API client in this repository provides functionality that is closely related to the API reference for each of the products, in this case youtube.

I don't see this functionality in the [rest API reference](https://developers.google.com/youtube/v3/docs), so unfortunately we can't really add that functionality.

If you think that the youtube API should have this feature, then I would recommend you to use the [Youtube support](https://developers.google.com/youtube/v3/support) page instead.

Thanks.
