### ISSUE TITLE
Local Service Ads API - messageLead missing customers Message/Enquiry

### ISSUE THREAD

**Issue by spirie** [googleapis/google-api-php-client#2515]
We've been using the Local Service Ads API for a while now, but Message leads do not contain the actual Message the customer added to their lead/enquiry - it's unavailable to pull out from the API, this is a pretty cruical piece of information missing from the API and should be added

**Comment by yash30201** [comment]
Hi @spirie , sorry for the late reply in this issue.

We request you to please use https://github.com/googleads/google-ads-php library for Ads as it has the complete feature set of what you're looking for.
