### ISSUE TITLE
Question: Customize the login button

### ISSUE THREAD

**Issue by a4992214** [googleapis/google-api-php-client#2517]
Is there a way to change the resulting login button that sits on the screen to be just the word "Login"?

from 
![image](https://github.com/googleapis/google-api-php-client/assets/122558474/4c6ac70a-3473-4fbc-b446-335f4fbc9177)    ....to.... ![image](https://github.com/googleapis/google-api-php-client/assets/122558474/8227c207-51b4-4549-b322-7ca4e9c603e5)

**Comment by vishwarajanand** [comment]
1. This is not a good place to ask Google HTML Api questions
2. Ref the [documentation for HTML Api](https://developers.google.com/identity/gsi/web/reference/html-reference#data-text), which explains limitations of what you're allowed to change.
