### ISSUE TITLE
Basic Question: Method Roles Get

### ISSUE THREAD

**Issue by derekritchison** [googleapis/google-api-php-client#2529]
Hey there- Not a bug, just a question. I feel like I am using the roles.get method (example below) properly according to Google's docs (also below). However, I am getting a 400. I've tried passing the role's ID as `roleId` and as `resource_id` but always get the same response. Has anyone used this method with the PHP client before? Am I missing something obvious?

---

**My code:**

```
try { // Retrieve role assignments for the user
    $roleAssignments = $service->roleAssignments->listRoleAssignments($customerID, ['userKey' => $user['primaryEmail']]);

    foreach ($roleAssignments as $roleAssignment) {
        try {
            $roleName = $service->roles->get($customerID, ['roleId' => $roleAssignment['roleId']]);
            ...and so on.
```

---

**Response:**

HTTP Status Code: 400
Errors: [
    {
        "message": "Invalid data: RolesGetRequest.resource_id",
        "domain": "global",
        "reason": "invalid"
    }
]

---

**Google's docs:**

https://developers.google.com/admin-sdk/directory/reference/rest/v1/roles/get

**Comment by derekritchison** [comment]
I figured this out. The API does not want the roleId sent in an array, but rather just a string. Somewhat confusing given the first call _requires_ the array but whatever.

`$roleName = $service->roles->get($customerID, ['roleId' => $roleAssignment['roleId']]);
`

**Comment by saranshdhingra** [comment]
Glad you figured it out.

We don't have samples for all API calls, so sometimes the only way to be sure is to see the [signature of the method call](https://github.com/googleapis/google-api-php-client-services/blob/8314a572c9b1da586aed465ca1d284a3d12a14e9/src/Directory/Resource/Roles.php#L60).

Often IDEs/editors help with that.

Thanks.
