### ISSUE TITLE
Security vulnerabilities in specific phpseclib/phpseclib dependency

### ISSUE THREAD

**Issue by gravelld** [googleapis/google-api-php-client#2537]
Thanks for this project. Due to these vulnerabilities:

- GHSA-hm7p-r324-hhf3
- GHSA-jpr7-q523-hx25
- GHSA-vf4w-fg7r-5v94

The minimum version for phpseclib/phpseclib should be 3.0.34. This means the entry in composer.json should be:

        "phpseclib/phpseclib": "^3.0.34",

Is this something you are likely to change and issue a release for?

**Comment by bshaffer** [comment]
Fixed in https://github.com/googleapis/google-api-php-client/pull/2524 and released in https://github.com/googleapis/google-api-php-client/releases/tag/v2.15.2
