### ISSUE TITLE
Security vulnerabilities in specific guzzlehttp/psr7 dependency

### ISSUE THREAD

**Issue by gravelld** [googleapis/google-api-php-client#2539]
Thanks for your work on this library.

Due to GHSA-wxmh-65f7-jcvw the minimum version for the 1.x version of guzzlehttp/psr7 should be 1.9.1. This means the entry in composer.json should be:

    "guzzlehttp/psr7": "^1.9.1||^2.2.1"

Is this something you are likely to change and issue a release for?

**Comment by bshaffer** [comment]
fixed in https://github.com/googleapis/google-api-php-client/releases/tag/v2.15.2

**Comment by bshaffer** [comment]
Woops, my mistake. The fix was for `guzzlehttp/guzzle`, not for `guzzlehttp/psr`. Yes please submit a fix, that would be much appreciated!

**Comment by Mohammed-radwan** [comment]
Hi,
Thanx for your effort,
Are you planning to release a fix for this soon?

Thanx
