### ISSUE TITLE
Wrong version constraint for Guzzle dependency in composer.json

### ISSUE THREAD

**Issue by p-golovin** [googleapis/google-api-php-client#2543]
Looks that "guzzlehttp/guzzle": "~6.5.8||~7.4.5" is not correct, because ~7.4.5 is equal to >=7.4.5 and <7.5.0, but the current actual version is 7.8.1.

I think it must be changed to "guzzlehttp/guzzle": "^6.5.8||^7.4.5"

**Comment by p-golovin** [comment]
Create PR #2544

**Comment by bshaffer** [comment]
fixed in https://github.com/googleapis/google-api-php-client/releases/tag/v2.15.3
