### ISSUE TITLE
Remove a particular project permission

### ISSUE THREAD

**Issue by jalpab** [googleapis/google-api-php-client#2545]
I have two projects, one is named 'test' and the other is 'test 2'. I have added the same permissions for a Google account, including webmaster and analytics, for both projects. Now, when I remove the 'test' project that shares the same email ID, the permissions for the 'test 2' project are also removed. Can you please let me know how to remove permissions based on the project?

**Comment by yash30201** [comment]
Hi @jalpab , thanks for finding this bug.
The proper medium for this issue would be https://cloud.google.com/support/docs as is not related to the api php client library's scope.
