### ISSUE TITLE
On PHP 8.3 Calling get_class() without arguments is deprecated in src/Http/REST.php:58

### ISSUE THREAD

**Issue by joshua-bn** [googleapis/google-api-php-client#2548]
`Fatal error: Uncaught ErrorException: Calling get_class() without arguments is deprecated in google/apiclient/src/Http/REST.php:58`

#### Environment details

  - OS: Ubuntu
  - PHP version: 8.3
  - Package name and version: google/apiclient

#### Steps to reproduce

  1. call `Google\Service\ShoppingContent\Resource\Products::custombatch()`

Simple fix is to just do `get_class($this)`

**Comment by yash30201** [comment]
Hi @joshua-bn , 
The fix for this issue has been rolled out as a part of [v2.15.2](https://github.com/googleapis/google-api-php-client/pull/2533). Please upgrade your package.
