### ISSUE TITLE
Error when trying to change thumbnail

### ISSUE THREAD

**Issue by icarojobs** [googleapis/google-api-php-client#2552]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOS M2
  - PHP version: 8.3
  - Package name and version: "google/apiclient": "^2.15.0"

#### Steps to reproduce

  1. After following the authentication flow and get/set the bearer token, I'm trying to change a thumbnail of specific video. I'm using Laravel too.

#### Code example

```php
// After flow of authentication....this is my code:
$service = new Google_Service_YouTube($this->client);

$videoId = "XG96bA9Q9OE";
$newThumbnailPath = storage_path('app/thumbs/1/test1.jpg');

$response = $service->thumbnails->set($videoId, [
    'mimeType' =>  'image/jpeg',
    'data' =>  file_get_contents($newThumbnailPath)
]);

dd($response);
```

Response error:
```json
{
  "error": {
    "code": 403,
    "message": "The thumbnail can't be set for the specified video. The request might not be properly authorized.",
    "errors": [
      {
        "message": "The thumbnail can't be set for the specified video. The request might not be properly authorized.",
        "domain": "youtube.thumbnail",
        "reason": "forbidden",
        "location": "videoId",
        "locationType": "parameter"
      }
    ]
  }
}
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by yash30201** [comment]
Hi @icarojobs , thanks for raising the issue.

Please make sure your account is verified. For more info, see:
1) https://support.google.com/youtube/answer/72431
2) https://stackoverflow.com/questions/38636310/set-custom-thumbnail-via-youtubeapi-doesnt-work-can-someone-tell-me-why

**Comment by icarojobs** [comment]
> Hi @icarojobs , thanks for raising the issue.
> 
> Please make sure your account is verified. For more info, see:
> 1) https://support.google.com/youtube/answer/72431
> 2) https://stackoverflow.com/questions/38636310/set-custom-thumbnail-via-youtubeapi-doesnt-work-can-someone-tell-me-why

Wow! This worked! Thank you! 🔥🚀
