### ISSUE TITLE
Support for Search Ads 360 Reporting API

### ISSUE THREAD

**Issue by AleeeKoi** [googleapis/google-api-php-client#2555]
Hello, 
If I'm not wrong this lib is not supporting yet the new "Search Ads 360 Reporting API".
If so, when will you add it?
Thanks

**Comment by Hectorhammett** [comment]
@AleeeKoi Hello! Thanks for reaching out!

Looking around a bit I found out that the 360 ADS API should be accessible via the `services` library here:
https://github.com/googleapis/google-api-php-client-services

This gets installed once you install the clients library. You should be able to use the API with something similar to this:
```php
$client = new Google\Client();
$client->setApplicationName("YOUR_APP_NAME");
$client->setDeveloperKey("YOUR_API_KEYS");

$service = new Google\Service\SA360($client);
$service->searchAds360Fields();
```

And using the the different resources from the client library. I hope this helps!
