### ISSUE TITLE
Contact Delegation API not implemented

### ISSUE THREAD

**Issue by rcalpha** [googleapis/google-api-php-client#2556]
Hi....

I was trying to do users operation using service account to delegate contact throught the Contact Delegation API, but it seems that it's not implemented in this library yet.

The reference of this API is at:

https://developers.google.com/admin-sdk/contact-delegation/guides?hl=en

**Comment by Hectorhammett** [comment]
@rcalpha Thanks for reaching out!

After taking a look at the code and walking through the code it seems that the PHP client API only supports a subset of the `Admin SDK`. I apologize for the inconvenience.

I suggest filling a bug against the Admin SDK issue tracker here:
https://issuetracker.google.com/savedsearches/566232

For now I would recommend using PHP's native capabilities to access this resource via the API routes noted here:
https://developers.google.com/admin-sdk/contact-delegation/guides/manage-delegates?hl=en

Once again I apologize for the inconvenience, please reach out if you have any more questions!
