### ISSUE TITLE
Wallet API error

### ISSUE THREAD

**Issue by pws2016** [googleapis/google-api-php-client#2557]
Hello,
i try using the API Wallet and i creqte the API key in console with domain restriction.
But the code return me an error:
`[{"message":"Login Required.","domain":"global","reason":"required","location":"Authorization","locationType":"header"}]`

I use the PHP library and i write this code: 
`$client = new Google\Client();		
$client->setApplicationName('Wallet Objects App');
$client->setDeveloperKey(GOOGLE_WALLET_API_KEY);`

How i can fix this?

Thanks

**Comment by bshaffer** [comment]
Hello @pws2016 !

The code you've provided looks correct to me - could you provide the rest of your code as well so we can help you debug better?

**Comment by Hectorhammett** [comment]
Closing the issue due inactivity.

Please let us know if we can help you further with a code example @pws2016 :)
