### ISSUE TITLE
What is redirect url 

### ISSUE THREAD

**Issue by syed-ahmad-dilshad** [googleapis/google-api-php-client#2559]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.
Request details: redirect_uri=https://smmpro.one/
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)

**Comment by saranshdhingra** [comment]
The redirect URI is the URL where your oauth enabled application redirects to with the required access token/code.
You can set this while creating a new oAuth client ID in the Google cloud console.

![image](https://github.com/googleapis/google-api-php-client/assets/1038319/a3efd959-8cf0-4414-931e-112e24e11fb9)

Please read about this in the [Authentication section of the readme](https://github.com/googleapis/google-api-php-client?tab=readme-ov-file#authentication-with-oauth).
