### ISSUE TITLE
Problem retrieving domain user list

### ISSUE THREAD

**Issue by claudiobat** [googleapis/google-api-php-client#2564]
Hi,
I'd like to get the list of the users of the domain using "google-api-php-client".
As SuperAdmin on the Google backend I have:
- Activated the library: Admin SDK API (Cloud console)
- Created a service account called "myserviceaccount@mydomain.com" (Cloud console)
- Created the credentials for "myserviceaccount@mydomain.com" (Cloud console) and downloaded the json with these credentials: config_google.json
- Given to the myserviceaccount@mydomain.com the domain delegation for the scopes: "https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/admin.directory.domain" (Admin console)

However, when executing the "listUsers" method I have the error:

`{ "error": { "code": 403, "message": "Not Authorized to access this resource/api", "errors": [ { "message": "Not Authorized to access this resource/api", "domain": "global", "reason": "forbidden" } ] } }`

This is the code I'm using:

`        $serviceAccountPath = base_path().'/config_google.json';
        $credentials = json_decode(file_get_contents($serviceAccountPath), true);

        $this->client = new Client();
        $this->client->setApplicationName('Google Workspace Directory API');
        $this->client->setAuthConfig($credentials);
        $this->client->setScopes([
            'https://www.googleapis.com/auth/admin.directory.domain',
            'https://www.googleapis.com/auth/admin.directory.user',
            'https://www.googleapis.com/auth/admin.directory.group',
        ]);

        $service = new Directory($this->client);
        $users = $service->users->listUsers([
            'domain' => 'mydomain.com',
        ]);
`
What could be the problem? How can I solve it?
Thank you very much

Claudio

**Comment by claudiobat** [comment]
Hi all,
I've solved specifying the "sub" parameter in the request.

claudio

**Comment by shankar0015** [comment]
@claudiobat can you post the working code?
