### ISSUE TITLE
Support for "forHandle" parameter in youtube->channels->list request

### ISSUE THREAD

**Issue by alexschastny** [googleapis/google-api-php-client#2578]
i'm noted in the [changelog](https://developers.google.com/youtube/v3/revision_history#january-31,-2024) that at 31.01.2024 api should support `forHandle`, but when i try to use it on the latest lib `"google/apiclient": "^2.15.3"` like

```
$result = $this->getYoutubeService()->channels->listChannels('id', ['forHandle' => $channelName]);
```
I get an exception
```
[2024-03-14T08:04:46.185822-07:00] google-api-php-client.ERROR: Service parameter unknown {"service":"youtube","resource":"channels","method":"list","parameter":"forHandle"} []
[error] Error processing stream ID: 9c400592-d638-11ee-9bf2-bd306e8dd87c with exception message: (list) unknown parameter: 'forHandle'
```

i guess that `forHandle` released at 31.01.2024, but lib `2.15.3` released at 04.01.2024, so looks like it just not supported yet, am i right?

**Comment by dmitriynet** [comment]
Have the same problem, do you have some progress with it?

**Comment by yash30201** [comment]
Hi @alexschastny, thanks for asking this question.

I can see that `forHandle` option has been added and released in [google-api-php-client-services](https://github.com/googleapis/google-api-php-client-services/pull/4553/files#diff-736101bf214b4b470e13f19e8a9b70307b43d5c041d73c759b5fdc6f85eb6b13) on 5th Feb 2024.

This library depends upon the `google-api-php-client-services` (see [composer.json](https://github.com/googleapis/google-api-php-client/blob/main/composer.json#L11)) and all the service related files comes from there.

You can take advantage of latest product enhancements just by running a `composer update` from the root of your `google-api-client-php` as new library features don't depend upon `google-api-client-php` releases.

Please let me know if running `composer update` solved your issue.

**Comment by alexschastny** [comment]
Hey @yash30201 thanks for the help! Definitely, it is enough just to update the dependency `google/apiclient-services` 🔥
