### ISSUE TITLE
Hey, I’ve been working with Swoole and I think there’s an issue when the application runs in a resident memory environment

### ISSUE THREAD

**Issue by yapengsoft** [googleapis/google-api-php-client#2583]
#### Environment details
  - OS:
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

  - PHP version:
  -php  8.1.x   swoole
  - Package name and version:
  - "google/apiclient": "^2.15",

#### Steps to reproduce

  When I have two different client IDs, after creating an authorized link using the first client ID, if I then try to create another authorized link using the second client ID, the program keeps using the first client ID due to the existence of the getOAuth2Service method
  And Is there a need for the getOAuth2Service method to exist?

#### Code example

![image](https://github.com/googleapis/google-api-php-client/assets/75244754/f72efc84-bfbd-4d15-9335-d99feace1f81)

**Comment by ajupazhamayil** [comment]
Could you please give me code to reproduce this issue?

**Comment by Hectorhammett** [comment]
Closing this issue due inactivity. Please feel free to comment back if you still have the same issue!
