### ISSUE TITLE
Uncaught TypeError: Argument must be an instance of RenderAccountIssuesRequestPayload

### ISSUE THREAD

**Issue by shurc1** [googleapis/google-api-php-client#2585]
When I try to call such function in my script.php file, it trow the error.

  `public function get_info($accountId) {
    $status = $this->session->service->merchantsupport->renderaccountissues(
        $this->session->merchantId, '{ "contentOption": "CONTENT_OPTION_UNSPECIFIED" }');
return $status;
  }`

**The error is:**
<b>Fatal error</b>:  Uncaught TypeError: **Argument 2** passed to Google\Service\ShoppingContent\Resource\Merchantsupport::renderaccountissues() **must be an instance of Google\Service\ShoppingContent\RenderAccountIssuesRequestPayload**, string given, called in /home/tatam0/tadam/test/php_merchant_api/AccountstatusesSample.php on line 65 and defined in /home/tatam0/tadam/test/php_merchant_api/vendor/google/apiclient-services/src/ShoppingContent/Resource/Merchantsupport.php:54

Here is documentation on this funtcion **renderaccountissues()**
https://developers.google.com/shopping-content/reference/rest/v2.1/merchantsupport/renderaccountissues

https://prnt.sc/iKGzL5HCHGTx - I did as it says

What does mean "must be an instance of RenderAccountIssuesRequestPayload"? I do not understand, how can I change my code to make this funnction work correctly?

[Merchantsupport.php.txt](https://github.com/googleapis/google-api-php-client/files/14848650/Merchantsupport.php.txt)
[RenderAccountIssuesRequestPayload.php.txt](https://github.com/googleapis/google-api-php-client/files/14848651/RenderAccountIssuesRequestPayload.php.txt)

**Comment by ajupazhamayil** [comment]
The link you provided talks about HTTP request and response. When you use it via this client, you may need to look at the code to understand how you could leverage this client. Eg: See here: https://github.com/googleapis/google-api-php-client-services/blob/a053f7dd118e46845fcefa9036c5b97b1050dfaa/src/ShoppingContent/Resource/Merchantsupport.php#L56, it is expecting `RenderAccountIssuesRequestPayload` in the function. Hope you can take it up from here, thanks!
