### ISSUE TITLE
Custom Namespace issue on google analytics-admin and analytics-data php api.

### ISSUE THREAD

**Issue by bilal-ahmed-wpb** [googleapis/google-api-php-client#2586]
A question raised in my mind. The files in which there is the following comment:

Generated by the protocol buffer compiler. DO NOT EDIT!
In google/analytics-admin and google/analytics-data can I add my custom plugin namespace on them and will they work then?

And to make them work as I am using php-scoper to contain them under my own custom namespace in order to avoid plugin conflicts on Wordpress. Any guidance on this please.

**Comment by ajupazhamayil** [comment]
To give you a context on the comment, the code is fully generated by a generator and, in normal scenarios, if we change that code and merge it to the repository, the generator will generate the code again and overwrite it in the repository (local machines are safe on this overwrite as long as you don't pull the latest, but local machine will be stuck with the old code). Thats why we have that warning.

Hope this information helps.

**Comment by Hectorhammett** [comment]
Hello @bilal-ahmed-wpb !

@ajupazhamayil is correct, this code is automatically generated from protobuffs from each API team, that way they can make any necessary changes and the code gets generated for the library :).

So editing the code inside the library is not advised. I recommend you to check the documentation for the `php-scoper` library.

Closing this as this is a question related to `php-scoper` and `wordpress`. If you have any specific questions about the usage of the library, please feel free to comment back!
