### ISSUE TITLE
allow gzip for API calls

### ISSUE THREAD

**Issue by molecularbear** [googleapis/google-api-php-client#26]
The [documentation](https://developers.google.com/admin-sdk/groups-settings/performance#gzip) recommends using gzip for API calls, but it doesn't look like the php-client is doing this. I thought maybe the `Google_Service` or `Google_Service_Resource` classes would be able to customize the headers of the `Google_Http_Request` object they ultimately call, but there didn't seem to be a way to do that.

Thanks for listening!

**Comment by vdbMark** [comment]
Hi, i just found this issue and have been taking a closer look at the packages.
It seems the functionality to add the GZIP header has been removed.
Is there still a way to add it manualy?

**Comment by jdpedrie** [comment]
You should be able to enable gzip encoding by providing a custom HTTP client instance:

```php
use GuzzleHttp\Client;

$google = new Google_Client;

$google->setHttpClient(new Client([
  'headers' => ['Accept-Encoding' => 'deflate, gzip']
]));
```

In my tests, this will result in gzipped responses.

**Comment by vdbMark** [comment]
Thanks!!
