### ISSUE TITLE
Call to undefined function GuzzleHttp\Promise\settle()

### ISSUE THREAD

**Issue by adem-genc53** [googleapis/google-api-php-client#2610]
Although I installed the latest version of "google-api-php-client", we can't fix the "Promise" error.
I'm updating with "Composer" but we can't fix the "Promise" error.
What am I doing wrong?

The following code is the code to create a folder tree.
`include __DIR__ . '/google_drive_setup.php';
use GuzzleHttp\Client;
use GuzzleHttp\Promise;

class GoogleDriveTreeView {
    private $service;
    private $folderId;
    private $client;

    public function __construct($service, $folderId = 'root') {
        $this->service = $service;
        $this->folderId = $folderId;
        $this->client = new Client();
        ob_start();
        ini_set('memory_limit', '-1');
        ignore_user_abort(true);
        set_time_limit(3600); // 1 saat
    }

    public function showSize($size_in_bytes) {
        if ($size_in_bytes >= 1073741824) {
            return number_format($size_in_bytes / 1073741824, 2) . ' GB';
        } elseif ($size_in_bytes >= 1048576) {
            return number_format($size_in_bytes / 1048576, 2) . ' MB';
        } elseif ($size_in_bytes >= 1024) {
            return number_format($size_in_bytes / 1024, 2) . ' KB';
        } elseif ($size_in_bytes >= 1) {
            return $size_in_bytes . ' Bayt';
        } else {
            return '0 Bayt';
        }
    }

    private function fetchFiles($query) {
        $pageToken = null;
        $files = [];

        do {
            $response = $this->service->files->listFiles([
                'q' => $query,
                'pageToken' => $pageToken,
                'fields' => 'nextPageToken, files(id, name, mimeType, size)',
                'orderBy' => 'name',
            ]);

            $files = array_merge($files, $response->files);
            $pageToken = $response->nextPageToken;
        } while ($pageToken);

        return $files;
    }

    private function fetchFileDetailsParallel($fileIds) {
        $promises = [];
        foreach ($fileIds as $fileId) {
            $promises[$fileId] = $this->client->getAsync("https://www.googleapis.com/drive/v3/files/{$fileId}?fields=size");
        }
        $results = Promise\settle($promises)->wait();
        $sizes = [];
        foreach ($results as $fileId => $result) {
            if ($result['state'] === 'fulfilled') {
                $sizes[$fileId] = json_decode($result['value']->getBody(), true)['size'] ?? 0;
            } else {
                $sizes[$fileId] = 0;
            }
        }
        return $sizes;
    }

    public function getFilesAndFolders() {
        $query = "'{$this->folderId}' in parents";
        $files = $this->fetchFiles($query);

        $drive_dizinler_arr = [];
        $drive_dosyalar_arr = [];

        $fileIds = array_map(function($file) { return $file->id; }, $files);
        $sizes = $this->fetchFileDetailsParallel($fileIds);

        foreach ($files as $file) {
            if ($file->mimeType == 'application/vnd.google-apps.folder') {
                $drive_dizinler_arr[$file->id][$this->showSize($sizes[$file->id])] = $file->name;
            } else {
                $drive_dosyalar_arr[$file->id][$this->showSize($sizes[$file->id])] = $file->name;
            }
        }

        return [$drive_dizinler_arr, $drive_dosyalar_arr];
    }

    public function emptyDir($dirid) {
        $query = "'$dirid' in parents";
        $files = $this->fetchFiles($query);
        return count($files);
    }

    public function generateList() {
        list($drive_dizinler_arr, $drive_dosyalar_arr) = $this->getFilesAndFolders();
        $list = '<ul id="uzak" class="filetree" style="display: none;">';

        foreach ($drive_dizinler_arr as $id => $arr_devam) {
            foreach ($arr_devam as $boyutu => $dizin_adi) {
                if ($this->emptyDir($id) == '0') {
                    $list .= '<li class="folder collapsed"><a href="#" rel="' . $id . '" adi="' . $dizin_adi . '">' . $dizin_adi . '<span style="float: right;color: black;padding-right: 10px;">4 KB</span></a></li>';
                } else {
                    $list .= '<li class="folder_plus collapsed"><a href="#" rel="' . $id . '" adi="' . $dizin_adi . '">' . $dizin_adi . '<span style="float: right;color: black;padding-right: 10px;">4 KB</span></a></li>';
                }
            }
        }

        foreach ($drive_dosyalar_arr as $id => $devam_arr) {
            foreach ($devam_arr as $boyutu => $dosya_adi) {
                $ext = preg_replace('/^.*\./', '', $dosya_adi);
                $list .= '<li class="file ext_' . $ext . '"><a href="#" rel="' . $id . '" adi="' . $dosya_adi . '">' . $dosya_adi . '<span style="float: right;color: black;padding-right: 10px;">' . $boyutu . '</span></a></li>';
            }
        }

        $list .= '</ul>';
        return $list;
    }
}

$folderId = isset($_POST['dir']) ? $_POST['dir'] : 'root';
$driveManager = new GoogleDriveTreeView($service, $folderId);
echo $driveManager->generateList();
`

**Comment by Hectorhammett** [comment]
Hello @adem-genc53! Thanks for reaching out!

So this seems to be an issue related with the `GuzzleHttp` library more than the client library itself. Still, I think I might be able to help you.

To my understanding, there is no `Promise\settle()` method in that namespace. If we take a look at the `Promise` class there is a private method for `settle` in there but it is private.

Reading the documentation of the `Promise` library from `GuzzleHttp`:
https://github.com/guzzle/promises

There seems to be a migration from version in the library. Here is a reference to the table in the link above:
![image](https://github.com/user-attachments/assets/14efdfd8-43d0-4994-bc99-6543a83c851b)

It seems that the `settle` function has been moved to the `Utils` class so I'd suggest changing:
```php
$results = Promise\settle($promises)->wait();
```

to:
```php
use GuzzleHttp\Promise\Utils;
...
$results = Utils::settle($promises)->wait();
```

Hope this helps! Closing the issue as it is unrelated to the client libraru itself. If you think this is related to the client library please give us a comment again so we re open the issue :).

Good luck!

**Comment by adem-genc53** [comment]
I'm sorry, I sent the wrong code without realizing it.

`use Google\Client as GoogleClient;
use Google\Service\Drive;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Promise\Utils;

class GoogleDriveDownloader {
    private $service;
    private $client;

    public function __construct($service, $client) {
        $this->service = $service;
        $this->client = $client;
    }

    private function listFiles($secilen_dizin, $folderId, $path = '') {
        $resultArray = [];
        $results = $this->service->files->listFiles([
            'q' => "'$folderId' in parents",
        ]);

        foreach ($results->getFiles() as $file) {
            $filePath = $path . '/' . $file->getName();

            if ($file->mimeType == 'application/vnd.google-apps.folder') {
                $resultArray = array_merge($resultArray, $this->listFiles($secilen_dizin, $file->getId(), $filePath));
                $resultArray[$file->getId()][$file->mimeType] = "/" . $secilen_dizin . $filePath;
            } else {
                $resultArray[$file->getId()][$file->mimeType] = "/" . $secilen_dizin . $filePath;
            }
        }
        return $resultArray;
    }

    public function downloadFile($yerel_hedef, $google_kaynak, $fileId) {
        if (pathinfo($google_kaynak, PATHINFO_EXTENSION)) {
            $file = $this->service->files->get($fileId, ['fields' => 'id,size']);

            if (intval($file->size) <= 0) {
                echo "Dosya boyutu geçersiz.";
                return;
            }

            $fileSize = intval($file->size);
            $http = new GuzzleClient(['base_uri' => 'https://www.googleapis.com']);
            $fp = fopen(rtrim($yerel_hedef, '/') . "/" . $google_kaynak, 'w');
            $chunkSizeBytes = 10 * 1024 * 1024; // 10 MB
            $promises = [];
            $chunkStart = 0;

            while ($chunkStart < $fileSize) {
                $chunkEnd = min($chunkStart + $chunkSizeBytes, $fileSize - 1);
                $range = sprintf('bytes=%s-%s', $chunkStart, $chunkEnd);
                $promises[] = $http->requestAsync('GET', sprintf('/drive/v3/files/%s', $fileId), [
                    'query' => ['alt' => 'media'],
                    'headers' => ['Range' => $range],
                ])->then(function($response) use ($fp) {
                    fwrite($fp, $response->getBody()->getContents());
                });
                $chunkStart = $chunkEnd + 1;
            }

            Promise\all($promises)->wait();
            fclose($fp);
            echo "<br /><b>Yerel </b> " . $yerel_hedef . " <b>dizine</b><br />";
            echo $google_kaynak . " <b>[İNDİRİLDİ]</b>";
        } else {
            $secilen_dizin = $google_kaynak;
            $googleden_secilen_dizin_arr[$fileId]['application/vnd.google-apps.folder'] = "/" . $google_kaynak;
            $filePathsArray = $this->listFiles($secilen_dizin, $fileId);
            $secilen_googleden_secilen_array = array_merge($googleden_secilen_dizin_arr, $filePathsArray);

            echo "<br /><b>Yerel </b> " . $yerel_hedef . " <b>dizine</b><br />";

            foreach ($secilen_googleden_secilen_array as $id => $dosya_tipi_dosya_adi) {
                foreach ($dosya_tipi_dosya_adi as $dosya_tipi => $dosya_adi) {
                    if ($dosya_tipi == 'application/vnd.google-apps.folder') {
                        if (!file_exists($yerel_hedef . $dosya_adi)) {
                            mkdir($yerel_hedef . $dosya_adi, 0755, true);
                        }
                    }
                }
            }

            foreach ($secilen_googleden_secilen_array as $id => $dosya_tipi_dosya_adi) {
                foreach ($dosya_tipi_dosya_adi as $dosya_tipi => $dosya_adi) {
                    if ($dosya_tipi != 'application/vnd.google-apps.folder') {
                        $file = $this->service->files->get($id, ['fields' => 'id,size']);

                        if (intval($file->size) <= 0) {
                            echo "Dosya boyutu geçersiz.";
                            continue;
                        }

                        $fileSize = intval($file->size);
                        $http = new GuzzleClient(['base_uri' => 'https://www.googleapis.com']);
                        $fp = fopen($yerel_hedef . $dosya_adi, 'w');
                        $chunkSizeBytes = 10 * 1024 * 1024;
                        $promises = [];
                        $chunkStart = 0;

                        while ($chunkStart < $fileSize) {
                            $chunkEnd = min($chunkStart + $chunkSizeBytes, $fileSize - 1);
                            $range = sprintf('bytes=%s-%s', $chunkStart, $chunkEnd);
                            $promises[] = $http->requestAsync('GET', sprintf('/drive/v3/files/%s', $id), [
                                'query' => ['alt' => 'media'],
                                'headers' => ['Range' => $range],
                            ])->then(function($response) use ($fp) {
                                fwrite($fp, $response->getBody()->getContents());
                            });
                            $chunkStart = $chunkEnd + 1;
                        }

                        Promise\all($promises)->wait();
                        fclose($fp);
                        echo $dosya_adi . " <b>[İNDİRİLDİ]</b><br />";
                    }
                }
            }
        }
    }
}

ini_set('memory_limit', '-1');
ignore_user_abort(true);
set_time_limit(3600);


if (isset($_POST['yerel_den_secilen_dosya']) && isset($_POST['google_drive_dan_secilen_dosya_id'])) {
    $yerel_hedef = rtrim($_POST['yerel_den_secilen_dosya'], '/');
    $google_kaynak = trim($_POST['google_drive_dan_secilen_dosya_adini_goster'], '/');
    $fileId = $_POST['google_drive_dan_secilen_dosya_id'];

    $downloader = new GoogleDriveDownloader($service, $client);
    $downloader->downloadFile($yerel_hedef, $google_kaynak, $fileId);
} else {
    echo "Kaynak ve indirilecek dizin seçilmelidir";
}`

Error message: Call to undefined function Promise\all()
`Promise\all($promises)->wait();`

Thank you for your help

**Comment by ocarlosapenas** [comment]
The 403 error occurs in the GoogleDriveDownloader class because it is making the request with GuzzleClient without using the Bearer token.
Change from this:
```
'headers' => ['Range' => $range],
```

to this:
```
'headers' => [
    'Range' => $range,
    'Authorization' => 'Bearer ' . $this->service->getClient()->getAccessToken()['access_token']
]
```
