### ISSUE TITLE
Backporting PHP 8.4 compatibility

### ISSUE THREAD

**Issue by mikkamp** [googleapis/google-api-php-client#2640]
PHP 8.4 compatibility was released in version [2.18.1](https://github.com/googleapis/google-api-php-client/releases/tag/v2.18.1) through PR #2638 

We need to offer compatibility to PHP 7.4+ meaning we are currently locked to the last version which supported PHP 7.4 (version [2.16.0](https://github.com/googleapis/google-api-php-client/releases/tag/v2.16.0))

So we'd like to request for the PHP 8.4 compatibility to be backported to this same version to be able to support PHP 7.4 up to and including PHP 8.4.

**Comment by bshaffer** [comment]
fixed in `v2.16.1`
