### ISSUE TITLE
$jwt typing error on AccessToken\Verify

### ISSUE THREAD

**Issue by gaea44** [googleapis/google-api-php-client#2641]
#### Environment details

  - OS: Linux Mint 21.3 
  - PHP version: 8.3.14
  - Package name and version: google/apiclient v2.18.1

#### Steps to reproduce

  1. instanciate a new Google Client with a $jwt oject 
```php
$client = new Google\Client();
$jwt = new Firebase\JWT\JWT();
$jwt::$leeway = 50;

$client->setConfig('jwt', $jwt);
```
  2. Call VerifyIdToken with the client
```php
$client->verifyIdToken($someApiToken);
```
  3. A 500 error is thrown
`Google\\AccessToken\\Verify::__construct(): Argument #3 ($jwt) must be of type ?string, Firebase\\JWT\\JWT given, called in \/home\/bbousba\/dev\/provider-api\/vendor\/google\/apiclient\/src\/Client.php on line 848`

The error is due to the newly `?string` typing in `src/AccessToken/Verify.php` l.72 where it should be `?Firebase\JWT\JWT`

```php
public function __construct(
    ClientInterface $http = null,
    CacheItemPoolInterface $cache = null,
    ?string $jwt = null
)
```

Thanks!

**Comment by bshaffer** [comment]
Fixed in [`v2.18.21](https://github.com/googleapis/google-api-php-client/releases/tag/v2.18.2)

Thanks for reporting this!
