### ISSUE TITLE
unble to found Google_Client.php and contrib/Google_AnalyticsService.php

### ISSUE THREAD

**Issue by rakheekadam** [googleapis/google-api-php-client#318]
unble to found Google_Client.php and contrib/Google_AnalyticsService.php

code mention below two files.

require_once dirname(**FILE**).'/GoogleClientApi/Google_Client.php';
require_once dirname(**FILE**).'/GoogleClientApi/contrib/Google_AnalyticsService.php';

can you please add above files

**Comment by craigiswayne** [comment]
# For newer versions of the Google API
```
 new Google_Service_Analytics( $google_client );
```
