### ISSUE TITLE
Adding the Search API

### ISSUE THREAD

**Issue by dinozombie** [googleapis/google-api-php-client#328]
I wanted to congratulate you guys on the awesome work you've doing lately.

However I've been wondering, are you planning on adding Search API support for PHP? Or is there a way I can access it from PHP?

**Comment by tomwalder** [comment]
Sorry, (very) late reply. If you want to access the Search API from AppEngine, you can do it with this:

https://github.com/tomwalder/php-appengine-search

It will not work remotely - it uses the Protocol Buffer access which only works from AppEngine.

Disclaimer: I am the author.
