### ISSUE TITLE
No support for Android Publisher apk upload?

### ISSUE THREAD

**Issue by doapp-ryanp** [googleapis/google-api-php-client#329]
From what I can tell there is no support in this lib for [Edits.apks: upload](https://developers.google.com/android-publisher/api-ref/edits/apks/upload).  The `Google_Service_AndroidPublisher_EditsApks_Resource` [code](https://developers.google.com/android-publisher/api-ref/edits/apks/upload) looks to not allow specification of `uploadType` query param AND it has no way to specify the APK binary that will be sent in the body of the POST.

I hope I am overlooking something. If so, can you please provide a code snippet?

If you look at the official python lib, you can see how they are [sending the apk in the body](https://github.com/googlesamples/android-play-publisher-api/blob/master/v2/python/basic_upload_apks.py#L55) as part of their `upload` method

**Comment by benaduggan** [comment]
Is there a way to feed the apk to the client in a stream? 

doing a "file_get_contents($localApkPath)" can get hairy if we're talking apps that could easily be several hundred mbs.

**Comment by joshuatam** [comment]
Hi @doapp-ryanp it is not working

```
{ "error": { "errors": [ { "domain": "androidpublisher", "reason": "editNotFound", "message": "Edit not found for this application." } ], "code": 404, "message": "Edit not found for this application." } }
```

**Comment by doapp-ryanp** [comment]
@joshuatam I'm guessing the newer versions of the SDK dont allow this. My post was from 2014.

**Comment by joshuatam** [comment]
@doapp-ryanp I finally get it working, the reason for the error is that the editid supplied is wrong.

**Comment by long1eu** [comment]
Hi @joshuatam ! Where can I get the editId?

**Comment by Christophe235** [comment]
To get the editID, you have to make a http request like this:
https://developers.google.com/android-publisher/api-ref/edits/insert

@long1eu
