### ISSUE TITLE
YouTubePartner.php not found

### ISSUE THREAD

**Issue by JavierGonzalez** [googleapis/google-api-php-client#39]
Hello

We here at Altafonte Music Network are trying to connect our automated system with your APIs. We’re working with Google API YoutubePartners. 

Our main goal is to upload audio references to match and automatically claim videos. We work ok PHP.

We’re following this example:
https://developers.google.com/youtube/partner/code_samples/php#uploading_a_new_reference__so_youtube_can_automatically_generate_claims_for_newly_uploaded_videos_on_behalf_of_the_asset_s_owner
(second half of the doc)

We got it through the old API (Google API PHP Client 0.6.7) and the "Google_YouTubePartnerService.php" file we found here: https://developers.google.com/youtube/partner/client_libraries , but this isn’t useful because we need “Service account” authentication, and the API doesn’t work with this.

So, we tried with Google API PHP Client 1.0.0 unsuccessfully. We get the authentication but we need to find this file: "Google/Service/YouTubePartner.php”, called by your example on the URL mentioned above: https://developers.google.com/youtube/partner/code_samples/php

Thanks for your help!

**Comment by alexandria757** [comment]
YouTubePartner.php is part of the Content ID API Client Libraries.

https://developers.google.com/youtube/partner/client_libraries

It's not currently included in the Google API PHP Client Libraries. 

There is a also a composer ready version of it created by another developer on github and packagist.org.
