### ISSUE TITLE
Google Calendar API - It retrieve the wrong calendar background color

### ISSUE THREAD

**Issue by sebastijanbauman** [googleapis/google-api-php-client#413]
Hi there,

I am using this API to access Google Calendar but having trouble with calendar background color. Basically it never display the right background color whatever I set on the Google Calendar site.

I can't find a solution, please help.

**Comment by nick-van-h** [comment]
Possibly I'm running into the same issue, see also my question on StackOverflow:
https://stackoverflow.com/questions/70633950/how-to-get-correct-color-value-for-preset-google-calendar-colors-via-api?noredirect=1#comment124892655_70633950

Not sure if TS is running into the same issue? The problem description is quite vague.
