### ISSUE TITLE
Google_Service_YouTube_Video->getId Null

### ISSUE THREAD

**Issue by modmanx** [googleapis/google-api-php-client#420]
I'm doing resumable video upload to youtube. I would like to get video ID, using getId method on Google_Service_YouTube_Video object. I did follow documentation, but I can not see what I'm doing wrong. Procedure:

```
$snippet = new Google_Service_YouTube_VideoSnippet();
// ...
$status = new Google_Service_YouTube_VideoStatus();
// ...
$video = new Google_Service_YouTube_Video();
$video->setSnippet($snippet);
$video->setStatus($status);
// ...
$this->gclient->setDefer(true);
$insertRequest = $this->youtube->videos->insert("status,snippet", $video);
$videoId = $video->getId(); // returns null
// ...
$media = new Google_Http_MediaFileUpload
// ... uploading
```

Uploading finishes OK and it's working after processing on YouTube.

**Comment by HeadStudios** [comment]
I just searched for 'Google_Service_YouTube_Video' in this repository and can't find it - can anyone explain why this works when the function isn't available?
