### ISSUE TITLE
Config.php line 130 -134

### ISSUE THREAD

**Issue by slxjhuang** [googleapis/google-api-php-client#424]
Maybe I am silly, but after upgrade the library, error coming.....my application is hosted on google app engine, and I assume it should related to curl is not allowed on google app engine? I make it work just simply comment out line 130 - 134. Please have a look

Use of undefined constant CURLE_COULDNT_RESOLVE_HOST - assumed 'CURLE_COULDNT_RESOLVE_HOST' [CORE/Google/Config.php, line 130]

Use of undefined constant CURLE_COULDNT_CONNECT - assumed 'CURLE_COULDNT_CONNECT' [CORE/Google/Config.php, line 131]

Use of undefined constant CURLE_OPERATION_TIMEOUTED - assumed 'CURLE_OPERATION_TIMEOUTED' [CORE/Google/Config.php, line 132]

Use of undefined constant CURLE_SSL_CONNECT_ERROR - assumed 'CURLE_SSL_CONNECT_ERROR' [CORE/Google/Config.php, line 133]

Use of undefined constant CURLE_GOT_NOTHING - assumed 'CURLE_GOT_NOTHING' [CORE/Google/Config.php, line 134]

**Comment by Wayn0** [comment]
I can confirm, I had the issue today.

**Comment by kennywyland** [comment]
I also had the issue, but I'm using the 2.0 version of the api (I think it's v1-master branch). I tried enabling curl_lite in my Google App Engine config, which made the Notices go away but none of my API calls would work after that. 

```
Notice: Use of undefined constant CURLE_COULDNT_RESOLVE_HOST - assumed 'CURLE_COULDNT_RESOLVE_HOST' in vendor/google/apiclient/src/Google/Http/REST.php on line 46

Notice: Use of undefined constant CURLE_COULDNT_CONNECT - assumed 'CURLE_COULDNT_CONNECT' in vendor/google/apiclient/src/Google/Http/REST.php on line 46

Notice: Use of undefined constant CURLE_OPERATION_TIMEOUTED - assumed 'CURLE_OPERATION_TIMEOUTED' in vendor/google/apiclient/src/Google/Http/REST.php on line 46

Notice: Use of undefined constant CURLE_SSL_CONNECT_ERROR - assumed 'CURLE_SSL_CONNECT_ERROR' in vendor/google/apiclient/src/Google/Http/REST.php on line 46

Notice: Use of undefined constant CURLE_GOT_NOTHING - assumed 'CURLE_GOT_NOTHING' in vendor/google/apiclient/src/Google/Http/REST.php on line 46
```
