### ISSUE TITLE
Is it possible to return a csv for the API request that allows it

### ISSUE THREAD

**Issue by maxgalbu** [googleapis/google-api-php-client#508]
Examples:
- https://developers.google.com/ad-exchange/seller-rest/reference/v2.0/accounts/reports/generate
- https://developers.google.com/adsense/management/v1.4/reference/accounts/reports/generate#try-it

These requests allow a alt=csv param, but throws an exception when I use it.

**Comment by ianbarber** [comment]
Whats the exception? There was a question about alt=media downloads the other day - we may need to extend the same raw response handling to alt=cvs.

**Comment by maxgalbu** [comment]
The exception is on this line: https://github.com/google/google-api-php-client/blob/master/src/Google/Http/REST.php#L121

Should i call setExpectedRaw(true)?

**Comment by ianbarber** [comment]
Yeah, enabledExpectedRaw and getExpectedRaw are the right way - but I think we might need to add the check on that from alt="media" or alt = "media" or "csv"

**Comment by tmatsuo** [comment]
@maxgalbu Is the link in https://github.com/google/google-api-php-client/issues/508#issuecomment-84279445 still pointing to the right code?

**Comment by maxgalbu** [comment]
Probably this line is more correct:

https://github.com/google/google-api-php-client/blob/e190c5b2ed586eaef431d4d0e5f7d6e72c0deb71/src/Google/Http/REST.php#L121

**Comment by mattwhisenhunt** [comment]
This is (now?) possible it is just poorly documented. #1140 is tracking it as a docs issue.
