### ISSUE TITLE
Requests don't specify response format (alt=json)

### ISSUE THREAD

**Issue by erickoledadevrel** [googleapis/google-api-php-client#559]
Most Google APIs default to JSON as the response format. However, this is not universal, and the Admin SDK Groups Settings API defaults to XML. The library expects a JSON response but doesn't set the alt parameter, resulting in errors like this:

```
PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 
'Invalid json in service response: <?xml version="1.0" encoding="UTF-8"?>
...
```

The library should explicitly set the alt parameter to ensure it always gets a JSON response. As a workaround the alt parameter can be manually set by the caller:

```
$group = $service->groups->get($groupEmail, array('alt' => 'json'));
```

**Comment by ianbarber** [comment]
I think the place to fix this is in the generated code. The default is specified in the alt parameter description, so we could specify json if atom is the default. Probably a reasonable work around to alwasys specify json as a default in the request object though.

**Comment by erickoledadevrel** [comment]
I would suggest the ladder. Regardless of what the API supports or defaults to, the library must have JSON returned in order to function correctly. Therefore I think it should explicitly request it for all requests.

**Comment by ianbarber** [comment]
Mostly - we can handle raw media download requests as well, so any patch needs to make sure it doesn't clobber the alt handling for that stuff. There is also a standing bug to handle CSV default format responses which would likely be fixed by respecting the default download type (there are some API calls which respond in CSV by default).

**Comment by mattwhisenhunt** [comment]
Fixed in https://github.com/googleapis/google-api-php-client-services/pull/132/commits/f59a178b5441dd170c943aed56afd8748b90734a
