### ISSUE TITLE
Google_Service_Oauth2 get user info

### ISSUE THREAD

**Issue by alvarolb** [googleapis/google-api-php-client#6]
I am unable of retrieving authenticated user information through Google_Service_Oauth2. After authentication processes i am able to execute the following method:

$user = $oauth2->userinfo->get();

But when I print user fields by calling getEmail, getGiven_name, getFamily_name and so on, these fields are in blank except for getId. User Id is ok, so the authentication process is correct, but basic profile information is in blank.

I saw that this get method accepts an array of optional parameters, and I have tried to add email, or other fields but it does not work.

With the old 0.6.x library I was able to extract these fields without problems.

Any hint?

**Comment by appadmindelhi** [comment]
I can print the user information if i put the below code on my localhost(Using Xampp Server)

$oAuth = new Google_Service_Oauth2($client);
$userData=$oAuth->userinfo_v2_me->get();
echo "<pre>";
print_r($userData);
echo "</pre>";

But can not print the user details when i have moved my code from local to live server.

I don't know what is the issue.

**Comment by bichitra12** [comment]
i am not getting name for some user please help
