### ISSUE TITLE
status.embeddable not recognized on insert/update

### ISSUE THREAD

**Issue by jsor** [googleapis/google-api-php-client#67]
Hi,

i'm not sure this an issue with the PHP api client, with the API itself or if i'm doing something wrong.

The value of [`status.embeddable`](https://developers.google.com/youtube/v3/docs/videos#status.embeddable) is simply ignored for `$youtube->videos->insert()` and `$youtube->videos->update()` and is always set to the (default) value `true`.

I'm basically using the code from the [PHP examples](https://developers.google.com/youtube/v3/code_samples/php).

Inspecting the `Google_Http_Request` object (at this [point](https://github.com/google/google-api-php-client/blob/master/src/Google/IO/Stream.php#L140)) shows that the property is set correctly:

```
Google_Http_Request Object
(
    ...
    [postBody:protected] => {"snippet":{"categoryId":22,"description":"Test","tags":[""],"title":"Test"},"status":{"embeddable":false,"privacyStatus":"unlisted"}}
    ...
)
```

The `responseBody`property shows that everything was accepted except `embeddable`:

```
Google_Http_Request Object
(
    ...
[responseBody:protected] => {
...
 "status": {
  "uploadStatus": "processed",
  "privacyStatus": "unlisted",
  "license": "youtube",
  "embeddable": true,
  "publicStatsViewable": true
 }
}
)
```

Any help or hints appreciated.

**Comment by samisalow** [comment]
I have the same problem, could you tell me if the problem is resolved?
