### ISSUE TITLE
Implementing exponential backoff

### ISSUE THREAD

**Issue by The-Lion** [googleapis/google-api-php-client#68]
I would like to see an exponential backoff implemented as is suggested in the Google documentation. Are there any plans to add this?

<a href="https://developers.google.com/drive/web/handle-errors#implementing_exponential_backoff">Exponential backoff</a>

**Comment by glen-84** [comment]
Please re-open this issue.

**Comment by bshaffer** [comment]
@glen-84 the [latest version](https://github.com/google/google-api-php-client/tree/v2.0.0-RC1) of this library uses Guzzle5, and may work well with [this plugin](https://github.com/guzzle/retry-subscriber)

**Comment by glen-84** [comment]
Okay, thanks.
