### ISSUE TITLE
use PSR-1 and PSR-2 coding standards

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-api-php-client#692]
- update .travis.yml to check CS using `php-cs-fixer`
- ignore `src/Google/Service` as these are generated elsewhere
- http://www.php-fig.org/psr/psr-1/
- http://www.php-fig.org/psr/psr-2/

**Comment by bshaffer** [comment]
Also incorporate PSR-4 by flattening the directory structure

**Comment by cnelissen** [comment]
+1

**Comment by hakimio** [comment]
Any progress?

**Comment by hacfi** [comment]
@bshaffer @jdpedrie Can someone from the community work on this or will this be provided by the Google APIs team as you generate it from some internal template?

**Comment by bshaffer** [comment]
@hacfi We always love and accept community support, but this one may be on us because of the complexity of BC issues. However voicing that you need this really helps with prioritization, and will result in us getting it done. The main reason we haven't taken action on this is nobody's pushed on this from the community.

In [the phpgen-2.0](https://github.com/googleapis/google-api-php-client-services/blob/phpgen-2.0/src/autoload.php) I've proposed an `autoload.php` file that fixes this. In order to move forward, we'd just need to publish a new php generator and add it as a Github action. This is something @jdpedrie and I will hopefully get done this year.

**Comment by mfn** [comment]
FWIF, here's my voice too 🗣️ 

;-)

**Comment by Genjiff** [comment]
Is this still on your roadmap? I would love to see this implemented

**Comment by repat** [comment]
@bshaffer there's definitely some need for this, see https://github.com/googleapis/google-api-php-client/issues/2073 Thanks! :)
