### ISSUE TITLE
Reference to undefined variable causing HTTP failure

### ISSUE THREAD

**Issue by DavidAnderson684** [googleapis/google-api-php-client#871]
In the v1 branch, in src/Google/IO/Stream.php, line 154 is:

```
$respHttpCode = $this->getHttpResponseCode($http_response_header);
```

There are no previous references to $http_response_header (and only one later one), and it's not obvious how to correct it. Attempting to use the stream handler gives a PHP warning for the undefined variable at this line, and also fails.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by DavidAnderson684** [comment]
It's still there. I don't seem to have a way to re-open directly, so will open a new one.

**Comment by mattwhisenhunt** [comment]
@DavidAnderson684, are you using the v1 branch? What is your fix in your code base?

**Comment by DavidAnderson684** [comment]
@mattwhisenhunt We didn't fix it. We put to one side investigations into whether the stream handler would be useful.

**Comment by mattwhisenhunt** [comment]
Let's close this for now and reopen if anyone asks for help with v1.
