### ISSUE TITLE
McfDataRows data is not properly set

### ISSUE THREAD

**Issue by Eldair** [googleapis/google-api-php-client#932]
Hello,

Data returned from data_mcf->get() request and contained inside rows (Google_Service_Analytics_McfDataRows objects) is not set properly, and is not easily accessible without toSimpleObject()

**Comment by owneroverall** [comment]
​
 kenny hermansson.png
<https://drive.google.com/file/d/0ByCA15d_nPrGVzBSd3FtY1JvRkU/view?usp=drive_web>
​

417 ☆☆☆☆☆☆[GO]☆☆☆☆☆☆Co.
  '''''''''''''''''''''''''''''''¤¤★¤¤''''''''''''''''"""""""""""





2016-04-25 19:12 GMT+02:00 Krisitjan <notifications@github.com>:

**Comment by bshaffer** [comment]
Please provide a sample of your code so that we can reproduce the issue.

**Comment by Eldair** [comment]
Hello,

Okey, this is how I get the results (response)
`$response = $mcf->get(
            'ga:'.$request->profile,
            $start,
            $end,
            'mcf:assistedConversions',
            [
                'dimensions' => 'mcf:source',
                'sort' => '-mcf:assistedConversions',
                'max-results' => '10'
            ]
        );`
which works fine and returns results.

But I have to do
`$report = $response->toSimpleObject();`
in order to be able to itterate over the results, otherwise it won't work because data is not properly set inside metadata property of Google_Service_Analytics_McfDataRows class.

**Comment by mattwhisenhunt** [comment]
So it has methods from Model (parent class) but not members and methods of the derived Google_Service_Analytics_McfDataRows?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by Eldair** [comment]
Hi @mattwhisenhunt sorry for not responding earlier, it has been year and a half since I posted the issue.
Each results row is an instance of `Google_Service_Analytics_McfDataRows` but all methods (getConversionPathValue, getPrimitiveValue) return either `null` or `[]`
When I try to iterate over one row I get `Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /home/vagrant/Code/reporting-tool/vendor/google/apiclient/src/Google/Collection.php:95)`

**Comment by dwsupplee** [comment]
It looks as though this is an edge case that has a workaround available - if this issue is something that is blocking you please let us know and we can take another look at opening this up, thank you!
